### PR TITLE
Ease the quickstart script by moving login() & end() methods alongside advanced exception handling into a separate function- smart_run()

### PR DESCRIPTION
**Pull request by uluQulu**
#### Hi all!
Here is a new version of quickstart script usage:
https://github.com/uluQulu/InstaPy/blob/master/quickstart.py

#### Extra benefits of `smart_run()`:
+ It will **auto**-login; You don't need to write down `session.login()` line
+ It will **always** end the session [using `session.end()`] at the end of the script or after some interrupt.
+ User will **only** provide _login credentials_, _instantiate InstaPy class_ and then _write down the activity flow_ [actions and settings]

Shortly,
```python
#imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = ''
insta_password = ''

# get an InstaPy session!
session = InstaPy()

with smart_run(session):
    # settings
    session.set_relationship_bounds(enabled=True, potency_ratio=1.07)
    
    # actions
    session.like_by_tags(["natgeo"], amount=10)
```
That's it!

### What more?
**While inside** `smart_run()`, now after a keyboard interruption [CTRL+C which is being pressed by the user], you will see only one line of message,
"_You have exited successfully._"
rather than long traceback of `KeyboardInterrupt` exception at the end of the file.
_Sure it will end as normal, e.g. `end()` method will be executed as intended. It's just not gonna printing the `KeyboardInterrupt` exception messages_.
**Side note**: It doesn't matter even if you keep pressing CTRL+C [or any other keyboard interruption keystroke] forever without releasing 💪🏼😁👈🏼 it
**Knowledge Base**: I have said "_While inside `smart_run()`_" - **yes**, it is important, cos outside the coordination of `smart_run()` function, it will raise that long `KeyboardInterrupt` exception message [e.g. during getting the session instance- `session=InstaPy()`].

For other exceptions, it will always `raise` the full stacktrace [as before]

-----

#### And other changes I did in quickstart script, _e.g._,
+ force people to use smarter comments by seeing better examples
+ remove "_girl_" [tag regex] from `set_dont_like()` - respect girls 😎 [although that may be a blacklisted tag]
+ add a light-weight quota supervisor usage

----

@timgrossmann @sionking @CharlesCCC and other collaborators and contributors,
I really stay long in the very details, but if there is something I have done wrong, please, let me know 👋🏼

@timgrossmann, this work actually started with your request [at #3001] then I decided to implement finally. I mean if you have additional ideas or suggestions, let's quickly discuss it 🤔

If you think some change is redundant or unwanted or misfit, please, raise it to remove [or change] 🎯

----

Cheers 🙂
----

### CODE REVIEW

**Comment by HCWcoder** [comment]
woow please consider staying here :$

i will test it now

@uluQulu

**Comment by HCWcoder** [comment]
@uluQulu 
Tested all working great ! now its more clear and i really clear and easier for new joiners
Thanks !

**Comment by uluQulu** [comment]
That's amazing, @HCWcoder!
Thanks for testing out my code.

No. I do not use Discord.

-----

Cheers 😁
-----

**Comment by IsNotMyIP** [comment]
Nice changes! Do you recommend to capsulate my script on smart_run always or what is the proper workflow for that?

In addition: I know it does not fit here but, Is it planned to apply the function `set_do_follow` to the functions `follow_commenter OR follow_likers`? Is there any workaround for that? I would like to play with the DOM sometimes while using InstaPy, is there any way for doing so? 

Hahahaha sorry for this amount of questions, maybe we can implement a FaQ on the Readme.md for people like mme

**Comment by uluQulu** [comment]
Hi Sean
>Nice changes! Do you recommend to capsulate my script on smart_run always or what is the proper workflow for that?

Sure. Though for old users, it will make them think 😁 a bit:
- Q: "_hmm how do I make it work with `smart_run()` as before?_"
Answer: Just put everything of setting and action into it. (_see the example in the description_)

If you have more specific questions ask it.

>Is it planned to apply the function set_do_follow to the functions follow_commenter OR follow_likers? Is there any workaround for that?

I think no. Cos follow likers and follow commenters features are follow based features and are meant to follow and having a follow percentage in them is unwanted behavior.
But if you want the usage of times parameter, it is another story.
Shortly, you can initialize `session.set_do_follow(times=5)`, then that times parameter will be used in both follow commenters and follow likers.

>I would like to play with the DOM sometimes while using InstaPy, is there any way for doing so?
+ You can use an intergrated IDE for that- e.g. PyCharm has amazing features to add breakpoints, pause code execution, change live variables values all while at program running.
+ Or use traditional way of sleep lines and doing anything you want [I use this method 😁]
_you just need to know where you must add that sleep*_

>Hahahaha sorry for this amount of questions, maybe we can implement a FaQ on the Readme.md for people like mme

Good idea. Can you do that?- Frequently Asked Questions [FAQ.md] 👈🏼🎖

---


Cheers 😁
----

**Comment by timgrossmann** [comment]
@uluQulu You are the man! Thank you very much for implementing this after our quick discussion in the other PR.
This is awesome and looks way cleaner!

One thing I noticed is that we might consider cleaning up a bit more while we are here:
- Completely remove the commenting feature from the default quickstart file (it's pretty spammy and a lot of people are really annoyed by it so it has to be used smartly, especially when we only have <50 different comments)
- Remove `potency_ratio` and `delimit_by_numbers` from the relationship bounds example (since they are not mandatory)
- I'd love to push quota supervisor, but I think we should add a comment over it to clear up what happens here
- Should we adjust InstaPy to by default have `multi_logs=True` and only keep the possibility to add a shared log? This seems to be the default other than `False`
- Adding a comment over InstaPy constructor telling the people that they can "run it in the background" with `headless=True` ?

Any thoughts?

> Love the point about removing the `#girl` from the don't likes 😄

**Comment by uluQulu** [comment]
Thank you for extending compassion and flexibility, @timgrossmann 🤩
>Completely remove the commenting feature from the default quickstart file (it's pretty spammy and a lot of people are really annoyed by it so it has to be used smartly, especially when we only have <50 different comments)

If the new **quickstart** script is so empty, new user will think hmm. What do I DO now? [it is so difficult 😳]
But you're right about the commenting part.

>Remove potency_ratio and delimit_by_numbers from the relationship bounds example (since they are not mandatory)

If `delimit_by_numbers` removed [or disabled] then no any _max_/_min_ numbers can work :)
Maybe remove `potency_ratio` & keep only 1 pair of _max_/_min_?

>I'd love to push quota supervisor, but I think we should add a comment over it to clear up what happens here

Right. Just remove it. People can find it in the README.

>Should we adjust InstaPy to by default have multi_logs=True and only keep the possibility to add a shared log? This seems to be the default other than False

I agree. Multi logs is the best option for clarity & performance and extra reason- file access conflict in case of simulatenous sessions at a moment. Its default should be `True`.
That part of code needs a revision.
E.g. all of the additions by me is written to behave normally in both multi logs turned on and off, e.g. relationship tools, record activity & follow restriction & graphql queries JSON files but other legacy files are prone to misbehave in multi logs turned off state.


>Adding a comment over InstaPy constructor telling the people that they can "run it in the background" with headless=True ?

Good idea.

Can you prepare your suggested style of quickstart script in final state, so that we can agree on finally and push it.
This is the current state after this PR: https://github.com/uluQulu/InstaPy/blob/master/quickstart.py

##### Also, having a super simple initial quickstart script and having a file called **quickstart_styles** containing _quickstart scripts_ with various efficient styles [by the community 😉] can make this problem solve fully 😋


-------


Cheers 😁
-----

**Comment by timgrossmann** [comment]
@uluQulu @sionking @CharlesCCC Thought about something like this to be very minimal to start with. Any thoughts?

Really love the idea of having more than one quickstart script, enabling the user to chose and edit the one he's actually interested in using without them needing to modify a lot of stuff!

**Comment by timgrossmann** [comment]
@uluQulu Thank you very much for this addition @uluQulu

**Comment by uluQulu** [comment]
You're welcome, @timgrossmann 
#### On quickstart styles IDEA
Can you open a new PR with a new folder called e.g. **quickstart_styles** at project root folder and invite every collaborator, contributor and community fella to share 1 good exceptional _InstaPy usage style_ [a **quickstart** file] each and then add them [efficient ones] to that folder and merge?
And people will also share gradually by time.

_I could do it but that PR might need to be kept open for days and I am afraid I can only keep one PR alive per time and soon I will share another PR containing a new fix & lots of changes_.

Notes:
+ no any personal information; just usage style
+ include a **usage.txt** file at that folder saying: "_If you want to use any of these quickstart files, move them to project root folder and modify & start!_" to prevent import & file access error
+ I will also add some 😎
+ some style rules should be added; for wannabe users easily understand how to apply it


------

Cheers 😄
----

**Comment by timgrossmann** [comment]
@uluQulu Love the idea. I think we can use the examples folder (not sure if quickstart_styles is better than quickstart_examples) and put it in there after removing the old stuff in there that's outdated.

**Comment by HCWcoder** [comment]
@uluQulu what a creative mind !

i would love to see you guys share your stuff there !

**Pull request merged**
