### PR TITLE
fix issue with smarthashtag returns no results

### PR DESCRIPTION
**Pull request by CharlesCCC**
Fix an issue that if there is no smarthash tag the Instapy will blow up with UnboundLocalError

```
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    session.like_by_tags(amount=10, use_smart_hashtags=True)
  File "/Users/congchencai/Documents/InstaPy/instapy/instapy.py", line 1885, in like_by_tags
    self.logger.info('Tag: {}'.format(tag.encode('utf-8')))
UnboundLocalError: local variable 'tag' referenced before assignment
```

TBH, not sure how it ever worked, as the `tag` wasn't even in the for loop.

### CODE REVIEW

**Comment by andifds** [comment]
I got the same problem, I haven't make it work yet.
Don't know how to modify my local files to check if your commit make it work.

**Comment by CharlesCCC** [comment]
@andifds you can pull down the change from my repo or you can add a tab(4 spaces) to your code at line 1885 in instapy.py file.

**Comment by timgrossmann** [comment]
@CharlesCCC Good catch! Never seen that error thou, probably only happens with very weird words :smile: 
I'll merge this and the other PRs later today and create a new fix-release before releasing a new minor version later this week :+1: 
Thank you very much for this fix!

**Review by timgrossmann — APPROVED** [review]

**Comment by andifds** [comment]
@CharlesCCC how can I modify filea on my setup. Got it on Ubuntu on EC2 and also on a RPi. Which is the path to files.

@timgrossmann thanks for the approval

**Comment by timgrossmann** [comment]
@CharlesCCC I'm really sorry... I feel super nasty for messing up your clean PRs like that 🙈 🙊
Please forgive me 😅

**Comment by timgrossmann** [comment]
Really sorry... #4246

**Comment by CharlesCCC** [comment]
@timgrossmann it all good, as long as we get this one merged.

**Pull request closed without merging**
