### PR TITLE
Add docker swarm config

### PR DESCRIPTION
**Pull request by funkypenguin**
And this PR just includes a sample docker-swarm config, plus a link to a [tutorial](https://geek-cookbook.funkypenguin.co.nz/recipies/instapy/) in the "recipe" format I like :)

### CODE REVIEW

**Comment by timgrossmann** [comment]
@funkypenguin I hope some people use this! 
Thank you very much

> Even though there is not a lot of insight about what you put into the `funkypenguin/instapy:latest`-image / might put in there 😛

**Comment by funkypenguin** [comment]
Oh, I made this screenshot from "docker cloud" to illustrate how to setup automated build against a specific Docker file. I couldn't make this work with DockerHub, since there was no way to set the context to "/".

screen shot 2018-04-17 at 21 38 54

Feel free to change the target image in the docker-swarm.yml file, I only used funkypenguin/instapy because you don't have an auto-built image (yet!) :)

D

**Comment by timgrossmann** [comment]
@funkypenguin Are you part of the discord channel? 
@scriptworld-git would like to ask you some questions in regards to the docker files in the repository since we want to completely extract the docker part out to this repository: https://github.com/InstaPy/instapy-docker

Thank you

**Comment by funkypenguin** [comment]
Incoooomiiiiinggg....

**Comment by timgrossmann** [comment]
@funkypenguin Haha, awesome 🙌 
Are you a member of the discord channel? 😋

**Comment by funkypenguin** [comment]
I am now, but I've got general notifications disabled, so @mention me to get my attention ;)

**Pull request merged**
