### PR TITLE
Use proxy to access clarifai; return clarifai tags to caller

### PR DESCRIPTION
**Pull request by sionking**
read the title.
@timgrossmann Documented for first time hope it is fine :)

### CODE REVIEW

**Comment by timgrossmann** [comment]
@sionking Awesome documentation! 😄 
Thank you for PRing this, it's very important to be able to do this.

One thing I saw is that the proxy is not passed as string value.
Is this a definition of Claraifai? There are a lot of proxy services that use an url as IP as well (e.g. Luminati). Will this work with them?

**Comment by sionking** [comment]
can you give an example?

**Comment by timgrossmann** [comment]
@sionking Absolutely!
`http://${username}-session-${sessionId}:${password}@zproxy.lum-superproxy.io:${port}`This is the proxy I'm using for a project. Using Luminati proxy service

**Comment by sionking** [comment]
@timgrossmann it uses Requests HTTP Library So yes it input should be string I fixed the doc.

**Comment by timgrossmann** [comment]
@sionking Perfect, thank you!

**Pull request merged**
