### PR TITLE
unfollow via FIFO (extract from #74)

### PR DESCRIPTION
**Pull request by AlainPilon**
This branch is a complete Cut&Paste from feature #74 from @sagielevy to only extract the FIFO unfollowing feature. 

I did not port the option to pick a FIFO/LIFO strategy since now that we have FIFO there is no logical reason why someone would want to use LIFO. 

I dont have enough followers to test it, so could someone check it out and confirm I did not miss anything from the original code.

### CODE REVIEW

**Comment by eduardocalazansjr** [comment]
I will make an PR to fix all the XPATH/JS refs and test this ASAP.

**Comment by AlainPilon** [comment]
Now that I think about it, one of the side effect of using the FIFO may be that we would unfollow users who have been added by the actual account owner. This wouldnt be an issue once #142 is done. Until then, it is caveat emptor!

**Comment by timgrossmann** [comment]
@AlainPilon could you add a parameter for the user to decide whether he wants to use FIFO or LIFO unfollowing? like #74 did?
Would be great!

**Comment by littleswany** [comment]
@timgrossmann @AlainPilon Do we want this for the master branch or for the develop branch as at some point master will be replaced?

**Comment by timgrossmann** [comment]
@littleswany Master, the one for V1 should have more feature... E.g. only unfollowing people the script followed, smart unfollowing after special amount of time...

**Comment by RealMakAttak** [comment]
I would love this feature

**Pull request closed without merging**
