### PR TITLE
Install improvements

### PR DESCRIPTION
**Pull request by douwevandermeij**
Add ability to install package as library (instead of main project) and install assets and db as well.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@douwevandermeij Awesome, thank you very much!

Let's still wait for one more approval before merging.

**Comment by douwevandermeij** [comment]
I updated the readme to be able to use this new functionality to its full extent.

**Comment by Tjorriemorrie** [comment]
I'm just worried that the readme update will confuse a lot of people that are new to python, which seems to be a lot of users from looking at the issues. Can we not rather keep the basic installation as it is, and rather add a 'preferred' section underneath that, or something like that.

**Comment by douwevandermeij** [comment]
Yes agree, let's keep basic "basic" and add a preferred section.

**Pull request merged**
