### PR TITLE
Change allfollowing xpath from find <a> element to child node instend

### PR DESCRIPTION
**Pull request by pleum**
from #761, when 0 following it use `<span>` tag instend of `<a>` because when you follow someone you can click number of following for show dialog user you following.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@pleum Thank you for the contribution!

Could you please resolve the conflicts? I'll merge your PR then.

**Comment by converge** [comment]
@pleum @timgrossmann I think this isn't working as expected, this is the output with project latest commit:
```
$ python quickstart.py
Logged in successfully!
set_automated_followed_pool error
 [Errno 2] No such file or directory: './logs/cycling_apparel_followedPool.csv'
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    session.unfollow_users(amount=3, onlyInstapyFollowed=False)
  File "/Users/converge/Documents/workspace/InstaPy/instapy/instapy.py", line 989, in unfollow_users
    onlyInstapyMethod, self.automatedFollowedPool)
  File "/Users/converge/Documents/workspace/InstaPy/instapy/unfollow_util.py", line 39, in unfollow
    allfollowing = browser.find_element_by_xpath("browser.find_element_by_xpath('//li[3]/child::node()/span').text)").text
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: Unable to locate an element with the xpath expression browser.find_element_by_xpath('//li[3]/child::node()/span').text) because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string 'browser.find_element_by_xpath('//li[3]/child::node()/span').text)' is not a valid XPath expression.
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
```

@timgrossmann merged a patch I made about this issue, take a look: https://github.com/timgrossmann/InstaPy/pull/749/commits/79626dd70e5ce26c831722966ca71e7d523fea7a

After this patch, when unfollowing and account has 0 following, it wont crash and skip to next bot action. When following user followers, if user to follow is a private account, it wont crash too, it just skip to next user to follow.

**Comment by pleum** [comment]
I just wondering why still can use `//li[3]/a/span` while it come to `//li[3]/span/span` when 0 following

element-diff

and here my result
result

**Comment by converge** [comment]
I think the main point is, if we have 0 following and we can't interact with it, skip it and go to next action.

can you see another scenario ?

**Pull request closed without merging**
