### PR TITLE
First quick fix for the memory leak problem

### PR DESCRIPTION
**Pull request by timgrossmann**
Simply handling a general `atexit` event which will eventually call the end method which at least closes the chrome instance and the xvfb instance making sure that on error or ctrl+c no restart is necessary

### CODE REVIEW

**Comment by rossbulat** [comment]
@timgrossmann Thank you, I am testing this now. Will see how it performs.

**Comment by thedappernisarg** [comment]
@timgrossmann I have not work on Python much. This thread might help you. [https://stackoverflow.com/questions/1641231/python-working-around-memory-leaks/1641280#1641280](https://stackoverflow.com/questions/1641231/python-working-around-memory-leaks/1641280#1641280)

**Comment by converge** [comment]
hey guys,
## I tested it using this InstaPy setup:
```python
from instapy import InstaPy
import resource
print ('Memory usage begin: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)

session = InstaPy(username=insta_username, password=insta_password)
session.login()

print ('Memory usage #1: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
session.follow_user_followers(['mundociclismo'], amount=7, random=True, interact=True, sleep_delay=30)

print ('Memory usage #2: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
session.follow_user_following(['lisabrennauer'], amount=5, random=True, sleep_delay=30)

print ('Memory usage #3: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
session.unfollow_users(amount=9, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=30)

print ('Memory usage #4: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
session.like_by_tags(['cyclingshoes'], amount=5)

session.end()

print ('Memory usage after session.end(): %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
```

## The result are:

### before #826 
Memory usage begin: 26083328 (kb)
Memory usage #1: 26324992 (kb)
Memory usage #2: 26513408 (kb)
Memory usage #3: 26595328 (kb)
Memory usage #4: 26824704 (kb)
Memory usage after session.end(): 26845184 (kb)

## after #826
Memory usage begin: 26779648 (kb)
Memory usage #1: 26779648 (kb)
Memory usage #2: 26779648 (kb)
Memory usage #3: 26779648 (kb)
Memory usage #4: 26820608 (kb)
Memory usage after session.end(): 26853376 (kb)

and this exception on exit:
```bash
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/converge/Documents/workspace/InstaPy/instapy/instapy.py", line 1419, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 744, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
```

**Review by converge — COMMENTED** [review]
hey guys,
**I tested it on a OSX,python3.5.2 and using this InstaPy setup:**
```python
import resource
print ('Memory usage begin: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)

session = InstaPy(username=insta_username, password=insta_password)
session.login()

print ('Memory usage #1: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
session.follow_user_followers(['profile_name'], amount=7, random=True, interact=True, sleep_delay=30)

print ('Memory usage #2: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
session.follow_user_following(['profile_name'], amount=5, random=True, sleep_delay=30)

print ('Memory usage #3: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
session.unfollow_users(amount=9, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=30)

print ('Memory usage #4: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
session.like_by_tags(['tag_name'], amount=5)

session.end()

print ('Memory usage after session.end(): %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
```

## The results are:

### before #826 
Memory usage begin: 26083328 (kb)
Memory usage #1: 26324992 (kb)
Memory usage #2: 26513408 (kb)
Memory usage #3: 26595328 (kb)
Memory usage #4: 26824704 (kb)
Memory usage after session.end(): 26845184 (kb)

## after #826
Memory usage begin: 26779648 (kb)
Memory usage #1: 26779648 (kb)
Memory usage #2: 26779648 (kb)
Memory usage #3: 26779648 (kb)
Memory usage #4: 26820608 (kb)
Memory usage after session.end(): 26853376 (kb)

and this exception on exit:
```bash
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/converge/Documents/workspace/InstaPy/instapy/instapy.py", line 1419, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 744, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
```

Next step is try the same InstaPy configuration as @rossbulat is using. It's a start, let me know what you think about this review.

**Pull request closed without merging**
