### PR TITLE
Memory leak fix

### PR DESCRIPTION
**Pull request by converge**
Just found out that our memory leak issue is caused when:

1. start InstaPy
2. InstaPy generates some error/exception
3. self.end() method is not called in the process
4. chrome and xvfb keeps open, consuming resources (cpu / memory)

### CODE REVIEW

**Comment by timgrossmann** [comment]
@converge Yes, that's the same problem I tried to fix with the other memory leak PR.

**Comment by converge** [comment]
@timgrossmann cool! I saw your PR about it, it was exclusively calling end() when ctrl+c is hit, right ?

This approach calls always call end() whenever an error/exception is raised or the script reach its end.

What do you think ?

**Comment by Naramsim** [comment]
@converge There is your account password in the PR!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by converge** [comment]
@Naramsim thanks! that was funny.

Fortunately is a testing account.

**Comment by Naramsim** [comment]
Yeah, consider that we are using Git, so everything remains, you should remove that commit.

https://github.com/timgrossmann/InstaPy/pull/1137/commits/44cfac52faa78005f1fcfead0f3fe8bfe5414968

**Comment by converge** [comment]
@Naramsim no problem, I don't use that passwd for other stuffs.

**Pull request merged**
