### PR TITLE
Fix on docker prod

### PR DESCRIPTION
**Pull request by pmusolino**
Docker now mount correctly the volume, and works properly with chromedriver installed under the assets folder

### CODE REVIEW

**Comment by timgrossmann** [comment]
@pmusolino Thank you very much for fixing this!

We are currently working on an easier installation of InstaPy, once this is ready and merged, we'd love to see Docker users like yourself helping set up an own Docker repository in the InstaPy org and maybe even create an image for Dockerhub. 

Would love to hear your thoughts on that.
Thanks

**Comment by timgrossmann** [comment]
@pmusolino Are you part of the discord channel? 
@scriptworld-git would like to ask you some questions in regards to the docker files in the repository since we want to completely extract the docker part out to this repository: https://github.com/InstaPy/instapy-docker

Thank you

**Comment by pmusolino** [comment]
Hi there. Yes, I'm in. I have the same username as GitHub.

**Comment by timgrossmann** [comment]
@pmusolino Awesome! Thank you very much

**Pull request merged**
