### PR TITLE
Fix "_Unable to locate element: ...xpath","selector":"//div[text()=\'Likes\'..._" error

### PR DESCRIPTION
**Pull request by uluQulu**
I have been reported it occurred with `follow_likers()` feature.

Fixes are applied to the `likers_from_photo()` function and each change is explained in the commit description.

---

Cheers 😁
---

### CODE REVIEW

**Comment by octavius-1** [comment]
What else is needed to merge this branch?

**Comment by uluQulu** [comment]
Hi @octavius-1 
I think a few more people to approve it really works.

**Comment by sionking** [comment]
I will test thanks

**Comment by sionking** [comment]
Seems to work, thanks!

**Comment by sionking** [comment]
I think the use of `get_active_users` should be modified to the `likers_from_photo` function, why aren't they same ?

**Comment by sionking** [comment]
please change:
```
    def set_dont_unfollow_active_users(self,
                                       enabled=False,
                                       posts=4,
                                       boundary=500):
        """Prevents unfollow followers who have liked one of
        your latest X posts"""

        if self.aborting:
            return

        # do nothing
        if not enabled:
            return

        # list of users who liked our media
        active_users = get_active_users(self.browser,
                                        self.username,
                                        posts,
                                        boundary,
                                        self.logger)

        # include active user to not unfollow list
        self.dont_include.update(active_users)
```
to :
```
    def set_dont_unfollow_active_users(self,
                                       enabled=False,
                                       posts=4,
                                       boundary=500):
        """Prevents unfollow followers who have liked one of
        your latest X posts"""

        if self.aborting:
            return

        # do nothing
        if not enabled:
            return

        active_users = []
        
        # list of users who liked our media
        photo_urls = get_photo_urls_from_profile(self.browser, self.username, posts, randomize=False)
        sleep(1)

        if not isinstance(photo_urls, list):
            photo_urls = [photo_urls]

        for photo_url in photo_urls:
            active_users.extend(users_liked(self.browser, photo_url, boundary))

        # include active user to not unfollow list
        self.dont_include.update(active_users)
```

**Comment by timgrossmann** [comment]
@sionking After reading through the code regarding your comment, do you mean that the `get_active_users` should make use of the `likers_from_photo` method since `likers_from_photo` extracts the likers from one post and `get_active_users` gives you the likers of a specified amount of posts?

**Comment by sionking** [comment]
@timgrossmann the get_active_users  isn't working ....

**Pull request merged**
