### PR TITLE
Abstracted out clicking elements

### PR DESCRIPTION
**Pull request by blesson3**
## Purpose
Too many crashes due to not being able to click an element on screen.
See this issue that explains this in a bit more detail: https://github.com/timgrossmann/InstaPy/issues/1232

## Fix
I created a new function in `util.py` that clicks elements using a various number of techniques, see code for more info.

I've documented the code I changed pretty well, if you don't understand why I changed something, ask.

### CODE REVIEW

**Comment by ArdySan2012** [comment]
Hey there - I am experiencing that error all the time (unable to click). Would love to test-try your version - is there a way I can download your build (new to github)

**Comment by ArdySan2012** [comment]
Figured that out, testing.

**Comment by ArdySan2012** [comment]
At times script says “now following” but nothing happens (if pressed manually “follow” on the page - leads to follow going through)

**Comment by Phazz** [comment]
@blesson3 I tested this branch for the past 2 days and so far it solved issues I had similar to #1232 Thanks for this

**Comment by Venni27** [comment]
Changed all files described and it works like a charme on raspberry jessie lite...thumbs up!
Thank´s for your work in fixing this :-)

**Comment by uluQulu** [comment]
This is amazing @blesson3 thanks for writing this!

**Pull request merged**
