### PR TITLE
Updated Unfollow to remove unfollowed or removed IG accounts from followedpool.csv; cancellation of ctrl+c when updating a file

### PR DESCRIPTION
**Pull request by sionking**
Thanks to @ximhotep

Accounts removed by IG aren't being removed from followedpool.csv causing unfollow to iterate through those accounts every cycle. Recommended adding the two additional calls to delete_line_from_file to remove users from followedpool.csv

** This is a diffrent fix based on the return following is False, so we will go to the else.

----------------
Added also the cancellation of ctrl+c when updating a file

### CODE REVIEW

**Comment by timgrossmann** [comment]
@sionking Looks like `interruption_handler()` is not defined in that context which leads the travis-ci checks to fail.

**Comment by sionking** [comment]
Fixed...

**Comment by sionking** [comment]
I do think we should change the order:
first call interruption_handler later open file.

**Comment by timgrossmann** [comment]
@sionking Awesome, now all the checks and the CI work 👍 

What's the reason you would prefer the order to be changed?

**Comment by sionking** [comment]
- open file than ctrl + c == not closing the file right.

but I don't really think it matter.

**Comment by timgrossmann** [comment]
Now it makes sense, awesome addition to InstaPy, @sionking!
Thank you very much

**Pull request merged**
