### PR TITLE
Fixed xpath on get_users_through_dialog

### PR DESCRIPTION
**Pull request by cyberpz**
Issue #5246

### CODE REVIEW

**Comment by Peppuz** [comment]
I'm sorry I keep doing mistakes, this PR is still open.

**Comment by Peppuz** [comment]
Please @timgrossman accept this little commit.

**Comment by cyberpz** [comment]
@timgrossmann please, this is fundamental to all Follow functions.

**Comment by thinhago** [comment]
> @timgrossmann please, this is fundamental to all Follow functions.

any fix for this issue? same problem here

**Comment by timgrossmann** [comment]
@Peppuz Is this problem valid for all the user or just another A/B Test?

**Comment by cyberpz** [comment]
Nice question! 
I tested on multiple profiles and it works for all of them, I can't confirm what you ask by myself.

**Review by timgrossmann — APPROVED** [review]

**Pull request merged**
