### PR TITLE
Added multi-account example #451

### PR DESCRIPTION
**Pull request by rzfzr**
I had no problems running from the same IP.
The code is still crude but works fine, I'll be working on it and accepting suggestions.

### CODE REVIEW

**Comment by CharlesCCC** [comment]
@rzfzr this will be a good combination with the [PR-1150](https://github.com/timgrossmann/InstaPy/pull/1150)

**Comment by rzfzr** [comment]
@CharlesCCC Sure, I guess it's a recurrent theme to have multiple users, I edited the source files to print the username whenever it prints an "INFO" or "-->", I plan to make it more elegant by overriding logger.info to print it, then I'll share it. Maybe then look into the logs.

**Comment by dimahadgi** [comment]
So multi-account is working? Can I start using it?

**Comment by timgrossmann** [comment]
@dimahadgi This is mostly an example on how you could do it. 
It's not the final thing but a start to make people aware that we are working on it and how they can use it right now (Note: This does not take separate log files into account yet)

**Pull request merged**
