### PR TITLE
FIxed follow commenters

### PR DESCRIPTION
**Pull request by david-vendel**
Xpath changed fixed. Should work now.

### CODE REVIEW

**Comment by hw711** [comment]
In get_relationship_count function, do you need two separate try blocks for getting follower and following counts?  Because if one fail, the other one will fail the same way so if you put them in the same block, you can cut the time the function takes when NoSuchElementException hits by 50%.

**Comment by timgrossmann** [comment]
@justdvl Thank you very much for the PR.

Could you explain what all the changes are that you did?
When looking at the diff there is a lot of stuff going on, not just a "simple" XPath change.
Thanks

**Comment by david-vendel** [comment]
You are right, I only made few changes but it displaied way too many things changed. Could it be because I didn't have the newest version of Instapy forked? I am not so good with Github, so it is bit confused now.

**Comment by david-vendel** [comment]
The thing is, Github is showing that I changed the parts of code, which I didn't, -- it shows all the changes since April when I was last working on this. Before working on this code, I downloaded the new fresh version to my pc and verified that I am up to date, and changed only few things.
How should I fix this now?

**Comment by timgrossmann** [comment]
@justdvl It actually should be as easy as doing a rebase on the current master branch from your branch.
You probably have to "update" your own fork with the latest changes.

**Comment by david-vendel** [comment]
I will try to do it again. Can you delete this pull request?

**Pull request closed without merging**
