### PR TITLE
Added 'comment_by_locations' method to allow commenting by locations without likes

### PR DESCRIPTION
**Pull request by ghost**
Added 'comment_by_locations' method to allow commenting by locations without liking the posts. Just commenting. Because I needed that and wanted to return something to the community and others who might need the same :)

### CODE REVIEW

**Comment by CharlesCCC** [comment]
Great feature, Can you please also update the READ.me to add some explain along with useage 👍

**Comment by ghost** [comment]
Added usage description to README.md

**Comment by sionking** [comment]
What is the use case ?
I don't see why not liking ...

**Comment by ghost** [comment]
Use case? When you want the bot just comment on photos without liking them which is currently unavailable. That's what I needed for myself and I thought to give something nice back to this repo for letting me doing other things in the first place.

**Comment by timgrossmann** [comment]
@keevna55 Awesome, that's the spirit!
Give and take, without that, open source wouldn't be what it is

Thank you for contributing

**Pull request merged**
