### PR TITLE
New feature: Mandatory Language (via check links > character set)

### PR DESCRIPTION
**Pull request by visualheroes**
Hi all,

First, be indulgent, i don't have that much experience with Python (or github) so this edit might need some extra testing and editing. I'll gladly accept your help!

**What?**
I really don't like when my bot likes images in foreign characters as i more often than not find that those posts are not related to the hashtag i'm working on.
The idea is simple, reject posts containing characters not specified in the character set.
Setting it to latin will block post containing cyrillic, arab, etc.. You get the idea.

**How?**
I tried first to implement alphabet-detector (on github) but i couldn't make it work on both python 2 and 3. The final piece of code is mostly recycled and edited so not my original idea.
Added to check_links before the new location_name so it wont filter out locations with different character sets.
I've been testing it the last couple of weeks and it works great for my needs so i thought i might share it. ;)

**In use?**
Simply add the following:
set_mandatory_language(enabled=True, character_set='LATIN')
Suported languages > 'LATIN', 'GREEK', 'CYRILLIC', 'ARABIC', 'HEBREW', 'CJK' ,'HANGUL', 'HIRAGANA', 'KATAKANA' and 'THAI

I'll update the readme file later if there isn't to much conflict with @uluQulu works. 

Edit:
As i do not use the comment feature, i did not test it!

### CODE REVIEW

**Comment by sionking** [comment]
You will fail on Chars with no Name

**Comment by visualheroes** [comment]
@sionking 
Sorry, i'm not sure what you mean by Chars with no name.
Can you elaborate?

**Comment by sionking** [comment]
Sure, Some chars have no name in unicodedata.name so it will raise ValueError.

**Comment by visualheroes** [comment]
@sionking
You mean \n and all chars with a control in the unicode table?
I did not rise an error while testing with isalpha or maybe it has been corrected after 3.3?
Thank you for the tip i'll test it tomorrow to see if i can rise a ValueError.

**Comment by visualheroes** [comment]
@sionking 
Ok i re-tested to be sure.
As unicodedata.name is only used on alphabetic characters (isalpha), i am not able to rise a ValueError at all (the chars with no names in the unicode table are stripped).
Maybe i'm missing something?

Edit: i did find another not related error tho, i'll correct it tonight. ;)

**Comment by visualheroes** [comment]
Added a reset for check_letters, i forgot to add it back when i added everything in Instapy. Sorry about that. ;)

**Comment by timgrossmann** [comment]
@visualheroes Sorry for the conflicts, we've just merged a PR of @uluQulu that was in the loop for quite a while.

Could you please also add a section in the README for this feature?
> And add an entry into the CHANGELOG file quickly describing your feature?

**Comment by visualheroes** [comment]
@timgrossmann 
No worries, i already updated my files to the latest master.
Maybe you can help me, is there a way to update my fork to the last master on github? I have everything ready on my computer but i struggle to add everything to my fork.

**Comment by timgrossmann** [comment]
@visualheroes Great to hear that!
Thank you for updating.

Sure, hope this helps, sorry I can't write down the steps on my own but I think this explains it better than I could 😅 
https://stackoverflow.com/questions/42084116/pushing-to-a-different-git-repo/42084519

You basically have to add another `remote` to your git and then you can push to your own repository from the master of InstaPy.

**Comment by visualheroes** [comment]
@timgrossmann Sorry for the delay. After the last pull instapy became not stable at all on one of my machine (still running python 2.7). I rolled back to the previous version.

I'll however post an up-to-date version tonight so you can merge it if you want.

@uluQulu Did we just abandon python 2.7 compatibility with the last pull?

**Comment by uluQulu** [comment]
Rumors rumors @visualheroes 😂

Assuming that you mean my PR by "_the last pull_";
Well, I have had reports from people on these problems so far,
+ issue with installing `regex` module for some Mac users [SOLVED]
+ bug with `ceil` returning _float_ in python 2 [SOLVED]

If you have faced another error, please, let me know.

---
InstaPy runs on both python 2 & python 3 as always 🛩

Cheers 😁
---

**Comment by visualheroes** [comment]
@uluQulu 
Hey i missed the ceil fix, i will remerge.
Thanks!

**Pull request closed without merging**
