### PR TITLE
Added unfollow_after arg to unfollow_users to Delayed Unfollow

### PR DESCRIPTION
**Pull request by uluQulu**
As of @underclass [issued](https://github.com/timgrossmann/InstaPy/issues/1330)
### I've added a new argument:  **`unfollow_after`** 
to `unfollow_users` feature, in order to unfollow users **_after_** following them certain amount of time..
```python
unfollow_users (amount=10,
                onlyInstapyFollowed=True, onlyInstapyMethod='FIFO',
                sleep_delay=600,                   
                onlyNotFollowMe=False,
                unfollow_after=24*60*60)  #here, will unfollow every single user
                                          #after following at least a day
```
_Time counts uniquely for every single user, after it is followed by InstaPy.._
**Actually**, it can be `unfollow_after=500` (will unfollow users if **500 seconds** of follow time passes), but
having it **`hours*minutes*seconds`** **is easier** than big numbers, such as `168*60*60` equals to a week (in other words `604800` seconds)

[]      []      []       []       []      []      []

###   DETAILS
Well, I have changed the logging style of followed people in
`myusername_followedPool.csv` of `./logs/username/`
 **from** just names, as
```python
myfirstfollower_cool,
mysecondfollower_wow,
```
 **to** include the time it is followed, e.g.,
```python
2018-02-01 02:54 ~ myfirstfollower_cool,
2018-02-01 03:17 ~ mysecondfollower_wow,
```
**so** if `unfollow_after` is not None **it will compare** each user's followed time with realtime and generate available users list to unfollow in return..
if `unfollow_after` is None (or not included in `unfollow_users()`) it will **not** compare againist time, and will return a list of **all** followed users.

[]      []      []       []       []      []      []

**Notice 1:** **Old usernames** in `myusername_followedPool.csv` **without datetime entry**, will **not** be **compared** againist time in any case. And will be added to any unfollow list.

**Notice 2:** **Currently this works **only with** `onlyInstapyFollowed=True` method.** 
_you don't need to disable unfollow_after parameter while using another method.._

_**tbh** another method of `onlyNotFollowMe` is just unfollowing every user, while may you have followed some users without InstaPy that it factically is impossible to record their follow time accurately to compare in `unfollow_after`.._

[]      []      []       []       []      []      []

**Fix:** _Also, fixed_ **missing** `log_followed_pool` _line_ at `follow_given_user`(called from `follow_by_list` feature) of `unfollow_util.py`, **now** it is recording every followed user from `follow_by_list` feature to `myusername_followedPool.csv` file.

### CODE REVIEW

**Comment by uluQulu** [comment]
### Little-update for previous commit- _Show Inappropriate words_, also included! 
Recently, I saw that there are other **3 styles also** available to use in `set_dont_like()`:
`'#word'` , `'[word'` and `']word'`
Because of all my blacklisted words are in basic `'word'` style, I did not notice them before
But now I've **added full support** for showing all 4 styles accurately in **like_util.py** file
```python
set_dont_like('badword1', '#badword2', '[badword3', ']badword4')
```
[4 styles from here](https://github.com/timgrossmann/InstaPy#restricting-likes)

> *only `check_link` (in `like_util.py`) is affected by update (just 2 lines)

I don't understand git _branching_ so good, so I included this update in this PR

**Comment by timgrossmann** [comment]
@uluQulu Awesome!
I hope we can merge this ASAP!

@converge Could you check if everything works, please?

**Comment by luigifaticoso** [comment]
Really good!

**Comment by underclass** [comment]
@uluQulu @timgrossmann do you know if this will be merged into the master, I'm unsure of the process you guys go through to make a release, is there any way I can help?

**Comment by timgrossmann** [comment]
@underclass Unfortunately we don't have any real releases yet... Right now it still is a bit messy where we just merge PRs into the current master. We definitely have to change this.

This can be merged once @uluQulu fixed the conflicts and I got at least 2 approvals that everything works fine.

And probably more important, if this is something that can be set, e.g. a flag we need good documentation in the README for this feature.

**Comment by timgrossmann** [comment]
@uluQulu What was the reason for closing this one @uluQulu ?

**Comment by uluQulu** [comment]
@timgrossmann 
messed up with `git` while rebasing

**Comment by uluQulu** [comment]
Hey @timgrossmann it is live again 🤝
Couple of people use it, already, including me
**Note**: As @luigifaticoso reported from Python 2.7 I changed `timestamp()` (only available after v3) to `total_seconds()` which itself is only available after v2.7
(so, if somebody really wants to stick to v2.6 (or below) and use `unfollow_after`, I could rewrite **datetime-epochtime** conversion to use `arrow` method, instead ... _I checked max 0.75% of ppl use v2.6 (or below) from last weeks PyPi downloads xD_)

> Meanwhile, I **disabled** `unfollow_after` **for unmatched versions** by checking `python_version` from `platform` module and also, in log, send user information of it is only supported above version 2.7


One more thing I modified is,
now inside InstaPy class, `set_automated_followed_pool` is only called when the unfollow method is `onlyInstayFollowed==True` cos currently, other method(s) do not need (or use) automated followed pool, rather they get from live graphql, this speeds up the process for other method(s)

give it a go! @underclass @CharlesCCC @migueldierssen
how to test? -  **tip**: open up `set_automated_followed_pool()` in `unfollow_util.py` and add 
**print(automatedFollowedPool)** before the **return** line and **compare the users** according to the time you set in `unfollow_after` (you must follow some people before testing this, cos, before this change, users' follow time is not recorded)
```python
print (automatedFollowedPool)   #add this to compare results
return automatedFollowedPool
```
Note **that**, as I said above in description, currently, it only works with `onlyInstapyFollowed` method, cos other mehtods work differently, but if this initial code gets approved, I will write some new lines to get it work for all~

**Comment by CharlesCCC** [comment]
@uluQulu great work friend,  I can't give my opinion on go/no-go yet, since I haven't tested it.  but I'm hoping i can test this out by this weekend (hopefully tonight). will give a vote after test it out. 👍

**Comment by timgrossmann** [comment]
@uluQulu Awesome!
Thank you for sharing your work

**Comment by underclass** [comment]
@uluQulu I've had this running for a week now and I'm receiving the following in my logs, is this correct? It looks like the script can't unfollow these accounts, I have it set to unfollow 2 to test but runs through 30-40 accounts, time is set to less than a week.

WARNING [liveimagery]  --> Cannot Unfollow From InstaPy 1, now unfollowing: b'rachelkong'
INFO [liveimagery]  2018-02-17 04:18 ~ luispedrophoto,
 removed from csv
WARNING [liveimagery]  --> Cannot Unfollow From InstaPy 1, now unfollowing: b'luispedrophoto'
INFO [liveimagery]  2018-02-17 05:37 ~ image_wedding_company,
 removed from csv
WARNING [liveimagery]  --> Cannot Unfollow From InstaPy 1, now unfollowing: b'image_wedding_company'
INFO [liveimagery]  2018-02-17 05:39 ~ calla_royal,
 removed from csv
INFO [liveimagery]  --> Ongoing Unfollow From InstaPy 2, now unfollowing: b'calla_royal'
WARNING [liveimagery]  --> Total unfollowNum reached it's amount given 2
INFO [liveimagery]  --> Total people unfollowed : 2 
INFO [liveimagery]  Session ended - 2018-02-27 13:09:48
INFO [liveimagery]  --------------------

**Comment by uluQulu** [comment]
@underclass 
It's is an ordinary unfollow (`onlyInstapyFollowed=True`) procedure and has nothing to do with `unfollow_after` parameter
If you wanna test `unfollow_after`'s behaviour, be precise in seconds and compare results accordingly
lf you have applied the lines correctly and still, really thinks that it doesn't work for you, then I think it is pointless to keep this PR alive cos it was written just for your request
Good luck!

**Comment by timgrossmann** [comment]
@uluQulu I'm pretty sure it's worth keeping this PR alive and merging it since this is an awesome feature

**Comment by gustafsom** [comment]
Hi friends, I'm new to Instapy and Python. I'm having trouble using unfollow_after. Instapy is unfollowing users who started following on the same day. I've already made all the modifications reported above, but the problem continues.

Editing...

I found the reason. At some point (I do not know why) the date was not being saved in the _followedPool file. Thus, instapy unfollowing users who did not have the saved data.

**Comment by uluQulu** [comment]
@gustafsom 
_While writing it I have checked and found out that **only** `follow_by_list()` feature was not recording followed users (with `log_followed_pool()`) that's why I have added it in this commit, if you are using that feature to follow and applied the lines correctly, it should work fine for all_

Which feature are you using that you think does not record **datetime** or does not record followed users
Also if you have missed passing `logtime` variable in some of the lines, it **will not** record datetime. __Please, check modified lines again before proceeding.__

**Comment by riccardorighettiphoto** [comment]
Hello,
any chance to get this stunning feature in the origin/master repo? Unfortunately, I did to purge my working version of InstaPy and then re-applying all these amendments by hand.
Thank you.

**Pull request merged**
