### PR TITLE
PR - Fix `extract_text_from_element()`and `find_element*()` to `find_element()`

### LINKED ISSUE #6352: [BUG] Tries to lookup and follow non-existent users
This bug seems to occur when using the follow feature where users who liked a post in feed will be interacted with. However, it seems like InstaPy tries to follow a random label that is scraped from the webpage (like the date of a post).

## Expected Behavior
InstaPy only looks up profiles of real people and not other elements on page.

## Current Behavior
```
[xxx]  Got 4 likers shuffled randomly whom you can follow:
['www', 'yyy', 'SEPTEMBER 30', 'zzz']
...
[xxx]  Failed to get followers count of 'b'SEPTEMBER 30''  ~empty list
[xxx]  Failed to get following count of 'b'SEPTEMBER 30''  ~empty list
[xxx]  User: 'SEPTEMBER 30'  |> followers: unknown  |> following: unknown  |> relationship ratio: unknown
[xxx]  ~could not check if profile is public or private
[xxx]  --> Not a valid user: --> Sorry, could not check if profile is public or private
```

## Possible Solution (optional)

Better scraping and filtering of possible users to follow.

### LINKED ISSUE #6393: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
```
InstaPy\venv\lib\site-packages\selenium\webdriver\remote\webelement.py:358: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")
```

instapy version 0.6.14
windows 10

### LINKED ISSUE #6435: inappropriate, user_name, is_video, reason, scope
## Expected Behavior
Though it's working fine with other Account why am I getting the issue with this one?

## Current Behavior
  File "C:\Users\ishus\Desktop\bounds_follow_tags.py", line 20, in <module>
    session.like_by_tags(['hashtag_eg1 ','hastag_example2 '],amount=20)
  File "C:\Users\ishus\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1977, in like_by_tags
    
inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\ishus\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 618, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
## Possible Solution (optional)
update like_util.py

### PR DESCRIPTION
**Pull request by elulcao**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Do not include any personal data.

Fixes # (issue)
#6352 
*is_private_profile() when sometimes NoneType is returned

- Added filter in `extract_text_from_element()` for non-username elements.
- Fixed `is_private_profile()` when 'NoneType' object is not subscriptable
- Fixed `find_element*()` to `find_element()`
  - Functionality is the same, but now selenium 4 uses `find_element()`

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [x] Manual Test, 

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project, `black -t py34`
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by lukesikora — APPROVED** [review]
LGTM

**Comment by elulcao** [comment]
Hi @breuerfelix 
hope you are doing good, happy 2022 ✌️
if you have a chance to take a look to this PR would be nice, 
let me know any questions or comments

**Comment by gabinfoulard** [comment]
@breuerfelix we need your verification !!

**Comment by maury37** [comment]
Hi @breuerfelix, 
Any chance you can have a look at this PR ? 
We're blocked for now ! 
Thanks

**Review by breuerfelix — APPROVED** [review]

**Comment by Tolmino** [comment]
after that mayor change to way to use By from selenium.webdriver.common.by 
i have a not working instapy....

the error i have is that:
  in instapy.py, line 1990, in like_by_tags self.logger,
  in like_util.py, line 619, in check_link media = post_page [0] ["shortcode_media"] KeyError:0

i think that my webdriver is too old for use By .... 
what do you think ?

i'm using now geckodriver in 64bit version 0.30.0
firefox is in version 68.9.0esr

what is right version of geckodriver i must use ?
thanks in advance

**Pull request merged**
