### PR TITLE
possible solution for  #506

### PR DESCRIPTION
**Pull request by sojan-official**
This is a quick fix i use for #506 .
Let me know if we are planning to take this upstream and if there is a better way to do this. 
will be happy to contribute the code.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@sojan-official Hmm... Now I understand what you're requesting.

If you can add the right documentation for this, this could be interesting.
Add an example in the example.py
Add documentation in the Readme
Add the param to the method header where the two other parameters are described

I think key to this feature will we that it's documented to be understood.
Make sure people understand what the scroll is for.

Also make sure that the parameter stays optional, meaning that if you leave it out, the script keeps working as it is right now.

Thank you for contributing

**Comment by sojan-official** [comment]
@timgrossmann the mentioned changes are performed. Let me know if i missed something.

**Comment by timgrossmann** [comment]
@sojan-official Thank you for the changes! I'm really sorry that there are quite a few conflicts now, but the feed interaction changed a bit...

**Comment by sojan-official** [comment]
@timgrossmann  no problem. will look through the changes and see what can be done.

**Comment by sojan-official** [comment]
i think with the latest implementation this shouldn't be an issue. so closing the request

**Pull request closed without merging**
