### PR TITLE
Continue following

### PR DESCRIPTION
**Pull request by 0x00secJinx**
With the GUI enabled, I noticed that if you are running the follow_through_dialog function and you click out of the following window, the program would exit because it could not find the follow buttons. I hacked up a way to open the following window again and call the follow_through_dialog function again. The new instance of the function called returns back into the original instance and returns with all users followed.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@0x00secJinx Thank you very much for contributing.

@converge Would be awesome if you could check that, too. Thank you very much!

**Comment by converge** [comment]
sure, I'll review it by tomorrow

**Comment by converge** [comment]
sorry I'm not able to test it, I don't use the GUI.

**Comment by timgrossmann** [comment]
@0x00secJinx I'll try to test this in the next few days.
Sorry for the delay

**Comment by timgrossmann** [comment]
@0x00secJinx Any updates on this one?

**Comment by timgrossmann** [comment]
@0x00secJinx Is this still a problem?

**Comment by timgrossmann** [comment]
Closing this due to inactivity... Please reopen if the problem is still present

**Pull request closed without merging**
