### PR TITLE
Updated business_categories.md

### PR DESCRIPTION
**Pull request by JosteinFraNorge**
Added some more categories.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@herrgutt Awesome, hopefully we can add to the list more and more.
Thank you very much!

**Comment by visualheroes** [comment]
You can add the following:
- "Athlete"
- "Photography Videography"
- "Public Figure"
- "Artist"
- "Sport"
- "Ski Resort"
- "Photographer"
- "Consulting Agency"
- "Jewelry/Watches"
- "Sports & Recreation"
- "Wine/Spirits"
- "Travel Agency"
- "Local Business"
- "Product/Service"
- "Community"
- "Arts & Entertainment"
- "Professional Sports Team"
- "Arts & Humanities Website"
- "Community Organization"
- "Art"
- "Management Service"
- "Company"
- "Art Museum"
- "Clothing Store"
- "Art Gallery"
- "Graphic Designer"
- "Advertising Agency"
- "Advertising/Marketing"
- "Media/News Company"
- "Public Relations Agency"
- "Party Entertainment Service"
- "Education"
- "Professional Service"

etc..

**Comment by visualheroes** [comment]
Something very useful in the future: a way to interact only with selected categories.
For me it's the number one feature with the "location + hashtag" interaction.

Less likes/follows but very targeted interactions. It's what i do manually on instagram.

**Comment by timgrossmann** [comment]
@visualheroes Awesome, thank you for the list!
That's a really interesting feature, maybe you should create an issue for that so we can tag it as feature.

**Pull request merged**
