### PR TITLE
Validate action; Fix unsafe delete_line_from_file ;

### PR DESCRIPTION
**Pull request by sionking**
Like click validation is done to check not been blocked, if been blocked we sleep for 2 minute but we can also handle it differently in the future.

Unfollow validation is done to not remove a username from list since been unfollowed but Instagram blocked us from unfollwing so the user is still followed but removed from the list.

Fix unsafe delete_line_from_file #992

### CODE REVIEW

**Comment by sionking** [comment]
also a missing logfolder:
-def like_image(browser, username, blacklist, logger):
 +def like_image(browser, username, blacklist, logger, logfolder):

**Comment by CharlesCCC** [comment]
If the like is blocked, is that two minutes later, the block will still exist?  Sleep for two minute won't help to remove the block, right ?

**Comment by sionking** [comment]
It is better than liking 100 times an hour like it happens now, and get no like this seems much stranger.
of course we need to handle it somehow.

**Comment by sionking** [comment]
Why not merged ? It's working very good.

**Comment by Naramsim** [comment]
Right, this PR broke the script

**Comment by jeremycjang** [comment]
Hi @sionking , could you please clarify how this new code should function? I have the most recent pull of the master, but currently the program doesn't remove any users from my `FollowedPool.csv` at all, nor do I see any old or temp files created in the logs folder. The new `delete_line_from_file` is never triggered when the `unfollow_users` is called upon and  the `removed from csv` message is never displayed.

**Pull request merged**
