### PR TITLE
fix no posts exception; add track

### PR DESCRIPTION
**Pull request by sionking**
Fix no posts exception when scraping likes
Add track post/profile
Avoid prints for only one user

### CODE REVIEW

**Review by timgrossmann — APPROVED** [review]

**Comment by timgrossmann** [comment]
@sionking Thank you very much for those updates!

Why don't we want to log the activities if we only have one account?

**Comment by sionking** [comment]
too many logs when calling this function each time in a loop every time with one log only. and all the actively for the one user is already printed in the actions it those

**Comment by timgrossmann** [comment]
@sionking If we can get one more approval/tester I'll merge this, thank you very much for this addition! 👍

**Comment by timgrossmann** [comment]
@sionking Tested those small additions again, they work fine.
Let's just merge this.

Thank you for the additions!

**Pull request merged**
