### PR TITLE
Repathing scripts

### PR DESCRIPTION
**Pull request by binhonglee**
Addressing #112 

It is not tested in Windows as I don't have access to any Windows machine right now. Would be great if someone can test it out. If not, I'll test it myself later and update this pull request if needed.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@binhonglee Thank you!

**Comment by eduardocalazansjr** [comment]
The windows script is more complex than that, since it need the c compiler from microsoft and some windows sdk for build everything.

**Comment by timgrossmann** [comment]
@vlntdds Hmm... Thanks for the information. We'll maybe have to fix this if no-one fixes it and PR's

**Comment by eduardocalazansjr** [comment]
It's on my todo list, captain.
Will push everything ASAP (i guess in the next 3 days)

**Comment by timgrossmann** [comment]
@vlntdds 😄 
Thank you! You're really valuable for this project. I'm serious.
This wasn't meant to be a command 😉

**Pull request merged**
