### PR TITLE
Added date and time to log

### PR DESCRIPTION
**Pull request by dar2015**
Added date and time to log

### CODE REVIEW

**Comment by sionking** [comment]
I already added to mine

**Comment by sionking** [comment]
We can than debug better

**Comment by dar2015** [comment]
I didn't saw yours can you give a link to the commit?

**Comment by uluQulu** [comment]
thanks @dar2015 
it is amazing now, champion commit!

althought, it would be significantly delightful for eyes if you could put datetime into round brackets instead of square brackets
```python
INFO (2018-02-18 18:42:34) [foobar] 
```
looks **cooler** (_and more readable_) **than**
```python
INFO [2018-02-18 18:42:34] [foobar] 
```

**Comment by dar2015** [comment]
@uluQulu sure, but I would like the community to say what is the best wrapping for date.
What do you think round or square?

**Comment by sionking** [comment]
I really dont care lets go with 
INFO [foobar] [2018-02-18 18:42:34] 

I prefer the data to be afeter the user...
I mean start with the things that less changed ... and end with the changing one

**Comment by uluQulu** [comment]
@sionking 
when looked to log, `date` should have higher priority off `username`
_you can look for a certain date and then find data according to the username easily
but when the username has higher priority, it become an aggravating job_

> I meant in the multi-user perspective

@timgrossmann although will get a longer output with a _full datetime stamp_, this is literally required piece for the substantially effective **log**ging activity and I've been using it for the last days, works just smoothly 👌

**Pull request merged**
