### PR TITLE
Xpath to focus in the comment field

### PR DESCRIPTION
**Pull request by keryc**
replace: //a[@role='button']/span[text()='Comment']/..
to: //button/span[@aria-label='Comment']

### CODE REVIEW

**Comment by timgrossmann** [comment]
@kdzch Thank you for this change, is this something that happens in "every" release of Instagram or is this, again, some A/B-Test rollout thing?

I just tested it and I get the same problem when trying to get the comments.

**Comment by keryc** [comment]
The previous xpath failed, gave an error when trying to write in a field that was not selected.

**Comment by keryc** [comment]
At this moment I am running the robots and they are running correctly.

**Comment by keryc** [comment]
Well the tests were done with firefox

**Comment by timgrossmann** [comment]
@kdzch Double checked it in Safari, FireFox and Chrome.
Looks good, thank you!

**Pull request merged**
