### PR TITLE
Use _additionalData to pull graphql info

### LINKED ISSUE #4882: KeyError: 'media'
I'm getting this error right before the bot is about to like a post:
`File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 1914, in like_by_tags self.logger, File "/usr/local/lib/python3.6/dist-packages/instapy/like_util.py", line 606, in check_link media = post_page[0]["media"] KeyError: 'media'`

This is the last step it always reaches:

> .................................................................
> INFO [2019-08-16 12:07:55] [accountname]  Logged in successfully!
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> INFO [2019-08-16 12:07:55] [accountname]  Saving account progress...
> INFO [2019-08-16 12:08:00] [accountname]  Location [1/7]
> INFO [2019-08-16 12:08:00] [accountname]  --> b'213385402/london-united-kingdom'
> INFO [2019-08-16 12:08:11] [accountname]  desired amount: 25  |  top posts [disabled]: 9  |  possible posts: 44373096
> INFO [2019-08-16 12:08:18] [accountname]  Like# [1/25]
> INFO [2019-08-16 12:08:18] [accountname]  https://www.instagram.com/p/B1OO9VTHmlO/
>  
> INFO [2019-08-16 12:08:24] [accountname]  Sessional Live Report:
>     |> No any statistics to show
>  
> On session start was FOLLOWING xxx users & had xxx FOLLOWERS
> [Session lasted 1.77 minutes]
>  
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2019-08-16 12:08:24] [accountname]  Session ended!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

If anybody has an idea about what's going on I'll be very grateful

### PR DESCRIPTION
**Pull request by enilsen16**
This PR is similar to https://github.com/timgrossmann/InstaPy/pull/4892 to fix some of the UA updates.

close #4882

### CODE REVIEW

**Comment by beatdeddeer** [comment]
Awesome, thank you :)

**Comment by flug** [comment]
fix you pr @enilsen16

**Comment by breuerfelix** [comment]
@enilsen16 could you fix the travis ? its just some lines which are too long :)

**Comment by enilsen16** [comment]
Updated

**Comment by breuerfelix** [comment]
thanks a lot ! will merge this now :)

**Pull request merged**
