### PR TITLE
Set headless_browser default value to True

### PR DESCRIPTION
**Pull request by tibor**
Fixes issue `instapy.instapy.InstaPyError: ensure chromedriver is installed`(#2592 and similar)

### CODE REVIEW

**Comment by sionking** [comment]
Y?

**Comment by ghost** [comment]
yeah this doesnt make sense to do.

**Comment by timgrossmann** [comment]
@tibor @sionking @halalfood @uluQulu  This is a really tough one I'm thinking about for some time already, that error is not new to me...

There are basically two situations.
1. People want to use it on ubuntu/a server and will encounter this, creating dozens of issues because it does not work and they do not read the documentation. But new users are able to see the bot work when trying it out.

2. We change it to the, currently proposed, version which also works on any other system. We'd loose the "haptic" for new users who simply want to try it out on their local machine and might get confused when they only see the terminal output.

I think, since the ubuntu/server thing is more advanced, people should "simply" know that they have to adjust that (read the documentation) when they want to use it on a server.

**Comment by sionking** [comment]
But no real fix for chrome and proxy with auth

**Pull request closed without merging**
