### PR TITLE
Support cyrillic in logger messages #1350

### PR DESCRIPTION
**Pull request by denisemenov**
https://github.com/timgrossmann/InstaPy/issues/1350

## Expected Behavior

`INFO [alpajessica]  Session started - 2018-02-04 13:58:10`
`INFO [alpajessica]  Logged in successfully!`
`INFO [alpajessica]  Tag [1/9]`
`INFO [alpajessica]  --> зенненхунд`

## Current Behavior
`INFO [alpajessica]  Session started - 2018-02-04 13:51:15`
`INFO [alpajessica]  Logged in successfully!`
`INFO [alpajessica]  Tag [1/9]`
`INFO [alpajessica]  --> b'\xd0\xb7\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xb5\xd0\xbd\xd1\x85\xd1\x83\xd0\xbd\xd0\xb4'`

## Possible Solution (optional)
Remove `.encode('utf-8')` from all files.

## InstaPy configuration
Digital Ocean, Ubuntu 16.04.3 LTS, Python 3.5.2
I didn't test it on Python2.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@denisemenov Thank you for your contribution!

I'm not sure if that will break a lot of peoples use of instapy since it crashes if the terminal is not set up to use utf-8...

We probably have to check this on different platforms and wait until we have several statements of people whether this works or not.

**Comment by CharlesCCC** [comment]
I don't think we should remove the utf-8 encoding.

**Comment by sionking** [comment]
Hebrew,
We need to add it.
e.g
```
self.logger.info(
                            '--> Image not liked: {}'.format(reason.encode('utf-8')))
```
otherwise we get logger error.

**Comment by uluQulu** [comment]
hi @denisemenov 
it's amazing **idea**, to have a clear output in console!
**I wonder** one **thing**, after you did skip encoding output strings to utf-8 bytestrings **don't you** get **exceptions with strings** unsupported by your console? (**e.g.** say arabic, japanese or some german letters)

_my current language is also russian for non-unicode programs, it displays russian text without problems except when encounters a different non-unicode letter from other languages throws an exception_

**Comment by ademaro** [comment]
Work fine for me! Thank you!) macos, python3.6

**Pull request closed without merging**
