### PR TITLE
Fix a typo on doing like when already liked.

### PR DESCRIPTION
**Pull request by uuaing**
Fix issue when perform like on an already liked.

### CODE REVIEW

**Comment by uuaing** [comment]
Fix a typo on doing re-like.

**Comment by uuaing** [comment]
is_video not defined

**Comment by timgrossmann** [comment]
@robin-6 Thank you!

Are you actually using InstaPy_V1 reversion already?

**Comment by uuaing** [comment]
@timgrossmann, yes, I'm running V1 now, fixed some bugs and it running great! thanks.

**Comment by timgrossmann** [comment]
@robin-6 Could you create a PR for the fixed bugs? 😉

**Pull request merged**
