### PR TITLE
 Added new feature: do not interact with same users

### PR DESCRIPTION
**Pull request by ghost**
## Reason for changes
Bot used to interact with same users over and over again when dealing with:

- Interact with someone else's followers

 - Interact with users that someone else is following

## What has been changed
- Added option to store users bot has already interacted with in database
- Added check for repetitive users, based on database entries
- Added instruction how to use new feature in documentation

## Problem reference
#4556

### CODE REVIEW

**Comment by timgrossmann** [comment]
@mateuszpokojowczyk Sorry for the long delay. 
I'll try to review it as soon as possible and hopefully merge it right away then.

Really appreciate you updating the docs as well.

**Comment by ghost** [comment]
@timgrossmann Okay, no problem.
Waiting then.

**Comment by breuerfelix** [comment]
@timgrossmann do you know why the diff is this big even though alot of things mentioned in the diff are already in the dev branch ? this is really hard to review ..

**Comment by timgrossmann** [comment]
@mateuszpokojowczyk @breuerfelix Yeah, sometimes the diffing is messed up when the branches are not up to date with the current state of the destination branch. So rebasing the PR branch to current dev will resolve this. 👍

**Comment by mateuszpokojowczyk** [comment]
@timgrossmann It was up to date, but you updated the repo before reviewing this branch, so now it's not.

**Comment by breuerfelix** [comment]
@mateuszpokojowczyk could you please rebase the branch so the review will be much easier for us ? :)

**Comment by mateuszpokojowczyk** [comment]
@bruerlefix It's not my fault that the autor haven't reviewed it before merging other branches. I've spent a lot of time on this feature and not gonna spend a minute more.

**Comment by ghost** [comment]
@breuerfelix How can I do that?

**Comment by breuerfelix** [comment]
@mateuszpokojowczyk https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa try this one :)

**Comment by breuerfelix** [comment]
@mateuszpokojowczyk I realised that its enough that you close the PR and make a new one :) that's an issue with GitHub

**Pull request closed without merging**
