### PR TITLE
Skip User base on Profile Bio

### PR DESCRIPTION
**Pull request by AKwoKWH**

### CODE REVIEW

**Comment by AKwoKWH** [comment]
This is refer to my feature suggestions https://github.com/timgrossmann/InstaPy/issues/4531

and also others ppl request on filtering user using bio
Add your stop keywords in set_skip_users
```python
Session.set_skip_users(skip_bio_keyword=['free shipping','Order','visa','paypal'])
```

**Comment by timgrossmann** [comment]
@AKwoKWH Could you please add a short section about this new feature to the `DOCUMENTATION.md`? 😊 

For now, I've changed the base branch to develop since this is not only a fix but also some additional functionality.
We'll merge this into dev first and then with the next release into master.

Thank you very much for this addition!

**Comment by breuerfelix** [comment]
@AKwoKWH sorry for mentioning the documentation again but it would be a pleasure for us to finally merge this pull request, so all here left is a small entry in the documentation file :)

It would be a shame if this pull request will be open for months only because the docs are left :D the earlier we merge this, the less problems we have while merging :)

**Comment by papillon-unix** [comment]
Can we use this new feature or not yet?
`TypeError: set_skip_users() got an unexpected keyword argument 'skip_bio_keyword'`
Does not work on my side, but would be very very usefull!!! Thx in advance

**Comment by papillon-unix** [comment]
> It would be a shame if this pull request will be open for months only because the docs are left :D the earlier we merge this, the less problems we have while merging :)

Yes it would be terrible!! Can't we add it to the documentation by ourselves? It seems pretty clear how to use it!

**Comment by breuerfelix** [comment]
@papillon-unix could you be able to add some documentation and make a PR with this doc to master branch ?

so I can merge both at a time :)

**Comment by papillon-unix** [comment]
@breuerfelix I would love to, I will try to figure out how it works (am new on git) and let you know

**Comment by papillon-unix** [comment]
hi @breuerfelix I'm sorry, I tried to help but I really don't know how git works. I couldn't manage to make a pull request.
If it's helping I prepared the change for the documentation file : 

\##### Skip users based on bio

\`\`\`python
session.set_skip_users(skip_bio_keyword=['free shipping','Order','visa','paypal'])
\`\`\`
This will skip all users that have one these keywords on their bio.

**Comment by redsector72** [comment]
I see this in the Documentation, but it is not yet working.
I receive 
TypeError: set_skip_users() got an unexpected keyword argument 'skip_bio_keyword'

**Comment by breuerfelix** [comment]
@redsector72 could be that you forgot to update instapy ? cause i am able to pass this argument :)

**Pull request merged**
