### PR TITLE
Disabled instagram server checking #5207

### PR DESCRIPTION
**Pull request by wsbuck**
* https://isitdownorjust.me website seems to be down
* InstaPy fails the instagram server check and then aborts
* Commented out check in login_util.py until a better website checker is found

### CODE REVIEW

**Review by riccardovalente — COMMENTED** [review]
This change isn't needed. Just add  `want_check_browser=False` in your quickstart file (only available in the latest builds).

**Comment by timgrossmann** [comment]
@wsbuck @riccardovalente Maybe it makes sense to set this parameter to be false by default? :)

**Comment by riccardovalente** [comment]
> @timgrossmann Maybe it makes sense to set this parameter to be false by default? :)

I agree

**Comment by jonjo156** [comment]
> want_check_browser=False

only available in the latest builds of what exactly?

Thank you in advance

**Comment by timgrossmann** [comment]
@jonjo156 He meant the last version of InstaPy (0.6.5) you can get from PyPi 😄

**Comment by timgrossmann** [comment]
@wsbuck Thanks for the change, I've retriggered the CI, seemed like there was some error on black formatting.

If it runs through, we'll merge it 👍

**Review by timgrossmann — APPROVED** [review]

**Comment by jonjo156** [comment]
> @jonjo156 He meant the last version of InstaPy (0.6.5) you can get from PyPi 😄

Hi Tim,

Thanks for the reply. I have 0.6.5 and I have added want_check_browser=False in my second cell but still getting the server error. Can you help at all / does the want_chec_browser need to be in a specific cell ?

**Comment by timgrossmann** [comment]
@jonjo156 Sorry, please refer to the discord server for any kind of questions or help :)

**Comment by timgrossmann** [comment]
@wsbuck Messed up 😄 Could you please run the python black formatter and commit it again?

```bash
pip install black

black -t py34 .
```

**Comment by wsbuck** [comment]
Ok all checks passed now. Thanks for the help!

**Pull request merged**
