### PR TITLE
Like different pictures of a user's profile

### PR DESCRIPTION
**Pull request by ahmadudin**
- All feature requested on #484
- Add like_by_user() function that like each given user's posts
- Include set_user_interact() to expand functionality with other feature
- change follow_user_followers return value to list of followed user for further interaction feature

**Single Use**
```python
#Likes 10 random photo of geach given user

session.like_by_user(usernames=['friend1', 'friend2', 'friend3'], amount=10, random=True, media='photo')
```

**Comined Use**
```python
# Follows the people that a given users are following
# The usernames can be either a list or a string
# The amount is for each account, in this case 30 users will be followed
# Like and comment 5 random posts of each new followed users
# If random is false it will like and comment posts in a top-down fashion

session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['Awesome', 'Really Cool', 'I like your stuff'])
session.set_user_interact(amount=5, random=True) 
session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, random=False, interact=True)
```

### CODE REVIEW

**Comment by timgrossmann** [comment]
@ahmadudin Awesome!
I'll look into it and get back to you ASAP.

Thank you so much for contributing!

**Comment by timgrossmann** [comment]
@ahmadudin I just tested it and it already works very well.

Here are a few things I noticed:

- You need to add a little bit more documentation (take a look at the other PR on what I mean (Readme and examples.py))
- change the like_by_user() to like_by_**users** to keep the interface a bit more consistent

This is definitely my fault,  but we need to add another parameter to the `set_user_interact`-method, I updated the issue for the requirements.
- add another param which is `percentage=...` like on a lot of the other methods.
Me might want to follow 250 of the given users followers but only interact with ~10% of them.

> Also, while testing the other PR I ran across a "Sorry this page is not available"-Page which led to the script aborting instantly. Please make sure that your implementation will skip the current user and continue on with the next one. I couldn't find another "Sorry ..." page to test your implementation with it

Thank you very much for contributing!

**Comment by ahmadudin** [comment]
One thing i forget to mention, i also add `media=` parameter to` set_user_interact()` for more option for interaction

**Comment by timgrossmann** [comment]
@ahmadudin Perfect, I will check that out tomorrow and merge it into InstaPy if it's working as expected.

Thank you for the changes

**Comment by timgrossmann** [comment]
@ahmadudin I checked it again.
Works like charm now!
Thank you for this.

Feel free to go to BountySource and claim your bounty 😉 

Thank you for contributing, I hope you'll be contributing again.

**Comment by timgrossmann** [comment]
#484

**Comment by ahmadudin** [comment]
its just me or there are no claim button on the bounty source?

**Comment by timgrossmann** [comment]
@ahmadudin Yes... there is none... I already sent BountySource a message asking what's wrong.

Can't get the BountySoruce Issue to close when I close this issue here
Sorry for the delay

**Comment by timgrossmann** [comment]
@ahmadudin Just checked again, you can now claim your bounty 😉

**Comment by timgrossmann** [comment]
@ahmadudin Please fix #507 first

**Comment by timgrossmann** [comment]
@ahmadudin I approved your implementation.
Please make sure to submit a fix for #507 as soon as the problem is clear!

Thank you, looking forward to future contributions.

**Comment by stephane-archer** [comment]
How to use the `like_by_user` feature? @timgrossmann @ahmadudin

**Pull request merged**
