### PR TITLE
Fixes issue #6085

### LINKED ISSUE #6085: Instead of tagged posts interact_by_users_tagged_posts interacts with user's posts
InstaPy starts interacting with user's posts instead of interacting with tagged posts of the user when using `interact_by_users_tagged_posts` function.
## Expected Behavior
InstaPy should interact with user's tagged posts.
## Current Behavior
InstaPy interacts with user's posts.
## Possible Solution (optional)
I looked into the InstaPy source code and found the call to `get_following_status` navigates the browser to user's ig homepage immediately after it was set to user's tagged page. Therefore moving the call to `get_following_status` above `web_address_navigator` call inside `get_links_for_username` fixes the issue.
## InstaPy configuration
```python
from instapy import InstaPy

session = InstaPy(username=_username,
                  password=_password)
session.login()
session.set_do_follow(enabled=False, percentage=50)
# session.set_comments(["Cool", "Super!"])
# session.set_do_comment(enabled=True, percentage=80)
session.set_do_like(True, percentage=70)
session.interact_by_users_tagged_posts(
    ['anotherusername'], amount=10, randomize=True)
session.end()
```

### PR DESCRIPTION
**Pull request by abhisarshukla**
Move call to `get_following_status` above `web_address_navigator` inside
`get_links_for_username` function

## Description
This PR fixes the issue #6085, where InstaPy starts interacting with user's posts instead of interacting with tagged posts of the user when using interact_by_users_tagged_posts function.

Fixes #6085

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [x ] Test

## Checklist:

- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] I have checked my code and corrected any misspellings
- [ x] I have performed a self-review of my own code
- [ x] My code follows the style guidelines of this project, `black -t py34`
- [ x] My changes generate no new warnings

### CODE REVIEW

**Review by elulcao — APPROVED** [review]
Hello @abhisarshukla 
Thanks for taking care of this,

**Comment by abhisarshukla** [comment]
Thanks for reviewing the PR @elulcao.
Is it merged? I am sorry, I am new to github.

**Comment by elulcao** [comment]
> Thanks for reviewing the PR @elulcao.
> Is it merged? I am sorry, I am new to github.

Not yet, Im still waiting for Travis results.

**Comment by elulcao** [comment]
@abhisarshukla Merged 👍

**Pull request merged**
