### PR TITLE
initial commit / setup clarifai custom commenting

### PR DESCRIPTION
**Pull request by justusdeitert**
Pulling from Original

### CODE REVIEW

**Comment by justusdeitert** [comment]
sry i did something wrong! wanted to pull timgrossmann:master into my JustusDeitert:master not the other way around!

**Comment by timgrossmann** [comment]
@JustusDeitert Could you explain a little bit more what you did, please?
If this whole PR was a mistake, please close it. Thank you 😊

**Comment by justusdeitert** [comment]
Hey Tim! I'am sorry for the late response and sry... i should have closed this PR. I'am following your project since a while and I'am pretty amazed! Thank you for charing it to the Community. Its my first try getting into python so i quess my code is not that sophisticated.. 

the attempt of my fork is to use the clarifai functionality of instapy to auto generate comments based on a specific model, its works quite well yet. wish you all the best! cheers justus

**Comment by timgrossmann** [comment]
@JustusDeitert Hey, no worries!
I was just wondering what happened 😉 

If you, at one point, want to PR this again, feel free to do so, sounds really good and useful.
I think you just have to make sure that you don't modify dozens of files and push all your quoickstarts and everything 😊 
If you need some help, let me know 👍

**Pull request closed without merging**
