### PR TITLE
fixes load button not found issue ( #857 )

### PR DESCRIPTION
**Pull request by converge**

### CODE REVIEW

**Comment by kuzne4eg** [comment]
still mising the code on line 71. just pulled and tested. I had to add manually "for i in....etc".

**Comment by converge** [comment]
@kuzne4eg it's here: https://github.com/converge/InstaPy/blob/5dbd970f0d8d63a7d41c58f5249979f94f5488a3/instapy/like_util.py#L76

Did use used the "command line instructions" ?

**Comment by kuzne4eg** [comment]
@coverge don't think i understand what you exactly mean.
Just made a new instalation on VM with git clone, checked the code and found the part is missing.
I only work with command line.
But sorry, i'm not good programming at all, only tester...

**Comment by kuzne4eg** [comment]
https://github.com/timgrossmann/InstaPy/pull/888/files 
should work!!! i just have
print ("Load button not found, scrolling.... yohoooooo!")
xD

**Comment by converge** [comment]
@kuzne4eg thank you for your test!! Nice of you take your time to help.

Can we merge it @timgrossmann ?

**Pull request merged**
