### PR TITLE
fixed problem with no follower count on completely new account

### PR DESCRIPTION
**Pull request by timgrossmann**
> Fixes the issue with crashing when the script is run with an entirely new account where there is no follower amount on the profile page

### CODE REVIEW

**Comment by eduardocalazansjr** [comment]
If you get the followers number from `window._sharedData.entry_data.ProfilePage[0].user.followed_by.count`, the issue is gone and we avoid the DOM differences between profiles/accounts.

**Comment by timgrossmann** [comment]
@vlntdds Thank you, i'll change that.
I'll really have to look into what this _sharedData is...

Hmm, well when trying this in the console I get:
```
VM219:1 Uncaught TypeError: Cannot read property '0' of undefined
    at <anonymous>:1:42
```

**Comment by eduardocalazansjr** [comment]
@timgrossmann you have to use it on your profile page, i guess.

**Comment by timgrossmann** [comment]
@vlntdds Hmm I tried it in chrome and safari, but both times with an account without any posts, that might be the problem. Does it work for you?

**Comment by timgrossmann** [comment]
@vlntdds Could you test it with this print_log_writer again, please?

**Comment by eduardocalazansjr** [comment]
@timgrossmann just realized that if you click on the "person" icon on the top to go to your profile, the entry_data.ProfilePage doesn't exist, but entry_data.FeedPage exists, but doesn't hold the followers count.
If you go to the profile url, the entry_data.ProfilePage exists.

It seems to work on a brand new (and empty) account and for my principal account.

**Comment by timgrossmann** [comment]
@vlntdds Ahh alright, now I got it.
Thanks for checking it out. Works pretty good now!

**Pull request merged**
