### PR TITLE
set_lower_following_count implementation Issue #908

### PR DESCRIPTION
**Pull request by fbleite**
Created feature for not interacting with user if the number of following is less than a minimum set by method set_lower_following_count. Issue #908

I've pretty much maintained the same coding style based on the set_upper_follower_count and set_lower_follower_countfor my implementation.

There are a couple of things that could be improved for better code readability, will continue working on that and propose another pull request later 👍 

Also are there any plans to implement unit tests? Can I take a stab at it?

### CODE REVIEW

**Comment by fbleite** [comment]
I have also done some refactoring on the checking if the number of followers is within the limits to a separate function.

Added unit tests to it and configured travis CI to run with the unit tests.

Now I'm a bit of a git newbie, I'm not sure why the pull request is showing too many commit that aren't mine here...

**Comment by timgrossmann** [comment]
@fbleite Awesome!
I think we can merge this as soon as you rebased it onto the newest master. 
There are too many commits in-between...

Thank you for contributing!

**Comment by luigifaticoso** [comment]
Any updates on this? it is an awesome feature!

**Comment by timgrossmann** [comment]
@luigifaticoso It definitely is, we only need the rebase on master 😄

**Comment by fbleite** [comment]
I'm not sure exactly how to fix this, I may just delete this fork, re fork, re apply the changes and make another pull request.

Unless anyone has some tips here :)

**Comment by timgrossmann** [comment]
@fbleite You can checkout the master branch, pull the latest changes and then checkout your branch and do a `git rebase master`.

Edit: Just saw that you made the changes to your forked master branch.
Might be easiest to just fork it again 😄

**Comment by timgrossmann** [comment]
@fbleite Any updates on this?

**Pull request closed without merging**
