### PR TITLE
Added a new feature: Quota Supervisor (DISCONTINUED)

### PR DESCRIPTION
**Pull request by uluQulu**
**DISCONTINUED**

> If you have downloaded it, please revert back changes to prevent conflicts or solve further possible conflicts yourselves

### CODE REVIEW

**Comment by sionking** [comment]
Dude ! you missed the real important information ! what did you had to lunch !?

Kidding... it is too long reading please just summarize the feature and not the all process ..
I do want to get ride of my pickle limit design, but it is simple and working and easy to read from any-where please keep on this in the design.


Sionking

**Comment by uluQulu** [comment]
right @sionking it really is too long, I am bad at writing brief reviews that I can't quit details :/
 I was busy lately soon will add a few lines to README including information on how to launch and use the supervising facilities.
Although Quota Supervisor is a sophisticated controller, I think you can simplify it, too, to supervise daily follows/likes only (at same amount)..
By the way thanks for the pickling method, this is built on your ideas using datetime :-)

**Comment by fegomess** [comment]
And how can i use it? Is it already merged so i can download it? By the way, its amazing.

**Comment by sionking** [comment]
Great job BTW! clean code! I will be first to try.
Did you make an easy reader, to access the current values from anywhere ?

**Comment by sionking** [comment]
I, for example read all pickles files from 1 manager PC and export all to 1 readable text file.
So I can see last executed action and check nothing is stuck/crash in one click.

**Comment by sionking** [comment]
What about sleeping at lunch time ? but everyday my lunch is not at the same time ?
How sophisticated it can be ?

**Comment by uluQulu** [comment]
Thanks @fegomess 
It's is still not merged but you can pull full project from my fork, after every update I'm solving conflicts and rebasing everyday so it is up-to-date with main repo, yet..

**Comment by uluQulu** [comment]
hi @sionking, because of it's complicated duties and access to many facilities, I tried my best to do standalone supervisor
Uhm, I have never thought you would really need to read kind of log data, where I also managed add 2 SQL query lines to delete all old logs to keep sueprvisor fast at querying time (bcos it is mostly based on querying) BUT if you really want to keep log files and read them:
 change SQL DELETE lines (2 lines) from 24/2 to e.g. 1000/200 so it keeps logs so long..or just delete those lines from InstaPy class.. after this, you can dump data and write to any file.. ask me at Slack for more.
BTW, SQLite is pretty reliable and I have used tact mechanism which will not bring out any errors and will not allow even 1 more like or server call... don't worry you :-)

**Comment by uluQulu** [comment]
@sionking Lunch time, well, I really not thought of :D 
if you have a dynamic lunch time interval, we can do some probablities but until you will use customized triggers it will be inaccurate and can sleep while you meant not..
 Okay, add this
```python
if data['state'] == 1:  #start processing if verified
    #add below
    real_hr= datetime.now().strftime('%H')
    if real_hr in range (14,16):   #hour(s) of lunch time
        sleep(3500)
    #continue inspection...
```
or if you want to be accurate in minutes
```python
if data['state'] == 1:  #start processing if verified
    #add below
    real_hr= datetime.now().strftime('%H')
    real_min=datetime.now().strftime('%M')
    mins=rel_hr*60+real_min
    if mins in range (835, 928):    #minutes of lunch time (from 13.09 to 15:45)
        secs=(rel_hr*60+real_min)*60
        sleep(secs)
    #continue inspection...
```
_Add it into `quota_supervisor` function in **util.py** file_

> Remember *realtime verifications always consume a piece of processor, consider using less

Hope helped! :-)

**Comment by sionking** [comment]
why DISCONTINUED?

**Comment by uluQulu** [comment]
This is a universal feature which is **accessing so many files** to do inspection. And having even a little indentation after a new pull may bring the problems.
I did solve all conflicts **for a while**, but I see it didn't bring any attention to _merge_,

> so I am sorry guys, I just can't support it anymore.

@sionking

**Comment by timgrossmann** [comment]
@uluQulu I'm sorry to hear this...
I hope you can understand that a PR that is this big is really hard to test and make sure that everything works... I already merged too many PR's that broke something in the end which was not what was intended.

Looking forward to future PRs

**Comment by uluQulu** [comment]
I wrote there the possible problems:
1. Icons I made for Mac(.icns) and Linux (.png) would not work for toast notifications 

 Also, to decrease the incompatibilities in future, I modified only very few parts,. except **break points** and **inspections**, included almost everything in new functions.
There are guys using it (_although discontinuation_), and not yet complained a bit, but offered new ideas,..
 
Anyways, I am new in programming, but I did not just put out code without thinking result, I spent last week testing every single step..
_it was a pleasure to write it, that actually, what I learnt about Python started from Quota Supervisor_ :-)
@timgrossmann 

EDIT (update): **MULTI-USER SUPPORT ADDED** (_every single **unique** user now owns a database_)

**Comment by keusta** [comment]
@timgrossmann Instapy need clearly this feature for a true V1..
and a fresh interface 
..with pretty reports... 
@uluQulu keep working on secret ahah ;)

**Pull request closed without merging**
