### PR TITLE
Multidimensional revisions & enhancements; Mainly- moved relationship bounds verification into `validate_username` definition AND redesigned `follow_user_followers` & follow_user_following` features to support relationship bounds verification & have on-the-go interactions

### PR DESCRIPTION
**Pull request by uluQulu**
As of @DimIsaev's second request at #1858,
**Added** **relationship bounds** _verification_ support to `follow_user_follower` & `follow_user_followers` which _costed_ the **redesign** of `follow_through_dialog` definition.
* **Now**, it gets the list of usernames in the desired amount from the dialog box and then does the rest of the procedure through `follow_by_list`.
**It has** several **benefits**:
**1**. having **relationship bounds** _verification_
**2**. having **on-the-go** interactions (_if enabled_) **rather** than following **all of the** users **and then** _starting_ interactions
**3**. **more reliable** and **efficient** control **over sleep delay**, now it takes **a break time** **per** _overall follows_ in the called feature, **rather than** break times **per user**
* **Also**, enhanced the **process of** getting _links of usernames_, **now** it will **scroll as required** and **will get links regardless of the amount** (_used_ the previously **shared** method at https://github.com/timgrossmann/InstaPy/issues/1548#issuecomment-372803884)

* **For relationship bounds** _verification_ to be _used for other features_, I **did pull** it _into a new_ definition, actually, it's **more friendly** and already **existing** definition- `validate_username`, and did some **other improves** in it, too.
* Now, `check_link` definition _does_ **only its job**- checking the links **only**, _rather than_ checking links and _verifying users_.
* Also, at `check_link`, `validate_username` and `get_relationship_counts`, added **a new layer** of **current URL** checking, which is helpful:
**1**. if the **current URL** is the same with _to be_ navigated, it **will not navigate** to it again (_saving server requests_)
**2**. if the URLs **are different**, then it **will navigate** to the required URL.
_**it is very helpful** at certain **situations**, e.g. if **relationship bounds** _verification_ is **disabled**, check_link **does not need to** navigate to the _post page_ **again**, **OR** if **relationship bounds** _verification_ is **enabled**, `follow_given_user` does **not need to** navigate to the _profile page_ **again**, cos it **already navigated** in `get_relationship_counts`_

* **Also, moved** `get_relationship_counts` from `unfollow_util.py` to `util.py` **to avoid circular dependant imports** and **it is more** like a _general utility_ to be _there_.

* **Interesting thing**: added **simulated follows**- after changing the _mechanism_ of following through dialog to following on-by-one **separately**, I realized **it would be** pretty _non-humanly_ activity if you just scroll a huge list **and do** nothing, that's why _I did add_ a **simulated following** _mechanism_, which will follow a bit of users (_max of ~4 per 100_) in _random intervals_ during the scrolling until getting _sufficient amount_ of links and it will pass those simulatedly followed users to main processer and _if any of those_ users is **not valid**, it **will unfollow** them (**simulated** users are _added_ to the main list **in random** order) immediately.
**I think** this idea of **simulated actions** _should be_ applied to other features, **as well**, _cos_ scrolling a list (_even a huge list_) and **doing nothing** seems pretty _weird_ _to be smartly handled_.

* **Enhanced** `unfollow_users` function a bit and added missing **capability** to remove unfollowed user from followed pool CSV file (_if exists_).

* **Prior break time** handling in `follow_user_followers` & `follow_user_following` based on 10 follows is **now replaced** with smarter randomized **range** of `[7, 14)` and sleep delay is **also gonna** be randomized **between** `85` & `100` percents of user-provided or default (`600`) time and these values are gonna change **periodically**.

* **Alongside**, `follow_user_followers` and `follow_user_following`, I've also added **relationship bounds** _verification_ support for `follow_by_list` feature.
* Also some modifications is **done in syntax** for more **generalized** structure and **good** looking _output_.

The **enhancements done** for `follow_user_followers` were also **recently requested** by @OGHARRY (_**relationship bounds** _verification_ support_) in #2003 and by @FranklinClinton (_**relationship bounds** _verification_ support_ and _on-the-go_ interactions) in #2009
> **I** have tested several times, if there are still, some **logical** or **mechanical** errors, please **notify**!

### CODE REVIEW

**Comment by timgrossmann** [comment]
@uluQulu You sir are incredible!
Thank you very much for all those improvements.

**Comment by DimIsaev** [comment]
@uluQulu  

very cool 
very speed  testing

**Comment by uluQulu** [comment]
Thank you my friends @timgrossmann, @DimIsaev.


**Recently**, I thought of **renaming**  `follow_given_user_followers`  and `follow_given_user_following` to `get_given_user_followers` and `get_given_user_following`. :.)

**Cos** now those 2 definitions _are not following_, **instead** _returns links_ for further follows, so renaming **would be cool**. 
 **But then** **I saw that** there are already existing definitions at those names which **are used** for `interact_user_following` & `interact_user_followers` methods to return the links **from a dialog box**.


**And** I **noticed that** those guys- `get_given_user_followers` and `get_given_user_following` are doing **the same thing** as NEW `follow_given_user_followers`  and `follow_given_user_following`.
**So**, I did **remove** _prior_ `get_given_user_followers` and `get_given_user_following`. **And then** **renamed** `follow_given_user_followers`  and `follow_given_user_following` **to** `get_given_user_followers` and `get_given_user_following`.


**Now** `interact_user_followers` and `interact_user_following` methods **are using** those **smarter** definitions. I have also added **support for** _simulated follows_ from a dialog box for these _interaction based methods_.

**Also**, added **URL checker** to `get_link_for_username` function, now it **will not navigate** to the already loaded webpage **again**.

_**The result** of last commit is **enhanced versions** of `interact_user_followers` and `interact_user_following` features and **more cleaner** source code with `2` **lesser** duplicated definitions._

>**BONUS**: fixed **quote conflicting** while trying _to send a comment_ which _itself contains_ a quote (_**single** or **double**_, _**escaped** or not_) issued at #2011.

**Comment by timgrossmann** [comment]
@uluQulu I tested it with some basic testing.
I think we can merge this now.

Thank you very much for this!

**Comment by joanroig** [comment]
Awesome work @uluQulu !

**Comment by jeremycjang** [comment]
@uluQulu Thank you for these changes and for also keeping awesome documentation! In the ```like_util.py``` the ```from .unfollow_util import get_relationship_counts``` needs to be changed to ```from .util import get_relationship_counts``` to support your changes. Small detail, but would be good to merge!

**Comment by uluQulu** [comment]
Thanks guys 😁,
@jeremycjang looks like you are deep into details, cool, but now `get_relationship_counts` is a part of `validate_username` definition rather than previous `check_link` definition AND both `validate_username` and `get_relationship_counts` definitions are located inside **util.py** file which means there is no need to import it into **like_util.py** file.

It worths to notify that, the message I've included in the description comment of #1969 PR:
  
change-to-util.py
is updated as,
```erlang  
from instapy.unfollow_util import get_relationship_counts
```
is changed to
```erlang  
from instapy.util import get_relationship_counts
```
_in case of you would like to access those counts from **quickstart** scripts_

And to be honest, I could not find a place to put it into README, maybe in future there can make `Tools` sections in there to include such small but useful standalone tool.

And a good style in README belongs to this project, really, although I am very new in GitHub, I have seen lots of of project and to say, this project's documentation is simply excellent and I tried to follow that tradition :)

**Pull request merged**
