### PR TITLE
adding delays after load cookie in login.util.py

### LINKED ISSUE #5993: Cookie file for user Loaded ....  Issue with cookie for user - IT IS FALSE: COOKIE IS GOOD
## Expected Behavior

use same cookie until instapy's users decide to create a new one

## Current Behavior

Discarging an old cookie activate instagram's bot detection
You have modified instapy to delete old cookie and create a new one, but this think active instagram's bot detection

## Possible Solution (optional)

To use my old cookie: 
every time instagram delete my old cookie i'm stopping instapy, i'm putting my old cookie (that i have saved), and trying to relogin, and after 2 or 3 time i can login with my old cookie.
If the cookie is good, why we are creating a new one at every login ?

### PR DESCRIPTION
**Pull request by Tolmino**
adding delays after load cookie, permit instapy to have time for cookie login, without erase it, if is valid

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Do not include any personal data.

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [x] Test

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project, `black -t py34`
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Polkyanik** [comment]
@Tolmino , fantastico!!
ho questo problema sul mio raspberry , aspettavo una soluzione... il tuo sembra funzionare (Y) (Y) 
i had the same problem and was waiting for an update .... great !! I'm running instapy automatically and it would seem to work .. what do you think, could it be a solution? @elulcao

**Comment by Tolmino** [comment]
Yes, that issue seem to exist only on hardware slow.
Adding delays, seem to be perfect on raspberry and on old pc.
And on fresh hardware, I think that 12 seconds of delay can't be a problem !

**Review by zubus — APPROVED** [review]

**Comment by elulcao** [comment]
> Yes, that issue seem to exist only on hardware slow.
> 
> Adding delays, seem to be perfect on raspberry and on old pc.
> 
> And on fresh hardware, I think that 12 seconds of delay can't be a problem !

Hello guys 
I will check today!
Thanks for contributing to the project

**Comment by elulcao** [comment]
@Tolmino 
Could you check and format the code with `black -t py34`
CI reported those failures 
Thanks,

**Comment by greyslater** [comment]
nice to see that there is work in prorgress about this fu**** cookie issue

**Review by elulcao — APPROVED** [review]
Fixed the black format
Updated the CHANGELOG

**Pull request merged**
