### PR TITLE
added FIREFOX remote webdriver to set_selenium_remote_session, pep8

### PR DESCRIPTION
**Pull request by 1pyxa1**

### CODE REVIEW

**Comment by timgrossmann** [comment]
@1pyxa1 Thank you for contributing! 
I'll test this as soon as possible.

If there is anyone that could approve this PR, I'd be happy to merge this next time I check GitHub!

**Comment by timgrossmann** [comment]
@converge Could you please quickly test this?

**Comment by converge** [comment]
Testing using OSX, Chrome and Firefox. Working fine in both.

There are two main points to think (maybe next release).

I had Selenium 2.53.6 and got this problem:
```
$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password, use_firefox=True)
  File "/Users/jp/Documents/workspace/InstaPy/instapy/instapy.py", line 100, in __init__
    self.set_selenium_local_session()
  File "/Users/jp/Documents/workspace/InstaPy/instapy/instapy.py", line 116, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/tp/kyn4jj355211h33q1yprn9cm0000gn/T/tmpIpdjdn If you specified a log_file in the FirefoxBinary constructor, check it for details.
```
We can check Selenium version, it will avoid new issue/tickets

--

I didn't have geckodriver, we can check it before run the bot
```
$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password, use_firefox=True)
  File "/Users/jp/Documents/workspace/InstaPy/instapy/instapy.py", line 100, in __init__
    self.set_selenium_local_session()
  File "/Users/jp/Documents/workspace/InstaPy/instapy/instapy.py", line 116, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```
And a minor issue because it wont affect the bot usage, Firefox render it weird:
https://i.imgur.com/895qZ33.png

**Comment by timgrossmann** [comment]
@converge Thank you very much!

**Comment by thisishotdog** [comment]
Although the images not loading won't effect the script, its a bit strange that all images fail to load since this merge.

Is this something that will be looked at? I'm no Python expert myself, but I suppose I could give it a go figuring out what's up with it if nobody has the time?

**Comment by converge** [comment]
@thisishotdog help is always welcome. It would be great if you could fix this.

**Pull request merged**
