### PR TITLE
#919 Smart hashtags Sort parameter

### PR DESCRIPTION
**Pull request by harrypython**
In addition to sorting random and Top (equivalent to popularity or rank in the json) we can order by relevance (same name in the json) of the hashtag.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@harrypython This is a great idea!

Thank you very much!

**Comment by timgrossmann** [comment]
@harrypython Any updates on this? Would really love to merge this!

**Comment by harrypython** [comment]
@timgrossmann 
To be sure about the between popularity and results I sent a direct message to faymontage, the creator of the Display Purposes, he replied my "Hello" but didn't return contact when I asked about the difference between popularity and results :/

**Comment by timgrossmann** [comment]
@harrypython Interesting... If we can't explain it, I think we should not have that option there.
It probably will only confuse people

**Pull request closed without merging**
