### PR TITLE
Update like_util.py

### LINKED ISSUE #6144: Cannot detect post media type. Skip https://www.instagram.com
from instapy import InstaPy

session = InstaPy(username='xxxxxxxx', password='xxxxxxxx', headless_browser=True)
session.login()
session.set_action_delays(enabled=True, like=120)
session.set_user_interact(amount=3, randomize=True, percentage=100)
session.like_by_tags(['car'], amount=500, interact=True )
session.end()

### LINKED ISSUE #6243: Cannot detect post media type. skip
Hi. 
Im working on windows and python 3.9 and latest instapy version.
my code:

from instapy import InstaPy

session = InstaPy(username="<my user>", password="<my pass>")
session.login()
session.like_by_tags(["tag"], amount=1)

### PR DESCRIPTION
**Pull request by BitCode-in**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Do not include any personal data.

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [x] Test

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have checked my code and corrected any misspellings
- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project, `black -t py34`
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by doxmey** [comment]
works bro thanks!

**Review by doxmey — APPROVED** [review]

**Review by doxmey — APPROVED** [review]
Works!

**Review by ergism — APPROVED** [review]

**Review by eupimenta — APPROVED** [review]

**Review by d2vin — APPROVED** [review]

**Comment by d2vin** [comment]
I'm having trouble finding the like_util.py file on instapy. any ideas?

**Comment by Marcaveli** [comment]
Changed my like util script and ran into the same problem. Additionally copy and pasted full script, renamed to like util and still getting nowhere. Is there a step I'm missing?

**Review by dsfrederic — APPROVED** [review]

**Comment by Marcaveli** [comment]
Thanks for the help Yuceltoluyag, however, that link is what ultimately led me here. It seems most people's fix worked with just the replacement of  span to div, however I'm still running into "Cannot detect post media type.Skip..."

Is it necessary to update or delete the like_util.cpython-39 in the _pycache_folder?

**Review by rafaelbmateus — APPROVED** [review]
LGTM

**Review by KonradLinkowski — APPROVED** [review]

**Comment by faizzxt** [comment]
sorry i'm new in coding
can someone please someone tell me how do i install/fix it ?

**Comment by KonradLinkowski** [comment]
> sorry i'm new in coding
> can someone please someone tell me how do i install/fix it ?

You have to make the same changes in your local library as in this pull request
https://github.com/timgrossmann/InstaPy/pull/6143/files

**Review by KonradLinkowski — CHANGES_REQUESTED** [review]
Doesn't work for me

**Review by ZMcGuckin — APPROVED** [review]

**Comment by sherxyar** [comment]
> I'm having trouble finding the like_util.py file on instapy. any ideas?

same :/
which directory should I search?
edit : i searched it up in windows search.
edit 2 : for me it was in line 903, i changed as said & it worked 💐.

**Comment by KonradLinkowski** [comment]
> > I'm having trouble finding the like_util.py file on instapy. any ideas?
> 
> same :/
> which directory should I search?

Root directory. How did you open library code?

**Comment by rishabhkd** [comment]
I  am still getting error after making the changes. any new updates?

**Comment by aleff-github** [comment]
it not works, when you change it gekodriver will close after a photo was opened

**Comment by thekorko** [comment]
> 
> 
> it not works, when you change it gekodriver will close after a photo was opened

I have the same issue, instead of displaying "Cannot detect post media type. Skip", now it simply crashes.
Logs say nothing:
```
INFO [] [account]  --> b'account_x'
INFO [] [account]  username actions: following=False commenting=True liking=True story=False
INFO [] [account]  Getting account_x image list...
INFO [] [account]  Post [1/4]
INFO [] [account]  https://www.instagram.com/p/given_post/
INFO [] [account]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 300 users & had 300 FOLLOWERS
[Session lasted 10 minutes]
INFO [] [account]  Session ended!
```
Any clues¿?

**Review by dermatz — COMMENTED** [review]
After this change the session ends.

`.../like_util.py", line 638, in check_link media = post_page[0]["shortcode_media"] KeyError: 0`

**Comment by alokkumarsbg** [comment]
#

> After this change the session ends.
> 
> `.../like_util.py", line 638, in check_link media = post_page[0]["shortcode_media"] KeyError: 0`

# #6202 #6195  This Pull request fixes the issue. Waiting for Approval for merging to Main Branch

**Comment by kartikey15** [comment]
"Cannot detect post media type. Skip..."
HELP!!!

**Comment by PiratesGomez** [comment]
Cannot find line 903, its doesnt exit (maybe got updated), but the error is the same.

**Comment by aleff-github** [comment]
@kartikey15 @PiratesGomez try using this repo https://github.com/schealex/InstaPy/zipball/develop

**Comment by kartikey15** [comment]
> @kartikey15 @PiratesGomez try using this repo https://github.com/schealex/InstaPy/zipball/develop

Ok

**Review by filiperivelli — APPROVED** [review]
I made a test using the master branch wich last commit is 3b94077df9f3ecd78c5717f1b0e239187093a961.
I made the changes as described in this PR and it works perfectly.

**Comment by kartikey15** [comment]
> I made a test using the master branch wich last commit is 3b94077df9f3ecd78c5717f1b0e239187093a961.
> I made the changes as described in this PR and it works perfectly.

What should i do to work it now?

**Comment by filiperivelli** [comment]
> > I made a test using the master branch wich last commit is [3b94077](https://github.com/timgrossmann/InstaPy/commit/3b94077df9f3ecd78c5717f1b0e239187093a961).
> > I made the changes as described in this PR and it works perfectly.
> 
> What should i do to work it now?

First of all, you have to install the the InstaPy from the branch master, you can see the instructions here:
[https://instapy.org/additional-information](https://instapy.org/additional-information)

Then you have to change the file like_util.py as described in this pull request, but the line number changes you have to find it by hand.

**Review by filiperivelli — CHANGES_REQUESTED** [review]
I think you should update your repository and make this change again because this file is a little different from the InstaPy branch master.

**Comment by Serfentum** [comment]
I've the same problem after changing like_util.py

> After this change the session ends.
> 
> `.../like_util.py", line 638, in check_link media = post_page[0]["shortcode_media"] KeyError: 0`

**Review by farshis — APPROVED** [review]

**Review by farshis — APPROVED** [review]

**Review by rahuljeyasingh — APPROVED** [review]
it works!

**Review by ardada2468 — APPROVED** [review]

**Comment by elulcao** [comment]
Fixed via #6202 
If any other issue please create new ticket explaining the problem.

**Comment by bboymega** [comment]
Not working ryt now

**Comment by shachar-ash** [comment]
Even after the fix it is still not working right now. I'm still getting the same "cannot detect post media type" messages.

**Pull request closed without merging**
