### PR TITLE
Fresh interact-by-comments: load unlimited comments & Add demographics filters: gender, age, multicultural appearances & Many more changes

### PR DESCRIPTION
**Pull request by uluQulu**
Hi there!

Implementation is complete. And soon, will try to write the required documentation in details.

Meanwhile, you can add like,
```python
session.set_demographics_filters(enabled=True,
                                 gender="feminine",
                                 gender_probablity=0.70,
                                 age=-40,
                                 age_probablity=0.54,
                                 multicultural= ["middle eastern", "white", "asian", "latino"],
                                 multicultural_probablity=0.27,
                                 unrecognizable="disallow"
                                 )
```
to your quickstart script and enjoy targeting users by demographics filters.
> Yeah, to test it you should pull my fork and must have a Clarifai API key (_set it with `set_use_clarifai()`_ as usual).

---

🖐
---

### CODE REVIEW

**Comment by timgrossmann** [comment]
@uluQulu Can I trust my eyes 😄 Qulu is back in business

How are you doing?

**Comment by ghost** [comment]
I have this problem:


Traceback (most recent call last):
  File "C:/Users/*****/Documents/GitHub/reallyhalalfood/InstaPy/quickstart.py", line 39, in <module>
    session.set_demographic_filters(enabled=True, gender="feminine", gender_probability=.5, unrecognizable="disallow")
AttributeError: 'InstaPy' object has no attribute 'set_demographic_filters'

**Comment by ghost** [comment]
whoops! due to my misspelling! I'm testing this out

**Comment by ghost** [comment]
seems to be working fine. going to keep running.

**Comment by ghost** [comment]
Not sure if it is related to this branch but I do run into this a lot now which I wasn't running into before:


Error

Please wait a few minutes before you try again.

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
Receive this bug now in this branch:

`    session.like_by_locations([b], amount=random.randint(1, 10), skip_top_posts=False)
  File "C:\Users\Adil\Documents\GitHub\reallyhalalfood\InstaPy\instapy\instapy.py", line 1492, in like_by_locations
    validation, details = self.validate_user_call(user_name)
  File "C:\Users\Adil\Documents\GitHub\reallyhalalfood\InstaPy\instapy\instapy.py", line 1324, in validate_user_call
    self.logfolder,
  File "C:\Users\Adil\Documents\GitHub\reallyhalalfood\InstaPy\instapy\util.py", line 432, in validate_username
    match = match_demographics_filters(username, profile_pic_URL, logger)
  File "C:\Users\Adil\Documents\GitHub\reallyhalalfood\InstaPy\instapy\clarifai_util.py", line 359, in match_demographics_filters
    logger)
  File "C:\Users\Adil\Documents\GitHub\reallyhalalfood\InstaPy\instapy\clarifai_util.py", line 330, in get_demographics_predictions
    "predicted_age": predicted_age,
UnboundLocalError: local variable 'predicted_age' referenced before assignment`

**Comment by uluQulu** [comment]
Hey all
Commits bringing the unnamed changes are mostly technical which also has informative naming enough for you to understand their specific changes, so did not write any more about them; If any question, please ask.

There were some problems and they are solved. Users will take its effect only after updating InstaPy saying - "Hey, there were this or that problem but now is gone!" - so no need to really write about those fixes/changes mentioned above.

Added documentation for the new feature - demographcis filters.

---

Thanks for keeping the PR live during this time guys, I have had a quite busy days. But got a bit time to finish this PR. 

Hey Tim 😂 thanks, hopefully, everything is good, how about you?

---

@halalfood, good to know that you've tried it and reported the results, thank you!
Basically, it means, many of your targets did not match the demographics filters you've set. That made tons of users to be skipped. And nowadays, I heard from an InstaPy fella, IG keeps track of such things. E.g. if someone skips many users.. So beware of not bursting usage and go soft with values a bit?

Complete solution to it:
1. Now demographics verification is done at the end of the validate_username() as other verifications be done there.
2. If we verify demographics info at the time of grabbing users then boom - server calls unspent! 

I thought about this after your reports, it is a bit thinky thing to do, cos gotta look if it also affects and/or can be applied to other verification procedures, so can be done in some other good day :)

> 'predicted_age` bug seems to be real. Will see and write about it now.

---

One more time, about the other unnamed technical changes, please ask if any questions. All I have done are of requirement to me.

---

Cheers 🙂
---

**Comment by Abdulsamipy** [comment]
> I have this problem:
> 
> Traceback (most recent call last):
> File "C:/Users/*****/Documents/GitHub/reallyhalalfood/InstaPy/quickstart.py", line 39, in
> session.set_demographic_filters(enabled=True, gender="feminine", gender_probability=.5, unrecognizable="disallow")
> AttributeError: 'InstaPy' object has no attribute 'set_demographic_filters'

hi, can you kindly tell me how to fix this issue?

**Comment by instasck** [comment]
nice addition just be aware aggressive filtering with clarify is 1$ for 1000 images.
Better use it with care or use some cheaper service.

**Comment by uluQulu** [comment]
@Abdulsamipy 
To use this feature, you should pull my fork, for now,

@instasck 
At the time I wrote it, Clarifai was the best suitable service to use. Not sure about the market at the moment.
Which service you would propose? I am sure I have tested the one in your mind. 😉
Also, overusage is always unwelcomed.
Meanwhile, one can open multiple accounts and switch accounts once the monthly quota is filled ✔

BTW, howdy boss @timgrossmann 🙌

**Comment by Abdulsamipy** [comment]
@uluQulu. Can you kindly check IG has changed the default profile picture code .. So skip_profile_no_picture is not working now

Ps.. English is not my main language can you kindly tell me how do you mean by "pull my fork"

**Comment by uluQulu** [comment]
@Abdulsamipy alright, I will try to give it a look.
It is a terminology specific to Git and Github, your english is good enough 🍿

In Github there is a project. Only its author and its collaborators (set by author) can modify its content.
But anybody who wants to modify it can fork it which literally means - copying it legally.

Any change to the main project is not affected in fork and vice verse.
Fork can get files of main repo which is called pulling master (main repo).
Main repo can also get files from fork by PRs (pull requests).

If you are using Git command line utility, you can 
Just ,
`git fetch upstream master`  (checks if there is a file to be downloaded)
`git pull upstream master` (downloads required files if there is any)

`upstream` is generally the called main repo and `master` is the name of the branch you will pull.


So, shortly, read about pulling a fork in the web.
If it is too difficult, just download my fork (InstaPy fork at my profile page) and use it. But I have not updated it after this PR, so it can be very behind of the main repo.

Have a good day 🎈

**Comment by Abdulsamipy** [comment]
@uluQulu .. Oh i understand now .. Thanks for taking time and explaining ... And i was able to fix the issue by replace the old cdn link with new one

Appreciate your kind reply :)

**Comment by Mr-Hodler** [comment]
i cant install, i have download the fork master form you @uluQulu and after what i do?

**Review by BerkSpar — APPROVED** [review]

**Comment by timgrossmann** [comment]
@uluQulu Sorry for dropping this for so long... Do you think you can merge and update this PR so we can finally merge it? 😉

**Pull request closed without merging**
