### PR TITLE
Fixes incorrect Logfolder

### PR DESCRIPTION
**Pull request by Tjorriemorrie**
I've noticed that the logfolder are created in the root incorrectly. This fixes that.

Apologies!

### CODE REVIEW

**Comment by timgrossmann** [comment]
@Tjorriemorrie Could we please still stick to the `.format()` way? Just to keep it consistent?

**Comment by Tjorriemorrie** [comment]
@timgrossmann done.

I personally think using the platform separator is more safe though.

**Comment by timgrossmann** [comment]
@Tjorriemorrie You're right...
Can't we combine that?

**Comment by Tjorriemorrie** [comment]
I don't know what you mean by that _combine_?

**Comment by timgrossmann** [comment]
@Tjorriemorrie Use the format method but still use the separator

**Comment by timgrossmann** [comment]
@Tjorriemorrie You're awesome!
Thank you very much

**Pull request merged**
