### PR TITLE
fix problem with only 27 posts

### PR DESCRIPTION
**Pull request by timgrossmann**
Finally fixes the problem with the 27 posts per tag/location in the core codebase instead of only #1844

### CODE REVIEW

**Comment by uluQulu** [comment]
@timgrossmann,
Thanks for taking the initiative and getting this pushed,, you rock! :)
But, I'm afraid `get_links_for_tag` function here, uses only the semi-fixed part of the original [gist](https://gist.github.com/uluQulu/162b0c1d387157ef6e163d796f9cdf7e) (_shared in #1365_) and is dismissing some useful lines,...
>I think, you have taken that function from @dimahadgi's file in #1825 who had an old (_one of the early_) edition of that fixed function and did not update with the latest changes (up to _revision 7_) there from the gist

**Comment by timgrossmann** [comment]
@uluQulu Hmm... weird. I took the files that were right before the issue was closed.
Yes, we have to get this into the actual code otherwise it will get really hard over time to just "patch it in"...

I tried it out with several different settings and it worked on my site. What are the problems you're facing?

**Comment by uluQulu** [comment]
@timgrossmann,
I've followed the issue for `like_by_tags` function as #1365, and #1825 for the `like_by_locations`
For more accuracy, the current state of the `get_links_for_tag` function in main repo is (_after this merge_) at the very earliest stage I have shared in a #1365 comment and a while back named it as an [OLD design](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-363586896)

People use with different settings (huge amounts (_generates too many requests to be handled.._), tags with no Top Posts (_page elements' locations differ..._), with spammish tags (_hardly loading pages..._), tags with less pictures than it looks (_handled with `possible_posts` variable_), requesting links after spending too many requests, and etc.) and I have handled all of those who gave a feedback and the latest gist includes those all (_last updated 14 days ago_).

>If you see the misbehaviours pointed out by people in #1365, you will realize how important are those changes.

**Comment by CharlesCCC** [comment]
@uluQulu Maybe you can help create a PR the latest version you have ?

**Comment by timgrossmann** [comment]
@uluQulu Good to hear that! Well, I really hope that we can work on getting this into the actual codebase. 
Thanks for pointing that out.

**Comment by uluQulu** [comment]
@CharlesCCC,
The reason I have not had intention to PR is the fact that, because of being the most busiest spot (_tags page_), that part of IG is (was) getting continious updates (_in this update season_) and I have waited for the supreme state of the fix, also, I have (had) got not much time to watch PR acitivities, merge conflicts, etc.,
I think @timgrossmann can easily merge it, the only thing will change is the `get_links_for_tag` function (`get_links_for_location` and `get_links` from this merge is already up-to-date) with the latest [gist](https://gist.github.com/uluQulu/162b0c1d387157ef6e163d796f9cdf7e)

>Although, I have not heard any problems for some time from #1365, if any further (_possible_) problems occur, it will be much easier to fix while having it merged to the main repo files..

**Comment by timgrossmann** [comment]
@uluQulu I'll look into that tomorrow

**Pull request merged**
