### PR TITLE
Twinses of recent delimitor feature: `delimit_liking` & `delimit_commenting`

### PR DESCRIPTION
**Pull request by uluQulu**
```python
session.set_delimit_liking(enabled=True, max=200, min=10)
```
and
```python
session.set_delimit_commenting(enabled=True, max=35, min=2)
```
Both tools bring _flexibility_ to improve the efficiency of the activities on targets in desired range of _max_ and/or _min_ values, any time.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@uluQulu This is awesome!

The links in the README are broken, but that's a really quick fix.

Still have to test it. Maybe @sionking could double check that too.

**Comment by uluQulu** [comment]
Thank you @timgrossmann,
It is really difficult to test markdown access links before posting cos Atom's markdown previewer I use has no such option

**Comment by sionking** [comment]
This is real nice feature. I won't be able to merge it soon due..

**Comment by uluQulu** [comment]
Hey Tim, a few lines of code in this PR is fixing **set_relationship_bounds**'s `enabled=False` misbehavior, and it should be merged as soon as possible.  
@joanroig just issued it here, https://github.com/timgrossmann/InstaPy/issues/1941#issuecomment-386274715 😅

**Pull request merged**
