### PR TITLE
skip following users that already are following you

### PR DESCRIPTION
**Pull request by condomfighters**
Hi, I think we should add the options to skip following users that already follow you.
I have a working prototype thanks to @uluQulu.
this is my first time opening a pull request.
In case I opened this in a wrong section and you are wondering why then remember this, I have no clue what I'm doing.

thanks for reading
[instapy.zip](https://github.com/timgrossmann/InstaPy/files/1921085/instapy.zip)

### CODE REVIEW

**Comment by timgrossmann** [comment]
@condomfighters @joanroig Thank you for the hard work on this!
However, before we can actually review this and merge it, you really need to rebase it on the master branch in order to only show the difference for the changes you made instead of the whole git history 😉 

Thank you!

**Comment by condomfighters** [comment]
@timgrossmann sorry, I have no idea what you just said and i'm unable to work with github.
If anyone else wants to do whatever you just said then go ahead! 👍 👍

**Comment by timgrossmann** [comment]
@condomfighters Thank you for letting me know.
I'll try to rebase it and push it into this PR.

Depending on how old your last state is, it might make most sense to download the latest version of InstaPy and make the changes again, but we'll see.

**Comment by timgrossmann** [comment]
@condomfighters Could you please upload your changes into a GIST or something else so I can do the merging?

Looks like you're trying to create a PR from master into develop which is really odd.

**Comment by condomfighters** [comment]
@timgrossmann Hi, sorry i'm a noob & all the credit goes to @uluQulu 
Here is my instapy folder, this is updated.
If you can guide me how to upload a "gist" then I'll be glad to help.
[instapy.zip](https://github.com/timgrossmann/InstaPy/files/1944708/instapy.zip)

**Comment by timgrossmann** [comment]
@condomfighters Thank you for uploading it and thanks to @uluQulu for all the hard work!

I'll try to find the time and extract the parts from the zip folder, thanks.

**Comment by sionking** [comment]
Please rebase so we can only see changed files

**Comment by uluQulu** [comment]
Hi guys
Nero took a **great effort** to bring this into attention and I should say **final words** for today:

**The implementation here** belongs to #1732 and the **full modification** is as in this https://github.com/timgrossmann/InstaPy/issues/1732#issuecomment-376577125.

**It was great** and it only supported follow user followers feature as @cormo requested there.

But my latest implementation which will be shared soon will make this **functionality be supported** by **ALL** of the features with _much smarter algorithms_.

**For that reason**, I can freely say that this PR can be closed for good.

Thanks again Nero, **keep up good work**!

**Pull request closed without merging**
