### PR TITLE
Allowing follow_by_tags to interact with the user.

### PR DESCRIPTION
**Pull request by joaoleite**
I had the same idea that was quoted in #3991. Because this interactive = True / False code block repeats throughout the code, I just copied and pasted it, adapting the user name.

However, I believe it could be generalized to avoid many duplicate codes.

What do you think??

### CODE REVIEW

**Comment by timgrossmann** [comment]
@joaoleite Love it! Having this addition with the `follow_by_tags` feature, too, will probably be used by tons of people 😍
 
As with https://github.com/timgrossmann/InstaPy/pull/3813 we'll have to "morph" that into a general `interact_by_tags` method which will incorporate the `set_do_like` etc. methods but I think this is part of the next iteration.

Thank you.

Do you think you can adjust the README and add the knowledge that there now is an interact parameter? 😊 
I'll make an addition to that Changelog in the meanwhile.

Maybe one more question, are you actively using this feature of have you just created the PR with it? 😊

**Comment by converge** [comment]
that's cool!

I tested and reviewed it, and it's working well. We just need some code improvements.

The comments style, it's better to keep the way we have it today
```python
# comment here
code_here
```

There is also some trailing whitespaces, and lines longer than 79 characters.

There is something not related to the PR, but this method has two unused variables, ```is_video``` and ```scope```, it would be nice to update if possible.

We will need also update our doc, so the users will know how to use it properly.

I don't want to be a pain in the *back, but I believe these small things are important to keep the project clean and easy to use. Can I ask for one more thing ? there is extra empty lines in the end, it's nice to have the if/else statement close to the start/finish of the statement.

**Comment by joaoleite** [comment]
> @joaoleite Love it! Having this addition with the `follow_by_tags` feature, too, will probably be used by tons of people 😍
> 
> As with #3813 we'll have to "morph" that into a general `interact_by_tags` method which will incorporate the `set_do_like` etc. methods but I think this is part of the next iteration.
> 
> Thank you.
> 
> Do you think you can adjust the README and add the knowledge that there now is an interact parameter? 😊
> I'll make an addition to that Changelog in the meanwhile.
> 
> Maybe one more question, are you actively using this feature of have you just created the PR with it? 😊

Thanks for the comments!

I'm actively using yes and this return has worked fine. In addition to following people, allowing interaction has increased engagement.

Yes, I will modify the README to add this interaction!

I'll do it this week! Thank you!

**Comment by joaoleite** [comment]
> that's cool!
> 
> I tested and reviewed it, and it's working well. We just need some code improvements.

I really have found this functionality very cool!

> The comments style, it's better to keep the way we have it today
> 
> ```python
> # comment here
> code_here
> ```

The code I did not even need to write, I copied from another method that did the same thing, so I stayed with the comments in the same way.

> There is also some trailing whitespaces, and lines longer than 79 characters.

I'll check those blanks, my fault. excuse

> There is something not related to the PR, but this method has two unused variables, `is_video` and `scope`, it would be nice to update if possible.

Can I remove these variables? Okay. I'll remove it!

> We will need also update our doc, so the users will know how to use it properly.
👍 

> I don't want to be a pain in the *back, but I believe these small things are important to keep the project clean and easy to use. Can I ask for one more thing ? there is extra empty lines in the end, it's nice to have the if/else statement close to the start/finish of the statement.

I will remove those lines, of course! Clean code is what we need most to keep the project working and easy to read.

Thank you for your help!!!

**Comment by joaoleite** [comment]
Basic fix and merge done. Missing just the readme.

@timgrossmann / @converge  can u check, please!?

**Comment by joaoleite** [comment]
@timgrossmann  / @converge can u check, please?!

🙃

**Comment by converge** [comment]
so much better! Just a small change, we released the 0.2.0 version yesterday, we just need to move the update on changelog to unreleased section.

After it, it's ready to merge.

**Comment by timgrossmann** [comment]
@joaoleite Thanks for adjusting your PR 💪 

I've added a link to the section in the README and adjusted the changelog.
It will take some time until we merge the dev branch into master again (probably ~1-2 weeks but after that everybody will be able to use your feature) 🙌 
Congrats to your first merged PR btw. 😋

**Comment by joaoleite** [comment]
Tks a lot @timgrossmann  and @converge 

🎉

**Pull request merged**
