### PR TITLE
Added username to log

### PR DESCRIPTION
**Pull request by dar2015**
Ability to track users action in log if there is multi users using same script.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@dar2015 Awesome, thank you very much!

**Comment by CharlesCCC** [comment]
hey @timgrossmann we need rollback this change... this is cause the issue [Here](https://github.com/timgrossmann/InstaPy/issues/1310)

**Comment by fegomess** [comment]
yes, its causing this issue!

**Comment by timgrossmann** [comment]
@CharlesCCC @fegomess Sorry...

Just merged #1313 hope that works for everyone

**Comment by uluQulu** [comment]
hey guys, in line 165
### Replace both `self.logger` to plain `logger` 
[here](https://github.com/timgrossmann/InstaPy/issues/1310#issuecomment-361485160)
@CharlesCCC @fegomess

**Comment by dar2015** [comment]
Sorry for issue. I'm going to add a username based log for each log in the code.
Do you think it will be helpful?

**Comment by uluQulu** [comment]
@dar2015 
I think, adding datetime to the log would be great

**Pull request merged**
