### PR TITLE
Use chrome proxy without extention

### PR DESCRIPTION
**Pull request by dar2015**
Support headless and UI proxy for chrome based on selenium proxy class (no extension needed)

### CODE REVIEW

**Comment by timgrossmann** [comment]
@dar2015 What is the difference between this and the already existent proxy config?

**Comment by dar2015** [comment]
It's required browser extension.
I coulnd't find it working headless.

**Comment by timgrossmann** [comment]
@dar2015  Do we need additional documentation for this?

**Comment by dar2015** [comment]
Absolutely no. It's should work seamless when setup proxy with chrome.

**Comment by timgrossmann** [comment]
@dar2015 Awesome! Thank you very much for this!

**Pull request merged**
