### PR TITLE
Updated How_To_DO_Ubuntu.md

### PR DESCRIPTION
**Pull request by ghost**
It should be cd InstaPy/scripts instead of cd scripts, because by default after cloning a repository, it will create a folder with repository name

### CODE REVIEW

**Comment by timgrossmann** [comment]
@jevtovich You really have to fix this PR if you want it to get merged 😉 

Thank you for contributing

**Comment by GrennUntree** [comment]
@timgrossmann what's the problem with the PR?

**Comment by timgrossmann** [comment]
@GrennUntree Take a look at the conflicting files...

**Comment by ghost** [comment]
@timgrossmann wtf i updated only readme file, I'll close this one and make a PR

**Pull request closed without merging**
