### PR TITLE
Add skipping of public profiles

### PR DESCRIPTION
**Pull request by schealex**
## Description

Adds skipping of public accounts

Implements #6215

## How Has This Been Tested?

Tested it and seems to work fine!

- [x] Test

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project, `black -t py34`
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by sherxyar — COMMENTED** [review]
I'm getting this error. I pasted all of the code from both of the files. The bot works fine without 'skip_public' argument.  [this is my first time checking & testing a PR , new to coding :P ]

 session.set_skip_users(skip_private=False,
TypeError: set_skip_users() got an unexpected keyword argument 'skip_public'

**Comment by schealex** [comment]
@sherxyar  That's weired. Give me a sec i'll check

**Comment by schealex** [comment]
can you try again? Seems to be working for me now, at least i don't get that exception anymore.

[EDIT] btw. remember to disable skip_private which is default true!

**Comment by sherxyar** [comment]
> can you try again? Seems to be working for me now, at least i don't get that exception anymore.
> 
> [EDIT] btw. remember to disable skip_private which is default true!

Hi,

I tried again but the same error :/

This might help you:

starting instapy with quickstart
================================
InstaPy Version: 0.6.14-AS
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "x"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-06-09 15:56:14] [x]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-06-09 15:56:14] [x]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-06-09 15:56:16] [x]  - Internet Connection Status: ok
INFO [2021-06-09 15:56:16] [x]  - Current IP is "x" and it's from "x"
INFO [2021-06-09 15:56:16] [x]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-06-09 15:56:16] [x]  - window.navigator.webdriver response: True
WARNING [2021-06-09 15:56:16] [x]  - Hide Selenium Extension: error
INFO [2021-06-09 15:56:41] [x]  - Cookie file for user 'halal.picels' loaded...
..................................................................
INFO [2021-06-09 15:57:07] [x]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2021-06-09 15:57:07] [x]  Saving account progress...

INFO [2021-06-09 15:57:14] [x]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 173 users & had 15 FOLLOWERS
[Session lasted 1.18 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-06-09 15:57:14] [x]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\Sheryar Tahir\Desktop\insta bot\instapy-quickstart-master\quickstart.py", line 45, in <module>
    session.set_skip_users(skip_private=False,
TypeError: set_skip_users() got an unexpected keyword argument 'skip_public'
Press any key to continue . . .

p.s, i had selenium error before too.

My config:

image

**Comment by schealex** [comment]
> > can you try again? Seems to be working for me now, at least i don't get that exception anymore.
> > [EDIT] btw. remember to disable skip_private which is default true!
> 
> Hi,
> 
> I tried again but the same error :/
> 
> This might help you:
> 
> # starting instapy with quickstart
> InstaPy Version: 0.6.14-AS
> ._. ._. ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "x"
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2021-06-09 15:56:14] [x] Session started!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> INFO [2021-06-09 15:56:14] [x] -- Connection Checklist [1/2] (Internet Connection Status)
> INFO [2021-06-09 15:56:16] [x] - Internet Connection Status: ok
> INFO [2021-06-09 15:56:16] [x] - Current IP is "x" and it's from "x"
> INFO [2021-06-09 15:56:16] [x] -- Connection Checklist [2/2] (Hide Selenium Extension)
> INFO [2021-06-09 15:56:16] [x] - window.navigator.webdriver response: True
> WARNING [2021-06-09 15:56:16] [x] - Hide Selenium Extension: error
> INFO [2021-06-09 15:56:41] [x] - Cookie file for user 'halal.picels' loaded...
> ..................................................................
> INFO [2021-06-09 15:57:07] [x] Logged in successfully!
> ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> INFO [2021-06-09 15:57:07] [x] Saving account progress...
> 
> INFO [2021-06-09 15:57:14] [x] Sessional Live Report:
> |> No any statistics to show
> 
> On session start was FOLLOWING 173 users & had 15 FOLLOWERS
> [Session lasted 1.18 minutes]
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2021-06-09 15:57:14] [x] Session ended!
> ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> Traceback (most recent call last):
> File "C:\Users\Sheryar Tahir\Desktop\insta bot\instapy-quickstart-master\quickstart.py", line 45, in
> session.set_skip_users(skip_private=False,
> TypeError: set_skip_users() got an unexpected keyword argument 'skip_public'
> Press any key to continue . . .
> 
> p.s, i had selenium error before too.

have you copied the code manually? can you please try to use my develop branch which already includes this PR?

pip install -I https://github.com/schealex/InstaPy/zipball/develop

To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"

i've just tested this and it's working fine for me

**Comment by sherxyar** [comment]
@schealex  yes i copied the code manually, we shouldn't do that? 😅
And yes it's working perfectly after i installed it through your develop branch. The script is able to skip public accounts & send follow request to private ones. 
Thank you so much for your time 🎉

**Review by sherxyar — APPROVED** [review]
@schealex  yes i copied the code manually, we shouldn't do that? 😅
And yes it's working perfectly after i installed it through your develop branch. The script is able to skip public accounts & send follow request to private ones. 
Thank you so much for your time 🎉

**Comment by schealex** [comment]
@elulcao can you merge this aswell?

**Comment by elulcao** [comment]
> @elulcao can you merge this aswell? 

Hello @schealex thanks for this enhance, 
all seems good :)

**Review by elulcao — APPROVED** [review]

**Review by elulcao — APPROVED** [review]

**Comment by elulcao** [comment]
Changes involved are not compromissing functionality, merging as UNRELEASED version in CHANGELOG

**Pull request merged**
