### PR TITLE
Fixed the issue that caused IndexError: list index out of range

### PR DESCRIPTION
**Pull request by mihikadutta**
The issue occured due to change in html structure in the instagram login page. @timgrossmann please review the change and let me know if it looks good. thanks.

### CODE REVIEW

**Review by brandonkovacs — APPROVED** [review]
This seems to fix the issue! 👍

**Comment by BernardoGO** [comment]
Nice quick fix.
The problem I see with this is that unlike the one seen in d7af29d of #457 this one is very sensible to future changes. Problems related to changes in the HTML structure will probably happen again.

I think that #457 is more of a "permanent" fix for this.

**Comment by mihikadutta** [comment]
@BernardoGO you are right, targeting the username field in the form is the permanent fix. I am closing this PR. 👍

**Comment by FBosler** [comment]
really dumb question. How do I get that installed on ubuntu? I only know how to do the initial setup.

**Pull request closed without merging**
