### PR TITLE
update instapy to disable image load in chrome webdriver from #1364

### PR DESCRIPTION
**Pull request by timgrossmann**
Kudos to @ganeshkrishnan1

### CODE REVIEW

**Comment by sionking** [comment]
I think you flag yourself as a bot when you do that.
Maybe not now, but one day IG will check this.

**Comment by timgrossmann** [comment]
@sionking True that.
In most cases the bandwidth isn't even a problem.

Let's add this as default `False` so people have an easy way to add it if they want to.
Still, partially loading images or restricting the image loading to a lower quality won't work that easy.

**Review by uluQulu — APPROVED** [review]
It is amazing, @timgrossmann 🎊🎊

**Comment by CharlesCCC** [comment]
change looks good. default to `False`  make perfect sense.

**Review by CharlesCCC — APPROVED** [review]
Let's merge this 👍

**Comment by sionking** [comment]
this is good when using luminti and other expensive proxy providers.

**Pull request merged**
