### PR TITLE
REMOVE USER FROM POOL FIX: Now we check that there is a whitespace/dot/newline at the end of username

### PR DESCRIPTION
**Pull request by sionking**
and also if not at the beginging of line we shall check whitespace before username:

YusernameX
Y = whitespace if not at start of line
X =  whitespace/dot/newline

### CODE REVIEW

**Comment by uluQulu** [comment]
@sionking 
It makes code unmaintainable.

I have a clear suggestion at https://github.com/timgrossmann/InstaPy/issues/2817#issuecomment-417850662.
Shortly,
```python
entries = line.split(" ~ ")
sz = len(entries)
user = entries[0][:-2] if sz==1 else entries[1][:-2] if sz==2 else entries[1]
```
💯% accuracy in simplicity and ease of maintenance.


----

Cheers 😁
------

**Comment by sionking** [comment]
@uluQulu 
Your code is nicer so i will take it.

**Comment by sionking** [comment]
@uluQulu 
this code:
user = entries[0][:-2] if sz==1 else entries[1][:-2] sz==2 else entries[1]
is not compailing

code:
```
                entries = line.split(" ~ ")
                sz = len(entries)
                if sz == 1:
                    user = entries[0][:-2]
                elif sz == 2:
                    user = entries[1][:-2]
                else:
                    user = entries[1]
```

**Comment by uluQulu** [comment]
@sionking 
I remember I WROTE IT on the fly without testing
`if` term was missing before `sz==2`
```python
user = entries[0][:-2] if sz==1 else entries[1][:-2] if sz==2 else entries[1]
```

----

Cheers 😁
----

**Comment by timgrossmann** [comment]
@uluQulu @sionking could you guys update the PR to the mentioned approach so we can merge this, please?

**Comment by timgrossmann** [comment]
@sionking @uluQulu What is the reason the file handling in this feature does not use the `with open() as f:` syntax?

**Comment by uluQulu** [comment]
@timgrossmann 
You're right. `delete_line_from_file()` should use `with open()` syntax for code strength.

I could do that change through web editor as gets some time.

----

Cheers 😁
----

**Comment by timgrossmann** [comment]
@uluQulu Sounds good, looking forward to it!
Make sure to also change the code to your proposed solution, please. So we can finally have some solid removing 😉

**Comment by sionking** [comment]
@timgrossmann @uluQulu I did a really good job on `delete_line_from_file()` function that is still not merged (atomic write)

**Comment by uluQulu** [comment]
@sionking
I remember that we agreed on an universal atomic write style in some thread but you have never fulfilled it.
And then closed your PR uncomplete.
Do you think you can finish it?

----

Cheers 😛
----

**Comment by timgrossmann** [comment]
@sionking I was just wondering why it's not in the PR section anymore when I read that it's closed.
I have to be honest that I don't know the reason anymore. I thought we'd have a different solution in another PR.
Wasn't aware that it's still a point.

I'm really sorry for that misunderstanding... 😔

**Comment by sionking** [comment]
@uluQulu I can't implement solution for python2 as I never used it.
My solution for python3 is perfect, never got missing data since then.

**Comment by sionking** [comment]
> @sionking
> I remember I WROTE IT on the fly without testing
> `if` term was missing before `sz==2`
> 
> ```python
> user = entries[0][:-2] if sz==1 else entries[1][:-2] if sz==2 else entries[1]
> ```
> 
> ## Cheers 😁

done

**Comment by timgrossmann** [comment]
@sionking Awesome one. 
Thank you very much for this, I'll quickly test it and merge this if there are no problems

**Comment by timgrossmann** [comment]
@sionking @uluQulu Looks like it's working perfectly fine! 🙌 
Perfect, do you guys think we should reopen the atomic write PR again?

**Comment by uluQulu** [comment]
@timgrossmann 
**Yeah** good idea 💯

@sionking I will try to help with python 2 in my free time.

I hope we will find that thread containing discussions on @sionking's atomic write idea WHERE the agreement on total solution was found 🕵🏼‍♂️

----

Cheers 😁
----

**Comment by sionking** [comment]
I think something went wrong here:
@uluQulu @timgrossmann 
Why are we doing [:-2] ???
It will get user without the last 2 chars ...
Split will remove the \n anyway and ',' can be exist at the end and can't (version)

**Comment by timgrossmann** [comment]
> I think something went wrong here:
> @uluQulu @timgrossmann
> Why are we doing [:-2] ???
> It will get user without the last 2 chars ...
> Split will remove the \n anyway and ',' can be exist at the end and can't (version)

@sionking Sorry is this resolved or was it just accidentally marked as such?

**Pull request merged**
