### PR TITLE
feature: Add total limit per hour and limit per day of likes and follows

### PR DESCRIPTION
**Pull request by sionking**
I started it since the automation crashed all the time so I was unable to track to total daily likes/follows.
Now it will read the file before every run so it wont start liking from the begginging.

- I used pickle.
- Able to read it at any time since it saved as file.
- wait for next hour/day to return to work if max is reached.
- can limit 2 or more process running simultaneously.
- If the Max is reached I print to console.

If the Max is reached I wait certain amount of time (instead of doing diff to next hour) since statisticly  it will be the same.
every follow/like will update the file (not best performance but reliablty).

Sion.

### CODE REVIEW

**Comment by sionking** [comment]
why is it compiling 2.7 ?
it says undefined name 'FileNotFoundError' ...

**Comment by timgrossmann** [comment]
@sionking Thank you for contributing!

You probably also have to add a few lines in the README for documentation and add, if you have any, external dependencies to the requirements file.

We'll review this soon and merge it if it's working out great!

What you could do tough is move the InstaPyStore out of the instapy.py file and put it in a separate file.

**Comment by sionking** [comment]
Sure it need to be done, BTW I am working with this for over a month.

**Comment by timgrossmann** [comment]
@sionking Awesome!

Also make sure to get the TravisCI errors fixed please 😉

**Comment by converge** [comment]
hey guys, we have two PR going in the same direction, #859 .

My idea is, if we approve #913, rewrite #859 to use the same sqlite database to check limits. What do you think ?

**Comment by sionking** [comment]
converge  the only this is we need a csv reader so it wil lbe easy to track record:
````
total Likes 35542 from date: 16/10/2017
this Day Total Likes: 608
this Hour Total Likes: 47
Day Executed last Likes: 2017-11-14
Hour Executed last Likes: 21
--
MAX_PER_HOUR 50 MAX_PER_DAY 900
--
total follows 11424 from date: 16/10/2017
this Day Total follows: 422
this Hour Total follows: 31
Day Executed last follow: 2017-11-14
Hour Executed last follow: 21
````

BTW, I works with mine for many monthes so it tested and works, it is much less complex than most solutions, but not that well writen (no time), so lets go with yours  :)


I read it with new reader file :
```
session = InstaPy(username=insta_username, password=insta_password, selenium_local_session=False)
session.read_likes_statistics()
session.read_follows_statistics()
session.end()
```

**Comment by converge** [comment]
@sionking you're totally right when you want less complexibility, it's the way I think as well. Less complexibility will be easier to extend the functionality and maintain.

I really like the CSV approach, it's so simple and fast, but we have big problems managing CSV files in Windows (works well in Linux and MacOS).

I like your idea about it:
```python
session.read_likes_statistics()
session.read_follows_statistics()
```
We're working in a new logging module for InstaPy, we could let this kind of data load to a dashboard, what do you think ?

**Comment by sionking** [comment]
COOL

**Comment by sionking** [comment]
addind the option to run the script only in specific hours:
````
        if not (_datetime.time(HOUR_START_DAY, 1) <= now.time() <= _datetime.time(HOUR_END_DAY, 30)):
...
````

Good for passing instagram bot detector.

**Comment by taradell** [comment]
@sionking hi mate! can you please specify how and where add your piece of code to the current set of files?

thanks :-)

**Comment by sionking** [comment]
I need to remerge to latest and I think we shall push it as an optional limit mechanisem.

**Pull request closed without merging**
