### PR TITLE
extending PR_860 sunnypatel165 solution and small change to not break…

### PR DESCRIPTION
**Pull request by converge**
hey @sunnypatel165 , great work! I just had to do a little change because update_activity wasn't being called, and extended your solution to other possibilities trying to find the Load Button.

### CODE REVIEW

**Comment by converge** [comment]
Hey, I don't know if we should keep this PR or not. Do we still need the load button ? The changes I made ignore the load button to load content.

**Comment by timgrossmann** [comment]
@converge Can we assume that every load button has been removed?

**Comment by converge** [comment]
@timgrossmann I think so, if someone complain about it, we claim a bounty. hehe kidding, as there is no information about the existence of the load button, we can merge it and see what happens.

**Comment by converge** [comment]
someone reported that his account uses the button.

**Comment by timgrossmann** [comment]
@converge But that's not on the issue, right?
Did he write you a message?

**Comment by converge** [comment]
@timgrossmann they reported it at #724 mpaolor and drogon34.

sounds like we need to treat more exceptions

**Comment by drogon34** [comment]
@converge @timgrossmann I just checked on my new account and the Load button is no longer present. Seeing infinite scrolling as the consistent UI across both my accounts now.

**Comment by converge** [comment]
just proposed another PR fixing this in a better way #888

**Pull request closed without merging**
