### PR TITLE
Merged both linux scripts to one

### PR DESCRIPTION
**Pull request by binhonglee**
Addressing #112 . If this script works, the other two can be removed.

@vlntdds

### CODE REVIEW

**Comment by timgrossmann** [comment]
@vlntdds Could you do some quick tests? Please

**Comment by pekapa** [comment]
Maybe we can merge OSx script as well.
I think `uname` and `uname -m` should give us all the information we need, ain't that right?

**Comment by nijaru** [comment]
Yeah uname output gives you specific kernel (linux or darwin) plus architecture

**Comment by timgrossmann** [comment]
@binhonglee Could you add the case for OSX as well, please?

**Comment by binhonglee** [comment]
`linux.sh` should work for Mac now.

**Comment by timgrossmann** [comment]
Awesome! Thank you @binhonglee

**Pull request merged**
