### PR TITLE
Fix "Failed to load desired amount of users!" & Add Progress Tracker to get_users_through_dialog()

### PR DESCRIPTION
**Pull request by uluQulu**

### CODE REVIEW

**Comment by gitpatrickhub** [comment]
@uluQulu I tested Fix "Failed to load desired amount of users!" issue on Raspberry Pi3 and is working perfectly.

**Review by timgrossmann — APPROVED** [review]

**Comment by timgrossmann** [comment]
@uluQulu Nice additions, as always. Thank you very much! 🙌 

Will merge and publish as soon as travis passed.

**Comment by tE3m** [comment]
Worked for me.

**Comment by oridamari** [comment]
sometimes the bottom of the dialog shows **'see all suggestions'** button and then i get
"Failed to load desired amount of users"

**Pull request merged**
