### PR TITLE
Firefox initialization issues, initial approach fix

### PR DESCRIPTION
**Pull request by converge**

### CODE REVIEW

**Comment by dsmh** [comment]
Same error as I show on #4845  with the approach:

```
Custom workspace set: "/root/botDev/InstaPy" :]

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/botDev/InstaPy"
Traceback (most recent call last):
  File "prueba.py", line 27, in <module>
    multi_logs=True)
  File "/root/botDev/InstaPy/instapy/instapy.py", line 320, in __init__
    self.logger,
  File "/root/botDev/InstaPy/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited proces
```

**Comment by converge** [comment]
@dsmh ping me on Discord if you can give me access to your server to debug it.

**Comment by papillon-unix** [comment]
I did update with this branch and I still have this:

```
Workspace in use: "/home/joseph/InstaPy"
Unable to locate the default Firefox binary path, trying to find it...
Firefox is installed at: /usr/bin/firefox
Firefox version: Mozilla Firefox 49.0

Traceback (most recent call last):
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 118, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Projects/instagram/instajoseph.py", line 13, in <module>
    disable_image_load=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 320, in __init__
    self.logger,
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 130, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```
Am I doing something wrong?

**Comment by dsmh** [comment]
> @dsmh ping me on Discord if you can give me access to your server to debug it.

I have it running on a local Rasberry PI 3. But I can give you any log you need if that's ok.

**Review by ghost — APPROVED** [review]

**Comment by Tachenz** [comment]
I have tried these proposed changes to browser.py as well, and also getting
"Matching set of capabilities error*

**Comment by papillon-unix** [comment]
Same for me. Still not fixed..

**Comment by Tachenz** [comment]
Is it some sort of serious version problem? So many having it

**Comment by etienne-turin** [comment]
I took this broswer.py file and it fixed the "Unable to find a matching set of capabilities" error, good job !

**Comment by Tachenz** [comment]
> I took this broswer.py file and it fixed the "Unable to find a matching set of capabilities" error, good job !

Gosh... how?? What version of everything are you using? I took this browser.py and still getting "matching set of capabilities error"... A bit at loss here, Windows 10 system

**Comment by Tachenz** [comment]
By some vodoo magic, I managed to change my error from the original, to this one (with this fix):

Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
Traceback (most recent call last):
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\Y
ura_follow.py", line 4, in 
session.login()
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\lib\site-packages\i
nstapy\instapy\instapy\instapy.py", line 408, in login
self.proxy_address,
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\lib\site-packages\i
nstapy\instapy\instapy\login_util.py", line 286, in login_user
if not check_browser(browser, logfolder, logger, proxy_address):
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\lib\site-packages\i
nstapy\instapy\instapy\login_util.py", line 184, in check_browser
logger=logger,
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\lib\site-packages\i
nstapy\instapy\instapy\util.py", line 457, in update_activity
take_rotative_screenshot(browser, logfolder, logger)
File "C:\Users\inna\AppData\Local\Programs\Python\Python36\lib\site-packages\i
nstapy\instapy\instapy\util.py", line 2373, in take_rotative_screenshot
browser.save_screenshot("{}{}_1.png".format(logfolder, logger.name))
AttributeError: 'LoggerAdapter' object has no attribute 'name'


Any advice?

**Comment by dyrgutt** [comment]
Thanks guys! This worked for me also *Thumbs-up*

**Pull request closed without merging**
