### PR TITLE
Fix xpath for post count

### PR DESCRIPTION
**Pull request by anna-sunberg**
Fixes #2596

### CODE REVIEW

**Comment by timgrossmann** [comment]
@anna-osipova Thank you for the PR.

What browser have you tested this in? (Also which country are you from )

Same thing as with #3062 as of now, I'm seeing the old path.
Any comments, @uluQulu @sionking @CharlesCCC

**Comment by anna-sunberg** [comment]
MacOS, Chrome (regular and headless), Instagram in English

**Comment by sionking** [comment]
why not graphql?

**Comment by sionking** [comment]
I don't have this issue

**Comment by timgrossmann** [comment]
@sionking True, GraphQL with this as a "backup" would be way better

**Comment by sionking** [comment]
@timgrossmann I did found out the graphql for private users is not working, works only after refresh the page ~ funny.

**Comment by timgrossmann** [comment]
@sionking You mean related to grabbing the amount of posts or in general?

**Comment by sionking** [comment]
> @sionking You mean related to grabbing the amount of posts or in general?

general

**Comment by timgrossmann** [comment]
@sionking That is really weird... Maybe a bug in their system?

**Comment by jsib0** [comment]
Seems like the issue is still recurring for me. Any suggestions?

**Comment by sionking** [comment]
Please applay this:
```
def get_number_of_posts(browser):
    """Get the number of posts from the profile screen"""
    try:
        num_of_posts = browser.execute_script(
            "return window._sharedData.entry_data."
            "ProfilePage[0].graphql.user.edge_owner_to_timeline_media.count")

    except WebDriverException:

        try:
            num_of_posts_txt = browser.find_element_by_xpath("//section/main/div/header/section/ul/li[1]/span/span").text

        except NoSuchElementException:
            num_of_posts_txt = browser.find_element_by_xpath("//section/div[3]/div/header/section/ul/li[1]/span/span").text

        num_of_posts_txt = num_of_posts_txt.replace(" ", "")
        num_of_posts_txt = num_of_posts_txt.replace(",", "")
        num_of_posts = int(num_of_posts_txt)


    return num_of_posts
```

**Comment by CharlesCCC** [comment]
I'm not seeming this issue on my side, but I think we should PR @sionking 's solution, which will cover almost all the scenarios.

**Comment by timgrossmann** [comment]
#3145

**Pull request merged**
