### PR TITLE
click on the unfollow button in the popup

### PR DESCRIPTION
**Pull request by ghost**
sometimes when unfollow massively, a popup show up and ask for confirmation. 
with this little change we can press unfollow button again and go on with others unfollows correctly .

### CODE REVIEW

**Comment by timgrossmann** [comment]
@uluQulu @sionking @CharlesCCC Could you guys double check that this is not something that only occurs for some people.
Looks fine on my side

@ilmetu Thank you

**Comment by anton4** [comment]
I manually applied your PR patch to current master, but i am seeing that the bot behaves strangely - 
INFO [2018-07-03 11:10:24] [myusername]  --> Removed '2018-06-26 14:14 ~ user1' from followedPool.csv file
WARNING [2018-07-03 11:10:24] [myusername]  --> Cannot Unfollow From InstaPy 0, maybe b'user1' was unfollowed before...
INFO [2018-07-03 11:10:29] [myusername]  --> Removed '2018-06-26 14:14 ~ user2' from followedPool.csv file
WARNING [2018-07-03 11:10:29] [myusername]  --> Cannot Unfollow From InstaPy 0, maybe b'user2' was unfollowed before...
INFO [2018-07-03 11:10:34] [myusername]  --> Removed '2018-06-26 14:14 ~ user3' from followedPool.csv file
WARNING [2018-07-03 11:10:34] [myusername]  --> Cannot Unfollow From InstaPy 0, maybe b'user3' was unfollowed before...

And it goes on like this. I verified by instagram app that i am still following these users and they do exist, but bot is only removing them from the followedPool.csv list, but not from instagram.
Am i doing something wrong?

I am using this unfollow function in config:
 session.unfollow_users(amount=35, InstapyFollowed=(True, "all"), style="FIFO", sleep_delay=600, unfollow_after=172800)

**Comment by ximhotep** [comment]
@timgrossmann I'm seeing the same issue here as well.  @ilmetu's code change worked for me.

@anton4 I'm seeing the same issue as well, but don't think the two issues are tied together.  I guessing this is because there are entries in the follower log for users that IG has deleted.  If the code change I made fixes this problem I will submit a PR.

**Comment by joanroig** [comment]
Same issue here, the change worked on my side, but after three unfollows it fails again...
Edit: seems like after some unfollows, instagram shows users as unfollowed but they aren't unfollowed if you look at your follows, then the unfollow script crashes saying the blocked message.
Edit2: tested with other accounts, I don't understand why it fails after some unfollows without being blocked
Edit3: Seems a sleep(1) problem, @ximhotep **changed them to sleep(5)** and works well on my side again 👍

**Comment by HansDaigle** [comment]
I dont see a Merge ? Can anyone merge this change to master ?

**Pull request merged**
