### PR TITLE
Subject: instagram_title_fix and other fixes

### PR DESCRIPTION
**Pull request by elulcao**
Hello all,

===============================================================================

broser.py:

Added `firefox_options.log.level` = `geckodriver_log_level` for debugging, normal user will use by default 
`info` level
nit: Imports were ordered

===============================================================================

instapy.py:

Modified `followed.txt` log to append information
Added `geckodriver_log_level` for debugging traces, normal user will use by default 
`info` level
nit: Imports were ordered
     handled unbounded variables
     fixed some comments were double quotes were not necessary

===============================================================================

like_util.py:

`like_image` now needs to handle images and videos, for now just informing to the user
that a video was liked or not. For now if a video is found, it will move until comment section and verify if post has been liked or not.

It will be necessary to define if more actions needs to be 
implemented (ie: play or not a video, detect when user posted a video and image in same post, etc.)

nit: Imports were ordered
     handled unbounded variables
     fixed some comments were double quotes were not necessary

===============================================================================

login_util.py:

Added `dissmiss_save_information` in `login_user()`,  for now is better to skip saving cookies.
Addressed issue where 'getTitle' was timing out due to new text from Instagram, now is returned 'Instagram' instead of 'Log In''. Most recent issue I found is #5799, #5145, #5616  

Added 'geckodriver_log_level' for debugging purpose only, a normal user will use 'info' by default but development or debugging should use 'trace'. With this change we can target changes in browser sessions using a high tracing level; it requires the new parameter in InstaPy() object creation.

Problem: Instagram title changed to ´Instagram´
From debug log:
```bash
INFO [2020-10-04 22:07:52] [user]  Creating new cookie...
INFO [2020-10-04 22:08:27] [user]  Timed out with failure while explicitly waiting until title contains 'Log In' string!
Traceback (most recent call last):
  File "/Users/user/Git/InstaPy/instapy/util.py", line 1781, in explicit_wait
    result = wait.until(condition)

geckodriver.log
1601930740848	Marionette	DEBUG	0 -> [0,20,"WebDriver:GetTitle",{}]
1601930740849	Marionette	DEBUG	0 <- [1,20,null,{"value":"Instagram"}]
```

Solution: Updated 'login_page_title' to "Instagram" since "WebDriver:GetTitle"
returns {"value":"Instagram"}

Note: Issue related #5799 
nit: Imports were ordered

===============================================================================

unfollow_util.py:

Fixed `get_users_through_dialog_with_graphql` with a new try/except, I detected that this def could 
fail when the IG is shadow banned. A message with "Failed to Load. Retry" is displayed in this case 
so the JSON is empty. The geckodriver log will have the next traces:

```bash
Marionette: {"value":"{\"message\": \"\", \"spam\": true, \"status\": \"fail\"}"}     
```
nit: Imports were ordered
       handled unbounded variables
       changed `ig_homepage` to `user_link`, the url `https://www.instagram.com` is common in all the cases

===============================================================================

xpath_compile.py:

Added new path used in `login_util.py`

```bash
xpath["dissmiss_save_information"] = {
    "offer_elem_loc": "//*[contains(text(), 'Save Info')]",
    "dismiss_elem_loc": "//*[contains(text(), 'Not Now')]",
}
```

===============================================================================

DOCUMENTATION.md:

Added information for `geckodriver_log_level`, development only
Fixed `like_by_feed` limits from 100 to 50 since function is having `50` by default 
Formatted some text to be aligned. 

===============================================================================

```bash
(venv) ➜  InstaPy git:(instagram_title_fix)   pycodestyle --max-line-lengt=200 instapy
instapy/util.py:1771:9: E731 do not assign a lambda expression, use a def
instapy/util.py:2255:50: E203 whitespace before ':'
(venv) ➜  InstaPy git:(instagram_title_fix)
```

### CODE REVIEW

**Comment by hijak** [comment]
this would fix my issue <3

**Comment by SanielDous** [comment]
I think you should split up your "style improvements" from this merge request. I don't think they are actually related to the issue mentioned in the description. It only makes it harder to review the essential changes. 
However, good work!

**Comment by elulcao** [comment]
> I think you should split up your "style improvements" from this merge request. I don't think they are actually related to the issue mentioned in the description. It only makes it harder to review the essential changes.
> However, good work!

Yep, added missing information,
Thanks for reviewing

**Review by OnlyOneMoreHour — APPROVED** [review]

**Review by timgrossmann — APPROVED** [review]

**Comment by timgrossmann** [comment]
@elulcao Well done! Absolutely nice PR, thank you very much.
Nice and clear explanation of the changes, clean code and comments to explain the additions!

**Comment by artur5236** [comment]
I installed this fix but the issue still persist. 
`
InstaPy Version: 0.6.11
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-10-22 13:05:54] [artur.chojnacki]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-10-22 13:05:54] [artur.chojnacki]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-10-22 13:05:55] [artur.chojnacki]  - Internet Connection Status: ok
INFO [2020-10-22 13:05:55] [artur.chojnacki]  - Current IP is "89.65.119.71" and it's from "Poland/PL"
INFO [2020-10-22 13:05:55] [artur.chojnacki]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-10-22 13:05:55] [artur.chojnacki]  - window.navigator.webdriver response: None
INFO [2020-10-22 13:05:55] [artur.chojnacki]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2020-10-22 13:06:50] [artur.chojnacki]  Timed out with failure while explicitly waiting until title contains 'Login' string!

INFO [2020-10-22 13:07:29] [artur.chojnacki]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20201022-130734.html
**********************************************************************

INFO [2020-10-22 13:07:40] [artur.chojnacki]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 2.1 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-10-22 13:07:40] [artur.chojnacki]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    with smart_run(session):
  File "/usr/lib/python3.7/contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
`

[20201022-130734.zip](https://github.com/timgrossmann/InstaPy/files/5422254/20201022-130734.zip)

**Comment by SanielDous** [comment]
@artur5236 This here solved the problem with 
`INFO [2020-10-22 13:07:29] [artur.chojnacki] Timed out with failure while explicitly waiting until visibility of element located!` 
for me:

https://github.com/timgrossmann/InstaPy/issues/5837#issuecomment-713202414

**Pull request merged**
