### PR TITLE
Fix for empty shared data

### LINKED ISSUE #6199: KeyError: 'graphql'
`Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    with smart_run(session):
  File "C:\Users\rwds\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\rwds\Desktop\a\instapy\util.py", line 1931, in smart_run
    session.login()
  File "C:\Users\rwds\Desktop\a\instapy\instapy.py", line 470, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\rwds\Desktop\a\instapy\print_log_writer.py", line 20, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "C:\Users\rwds\Desktop\a\instapy\util.py", line 469, in getUserData
    data = data[subobject]
KeyError: 'graphql'`

This happens right after Instapy tries to save account progress. 
`Unable to save account progress, skipping data update
        b"'graphql'"`

### PR DESCRIPTION
**Pull request by TomaszWychocki**
## Description

I was getting following error every time I was trying to run the simplest script:
```
INFO [2021-06-17 15:30:35] [LOGIN]  Logged in successfully!
INFO [2021-06-17 15:30:35] [LOGIN]  Saving account progress...
WARNING [2021-06-17 15:30:38] [LOGIN]  Unable to save account progress, skipping data update 
	b"'graphql'"
Traceback (most recent call last):
  File "---PATH---/instaBot.py", line 7, in <module>
    session.login()
  File "---PATH---\InstaPy\instapy\instapy.py", line 472, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "---PATH---\InstaPy\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "---PATH---\InstaPy\instapy\util.py", line 490, in getUserData
    data = data[subobject]
KeyError: 'graphql'
```

I analyzed the code and logs and I found something strange:
```
def getUserData(
    query,
    browser,
    basequery="no-longer-needed",
):
    shared_data = get_shared_data(browser)
    data = shared_data["entry_data"]["ProfilePage"][0]

    if query.find(".") == -1:
        data = data[query]
    else:
        subobjects = query.split(".")
        for subobject in subobjects:
            data = data[subobject]

    return data
```

Sometimes `shared_data["entry_data"]["ProfilePage"][0]` is empty and this is the reason of this crash. Maybe it depends on geolocalization? Fortunately all data needed here can be fetched by get_additional_data() function. My PR fixes this issue and leaves legacy behavior to use get_shared_data() if it's possible.

Fixes #6199

## How Has This Been Tested?

To reporduce this issue, you can run this script:
```
import settings
from instapy import InstaPy

session = InstaPy(username=settings.USER, password=settings.PASSWORD, headless_browser=False)
session.login()

session.set_do_follow(enabled=True, percentage=70, times=5)
session.set_user_interact(amount=3, randomize=True, percentage=70, media='Photo')
session.like_by_tags(['scalemodels'], amount=40, interact=True)
```
Everything works with my fix. I didn't test anything more.

- [x] Test

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (probably not needed)
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project, `black -t py34`
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by schealex** [comment]
this is already fixed in current master...

**Comment by schealex** [comment]
use this guide to update to current master (unreleased version): https://instapy.org/additional-information

**Comment by MohakAoki** [comment]
> use this guide to update to current master (unreleased version): https://instapy.org/additional-information

i have same issue. i read your answer and follow the guid. but with new version also have same error.
Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined

**Comment by akbari-mh** [comment]
> use this guide to update to current master (unreleased version): https://instapy.org/additional-information

i have same issue. i read your answer and follow the guid. but with new version also have same error.
Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined

**Comment by akbari-mh** [comment]
> use this guide to update to current master (unreleased version): https://instapy.org/additional-information

i have same issue. i read your answer and follow the guid. but with new version also have same error.
Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined.

**Review by elulcao — APPROVED** [review]

**Pull request merged**
