### PR TITLE
New feature: like likers

### PR DESCRIPTION
**Pull request by orlangure**
This PR adds a new feature: `like_likers`.

We currently support `follow_likers`, which seems not enough as sometimes we might wish to only like our likers and not follow them (or maybe we already follow them). The code is very similar to `follow_likers`.

Related/might close https://github.com/timgrossmann/InstaPy/issues/4039

### CODE REVIEW

**Comment by timgrossmann** [comment]
@orlangure Thank you very much for this feature!

I'm still very much into having everything as `interact_...` do you think you could refactor this to be a more generic version (so we could use `set_do_like`, `set_do_follow`, `set_do_comment`)?

If not, we maybe should extend the documentation a little bit.
It's not exactly clear to me what all the parameters do.

What is the example of 'not-a-user'?

```python
session.like_likers(['user', 'not-a-user'], photos_grab_amount=3,
                     like_likers_per_photo=3, likes_per_liker=3)
```

Thanks :v:

**Comment by orlangure** [comment]
@timgrossmann, `not-a-user` is just a very bad choice of a username to put after `user` 😹

I'll look into refactoring and generalizing it eventually, not sure when I'll have time. If there is no time pressure, I'll continue using my own fork (I use this feature now) and keep this PR open indefinitely. Unless someone wants to step in and move things around.

**Comment by timgrossmann** [comment]
@orlangure Ahh ok 😂 

Well I think we can merge this for now (after elaborating a bit more in the README and changing the example users 😛)
And then get back to it once we start having a bigger refactoring.

@orlangure Could you do the additions in the README, or should I do them? 😊

**Comment by HCWcoder** [comment]
@orlangure thanks for this feature

**Comment by orlangure** [comment]
@timgrossmann, on it.
@HCWcoder, glad you find it useful😼

**Comment by orlangure** [comment]
I changed `like_likers` docs, let me know if there is something else that needs fixing before the great refactor.

**Comment by dmsfabiano** [comment]
I did a very quick check, but from when I saw there are a couple things you should check. This could have way better functionality @timgrossmann 

1 - New function does not do checks for videos that don't display likes. What will the behavior be?
2 - Where is the check to see if user has likes activated and with what percentage?
3 - Why only `like_likers` and not `interact_likers` the fucntion is already implemented here so most of the work is done; is fairly easy to extend it using API calls to complete interacts (i.e. Like, commenting, following)

New features should be as complete as possible and using the tools we already have (API functions). Otherwise we will end up with a lot of single purpose functions that could be doing a lot more. 

Overall, great addition, I've had something like this in my toolset for a while, but let's make the official version as complete as possible  👍

**Comment by ishandutta2007** [comment]
@timgrossmann 
I have been meaning to stir this discussion , maybe this is the right thread, we have way too many APIs to do the same or similar things. This kind of design is making it a hell to maintain the code.

How I see is there should be one and only one api which does this three steps:
1. Choose target user(by _tag_, or by _location_, or _by hashtag or from Followers/Following of a user_, from _a specific list_)
2. Choose the desired item of that user(_post_ or _profile_ or _comment_)
3. Interact with that item(_follow_ or _like_ or _comment_)

If we see these three steps separaly we may enhance either of one of these three steps iteratively than trying to create new workflows which are essentially new combination of a usecase of these three steps.
You can expose these three APIs separately or wrap with one. To start we can create a universal wrapper and refactor incrementally later as and when we get opportunity.

**Comment by timgrossmann** [comment]
@dmsfabiano Thank you for the review, you've got very good points there. We should consider implementing the mentioned changes @orlangure :blush: 

@ishandutta2007 Well, absolutely. There is an issue open since Feb 19 (https://github.com/timgrossmann/InstaPy/issues/4013) and I already mentioned it several times on the discord channel. Would even be able to provide bounties for the refactoring through OpenCollective. The problem right now only is that I don't have the time to do refactors as big as those ones in my free time.

I'd love to see this happening but well yeah, we can't pay someone for a month to do that. Maybe at some point in the future.
For now having all of them separate with all the logic in place might motivate someone to merge together the logic and still PR an `interact_by` feature.

But I absolutely agree with you!

**Comment by imjustin** [comment]
Has this been merged to the main branch? if I'd like to try this feature, what's the best way to go about that? (sorry i'm not super familiar with git...)

**Comment by orlangure** [comment]
@imjustin not yet. You can do the following with git cli:
```
cd <instapy-dir>
git checkout -b like-likers
git pull origin pull/4177/head
```
This will move you to a new branch from master (latest version) and get the contents of this PR from github. You'll then be able  to use this feature, but only while being on that new branch. If you'd like to use the feature on `master`, just don't `git checkout`.

**Comment by imjustin** [comment]
how does that work if i've installed instapy through the pip3 installer rather than cloning the repo?

**Comment by orlangure** [comment]
I think you can install packages with `editable` option and then modify the files directly.
Or you could clone the repo to some other directory and run it from there a couple of times with this feature branch.

**Comment by imjustin** [comment]
I follow what you're saying in theory, but i'm not sure i'm doing it right in practice haha. so what i've done is cloned your repo with the right interacty_by_likers branch into a separate folder, but when I put my new quickstart.py into that folder and run it from there, i think it's still using the existing installation of instapy. how do i force it to use the local instapy files rather than the system-installed version i previously had?

**Comment by orlangure** [comment]
@imjustin Try looking into virtual environments in python, they can allow to isolate the scripts you are running from other scripts/projects that exist in your environment.

**Comment by timgrossmann** [comment]
@orlangure Sorry for not merging this but I'm sure we can integrate this once we start to refactor our interaction methods into an `interact` based system.
Sorry 😞

**Comment by stephane-archer** [comment]
Any news about this feature? @timgrossmann @orlangure

**Pull request closed without merging**
