### PR TITLE
improve verify action by adding explicit_wait check

### PR DESCRIPTION
**Pull request by sionking**
This check is a must before get_following_status since button change is not guarantee, so get_following_status can return false results, this will later reload and results will be fine but explicit_wait can save time by preventing reload.
explicit_wait  now waits for the exact xpath element, that will prevent false detect.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@sionking Awesome, very important change, thank you very much! 🙏 

Code looks sophisticated, the only thing bugging me are the very specific xPaths at the start of the files...
Do you think we could make them a little bit more dynamic, please?

**Comment by sionking** [comment]
> @sionking Awesome, very important change, thank you very much! 🙏
> 
> Code looks sophisticated, the only thing bugging me are the very specific xPaths at the start of the files...
> Do you think we could make them a little bit more dynamic, please?

Please I have trouble with XPATHing .. if someone can improve it, I really don't know how.
But it must be specific and not generic, to avoid future mistakes.

Sion

**Comment by timgrossmann** [comment]
@sionking Absolutely, could you please resolve the merge conflicts?
I'll take care of the xPath then when testing your updates 😊

**Comment by timgrossmann** [comment]
@sionking I've updated the xPaths. Could you please also give it a go to check if everything still works as before?
Thank you 🙏

**Comment by bugre** [comment]
👏 👏 👏 Nice code. 
I'm no specialist on selenium usage, but always when i wanna use explicit wait, i remember a warning on their page (https://www.seleniumhq.org/docs/04_webdriver_advanced.jsp -- 2nd paragraph.

Per default instapy uses implicit wait (https://github.com/timgrossmann/InstaPy/blob/master/instapy/browser.py#L166), if i remember correctly, i saw somewhere in the code it's setup to 25seconds.

I mention it only to have in consideration with this new code.

**Comment by sionking** [comment]
this explicit wait don't work when following on posts but only on profile. need to find diffrent xpath

**Comment by timgrossmann** [comment]
@sionking What is you proposal with this?
Any way we can update and merge this?

**Comment by mando15** [comment]
Traceback (most recent call last):
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quick starts\majesticwomen.py", line 53, in <module>
    interact=True, sleep_delay=100)
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 3146, in follow_user_followers
    interact)
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 1011, in follow_by_list
    self.logfolder)
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\unfollow_util.py", line 643, in follow_user
    logfolder)
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\unfollow_util.py", line 1450, in verify_action
    post_action_xpath = Selectors.follow_button_xpath
NameError: name 'Selectors' is not defined
>>> 
  ISSUE IM HAVING AFTER TRYING TO SORT THIS BUG PLEASE HELP

**Comment by sionking** [comment]
> Traceback (most recent call last):
> File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quick starts\majesticwomen.py", line 53, in 
> interact=True, sleep_delay=100)
> File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 3146, in follow_user_followers
> interact)
> File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 1011, in follow_by_list
> self.logfolder)
> File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\unfollow_util.py", line 643, in follow_user
> logfolder)
> File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\unfollow_util.py", line 1450, in verify_action
> post_action_xpath = Selectors.follow_button_xpath
> NameError: name 'Selectors' is not defined
> 
> > > >
> 
> ISSUE IM HAVING AFTER TRYING TO SORT THIS BUG PLEASE HELP

Please align to latest.
I think this can be merged, the only issue is the xpath not match when on post.

**Review by MedRedha — APPROVED** [review]

**Comment by breuerfelix** [comment]
@sionking is this PR still a thing ? I wanna clear up the PRs and wanna know if it would be good to resolve the conflicts to merge it, or just close it cause it would be too much work ?

**Pull request closed without merging**
