### PR TITLE
Urgent fix issue that will cause the instapy crash because Instagram changed…

### PR DESCRIPTION
**Pull request by CharlesCCC**
This is needed in order to fix this urgent issue.  It is affect everybody who is using Instapy

### CODE REVIEW

**Comment by bertlandh** [comment]
the master thanks

**Comment by bertlandh** [comment]
do i have to fork your version or can i add the files u changed to tims master

**Comment by CharlesCCC** [comment]
@bertlandh you can manually change in your own repo. we will have to wait @timgrossmann  to merge this PR

**Comment by windgan** [comment]
@CharlesCCC There is an error during unfollowing:

```
INFO [thorraw]  Session started - 2018-03-13 20:32:54
Cookie file not found, creating cookie...
INFO [thorraw]  Logged in successfully!
ERROR [thorraw]  set_automated_followed_pool error [Errno 2] No such file or directory: './logs/thorraw_followedPool.csv'
unable to get user information
 'user'
INFO [thorraw]  Session ended - 2018-03-13 20:33:20
INFO [thorraw]  --------------------
Traceback (most recent call last):
  File "quickstart.py", line 56, in <module>
    session.unfollow_users(amount=1000, onlyNotFollowMe=True, sleep_delay=60)
  File "/home/windgub_gmail_com/InstaPy/instapy/instapy.py", line 1365, in unfollow_users
    self.logfolder)
  File "/home/windgub_gmail_com/InstaPy/instapy/unfollow_util.py", line 152, in unfollow
    variables['id'] = user_data['id']
UnboundLocalError: local variable 'user_data' referenced before assignment
``` 
The problem is in `unfollow_util.py` file (line 138):
`user_data = json.loads(pre)['user']`

**Comment by CharlesCCC** [comment]
@windgan looks like totally different error.

Can you check if this file exists on your locally ?  
`./logs/thorraw_followedPool.csv` 
it says missing the file...

**Comment by windgan** [comment]
@CharlesCCC 

> it says missing the file...

It is not an initial cause, I think. 
I disabled unfollowing in my quickstart.py and InstaPy works fine after it.

Try to run InstaPy with unfollowing operation.

**Review by wemakefuture — APPROVED** [review]

**Comment by GabrieleCalarota** [comment]
@windgan 

user_data = json.loads(pre)['user']

change to

user_data = json.loads(pre)['graphql']['user']

**Comment by sionking** [comment]
@CharlesCCC you are doing a good jjob !

**Comment by timgrossmann** [comment]
@CharlesCCC can we merge this?
What's the part that @GabrieleCalarota mentioned?

**Comment by windgan** [comment]
@GabrieleCalarota @timgrossmann 

> user_data = json.loads(pre)['user']
change to
user_data = json.loads(pre)['graphql']['user']

Need to fix it.

**Comment by CharlesCCC** [comment]
```
user_data = json.loads(pre)['user']
change to
user_data = json.loads(pre)['graphql']['user']
```
has fixed with the latest PR #1616

**Comment by patrickdundas** [comment]
@CharlesCCC Thanks mate! You've made our lives simpler with this one

**Comment by condomfighters** [comment]
thanks boi

**Comment by athena15** [comment]
Still seem to have had this issue despite installing InstaPy on my Rpi for the first time ever today. I had to make these changes manually, and that fixed the issue, but the version that installed on my machine via the instructions for the RPi does not seem to be current.

**Pull request merged**
