### PR TITLE
applying @sionkings proposal about getting post count

### PR DESCRIPTION
**Pull request by timgrossmann**
Thanks @anna-osipova for pointing this out
@sionking For the more generally applicable fix

### CODE REVIEW

**Comment by sionking** [comment]
verified

**Comment by timgrossmann** [comment]
@sionking I just saw that the 
```python
num_of_posts_txt = num_of_posts_txt.replace(" ", "")
num_of_posts_txt = num_of_posts_txt.replace(",", "")
num_of_posts = int(num_of_posts_txt)
```

Is only inside the second except block, shouldn't this be on the root level like the return statement?

**Comment by sionking** [comment]
@timgrossmann  no the graphql return int.

**Comment by timgrossmann** [comment]
@sionking Thank you for clarifying, the graphql in fact returns an int.

Also, I just realised that the indentation of the conversion is one less than the try/catch block which means that it will be executed after either the try or catch block have been completed.

Thank you @sionking

**Pull request merged**
