### PR TITLE
Store username in statistics sqlite DB

### PR DESCRIPTION
**Pull request by 2ZZ**
Added updates to store the account's Instagram username in the statistics table. Useful if you run with multiple accounts and want to see stats. Also added DB check to see if any likes/follows have been completed already to prevent going over daily limits when Selenium crashes. Set this to default off.

### CODE REVIEW

**Comment by CharlesCCC** [comment]
You will need resolve the merge conflicts first before it can be test/merged. 
you can do it by merge latest master branch to your feature branch.

**Comment by timgrossmann** [comment]
@2ZZ Any updates on this?
Is this still on?

**Comment by MrBeardedGuy** [comment]
@2ZZ Any update on this???

**Comment by CharlesCCC** [comment]
@2ZZ  :) still there ?

**Pull request closed without merging**
