### PR TITLE
Fixed xpath for get links of feeds

### PR DESCRIPTION
**Pull request by kharazian**
## Description
 get_links_from_feed() was failing because could not be found in the path matching  "//article/div[3]/div[2]/a" and solved with changed to //article/div/div[3]/div/div/div[2]/a
 
 Fixes # (issue)
 
 ## How Has This Been Tested?
 Locally installed and able to use get_links_from_feed()
 
 * [x]  Test
 
 ## Checklist:
 * [x]  I have commented my code, particularly in hard-to-understand areas
 * [x]  I have made corresponding changes to the documentation
 * [x]  I have checked my code and corrected any misspellings
 * [x]  I have performed a self-review of my own code
 * [x]  My code follows the style guidelines of this project, `black -t py34`
 * [x]  My changes generate no new warnings

### CODE REVIEW

**Review by gdr2404 — APPROVED** [review]
This worked great for me!

**Review by kharazian — COMMENTED** [review]
viewed.

**Review by erwinbierens — COMMENTED** [review]
Worked for me, thanks!

**Review by erwinbierens — APPROVED** [review]
Great worked for me!

**Pull request closed without merging**
