### PR TITLE
Fix issue #5002 with new feature

### PR DESCRIPTION
**Pull request by ianmihura**
Issue #5002 : internet connection status = error, when it should not be error
check_browser() function in login_util.py does some checks online that depend on some third party webpages to be available, which does not guarantee the integrity of the results of this check. To my experience this crashes more often than not.
 
New feature : want_check_browser boolean option at session start, prompts the user a possibility to decide if they want to perform this online check.

### CODE REVIEW

**Comment by christophe-duc** [comment]
@converge: what do you think? you were the one adding the checks. Let us know your thoughts.

**Comment by breuerfelix** [comment]
@ianmihura could you please run `black -t py34 .` locally and commit the changes so the tests work ? :)

**Comment by ianmihura** [comment]
I'm sorry for my lack of knowledge, but I have no global variable, executable or file named black

**Comment by riccardovalente** [comment]
> I'm sorry for my lack of knowledge, but I have no global variable, executable or file named black

Try pip3 install black

**Comment by ianmihura** [comment]
Are there any follow-ups with this pull requests?

**Comment by breuerfelix** [comment]
@ianmihura sorry for not paying attention... guess everybody from the core team got a lot of stuff to do right now :S

are you able to add just a short section about this parameter in the documentation file ? guess then everything is done to merge this pr :)

**Comment by ianmihura** [comment]
Short description added ;)

Hope it helps!

**Comment by timgrossmann** [comment]
Page that is checked is down (https://isitdownorjust.me), that's probably why it fails most of the time...

Relying on third party applications is error prune, we could just check the response code of simple get request to Instagram to check if it's there or not...

**Pull request merged**
