### PR TITLE
Insert target users, hashtags etc from text file - Issue #5396

### PR DESCRIPTION
**Pull request by IreneArapogiorgi**
Hello, I was assigned to implement the ability to parse text files containing target users, hashtags, comments etc in order to use it with functions which accept lists as given parameters. This will be a part of a university assignment of mine as I also mentioned on issue #5396.

**Functions added:**
file_handling in util.py
target_list in instapy.py

_PS: At first, I implemented file_handling function inside instapy.py (with only a few changes) & that also worked, but I had to change that implementation because I wasn't able to do some unit testing._

**Unit testing:**
test_file_handling.py in tests folder
invalid_target_list.txt in tests/resources folder
valid_target_list.txt in tests/resources folder

**Example of using new feature in quickstart.py**
```
""" Quickstart script for InstaPy usage """

# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

# login credentials
insta_username = "your instagram username"
insta_password = "your instagram password"

# get an InstaPy session
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):

    # like posts based on hashtags
    hashtags = session.target_list("C:\\Users\\..........\\hashtags.txt")
    session.like_by_tags(hashtags, amount=9)
```
If there are any changes/improvements needed, please let me know so that I can work on them.

I will be thrilled if you accept my contribution in the end, as this is also a grading factor for my assignment.

### CODE REVIEW

**Comment by breuerfelix** [comment]
Clean code, looking really good!

Would you mind also adding a quick line in the changelog file and also put some example in the documentation ? somewhere in the section about like by tags :)

otherwhise nobody will ever know that this function exists cause the majority is not looking in the code and only have a look at the documentation :)

**Review by breuerfelix — CHANGES_REQUESTED** [review]
a note in the changelog and some example in the documentation :)

**Comment by IreneArapogiorgi** [comment]
Thank you for your response! I just made all changes required, so I guess I'm waiting for a new review and possible acceptance of my contribution.

**Review by breuerfelix — APPROVED** [review]

**Comment by breuerfelix** [comment]
Thanks alot, nice work :) 

Good Luck with your assignment :)

**Pull request merged**
