### PR TITLE
Update to let Blacklist Actually be referred

### PR DESCRIPTION
**Pull request by redsector72**
This PR add support for the blacklist check.
The actual code does not work for me on python 2.7, my modification works perfectly.
Take care

### CODE REVIEW

**Comment by timgrossmann** [comment]
@redsector72 Perfect, looks way better now!
Let's just check it and merge this asap.
Thank you

**Comment by timgrossmann** [comment]
@redsector72 Just saw that we're doing this for every username that has to be validated.
What is the reason for positioning this code snippet there?
Wouldn't it be better to load the blacklist once?

**Comment by redsector72** [comment]
My programming knowledge is limited. 
The blacklist function was already there in the code as this is where each user get validated.
Probably the original code was in accordance with your idea, but it does not works as expected in python 2.7.
I do not have the knowledge to "load the blacklist once"

**Comment by timgrossmann** [comment]
@redsector72 I think we can merge this for now, I've seen that this method is not called too extensively.
Could you add an entry to the CHANGELOG file as a fix, please?

**Comment by redsector72** [comment]
I hope to have done it correctly.

**Comment by timgrossmann** [comment]
@redsector72 Fixed it 😉 

Thank you for this PR

**Comment by LotusPainter** [comment]
Does this work in regards to when the bot grabs followers from an account? i.e 

```
User 'EXAMPLEUSER' [1/1]
Grabbed 5 usernames from 'EXAMPLEUSER's `Followers` to do interaction.
```

Before grabbing the 5 usernames the bot should check to make sure none are in the blacklist. Otherwise it will waste time skipping each user that is in blacklist, and also subsequently increase the count/amount on `session.interact_user_followers ` which of course we want to avoid for skipped accounts.

**Pull request merged**
