### PR TITLE
Follow someone else's followers

### PR DESCRIPTION
**Pull request by BernardoGO**
**Follow the followers of a given user or follow everyone that a given user is following**
- Follows everyone or an specified amount of users
- Built-in delays following the ones we see in the unfollow function
- Keep track of followed users using the existing log handler
- Sets follow_restrict
- Skips users that are already being followed
- Sleeps for 10 minutes after 10 users
- Makes use of the dont_include list to skip users

**follow_through_dialog function**
- A centralized way to handle all the following tasks done in the dialog list
- Currently being used by both functions above

**formatNumber function**
- Converts to integer numbers like: 2.2K, 1K...
- Added to util.py

**Example for following followers**
- Examples were added

### CODE REVIEW

**Comment by BernardoGO** [comment]
Ok, I just realized that @timgrossmann has set a bounty for this feature in #444.
I'll implement the other requirements.

**Comment by BernardoGO** [comment]
**I can provide a list of users from which the followers will be followed**
- Both functions can now accept either list or str for the accounts.

**I can provide a number of followers which will be used for each provided account**
- Already done in the first comment.

**I can either choose to do it top-down or "random", which will simply follow some random followers**
- Both functions will pick the users to follow in a random or top-down fashion, selectable.

**The feature can be "easily" extendable with the next "interact with user" feature**
- Both functions have their core functionality implemented in a single method, making it easy to extend. Since it contains a list of the picked users it is easy to implement callbacks, export a list or add another feature into it. The callbacks can be used to like or comment for a specific user.


Example of simple callback to extend the function:
```
    def printName(name):
        print("Callback: " + str(name))
    followNum = follow_through_dialog(browser, user_name, amount, dont_include, login, follow_restrict, allfollowing, random, callbacks=[printName])

```

So this will basically call the function `printName` for each user it follows. The output will be:

> [bernardo@foobar-pc InstaPy]$ python followExample.py 
> Logged in successfully!
> --> Ongoing follow 1, now following: b'friend2'
> Callback: b'friend2'
> --> Ongoing follow 2, now following: b'friend1'
> Callback: b'friend1'
> --> Total people followed : 2 
> 
> Session ended
> -------------


This is probably all for #444

**Comment by timgrossmann** [comment]
@BernardoGO Awesome! 
I'll try to find time today to test this feature and will get back to this ASAP.

Thank you very much for your contributions.
(Maybe you'll also be interested in working on the next bounty feature as well :P )

**Comment by timgrossmann** [comment]
@BernardoGO What I unfortunately also have to ask for (even though not explicitly stated in the requirements) is some documentation of the feature in the README.

Please add that

**Comment by BernardoGO** [comment]
@timgrossmann Documentation added.
(I'm down for more bounties.)

Another cool thing about this implementation that I forgot to say is that instead of getting the list of everyone in the dialog (as seen in the unfollow function), it get only the ones that are not being followed so there is no risk to pick someone that is being followed already.
It uses a random sample instead of following a top-down fashion with a chance to follow. This provides a better distribution.
It is also guaranteed to follow the specified amount even in random unless there are no users left to follow. If it cannot follow or if the picked user is in the dont_include list it will repick.

The follow_through_dialog() function can be modified to handle the unfollow too. It will fix some of the problems related to the unfollow itself and also make the maintenance easier. If you think it's cool I can make it in another PR later.

**Comment by timgrossmann** [comment]
@BernardoGO I only need to do some local testing to make sure it works and look over your code really quickly.

Thank you so much for making InstaPy a little bit better, I really appreciate all the support and contributions to this project 👍 

The improved unfollow sounds awesome!
If you could make a PR for that as well, I'd be very thankful!

**Comment by BernardoGO** [comment]
The way I'm seeing this is to use that 'follow_throught_dialog" function only to get the users and use the callbacks to do the other interactions.
In this case, even the following part would be moved to a separate callback. 

Tell me what you think about this design. I think it helps to implement new interactions and also select which one to do.
Maybe this next PR should go to the develop instead?

**Comment by timgrossmann** [comment]
@BernardoGO Sounds good to me. I think this design is, as you already stated, a nice decision for the develop branch.

Your PR works like charm. Do you already have a bounty source account?

This fixes #444

**Comment by timgrossmann** [comment]
@BernardoGO Please visit https://www.bountysource.com/issues/47675897-interact-with-the-followers-of-given-list-of-users and "Claim Bounty" 👍 

Thank you for contributing

**Comment by BernardoGO** [comment]
Thanks, @timgrossmann. I have an account, just claimed the bounty.

**Comment by timgrossmann** [comment]
@BernardoGO Should already be paid out 😉

**Comment by jeffreylm** [comment]
This is really a nice system this github. Learning python now and from reading all the fixes and using the scrpts, it really is helping with the learning curve. Just last week had no idea what import did and why it was used, now it's totally clear.  It will be funny some day when I look back and tell my learning story, I will say I learned python through learning to use a opensource bot created by @timgrossmann , hahahahahahaha

**Comment by thonyhenrique** [comment]
Do you add this line of code in quickstart.py?

**Pull request merged**
