### PR TITLE
minor addition to docs

### PR DESCRIPTION
**Pull request by ishandutta2007**
PR to master as are minor changes.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@ishandutta2007 Seems like the organization has been flagged and will be on watch by GitHub.
I don't think directly forwarding traffic from InstaPy and therefore directly associating it with each other will do good to the project. Sorry.

What are your thoughts on that, I'd really appreciate to know and understand.

**Comment by ishandutta2007** [comment]
@timgrossmann It has been flagged for sending 200+ invites in a single day. I am on dialogue with the github support team. I am cancelling all pending invites, once unflagged there wont be any issue
 linking it.

**Comment by timgrossmann** [comment]
@ishandutta2007 Any updates on the orga? 😊

**Comment by ishandutta2007** [comment]
@timgrossmann it has been unflagged, I believe you received a notification too since you are one of the admins. Interestingly github don't disclose the upper limit on the number of invites or follows or PRs allowed no matter how you ask them.

**Comment by timgrossmann** [comment]
@ishandutta2007 Thanks for letting me know 😊 
I see that it has been unflagged and understand that it was flagged because of too many invites being sent out.

I like the idea of having a pool of bots for everything, I even had the same idea about the naming 😄 
However, I think referencing should be done in a different way to not confuse the connection of InstaPy with the other tooling.
The InstaPy community at this point in time, should focus on InstaPy itself. Especially the people that might be interested in working on an Open Source project like InstaPy.

Therefore I think cross-referencing projects other than directly related tooling will overflow the readme and take away focus from the dashboard and GUI tooling.

I'm confident that one point in time we can add references to other tooling in this Readme to use the attention of InstaPy for other projects,

Hopefully you can understand parts of my reasoning

**Comment by ishandutta2007** [comment]
> The InstaPy community at this point in time, should focus on InstaPy itself. Especially the people that might be interested in working on an Open Source project like InstaPy.

It's not about focus, it's more about maximising code reusability.
See I have abstracted out common logic to a separate package (https://github.com/socialbotspy/SocialCommons)
Even though InstaPy don't have any shortage of developers  but even InstaPy can start using it as a library so that it can benefit from the contributions of people interested in other social netoworks but not instagram and vice-versa.

**Pull request closed without merging**
