### PR TITLE
ADDED - break if image already liked

### PR DESCRIPTION
**Pull request by YannikFirre**
Hello,

Break the current loop if one image is already liked. #2827 

What do you think ?

### CODE REVIEW

**Comment by sionking** [comment]
Will it break the tag/location loop ? not a good idea, maybe you should count at least 5 .

**Comment by YannikFirre** [comment]
Why after x count ? if one image is already liked, the following ones too. 

No ?

**Comment by Nocturnal-2** [comment]
> if one image is already liked, the following ones too

@InfinityWebMe not necessarily. While liking images using closely related tags, there are chances that some images are posted with both these tags. For example, consider the tags 'pursuitofportraits' and 'portrait_perfection'. Assuming that both these tags are in _like_by_tags_ list and assuming we like by  'pursuitofportraits' first and 'portrait_perfection' next, we might encounter an image which has both these tags. So if we break on first _already liked image_ while traversing through 'portrait_perfection' (since it also had hashtag 'pursuitofportraits'), we will miss other images which did not use 'pursuitofportraits' but only used 'portrait_perfection'.

So like @sionking has mentioned, it will be better to break only if there is an _x_ number of _continuous already liked images_.

**Comment by YannikFirre** [comment]
Good catch, i will change this PR :)

**Comment by redsector72** [comment]
I think the best way to address this is the blacklist. 
If a user is in blacklist, it is skipped.
No need to break cycle.

**Comment by YannikFirre** [comment]
@redsector72 i don't understand what you mean ? How the blacklist can affect the images already liked ?

**Comment by YannikFirre** [comment]
@sionking @Nocturnal-2  Like this ?

**Comment by redsector72** [comment]
@InfinityWebMe you can use the black list function. When you first like, the user is blacklisted and will never get a second like. there is no need to break, as the users are skipped already.

**Comment by InfinityWebMe** [comment]
@redsector72 okey but you need to remove them for the next tag/action. 

Use the blacklist function is not enought.

**Comment by YannikFirre** [comment]
@redsector72 Not if you use multiple tags.

**Comment by YannikFirre** [comment]
@timgrossmann  Any review on this ? :)

**Comment by converge** [comment]
hey mate, it's a really nice idea!

I tested it, but it doesnt seam to work for me, I set:
```python
session.set_break_after_already_liked(after=2)
session.like_by_tags(['balao', 'bike'], amount=5)
```
but it keeps liking already liked posts

To merge it we will also need an update in our README file explaining the feature.

Congratulations! Some adjust and we're ready to merge it.

**Comment by timgrossmann** [comment]
@InfinityWebMe Any updates on this? 😊

**Comment by timgrossmann** [comment]
@InfinityWebMe Any updates on this? 😊

**Comment by timgrossmann** [comment]
@InfinityWebMe Unfortunate that we had to close this... 
I'm really sorry to see this.

Maybe if we can update everything to the current state, we can get this feature merged 😊

**Pull request closed without merging**
