### PR TITLE
Daily limit based on converge/limit_daily_interactions

### PR DESCRIPTION
**Pull request by ugurozturk**
Please review carefully. I am not good on python. I dont want to damage this amazing InstaPy repo.

Note : it didn't auto-merge so i did manuelly, anyhow i might did something wrong in the merging. Saying again, please review carefully

### CODE REVIEW

**Comment by timgrossmann** [comment]
@ugurozturk Thank you very much!
We will review this soon.

**Comment by converge** [comment]
Hey mate, it will be great, just need some little improvements.

- we're using a new logging system, and we show log informations in this way (ex.):
```self.logger.info('Session started')```

- we can avoid repeating verification for every method and use only one verification at update_statistics method, to keep InstaPy working after it, we could have something like an action control (able to like, but comment is not available because it already reached it's daily limit)

**Comment by ugurozturk** [comment]
is self.logFile.write still avaible or no-needed ? 

https://github.com/timgrossmann/InstaPy/pull/1034/files#diff-de2ecb8866219bb53ba97e8377a2f26dR425

**Comment by converge** [comment]
hey @ugurozturk, it's not needed, neither print, just logger is enough to do the magic.

**Comment by ugurozturk** [comment]
- [x] logger system
- [ ] avoid repeating verification
-- couldn't find any solution for it. Couldn't use limit parameters inside update_activity so couldn't send it to check_activity_limits. Tried to create an table and go with it then got problems.
-- Using sqlite: What will happen if a person did use the limitions then will not use anymore. The table would be there so the inside check_activity_limits how to know if the person is using or not
- [ ] able to like, but comment is not available because it already reached it's daily limit.

**Comment by beranPro** [comment]
+1

**Comment by luigifaticoso** [comment]
This would be awesome!

**Comment by timgrossmann** [comment]
@ugurozturk Any updates on this?

**Comment by ugurozturk** [comment]
@timgrossmann nope and closing this

**Pull request closed without merging**
