### PR TITLE
Add decision making in interaction

### PR DESCRIPTION
**Pull request by sionking**
When interaction with a user start we shall:
* do at least one action follow/like/like+comment if validation is pass
* dont follow if one image in posts fail in check_image (optional* default is True)
* roll decision again in second post and beyond.
* fix: don't try to follow (again) when amount of posts is more than 1.
* save time by not checking the data bases over and over (static decisions)

Please verify logic.

### CODE REVIEW

**Comment by sionking** [comment]
can someone try?

**Comment by timgrossmann** [comment]
@sionking Just tested it and it seems to work fine, when looking through the code I noticed a tiny typo, fixed that before merging.

Thanks for the improvements, @sionking 
Really appreciate that!

**Comment by sionking** [comment]
But more important, is this something tht we all agree we need ?

**Comment by timgrossmann** [comment]
@sionking Good question.

For me: 

> - do at least one action follow/like/like+comment if validation is pass

That's the only thing I actually can't say anything about... For me, this is kind of weird, however it seems like some users forget to actually put some settings into the quickstart when using the interact function. Encountering a problem they might not know how to fix.
Also, could you point me to the part in the code where you do one of the actions if the validation passes? Somehow I might understand this wrong.
Is this simply the part which skips if all the settings are not set?

> - dont follow if one image in posts fail in check_image (optional* default is True)

Absolutely believe that this is what users want (including me)

> - roll decision again in second post and beyond.

Should've been like that from the beginning. Makes way more sense

> - fix: don't try to follow (again) when amount of posts is more than 1.

Totally valid, just wastes time

> - save time by not checking the data bases over and over (static decisions)

Also totally valid

**Comment by sionking** [comment]
> Also, could you point me to the part in the code where you do one of the actions if the validation passes? Somehow I might understand this wrong.
> Is this simply the part which skips if all the settings are not set?

I don't understand what you meant sorry.

**Comment by timgrossmann** [comment]
@sionking 
I just saw this:
> do at least one action follow/like/like+comment if validation is pass

And for me it reads like even if the user has nothing enabled with `.set_do_...` you simply do one interaction just because the user is pass

However I can't find this behaviour in your code so I guess I misunderstood this.

**Pull request merged**
