### PR TITLE
Stories: various small fixes

### PR DESCRIPTION
**Pull request by christophe-duc**
small fixes on stories:
- ensure that we work with tags where input was lower/upper case (for example #InstaGood), reported by JayPixx
- added action_delays for story (suggested by JayPixx)
- updated the TOC of the documentation (reported by Leak)

### CODE REVIEW

**Comment by HCWcoder** [comment]
@christophe-duc That was fast! **Thanks alot**

**Review by HCWcoder — COMMENTED** [review]
**I Used this script:**
```
    session.set_action_delays(enabled=True,
                           story=10)
    session.set_do_story(enabled = True, percentage = 100, simulate = True)

    # activity
    session.story_by_tags(['techno','techhouse','housemusic'])
    
```
```
................................................................
INFO [2019-07-23 23:00:00] [Unknown]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-07-23 23:00:00] [Unknown]  Saving account progress...
INFO [2019-07-23 23:00:04] [Unknown]  Tag [1/19]
INFO [2019-07-23 23:00:04] [Unknown]  Loading stories with Tag --> b'techno'
INFO [2019-07-23 23:00:16] [Unknown]    --> simulated watch reel # 1
INFO [2019-07-23 23:00:22] [Unknown]    --> simulated watch reel # 2
INFO [2019-07-23 23:00:28] [Unknown]    --> simulated watch reel # 3
INFO [2019-07-23 23:00:33] [Unknown]    --> simulated watch reel # 4
INFO [2019-07-23 23:00:37] [Unknown]    --> simulated watch reel # 5

INFO [2019-07-23 23:00:54] [Unknown]  Sessional Live Report:
        |> No any statistics to show
```

**As you can see its not pausing for 10 seconds between the actions .**
there is like 5 to 6 seconds between watching each story ( I think this is the time the code need to be executed)

**Comment by christophe-duc** [comment]
@HCWcoder : yes, the action delay happens in between stories, not in between reels. I cannot really wait in between reels, because you are "supposedly" watching the story, so I have to send the events that you have seen it fast enough. (the reels are the different segments inside the stories)

hope it helps.

**Comment by HCWcoder** [comment]
@christophe-duc Oh okay I see thanks for clarifying :)

well done!

Edited:
Can we somehow disable video  ? as we are disabling images on the browser
so we can turn off Simulate and dont waste data consumption

**Review by converge — APPROVED** [review]
🤘

**Comment by christophe-duc** [comment]
@HCWcoder : just set simulate to True and you will not be downloading anything.

**Pull request merged**
