### PR TITLE
Fix for scrollIntoView error

### PR DESCRIPTION
**Pull request by honoallu**
New xPath for Follower Dialog Box

File changed:  instapy/unfollow_util.py

### CODE REVIEW

**Comment by tE3m** [comment]
Great! Have you tested it?

**Comment by honoallu** [comment]
yep

**Comment by tE3m** [comment]
@timgrossmann @uluQulu looks like we have a very quick fix here

**Review by timgrossmann — APPROVED** [review]

**Comment by Kazansky** [comment]
With that fix now I have  "Failed to load desired amount of users!"

**Comment by uluQulu** [comment]
@Tr1pke https://github.com/timgrossmann/InstaPy/pull/3910

**Comment by soltanabadiyan** [comment]
instagram changed DIVs, use  "//body/div[3]/div/div[2]" in unfollow_util.py line 654

**Comment by timgrossmann** [comment]
@soltanabadiyan Could you please PR this? 😊 

I'll try to go over the PRs tonight, so it would be perfect if I could just check the PR and merge it to fix it 🙏

**Pull request merged**
