### PR TITLE
1321_1314_1304_1300_1299_1285_1065_1046_1042_bug_fix

### PR DESCRIPTION
**Pull request by converge**
#1321 #1314 #1304 #1300 #1299 #1285 #1065 #1046 #1042 bug fix

### CODE REVIEW

**Comment by timgrossmann** [comment]
Can someone second this is working on all platforms?

Thank you @converge !

**Comment by FreakyBoy** [comment]
Work for me on Raspberry Pi 3, Debian Stretch VPS and Bannani Pi R2
all headless 34bit and 64 bit / firefox and chrome

**Comment by wizarduk** [comment]
@converge best way to update this on Linux ?

**Comment by converge** [comment]
@wizarduk git pull at InstaPy folder

**Comment by wizarduk** [comment]
@converge thanks updated all servers and working perfect !!!

**Comment by filipstrapinadotcz** [comment]
Not working on Windows. It will load only 27 pics at all with whatever settings. And yes, I did pull today.

-------------------------------------------------------------------------------------------------------

C:\Users\Filip Strapina\Documents\GitHub\InstaPy>set PYTHONIOENCODING=UTF-8

C:\Users\Filip Strapina\Documents\GitHub\InstaPy>py quickstart.py

DevTools listening on ws://127.0.0.1:12427/devtools/browser/ad15c4ea-b24d-48ba-86bc-01abbe9eea02
INFO [filipstrapinadotcz]  Session started - 2018-02-13 19:28:24
WARNING [filipstrapinadotcz]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [filipstrapinadotcz]  Logged in successfully!
INFO [filipstrapinadotcz]  Tag [1/1]
INFO [filipstrapinadotcz]  --> b'brno'
[11880:3456:0213/192854.754:ERROR:connection.cc(1947)] Cookie sqlite error 1555, errno 0: UNIQUE constraint failed: cookies.creation_utc, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, secure, httponly, firstpartyonly, last_access_utc, has_expires, persistent, priority) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)

**Comment by filipstrapinadotcz** [comment]
@converge did not helped :(

**Comment by converge** [comment]
hi @filipstrapinadotcz , this fix/PR isn't related to your issue..

**Comment by filipstrapinadotcz** [comment]
@converge weird, I clicked here through several post by googling "Cookie sqlite error 1555"

**Comment by uluQulu** [comment]
hi @converge,
There is a situation I had where the element was undetectable by Selenium then I remembered this commit WHERE _after this PR I did check that the full (_prior_) element XPATH was correct but you used targeted class's XPATH only and it did work._
##### It has been a mystery for me back then but after the situation I had last time, I reminded this method and guess that it is a similar situation.
Can you tell the idea behind this method?
Thanks!

**Pull request merged**
