### PR TITLE
Fix like when the "Get the App" bar is visible

### PR DESCRIPTION
**Pull request by eduardocalazansjr**
Instead of calling Selenium method Click, get the Class of the Like
Button and do a Click() with Javascript.

If there’s an element above the Like Button, Selenium doesn’t hit it
and throw an error, JS don’t.

### CODE REVIEW

**Comment by eduardocalazansjr** [comment]
Fixes #42

**Comment by timgrossmann** [comment]
@vlntdds Insanely smart fix for this problem!
Thank you.

**Comment by blesson3** [comment]
This change was overwritten in the current `master` commit 7ab3e0042c3c8ed9c7f5abad9d201ed55b972b54 (file w/ line: https://github.com/timgrossmann/InstaPy/blob/master/instapy/like_util.py#L538).

I suspect the overwrite is causing issues that this PR solved to come back up.

**Comment by timgrossmann** [comment]
@blesson3 Thank you for pointing out!
Can you double check if it works again now?

**Comment by blesson3** [comment]
@timgrossmann I ran the script for a while and it seemed to fix the problem with clicking the like button! 

I see that you overwrote that line above to what the PR changed it to, see below why I don't think the solution is that easy in this case. https://github.com/timgrossmann/InstaPy/commit/ad6e579b56b464698cd13b01faca18291f639659
(https://github.com/timgrossmann/InstaPy/blob/master/instapy/like_util.py#L538)

Now I'm running into another issue similar, but different:
```
except: Message: unknown error: Element <a href="/explore/tags/sun/?max_id=1691136460033415146" class="_1cr2e _epyes">...</a> is not clickable at point (381, 340). Other element would receive the click: <div class="_eyflt">...</div>
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-53-generic x86_64)
```

See the following issue for discussion: https://github.com/timgrossmann/InstaPy/issues/1232

**Pull request merged**
