### PR TITLE
Incorporate fixes for/from Issue #2131

### PR DESCRIPTION
**Pull request by jaybocc2**
Thanks everybody for the solutions as i ended up not having time to put it all together.  

Here is the aggregated fixes from #2131

### CODE REVIEW

**Comment by jaybocc2** [comment]
still some things to fix `{"method":"xpath","selector":"(//div[contains(@class, '_9AhH0')])[0]"}`

**Comment by uluQulu** [comment]
Nice going @jaybocc2 
I just checked and the fix in here is not identical as suggested in https://github.com/timgrossmann/InstaPy/issues/2131#issuecomment-393550848 that's why you have encountered that problem.

_I recommend to re-check all of the changes in all three posts at https://github.com/timgrossmann/InstaPy/issues/2131#issuecomment-393531365 (_your problem was solved in this one_), https://github.com/timgrossmann/InstaPy/issues/2131#issuecomment-393550848 and https://github.com/timgrossmann/InstaPy/issues/2131#issuecomment-393567856._

Cheers 👍

**Comment by jaybocc2** [comment]
@uluQulu  updated per your feedback

**Comment by joanroig** [comment]
As said here by @mrboomer : https://github.com/timgrossmann/InstaPy/issues/2133

> It seems they updated their styles which changed the select element class name from _fsoey to hztqj. This edit belongs in the login_util.py.

After changing it, seems to work for me. Probably after cleaning cookies this change will be needed too.

@uluQulu I want to say that after some ongoing unfollows this message is shown: `unfollow loop error Message: stale element reference: element is not attached to the page document`, any idea on that :S ?

**Comment by uluQulu** [comment]
Hey guys
This needs to be merged ASAP (_and some other PRs related to the changes occurred after page element re-naming_).
Do you also approve this?
@timgrossmann @sionking @CharlesCCC 

Thanks @jaybocc2 for great efforts!

**Comment by uluQulu** [comment]
@joanroig 
There is a guy- @sionking, who knows **stale element exceptions** very well and maybe already knows the solution ;)

**Comment by timgrossmann** [comment]
@uluQulu Feel free to merge the PRs that are open and working.

**Comment by sionking** [comment]
Hi regarding stale element exceptions
what is the issue?

        # https://stackoverflow.com/questions/16166261/selenium-webdriver-how-to-resolve-stale-element-reference-exception
        # 1. An element that is found on a web page referenced as a WebElement in WebDriver then the DOM changes
        # (probably due to JavaScript functions) that WebElement goes stale.
        # 2. The element has been deleted entirely.

Sorry I am not here to help more, I have 2 kids and 2 jobs :()

**Comment by uluQulu** [comment]
Thanks @timgrossmann 
I started using GitHub with this project and I have not so good merging skills like you :_)

Well, I tested again and everything is applied correctly by @jaybocc2 and these changes are being used by many in #2131 without a problem, so, in this important day of GitHub's acquisition by Microsoft I will do my first merge into an external repository 🎉

Hope you keep continuing it 👍

**Pull request merged**
