### PR TITLE
Fixed #6417

### LINKED ISSUE #6417: Cannot get followers of owner account if it's private
## Expected Behavior

Get followers/followings of owner profiles.

## Current Behavior

Logs "this account is private".

## Possible Solution (optional)

Modify relationship_tools.py to check if `not username == self_username`.

### PR DESCRIPTION
**Pull request by k86td**
## Description

Fixes #6417

## How Has This Been Tested?

- [x] Using grab_following
- [x] Using grab_followers
- [x] Using pick_unfollowers

### CODE REVIEW

**Comment by elulcao** [comment]
@k86td 
Could you check the test results, thanks

**Review by lukesikora — APPROVED** [review]
LGTM

**Review by elulcao — APPROVED** [review]

**Comment by elulcao** [comment]
Merging changes, the functionality is not compromised

**Comment by lucianolacurcia** [comment]
this also closes this: 
https://github.com/InstaPy/InstaPy/pull/6344

**Pull request merged**
