### PR TITLE
Fix 'Failed to load desired amount of users!' issue

### PR DESCRIPTION
**Pull request by uluQulu**
Dialog box has changed, XPath was affected by that.

### CODE REVIEW

**Comment by HCWcoder** [comment]
@uluQulu 
Thanks mate I can confirm its working now !

**Comment by tourhuntr** [comment]
Works for me

**Comment by sionking** [comment]
thanks, will check now.
Isn't there a more general path than structured ?

**Comment by sionking** [comment]
is it the same change for every one or it is a/b testing ?

**Comment by timgrossmann** [comment]
@uluQulu @sionking Feel free to merge this if it's working.

I'm having trouble with my laptop battery so I'm on GitHub only sparsely till Friday.

**Comment by uluQulu** [comment]
Thanks all. 
This is a broader problem and affects many blocks. 
That's why must be solved quickly. 
İ've also received from people at Discord that it works. 

İk that it's not best selector, @sionking, that was a quick solution cos İ'm busy with my other PR. 

When you find a better selector, you'd share it. 

İ'll merge it now. 

---

Cheers 😀
---

**Comment by mgconejero** [comment]
It works! You are the best @uluQulu

**Comment by Kazansky** [comment]
i still have that problem only if i try to follow user followers. when i change user of my interesting it works. why?

**Pull request merged**
