### PR TITLE
Full docker-compose and complex template + documentation

### PR DESCRIPTION
**Pull request by gdurandvadas**
## Changes
- Add support to `yaml` configuration files
- Added **z_*** to .gitignore, to avoid users's configs to be published.

## quickstart_template
This config is meant to run with docker-compose inside a folder call **z_{user}** (Added to gitignore)
Folder content:
  - data.yaml
  - docker-compose.yaml
  - start.py

Comments are generated on every run, the scrip will generate 5 comments of a random number and selection of emojis in characters list.

### Setup
**Docker Compose**
- Will wait for Selenium to be ready, then execute `start.py`
- Uses local files `logs`, `data.yaml` configuration file and `start.py` script.
```yaml
version: '3'
services:
  web:
    command: ["./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "start.py"]
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: ../
      dockerfile: docker_conf/python/Dockerfile
    depends_on:
      - selenium
    volumes:
      - ./start.py:/code/start.py
      - ./data.yaml:/code/data.yaml
      - ./logs:/code/logs
  selenium:
    image: selenium/standalone-chrome
    shm_size: 128M
```

**Configuration file**
Is a `yaml` file with the following required variables
```yaml
username: string
password: string
friends_interaction: boolean
do_comments: boolean
do_follow: boolean
user_interact: boolean
do_unfollow: boolean
friendlist: [list]
hashtags: [list]
```
- username: Instagram Username
- password: Instagram Password
- friends_interaction: If `True` will like last two post from friendlist, if not, it won't even create _friends_ session
- do_comments: If `True` will enable comments in like_by_tags interaction
- do_follow: If `True` will enable follow users in like_by_tags interaction
- user_interact: If `True` will enable interact with user's posts in like_by_tags interaction
- do_unfollow: If `True` will enable unfollow execution

### How to run
Inside **z_{user}** directory:
- run in background:
`docker-compose down && docker-compose up -d --build`
- run with log in terminal:
`docker-compose down && docker-compose up -d --build && docker-compose logs -f`

### CODE REVIEW

**Comment by timgrossmann** [comment]
@gdurandvadas This is great, could you add a file to the docs folder on how to use it (just copy the stuff you wrote in this PR) and link it in the README file where we mention Docker, please?

**Comment by gdurandvadas** [comment]
@timgrossmann done 🙌

**Comment by timgrossmann** [comment]
@gdurandvadas Nice one! Now we only have to take a closer look and test it.
Once that is done we can merge this 🙌

Thank you very much for adjusting the PR

**Comment by timgrossmann** [comment]
@gdurandvadas Just checked it, seems to be working fine.
Thank you very much and congrats to your first PR in InstaPy! 🙌 

Looking forward to your next one 😉

**Comment by timgrossmann** [comment]
@gdurandvadas  Are you part of the discord channel? 
@scriptworld-git would like to ask you some questions in regards to the docker files in the repository since we want to completely extract the docker part out to this repository: https://github.com/InstaPy/instapy-docker

Thank you

**Comment by viktaur** [comment]
Where can I find this folder with the content inside??

**Pull request merged**
