### PR TITLE
Text feature

### PR DESCRIPTION
**Pull request by gitpatrickhub**
@timgrossmann created a short python script using Twilio to send me a text message when InstaPy has successfully completed. The idea is that users don't want to constantly check to see if InstaPy is running. This first feature simply handles when InstaPy completes successfully, the next step would be to incorporate the text messages for when it crashes. I'm not an expert in Python, so there is quite possibly a more elegant way to code this, but this method is working for me on my rpi3 right
 now. 

```commit textFeature 195699a - adds the code to instapy.py```
```commit textFeature d1a66a7 - adds the text_user.py file ```

### CODE REVIEW

**Comment by timgrossmann** [comment]
@gitpatrickhub This actually is a really nice idea.
Would you be interested in developing this feature further?

I unfortunately can't merge it as it is right now, but I could write up a little Requirements-Issue on how this could be implemented (the interface). 
Would love to have this feature in InstaPy for both success and crashes.

Of course this should be simple to setup in your quickstart.py.

**Comment by gitpatrickhub** [comment]
@timgrossmann, yes I'd like to implement this code in the most efficient manner, but will need some direction on what that looks like. My background is as a product owner, I only attempt to code on the side. If you or someone else can give me a bit of guidance, I will knock it out.

**Comment by gitpatrickhub** [comment]
@timgrossmann I'm looking at different ways to implement this feature more efficiently and to fit it into the current interface. I don't see that there is any current error logging to leverage, so my first thought was to use logging.handlers.StreamHandler for debug_level = Critical and pass the error into the sms message. But I'm not sure if Critical causes the application to stop or if this would catch all errors that stop the application. Let me know if you have any ideas.

**Comment by timgrossmann** [comment]
@gitpatrickhub I'm sorry I couldn't get to this yet. 
I will try to get to this tomorrow

**Comment by timgrossmann** [comment]
@gitpatrickhub I'm really sorry but I couldn't find time for this by now...
I'll try to find some time soon

You could open up a feature issue to discuss this feature with the other users so we can see how many people would be interested in something like this

**Comment by converge** [comment]
It would be nice to send the message using Telegram

**Comment by gitpatrickhub** [comment]
@timgrossmann and @converge I finally had a chance to look at this again and guessing this isn't the best approach, but is working for both success of the bot and failures.

new file text_user.py

````

from twilio.rest import Client


def text_msg(enabled=False, body=None): 

  account_sid = "account sid from twilio"
  auth_token = "token"
  client = Client(account_sid, auth_token)
 
  message = client.api.account.messages.create(to="+55555555555",
                                             from_="+15555555555",
                                             body=body)
 
 
  print (message.sid)
````

quickstart.py changes

````
from instapy import InstaPy
from instapy import text_user

insta_username = 'account name'
insta_password = 'password'

try:


    session = InstaPy(username=insta_username, password=insta_password, use_firefox=True, page_delay=25)
    session.login()


    session.set_upper_follower_count(limit=3500)


    session.set_dont_include(['user1', 'user2', 'user3'])
    session.set_dont_like(['sex', 'nsfw', 'gun', 'knife'])


    session.set_user_interact(amount=3, random=False, percentage=100)
    session.set_do_follow(enabled=False, percentage=70)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments([u':clapping_hands: :clapping_hands:', u':thumbs_up:', 'Sweet!'], media='Photo')
    session.set_comments(['Sweet vid!', 'Nice edit!'], media='Video')
    session.set_do_comment(True, percentage=33)
    session.interact_user_followers(['account to follow'], amount=5, random=True)



    session.end()
    

    text_user.text_msg(enabled=True, body="InstaPy completed successfully")


except Exception as err:
    print('Error running InstaPy: {}'.format(err))
    text_user.text_msg(enabled=True, body="InstaPy crahsed")
````

**Comment by converge** [comment]
@gitpatrickhub that's really cool, good work!!

**Comment by converge** [comment]
@gitpatrickhub take a look #880

**Comment by timgrossmann** [comment]
#880

**Pull request closed without merging**
