### PR TITLE
Problem: Added Two Factor Authentication feature, intended for protected

### LINKED ISSUE #2118: [request] Two-step authentication
Hey guys, so I'm thinking that it would be a great security improvement to allow us using two-step autentication with InstaPy. As of today, if you have this option on, instapy fails. However, since instagram gives us a few security codes, wouldn't it be possible to feed instapy those codes so that it could work having this feature enabled?

Thanks! :)

### PR DESCRIPTION
**Pull request by elulcao**
Hello all,
Hope you doing well,

Added Two Factor Authentication feature, intended for protected
accts. If the acct is not protected this feature will be ignored and will
be unnoticed. This feature basically should be used to bypass the 
extra security configuration used by the InstaPy user.

- comment_util.py: replaced unused variables in process_comments()
- instapy.py: added `security_codes` arg in constructor and `login_user()`
            `process_comments()` now uses `user_name` for commenting a
            target user; #5932
            `comment_by_locations()` now has the same code for `process_comments()`
- login_util.py: Added random import due to login_user() feature with Two Factor
               Authentication. `security_codes`, must be a list with codes
               and InstaPy will chose only one element randomly.
               Added new `def two_factor_authentication()`
- xpath_compile.py: Updated `get_comments_on_post` xpath with a generic form
- Added `pull_request_template.md`: to have a new format in the PR.
- instance-settings.md updated with steps for Two Factor Authentication
- Updated CHANGELOG with commit changes

### CODE REVIEW

**Review by timgrossmann — APPROVED** [review]
Looks really good again!
Also. love the clear explanations on the PRs.

Thank you very much for this update 😍

**Comment by breuerfelix** [comment]
i just got one question to this:  
isn't the instagram two factor auth just like google auth ? when you login you have to look on your smartphone and get a time based token you have 30 seconds time to enter ?  
if yes, then isnt it impossible to know these beforehand ?

i could be totally wrong since i never used two factor auth at instagram but i am just curious :D  
cause if it is like that, it would be better to prompt the user for the code and not make him provide it via constructor :)

**Comment by timgrossmann** [comment]
> i just got one question to this:
> isn't the instagram two factor auth just like google auth ? when you login you have to look on your smartphone and get a time based token you have 30 seconds time to enter ?
> if yes, then isnt it impossible to know these beforehand ?
> 
> i could be totally wrong since i never used two factor auth at instagram but i am just curious :D
> cause if it is like that, it would be better to prompt the user for the code and not make him provide it via constructor :)

Looks like one can use the recovery codes to have a fixed value for this: 
Security codes can be found in: `Settings` -> `Security` -> `Two-Factor-Authentication` -> `Backup Codes`

**Comment by breuerfelix** [comment]
> > i just got one question to this:
> > isn't the instagram two factor auth just like google auth ? when you login you have to look on your smartphone and get a time based token you have 30 seconds time to enter ?
> > if yes, then isnt it impossible to know these beforehand ?
> > i could be totally wrong since i never used two factor auth at instagram but i am just curious :D
> > cause if it is like that, it would be better to prompt the user for the code and not make him provide it via constructor :)
> 
> Looks like one can use the recovery codes to have a fixed value for this:
> Security codes can be found in: `Settings` -> `Security` -> `Two-Factor-Authentication` -> `Backup Codes`

awesome! thanks for the clarification :) let's merge it!

**Pull request merged**
