### PR TITLE
FIX: updated xpath in unfollow util

### PR DESCRIPTION
**Pull request by torbenberger**
IG changed location of follow buttons
Issue: Following problem ? #2461

### CODE REVIEW

**Comment by timgrossmann** [comment]
@torbenberger Thank you very much for this fix.

Could you do some tests with only using `//button[text()='Follow']` and `//button[text() = 'Following']`, please? 
This actually should lead to the same result without always having to be changed when the path to those elements is affected.
Maybe you have to see if it takes significantly longer than the current implementation.

Thank you
Best
Tim

**Comment by torbenberger** [comment]
@timgrossmann i gave your suggestion a try, it works and doesn't seem to have any negative impact on speed.

**Comment by furiont** [comment]
image
got errors....

**Comment by torbenberger** [comment]
@furiont i don't get these errors. Your screen is hard to read. Did you actually pull my changes or just applied them by yourself? I'am not quite sure but the single quotation marks in your screen look a bit strange..

**Comment by DavidMolinari** [comment]
Unfollowing is working great with these changes

**Comment by dds14** [comment]
@torbenberger @timgrossmann thank you for the proposed solutions! I've added the edits as follows:

 
        buttons = dialog.find_elements_by_xpath(
            "//button[text()='Follow']")

    elif channel == "Unfollow":
        buttons = dialog.find_elements_by_xpath(
            "//button[text() = 'Following']")  

    abort = False
    person_list = []
    total_list = len(buttons)
    simulated_list = []
    simulator_counter = 0

    # scroll down if the generated list of user to follow is not enough to
    # follow amount set
    while (total_list < amount) and not abort:
        before_scroll = total_list
        for i in range(3):
            scroll_bottom(browser, dialog, 2)
            sc_rolled += 1
            simulator_counter += 1

        if channel == "Follow":
            buttons = dialog.find_elements_by_xpath(
                "//button[text()='Follow']")              

        elif channel == "Unfollow":
            buttons = dialog.find_elements_by_xpath(
                "//button[text() = 'Following']")  


However, I am still getting this:

`('Scrolling down... ', 0, '->', 0, ' / ', 20)
Like window closed
('\nGot ', 0, ' likers shuffled randomly, who you can follow:\n', [], '\n')`

Any ideas of what I am doing wrong?

**Comment by sionking** [comment]
What is the status ?

**Comment by swznd** [comment]
@dds14 you can check this https://github.com/timgrossmann/InstaPy/pull/2476

**Comment by dds14** [comment]
@swznd worked like a charm!

**Review by andreyrozumnyi — APPROVED** [review]

**Comment by jeremiealvin** [comment]
Thank you for solutions @torbenberger @timgrossmann ! :D 
It works perfectly now to follow people but I'm still blocked to unfollow all user not in my whitelist: I've got an error message : 

> Sorry, an error occured: 'bool' object is not subscriptable

Reference to this issue #2475

**Comment by cesarcm96** [comment]
Same here, @alvinje
All running right except the unfollow function, i am getting the same error. 
Bool object is not subscriptable

**Comment by torbenberger** [comment]
thats strange, unfollowing is working for me without any problems

**Comment by jeremiealvin** [comment]
@torbenberger  @cesarcm96  I just pull the master branch and it works fine for me now :)

**Comment by unipython** [comment]
Just synced the fork and it was working fine until I tried implementing headless browser, one hour later the fix stopped working.

Error: Got 0 likers shuffled randomly whom you can follow

Any ideas?

**Pull request merged**
