### PR TITLE
Feature: Remove outgoing unapproved follow requests from private accounts

### PR DESCRIPTION
**Pull request by dar2015**

### CODE REVIEW

**Comment by sionking** [comment]
great tool!

**Comment by sionking** [comment]
I will test whenever

**Comment by timgrossmann** [comment]
@dar2015 Thank you very much for this interesting feature.

Looking through your code it seems that the code is not completely PEP8 formatted. Please reference #3637 for the right formatting.

Please also try to add an entry to the CHANGELOG file stating your additions

**Comment by w4ngel** [comment]
> @dar2015 Thank you very much for this interesting feature.
> 
> Looking through your code it seems that the code is not completely PEP8 formatted. Please reference #3637 for the right formatting.
> 
> Please also try to add an entry to the CHANGELOG file stating your additions

If you merge this I can add the PEP8 changes.

**Comment by timgrossmann** [comment]
@w4ngel Thank you. Have you reviewed the code?
@dar2015 Where is that hard coded number of 750 coming from?
Just seems a bit extensive considering that it will press the load more button up to 750 times.

```python
while len(list_of_users) < amount and view_more_clicks < 750 and view_more_button_exist:
```

Edit: Just checked out the page, 750 looks like a value that simply represents infinity here.

**Comment by w4ngel** [comment]
> @w4ngel Thank you. Have you reviewed the code?

I have not managed to just yet.

**Review by w4ngel — APPROVED** [review]
Reviewed. Looks good.

**Comment by timgrossmann** [comment]
@w4ngel Thank you very much, if you can find some time, PEP8 adjustments would be great 😊

**Comment by RachelDuffin** [comment]
Is there an unfollow_after option for removing follow requests?

**Comment by dar2015** [comment]
> 
> 
> Is there an unfollow_after option for removing follow requests?

It's part of standard unfollow process

**Pull request merged**
