### PR TITLE
Reorganizing documentation

### PR DESCRIPTION
**Pull request by Herrox**
This PR is about reorganizing documentation:
- Adding TOC (Table of Contents) to README.md to be easiest to navigate between sections
- Adding GUI section to README.md (@breuerfelix I think `GUI` should be rename to `WebUI` or to `Web Interface` to be clearer for end users because I'm not sure everyone out there know what a GUI means 😄 ) to let people know about the project
- Moving Docker section from DOCUMENTATION.md to README.md because it was not easy to find for new users

### CODE REVIEW

**Comment by breuerfelix** [comment]
am I blind or did you forget to add docker section to the readme.me ? :D you just removed it from the documentation.md :D

also, thanks for this amazing gui entry ! I like it :) 

and about the toc, I think its cool but I also think its not needed 100% since the readme is kinda short, but I am also okay with it being in there :D

**Comment by Herrox** [comment]
I just double check and it is at line 126 and 127 in `README.md` 😄

**Comment by breuerfelix** [comment]
ahh well you didnt put it there in this PR right ? since I can't see it in the changes you made in this pr :D

**Comment by Herrox** [comment]
Yes, I did it in this PR https://github.com/timgrossmann/InstaPy/pull/4476/files#diff-04c6e90faac2675aa89e2176d2eec7d8

Maybe I'm wrong but at line 126 and 127 there is the section 😄

**Comment by breuerfelix** [comment]
I am fucking blind or is GitHub kidding me ??

http://prntscr.com/nt9wo0

I can't see any diff on these lines :D

**Comment by Herrox** [comment]
I did 3 commits to this PR. If you look at commit Files > README.md you should see it.
It's just under your GUI section mate !

image

**Comment by breuerfelix** [comment]
wooooow I was so damn blind ! now I also see it ... sorry mate :D ahahaha crazy :D I should get some rest for today ... :D:D

**Review by breuerfelix — APPROVED** [review]
just not sure about the table of contents :) but thats not my decision!

**Comment by Herrox** [comment]
No worries! Take some rest and get back fully reloaded 😄 
Alright about TOC, I just thought it was a good way to rapidely and easily check what the README.md's contents and navigate more easily. It's just a bit more 'pro' in my opinion

**Comment by timgrossmann** [comment]
@Herrox Thank you very much for the documentation update!
I switched the links to the parts back to actually being markdown links where possible. (instead of a tags)

Wasn't sure about the table of content, but I think I like it.

**Pull request merged**
