### PR TITLE
Add unfollow if not follow me feature

### PR DESCRIPTION
**Pull request by CharlesCCC**

### CODE REVIEW

**Comment by timgrossmann** [comment]
@CharlesCCC Great feature to work on!

Just make sure you have to newest version of InstaPy, it looks like you have to do a git pull on your side to make sure you're up to date. The merge conflicts will disappear then.

**Comment by timgrossmann** [comment]
@CharlesCCC Any updates on this one?

**Comment by CharlesCCC** [comment]
@timgrossmann I resolved the conflicts locally, but unfortunately this change is made by @pleum , he will need to merge it in and push the change.

**Comment by pleum** [comment]
Sorry, i'm very busy last week and still learn to use git. 😄

**Comment by timgrossmann** [comment]
@pleum the diff looks pretty weird, we can't review it that way...

Yes git can be pretty weird :smile: 

Also, it might make sense to extract the main "logic" of this feature into the `unfollow_util.py` where all the following/unfollowing logic is located

Thank you very much!

**Comment by pleum** [comment]
@timgrossmann 😢 Ah, should i create new branch ? if i still working on this branch and this weird commit will merge PR or only new commit ? So i still can continue with this branch and just reset to master ?

**Comment by timgrossmann** [comment]
@pleum I'm not sure what happened here, maybe it's best to close this PR and start a new one with a cleaner commit history.
Or if you want to, you can continue working on this PR and we'll fix the problems later once you implemented everything.

It;s just way easier to review and more likely to merge it soon if it's cleaner

**Comment by pleum** [comment]
I already move logic to `unfollow_util.py`  @timgrossmann can you help me test it 😃

**Comment by timgrossmann** [comment]
@pleum Looks way better!
I'll test it this evening.

Thank you very much for the hard work.
Could you also add some documentation for the ReadMe? Would be great to have a few lines describing what this feature does and how to use it (code example).

**Comment by timgrossmann** [comment]
@converge Could you also test this?
Looks like it's working, but I can only test on Mac...

@pleum Looks like it's working great!

Would you be interested in helping improve some of the other features (and the whole unfollow feature) to using graphQL? It's probably way more consistent than relying on the page structure!

Thank you for this!

**Comment by converge** [comment]
I'll test it for sure, I'll try to do it tonight.

**Comment by pleum** [comment]
@timgrossmann Interested, but i'm still working on other project So i'm very busy this month 😢

**Comment by AustineA** [comment]
@pleum hi buddy how can i start using this right away? I've been waiting forever 😀  for this to get merged.

**Comment by converge** [comment]
hey @CharlesCCC I just tested it, great work! I just made some code improvements and wanna commit it to your branch, can you give me access to it ?

**Comment by CharlesCCC** [comment]
@converge credit all goes to @pleum and he should able to give you access as well.

**Comment by converge** [comment]
@CharlesCCC thanks. @pleum the changes are here[1] if you wanna check it before give me access to commit.

[1] https://github.com/converge/InstaPy/commit/2b7f76f300c72c827ae1f932909a6d12f5d4bc3a

**Comment by pleum** [comment]
@converge How to give you access ? `Settings > Collaborators` right ?

**Comment by converge** [comment]
@pleum that's right.

**Comment by converge** [comment]
@pleum if you think it's everything ok, we can merge it now. What do you think @timgrossmann ?

**Comment by timgrossmann** [comment]
@pleum @converge This is awesome work!

I'd love to merge it, but I unfortunately can't see your improvements, @converge, in the current commit.

@pleum  Did you merge and update the PR?

Once it's updated, let's merge this and get this great feature out to the people!
You guys rock! 👍

**Comment by pleum** [comment]
i merged to master, So should we close this and create new PR ?

**Comment by converge** [comment]
@pleum I think you should merge it to your unfollow_feature branch, and it will update this PR by it self.

**Comment by converge** [comment]
@pleum maybe create a new PR based on your master(merged) would be the easier way for now.

**Comment by timgrossmann** [comment]
@pleum @converge Thank you very much guys!
Just tested it again and it looks like it's working fine. 

I'll merge this now, this is awesome!
Thanks

@pleum Feel free to grab the bounty on this now: https://www.bountysource.com/issues/49761251-feature-only-unfollow-users-who-don-t-follow-me

**Pull request merged**
