### PR TITLE
Catch exceptions for unfollow_user inside loop

### PR DESCRIPTION
**Pull request by mariusglauer**
Prevents crashing when unfollowing fails for a certain user

Should provide a workaround for
#3602
#3523

### CODE REVIEW

**Comment by timgrossmann** [comment]
@gbhrdt Good one.
Thank you very much and congrats to your first PR to InstaPy 🙌

**Comment by sionking** [comment]
Is it just me ? if exception occuer the `unfollow_state, msg`  will not be internalized and another exception will be.

**Comment by timgrossmann** [comment]
@sionking Sorry, could you elaborate a bit more, please?

**Comment by sionking** [comment]
@timgrossmann  We are using `unfollow_state` after we catch the exception, but if we have exception this var is not exist ...

**Comment by timgrossmann** [comment]
@sionking Now I understand, meaning this PR will lead to another error once an exception is encountered

**Pull request merged**
