### PR TITLE
change login xpath

### PR DESCRIPTION
**Pull request by moharami**

### CODE REVIEW

**Comment by timgrossmann** [comment]
@moharami @CharlesCCC @orhan-drsn 
Maybe it makes sense to remove the first checks and go with the #4218 right away and only do more checks if that fails.
It seems to work pretty well

**Comment by CharlesCCC** [comment]
@timgrossmann I believe this change actually is for verify if the user logged in or not. Which not need to click/Enter as #4218 did.

**Comment by timgrossmann** [comment]
@CharlesCCC just looked at the code again.
True, this is only to find the Login element before actually logging in.

We at least need to check for both cases like we tried to do before we merged #4218 because some users seem to have "Log in" and the others have "Log In"

**Comment by CharlesCCC** [comment]
@timgrossmann Agreed, probably can pull all the case that I previously gathered before we switch with the Enter-press.

**Comment by timgrossmann** [comment]
@moharami Any chance you can update the script to include the other checks @CharlesCCC proposed at #4218 ? 😊

**Comment by analyticsdept** [comment]
@timgrossmann not sure if this comment will be helpful or not, but would it be easier just adding this change to the xpath file? That'll save @moharami the time making other script changes.

I also noticed this xpath is a button and the older version is an anchor - browser.py treats a list from the xpaths as *args so it can be added safely without breaking login a/b tests :)

**Comment by timgrossmann** [comment]
@analyticsdept Absolutely helpful! If we can just have a list of all possible Login buttons/links/spans/divs inside the newly introduced xPath file, this will be much cleaner :+1:

**Comment by HCWcoder** [comment]
Im still getting login issue

**Comment by analyticsdept** [comment]
> Im still getting login issue

@HCWcoder would you be able to check and post the xpath of your login button?

**Comment by HCWcoder** [comment]
> > Im still getting login issue
> 
> @HCWcoder would you be able to check and post the xpath of your login button?

```
Traceback (most recent call last):
  File "follow_quickstart.py", line 159, in <module>
    follow()
  File "follow_quickstart.py", line 78, in follow
    with smart_run(session):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\contextlib.p
y", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\user\Documents\GitHubs\InstaPy\instapy\util.py", line 1680, in
smart_run
    session.login()
  File "C:\Users\user\Documents\GitHubs\InstaPy\instapy\instapy.py", line 381, i
n login
    self.bypass_with_mobile):
  File "C:\Users\user\Documents\GitHubs\InstaPy\instapy\login_util.py", line 262
, in login_user
    "//button//div[text()='Log in']")
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-package
s\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-package
s\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-package
s\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-package
s\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una
ble to locate element: {"method":"xpath","selector":"//button//div[text()='Log i
n']"}
  (Session info: headless chrome=73.0.3683.103)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361
e1),platform=Windows NT 6.1.7601 SP1 x86_64)
```

`//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[4]/button/div`
image

**Comment by diegocarluc26** [comment]
It is probably me not being enough experienced but I'm having issues fixing this. I'm not quite sure what should I change it the login_util.py file. 

Can anyone quickly guide me through this? :)

**Comment by timgrossmann** [comment]
@diegocarluc26 @HCWcoder Is this issue still occurring?

**Comment by timgrossmann** [comment]
Please reopen if this error is still persistent 😊

**Comment by Marzocchi666** [comment]
Hi, im having this issue again.. i've done this and that in the login_util.py but no success, is there anyone who is having the issue? ty.

**Comment by analyticsdept** [comment]
@Marzocchi666 I'm not, so could you share your xpath and Instapy version please?

**Comment by Marzocchi666** [comment]
instapy==0.5.7, xpath['bypass_suspicious_login'] = {
    "bypass_with_mobile_choice":"//label[@for='choice_0']",
    "bypass_with_mobile_button":"//label[@for='choice_0']",
    "choice":"//label[@for='choice_1']",
    "choice_no_such_element":"//label[@class='_q0nt5']",
    "choice_exception":"//label[@class='_q0nt5 _a7z3k']",
    "close_button":"[text()='Close']",
    "security_code_field":"//input[@id='security_code']",
    "send_security_code_button":"//button[text()='Send Security Code']",
    "submit_security_code_button":"//button[text()='Submit']",
    "this_was_me_button":"//button[@name='choice'][text()='This Was Me']",
    "wrong_login":"//p[text()='Please check the code we sent you and try again.']"
}

**Comment by analyticsdept** [comment]
@Marzocchi666 thanks! Sorry though, I wasn't clear about what I was asking for... Are you able to run it in a browser window and when the flow breaks capture the xpath of the button/s you're supposed to be pressing? That'll help with comparing what's implemented with whatever's breaking it.

**Comment by Marzocchi666** [comment]
hm, i never done that, im running the script from linux terminal, but i will try as you say. Thanks for assist. Will come back later with a reply.

**Pull request closed without merging**
