### PR TITLE
Use clarifai to check whether profile is male or female

### PR DESCRIPTION
**Pull request by Tidle999**
Hey Guys,

i am using the instapy for a few days now and i love it and its features. especially the image recognition feature with clarifai is an awesome feature.
and i thought it should be able to use clarifai to analyse the profile picture to follow only male or females or specific (cars, animals, nature) instagram accounts or also analysing the last five post and depending on the results following the acocunt, if its a fashion, nature or whatever account.
this should be a great result to limit the potential targeting audience.

what do you think?

regards

tom

### CODE REVIEW

**Comment by sionking** [comment]
I use this, this way for long time.
BTW see my PR it add the option to give url_image instead of current post.
We need to check we are not bumping

**Comment by Tidle999** [comment]
Hello and thank you for your answer. i have seen your PR 2051 but i dont see how to use it, can you give an example please on how to use it for profile pictures?

**Comment by sionking** [comment]
You need to just send the profile url to the clarifi with atr picture_url=url

**Comment by Baniyal** [comment]
Thankyou! But m kinda new to python. Could you elaborate on it?

**Comment by Baniyal** [comment]
Thankyou for replying back

**Comment by sionking** [comment]
So I am not sure, it this PR should be a question or implemented code ?

**Comment by sionking** [comment]
This is not a PR, it is a Feature request please open under issues.

**Pull request closed without merging**
