### PR TITLE
Optional ignore check image; optional use profile path for chrome; …

### PR DESCRIPTION
**Pull request by sionking**
List of new/small improvements:
- Remove infobars from chrome.
- Mute sound in chrome.
- Optional ignore check image from Clarifi:
   e.g. If we want t to **ignore** **dogs** but not if a **person** is also in the picture.
- Optional provide image url for image check Clarifi (e.g. profile picture).
- Optional use profile path for chrome and not only for Firefox.
- log following of profile

I run one test but please check it as it is not my main repo.

### CODE REVIEW

**Comment by CharlesCCC** [comment]
username/password, instapy.db are not needed :)

**Comment by CharlesCCC** [comment]
if is optional, please make sure add the proper instruction to the wiki page

**Comment by sionking** [comment]
Hate this PR always exposing my password lol

**Comment by timgrossmann** [comment]
@sionking Will we get those features without your credentials again?

**Pull request closed without merging**
