### PR TITLE
Dismiss Turn-On popup

### PR DESCRIPTION
**Pull request by oke11o**
After login user see popup Turn On.
If InstaPy can find it, it dismiss it.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@oke11o Thank you very much for this addition.
Really nice usage of the, by @uluQulu introduced, explicit wait and the clicking wrapper.

Code looks good, I'll try to test it later today or tomorrow.
Let's also wait for a second person to approve this.

Thank you
And congrats to your first PR to InstaPy!

**Comment by uluQulu** [comment]
@timgrossmann @oke11o 
I remember I have shared that solution in https://github.com/timgrossmann/InstaPy/issues/2929#issuecomment-424256117 for people to apply it manually.
Well, I also included that change for the **login_util.py** in my unreleased version.
And I did it like this:
login solution


How different it is than this PR?
+ `dismiss_notification_offer` is a separate function rather than part of `dismiss_get_app_offer` cos they both have the same status and can't be part of one another.
In future they can be refactored into some `dismiss_offer(offer_type=[])` function wisely.

+    `dismiss_notification_offer` is being called in both cookie loaded sesion and in a fresh login (no cookie)
```python
    if len(login_elem) == 0:
        dismiss_notification_offer(browser, logger)   # THIS LINE will dismiss that offer in COOKIE LOADED LOGIN session
        return True
```
```python
    dismiss_get_app_offer(browser, logger)
    dismiss_notification_offer(browser, logger)   # THIS LINE will dismiss that offer in NO COOKIE EXISTENT FRESH LOGIN session
```
Result is zero leak.

That set of code in my new revision includes mainly refactor & redisgn in action verification definitions to fulfill simpler and easily maintainable source code and custom action delays.
It has been ready for a long time but I have no time to clear it up and share with the community yet.   
Soon will have free time, hopefully.

------

Cheers 😁
-----

**Comment by timgrossmann** [comment]
@uluQulu Awesome to hear and see that.
Your solution looks a little bit more sophisticated so hopefully we can incorporate that.

Maybe @oke11o is able to add it like you proposed in the mentioned issue.

Thank you

**Comment by oke11o** [comment]
I extract functional to separate method. As suggested by @uluQulu 
It is work.

**Comment by timgrossmann** [comment]
@oke11o Looks good, thank you for the update.
@uluQulu Thanks for the improvement 😉

**Comment by ghost** [comment]
This actually doesn't work for me - not sure if something changed in the last 6 days on instagram.

**Pull request merged**
