### PR TITLE
issue with getting following users (#807)

### PR DESCRIPTION
**Pull request by XemyL**
Fixed issue with getting following users

### CODE REVIEW

**Comment by converge** [comment]
hey @XemyL , I'm testing your PR. Pls, correct me if I'm wrong.

today:
```interact_user_following```
calls:
```get_given_user_following```
then
- browse to some profile defined in interact_user_following(['profile_name'], ...)
- click at Following button
- collect a list of profiles/usernames using ```//div/div/span/button[text()='Follow']```, that means: collect profiles/usernames with "Follow" link active
--
Your PR says to collect profiles/usernames with "Following" link active, in other words it says to unfollow who I'm already following.

**Comment by XemyL** [comment]
Hi
thanks @converge, I understand that
what about case of profiles you following? add one more xpath or there is another method?

**Comment by converge** [comment]
@XemyL I didn't got it, can you explain a little longer ?

**Comment by XemyL** [comment]
@converge what will be the result of interact_user_following() with username that equal to username I logged?

**Comment by timgrossmann** [comment]
@XemyL Any updates on this, yet?

**Comment by timgrossmann** [comment]
@XemyL Is this still a thing?
There have been many updates, we might close this one... What do you think @converge ?

**Comment by converge** [comment]
@timgrossmann I think so, I'm closing it. @XemyL if you have some update about it, please reopen the PR ou create a new one. If you want to talk a little more about this idea, we're at our Slack channel.

**Pull request closed without merging**
