### PR TITLE
Update logging system

### PR DESCRIPTION
**Pull request by converge**
removes all print statements and uses Logging python module to handle logging informations

### CODE REVIEW

**Comment by converge** [comment]
output example: (tail -f general.log)
```
INFO - Session started - 2017-11-17 00:05:09
INFO - Logged in successfully!
INFO - --> Ongoing follow 1, now following: b'ciclismo_and_beers'
INFO - --> Ongoing follow 2, now following: b'molinger7'
INFO - --> Ongoing follow 3, now following: b'memochucho'
INFO - --> Ongoing follow 4, now following: b'ptypaldo'
INFO - --> Total followNum reached: 4
INFO - --> Total people followed : 4
INFO - --> User followed: ['ciclismo_and_beers', 'molinger7', 'memochucho', 'ptypaldo']
INFO - Username [1/2]
INFO - --> b'memochucho'
INFO - Getting memochucho image list...
INFO - Interaction begin...
INFO - --> Already following
INFO - Post [1/5]
INFO - https://www.instagram.com/p/BZzCd1nFmLv/?taken-by=memochucho
INFO - Image from: b'memochucho'
INFO - Link: b'https://www.instagram.com/p/BZzCd1nFmLv/?taken-by=memochucho'
INFO - Description: b'La favorita -\n-\n-\n-\n-\n-\n-\n-\n#cinelli #mashsf #parallax #trackbike #bikeporn #fixedgear #brakeless #mexicocity'
INFO - --> Image Liked!
INFO - --> Not commented
INFO - Post [2/5]
```

What do you guys think about the file name ? general.log ? Is there a better name ?

**Comment by timgrossmann** [comment]
@converge Awesome! Thank you very much!
I'm not sure if we should remove the default console printing though...

Maybe we could also log out to the console.

**Comment by converge** [comment]
@timgrossmann nice idea, just did it.

**Comment by timgrossmann** [comment]
@converge Awesome! Looks great!
Thank you very much.

**Pull request merged**
