### PR TITLE
improve selenium settings

### PR DESCRIPTION
**Pull request by phongtt3**
i've make a small change to improve selenium running more fast & smooth:
- managed_default_content_settings.images = 2: Disable images load, this setting can improve pageload & save bandwidth
- default_content_setting_values.notifications = 2: Disable notifications
- credentials_enable_service & password_manager_enabled = false: Ignore save password prompt from chrome

### CODE REVIEW

**Comment by timgrossmann** [comment]
@phongtt3 Sounds really interesting, thank you for this!

**Comment by timgrossmann** [comment]
@phongtt3 Would you also be interested to look into the new chrome headless feature and check if that could be implemented as easy as this as well?
Thank you for your contribution!

**Comment by phongtt3** [comment]
Yes, i already use chrome headless feature, but my account is banned immediately :D, i think they (facebook - who behind instagram) can detect headless signal from browser.

**Comment by timgrossmann** [comment]
@italianrobot Would be interesting to know!
Could you submit a new PR which includes this to make people see and test it?

Thank you

**Pull request merged**
