### PR TITLE
flake8 code style, deleted some unused variables/imports, avoid crash…

### PR DESCRIPTION
**Pull request by converge**
flake8 code style, deleted some unused variables/imports, avoid crash when unfollowing if profile have 0 following

### CODE REVIEW

**Comment by timgrossmann** [comment]
@converge Thank you very much for your contributions!

This has a lot of changes, would be nice if someone (in addition to myself) could test this and make sure that everything still works.

**Comment by timgrossmann** [comment]
@converge Can we close this PR since the other 2 got merged?

**Comment by converge** [comment]
@timgrossmann I think its a good idea merge it because it fix the problem when trying to unfollow and the profile has 0 following

**Comment by timgrossmann** [comment]
@converge Could you please resolve the merge conflict before?

Thank you!

**Comment by converge** [comment]
@timgrossmann done

**Pull request merged**
