### PR TITLE
Fix issue that can't get the possible_posts amount

### PR DESCRIPTION
**Pull request by CharlesCCC**
Fix issue that can't get the possible_posts amount due to the css class changed to `g47SY`

### CODE REVIEW

**Comment by timgrossmann** [comment]
@CharlesCCC is this global? Or is it some incremental A/B-Testing change?

@uluQulu Could you double check that. Looks like it's the same change on my side.

**Comment by uluQulu** [comment]
Hi guys
This problem stuck my mind. xD
Cos in the issue raised by @CharlesCCC in #2129 which lead to this PR, the error log shows:
skippingtag
But it is impossible, cos if it failed to get useful `possible_posts` count, it should still work without a problem and not show that error: `Too few images, skipping this tag`.
_Then, also wondered why it couldn't get that `possible_posts` count within **graphql** element..._

And yes it happened cos the files used in that setup is missing the commits came with #2042 
possibleposts

And since those changes are not existing, in case of `NoSuchElementException` raised while getting `possible_posts` count will be caught only by the outer except block in `InstaPy` class rather than the inner except block in the `get_links_for_tag` definition and will not be handled correctly.

That is not a problem if @CharlesCCC pulls those commits, it just did stuck my mind to see the `NoSuchElementException` caught by the outer except block in `InstaPy` class xD
error


And yes @timgrossmann, it is the same change in my side, too. And moreover, I checked, it has affected the **followers**/**following** counts elements, too, and there are 2 of them in **unfollow_util.py** and another 2 in **util.py** (_counts the changes with my latest PR_) which must all be renamed from `_fd86t` to `g47SY`.

Thanks to @CharlesCCC for super-quick catch 👍

**Comment by CharlesCCC** [comment]
@uluQulu you are correct, my locally didn't have the later version (my bad). 
but the change should still valid. (of course, there are additional place need be changed as you pointed out).

Thank you for the code review and hopefully this is not a A/B test

**Comment by bardascat** [comment]
why is this not merged yet ? Thanks !

**Comment by sionking** [comment]
this is Y I am more of graphql fan

**Comment by sionking** [comment]
i CHECKED BOTH CHANGES AND THEY ARE FINE

**Pull request merged**
