### PR TITLE
Simply follow followers of given users list

### PR DESCRIPTION
**Pull request by ahmadudin**
- Follow specified amount of follwers #444
- One follow action for every specified time interval, default = 40 sec
- random follower picking feature
- easiy extendable
- example added

### CODE REVIEW

**Comment by timgrossmann** [comment]
@ahmadudin Thank you for contributing, I'll check out your PR and get back to you as soon as I reviewed it!

**Comment by timgrossmann** [comment]
@ahmadudin  What I unfortunately also have to ask for (even though not explicitly stated in the requirements) is some documentation of the feature in the README.

Please add that

**Comment by ahmadudin** [comment]
okay

**Comment by timgrossmann** [comment]
@ahmadudin Just tested it and have to say that I works really nicely. However, regarding the "overhead" of implemented features of #477 I just have to choose his implementation.

I hope you can understand that and will still consider contributing to InstaPy in the future.
I will post the next Bounty-Issue later today.

Please understand my decision.
Thank you very much for your time!

**Comment by ahmadudin** [comment]
sure, that's great.

**Pull request closed without merging**
