### PR TITLE
Fix set set as dict; introduce white_list; fix like amount wrong logic

### PR DESCRIPTION
**Pull request by sionking**
1. Fix set set as dict
2. Separate dont_include users set at init(white list) from set during run time (like in set_dont_unfollow_active_users). this will remove the white list person from followers csv.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@sionking Good point 👍 
Thank you

**Comment by sionking** [comment]
@timgrossmann is Fix wrong logic fine ?

**Comment by ghost** [comment]
im currently running this branch. fix for dict is working, not sure about like amount. @sionking

**Comment by axlright** [comment]
For what it's worth, this is working for me and fixed an error while unfollowing while keeping `dont_unfollow_active_users`

THANX

**Pull request merged**
