### PR TITLE
Check if user's account is private - Issue #5451

### PR DESCRIPTION
**Pull request by IreneArapogiorgi**
Hello, I was assigned to implement checking whether target user's account is private or not in order to proceed into finding his followers/followings. This will be a part of a university assignment of mine as I also mentioned on issue #5451.

About my implementation, I used [is_private_profile()](https://github.com/timgrossmann/InstaPy/blob/master/instapy/util.py#L65) to check if target user's account is private or not. In addition to that, I created a new file `follow_util.py` in which I moved the implementation of [get_following_status()](https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L147) and then I imported it inside both unfollow_util.py and like_util.py, where it was already needed and used, and then inside relationship_tools.py in order to check whether the user is following the targeted private account, so in this case we can proceed into finding his followers and followings.

**Files added:**
follow_util.py

**Files changed:**
unfollow_util.py
relationship_tools.py
like_util.py
instapy.py
util.py

If there are any changes/improvements needed, please let me know so that I can work on them.
Also, any advice about unit testing my implementation is welcomed.

### CODE REVIEW

**Comment by breuerfelix** [comment]
thanks for this PR :) 

I hope to find the time to look into this and test it out.
I just got one question right of the start.
What does happen when you pass 'unneeded' as a parameter ?  
a cleaner solution would be to append self_username as the last argument of this function and set the default value to None. so all the current functions using it do not have to get touched since there is a default value for that :)

also None is way clearer  than a string with 'unneeded'.

I am still curious because i do not see any check if the variable is "unneeded" or not. So the Bot will try to interpret unneeded as a username right ?

**Comment by IreneArapogiorgi** [comment]
@breuerfelix you're so right, I didn't even think of that. I used the "unneeded" parameter in order to avoid any no-argument-found errors when using all other relative functions, but setting the default value to None is much clearer. I just fixed that.

Anything else you think I should change/improve?

**Comment by IreneArapogiorgi** [comment]
@breuerfelix I changed the implementation replacing the "unneeded" string with the actual `self.username` for all relevant functions, as we need to check whether the target user is private and whether we follow him inside all these functions before we proceed.

Let me know if there is anything else I need to improve/change.

**Comment by breuerfelix** [comment]
perfect ! looks way better now :) and actually just by looking at the PR there shouldnt be any errors :)

now we just need to get someone individual to test this PR :D

are you able to find someone (maybe in discord or a friend or smth like that) who can test out the old and new functions with a simple script ? i will also try to do some tests but with a more complex PR more testers are always better :)

**Comment by IreneArapogiorgi** [comment]
Absolutely! I also made a script which might help with testing all possible cases. For each of the relative functions, you can run seperately the 3 possible senarios - we cannot check all cases by running the script once, obviously. For me everything works fine.
```
""" Quickstart script for InstaPy usage """

# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

# login credentials
insta_username = "your instagram username"
insta_password = "your instagram password"

# get an InstaPy session
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):

    # grab followers of given user
    followers1 = session.grab_followers(username="public account", amount="full", live_match=True, store_locally=True)
    followers2 = session.grab_followers(username="private account you don't follow", amount="full", live_match=True, store_locally=True)
    followers3 = session.grab_followers(username="private account you do follow", amount="full", live_match=True, store_locally=True)

    # grab followings of given user
    following1 = session.grab_following(username="public account", amount="full", live_match=True, store_locally=True)
    following2 = session.grab_following(username="private account you don't follow", amount="full", live_match=True, store_locally=True)
    following3 = session.grab_following(username="private account you do follow", amount="full", live_match=True, store_locally=True)

    # pick unfollowers of given user
    all_unfollowers1, active_unfollowers1 = session.pick_unfollowers(username="public account", compare_by="month",
                                                                     compare_track="first", live_match=True, store_locally=True, print_out=True)
    all_unfollowers2, active_unfollowers2 = session.pick_unfollowers(username="private account you don't follow", compare_by="month",
                                                                     compare_track="first", live_match=True, store_locally=True, print_out=True)
    all_unfollowers3, active_unfollowers3 = session.pick_unfollowers(username="private account you do follow", compare_by="month",
                                                                     compare_track="first", live_match=True, store_locally=True, print_out=True)

    # pick nonfollowers of given user
    nonfollowers1 = session.pick_nonfollowers(username="public account", live_match=True, store_locally=True)
    nonfollowers2 = session.pick_nonfollowers(username="private account you don't follow", live_match=True, store_locally=True)
    nonfollowers3 = session.pick_nonfollowers(username="private account you do follow", live_match=True, store_locally=True)

    # pick fans of given user
    fans1 = session.pick_fans(username="public account", live_match=True, store_locally=True)
    fans2 = session.pick_fans(username="private account you don't follow", live_match=True, store_locally=True)
    fans3 = session.pick_fans(username="private account you do follow", live_match=True, store_locally=True)

    # pick mutual followings of given user
    mutualFollowing1 = session.pick_mutual_following(username="public account", live_match=True, store_locally=True)
    mutualFollowing2 = session.pick_mutual_following(username="private account you don't follow", live_match=True, store_locally=True)
    mutualFollowing3 = session.pick_mutual_following(username="private account you do follow", live_match=True, store_locally=True)

```

**Comment by timgrossmann** [comment]
@IreneArapogiorgi Hey, sorry for dropping this PR for so long... Any chance you can merge it with the current master so we can merge this into InstaPy? 😉

**Comment by IreneArapogiorgi** [comment]
@timgrossmann hey, I did merged the upstream/master but build failed and I'm trying to revert the changes however build is still failing. I'll be working on it for the next days and hopefully will fix it.

**Comment by IreneArapogiorgi** [comment]
@timgrossmann Hey, I did merged the upstream/master, however build is failing and I don't understand why. Could you help me out? Travis is giving me the following error:
```
ERROR: InvocationError for command /home/travis/build/IreneArapogiorgi/InstaPy/.tox/black/bin/black -t py34 --check . (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   black: commands failed
The command "tox" exited with 1.
```

**Comment by timgrossmann** [comment]
@IreneArapogiorgi Thank you very much for updating!

Please use the `black` python formatter to format the code once and then push it again 😄

**Comment by IreneArapogiorgi** [comment]
@timgrossmann Due to several conflicts between InstaPy's current master branch and my own branch, which I was not able to resolve, I created a new one having the same code contribution & made a new PR with the identification #5855. I hope that's not too confusing.

**Comment by timgrossmann** [comment]
@IreneArapogiorgi Perfect, thank you for doing this!
Much better, once the review of @elulcao has been adressed we can merge it! 😊

**Pull request closed without merging**
