### PR TITLE
telegram_util.py

### PR DESCRIPTION
**Pull request by LoopForYou**
Notifies you (or someone else) that the bot has started, finished or is paused. This is better than using SMS because Telegram is free and easy to use.

I am not that good at Python and i'm still learning, but this code works when I put it in quickstart.py and I would like your help to make the code better and have it as its own file so we can just call the functions from quickstart.py

You can find more details for integrating this util in the file comments

### CODE REVIEW

**Comment by timgrossmann** [comment]
@LoopForYou This is awesome! Thank you for contributing.

Could you please add some documentation to the README and maybe an example in the examples folder?

Also, make sure to fix the travis-ci errors.

Thank you very much

**Comment by LoopForYou** [comment]
Fixed the travis-ci error. Going to add documentation to README later tonight and an example in the examples folder.

thx

**Comment by timgrossmann** [comment]
@LoopForYou Thank you very much for this!
I'm not sure if we should put this into the instapy core module itself .
@converge aslo has a telegram extension that can be downloaded and put into the extensions folder

**Comment by sionking** [comment]
Maybe it is good idea to send telegram msg when there is no activity (maybe crash)

**Comment by timgrossmann** [comment]
@LoopForYou @sionking We should definitely merge this with @converge [telegram extension](https://github.com/converge/instapy_telegram_extension) and merge it into InstaPy

**Comment by timgrossmann** [comment]
@LoopForYou I think we'd use #1039

**Comment by sionking** [comment]
I already uses telegram when I have no action(like/follow) for last hour (external tool check the statistics for each user every hour).
I also use it when follow/like block detected.


Will PR soon

**Comment by timgrossmann** [comment]
Awesome!

**Pull request closed without merging**
