### PR TITLE
Solve issue 2322

### PR DESCRIPTION
**Pull request by ortegafernando**
See [https://github.com/timgrossmann/InstaPy/issues/2322](https://github.com/timgrossmann/InstaPy/issues/2322)

### CODE REVIEW

**Comment by timgrossmann** [comment]
@ortegafernando Thank you very much, looks like there were more people than you who had problems with this.

**Comment by xvx29a** [comment]
This needs to be reverted or changed, it breaks headless_browser on linux with chromedriver.  If I manually remove this from instapy.py it works without issue.

Moving the --no-sandbox to the if headless_browser may be a better option.

> 

      else:
            chromedriver_location = Settings.chromedriver_location
            chrome_options = Options()
            #chrome_options.add_argument("--disable-infobars")
            chrome_options.add_argument("--mute-audio")
            chrome_options.add_argument('--dns-prefetch-disable')
            chrome_options.add_argument('--lang=en-US')
            chrome_options.add_argument('--disable-setuid-sandbox')

            # this option implements Chrome Headless, a new (late 2017)
            # GUI-less browser. chromedriver 2.9 and above required
            if self.headless_browser:
                chrome_options.add_argument('--headless')
                chrome_options.add_argument('--no-sandbox')

**Comment by timgrossmann** [comment]
@xvx29a Could you please create a PR for that?

**Comment by douwevandermeij** [comment]
@timgrossmann it does still fail on Linux headless. The PR doesn't contain `chrome_options.add_argument('--no-sandbox')` in the headless_browser section.
When I manually add the option there, it runs correctly with chromedriver 2.36 but fails on version 2.40.

**Comment by douwevandermeij** [comment]
PR here https://github.com/timgrossmann/InstaPy/pull/2365

**Pull request merged**
