### PR TITLE
Implement #55

### PR DESCRIPTION
**Pull request by pekapa**
Also improved how we find links so we can get the proper amount of links for the appropriate media type.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@pekapa @vlntdds With such an amount of changes, this definitely needs some testing.
Did you move the chrome window out of focus while scrolling up and down to get all the links to the images?

Currently, if you move to chrome window out of focus, it won't get all the links since the automatic load more upon reaching the pages end won't work anymore. The while loop seems pretty dangerous combined with that problem...

Will it get the exact amount of posts?

**Comment by pekapa** [comment]
@timgrossmann thanks for pointing that out. Added a method to bring it the focus and guarantee we can actually get the posts.
I've tested while out of focus and it works (can be a little annoying to have the window popping in your face while scrolling but I guess it's a necessary evil! Let me know if you have another solution.

Yes, it loads up to 11 more posts than needed (if the last load needs just one and it gets 12 of the right media type). And passes through the exact amount.

**Comment by eduardocalazansjr** [comment]
Get the focus is not the recommended.
I think that it needs a in-depth test, will do ASAP.

**Comment by eduardocalazansjr** [comment]
Sorry for the delay, @pekapa!
I will start testing this PR and #60 just now and will write some feedbacks and ideas for you, ok?

Thanks.

**Comment by timgrossmann** [comment]
@vlntdds Any updates on this and #60 ? 😉 👍

**Comment by timgrossmann** [comment]
@vlntdds Any updates?

**Comment by eduardocalazansjr** [comment]
@timgrossmann as soon as i get home (today) i will test (i'm on a unplanned trip :( )

**Comment by eduardocalazansjr** [comment]
Made some tests, seems to work fine with all of my accounts.
@pekapa fix the conflicts, thks!

**Comment by pekapa** [comment]
Just fixed the conflicts.
Also fixed #118 with this and improved the `while` to avoid loading more than there's available.

It is working for me but might be worth to test again.

**Comment by eduardocalazansjr** [comment]
Why not split the commits?
Too much changed, it's better test and review them separately

**Comment by pekapa** [comment]
Because the point he raised in that issue is valid and affects the `while` loop directly. User could be really stuck in it so I was not comfortable letting this goes live without that fix.

If you want I can split them, but the logic to fix without the `while` is different than with the `while` so I think it would be just extra trouble.

If you need tags to help you text, I used `['#landscapeasdf', '#landascapesicily', '#landscape']`
The first has no image, the second, about 130 images and the latter, all the images you might need.

**Pull request merged**
