### PR TITLE
Code rewrite to fix crash in load_followers_data() on year/month change. Upstream Issue3874.

### LINKED ISSUE #3874: load_followers_data(...) crashes on month change.
I'm playing with InstaPy trying to understand IG user behavior. But for now, i was only tracking my followers and unfollowers on a daily basis (sometimes two or tree times, if i saw some bigger relation change.

I started around mid January, and on February, 1st the docker_quickstart.py that i was using started to crash on the "session.pick_unfollowers(...)" call. 

My call is:
`all_unfollowers, active_unfollowers = bot.pick_unfollowers(username="ig_id", compare_by="earliest", compare_track="first", live_match=True, store_locally=True, print_out=True)`

I've checked if no corrupted json or something strange was present in the "~/InstaPy/logs/<my_id>/relationship_data/<ig_id>/followers" , and found nothing wrong with the data present there. 

**If you can create and assign the issue to me, i'll provide a suggested solution as soon i've it tested.**

## Expected Behavior

Collect and store follower/unfollower information.

## Current Behavior

Crashing to collect unfollower users after month changed from January to February.
Crash occurs at: https://github.com/timgrossmann/InstaPy/blob/0c8a86057aa2959af47a38bca4f1c25edf92a1cd/instapy/relationship_tools.py#L1088

## Possible Solution (optional)

I think i already found the problem ( as it crashes trying to "check" for a dictionary entry of the new month before setting it),  and i'm currently testing a solution. I can provide a PR with it as soon i've done some more testing.

## InstaPy configuration

Currently running the docker version, but problem is reproducible, with a very simple setup.

###
To reproduce the problem:
---
```
cd *directory where InstaPy is installed*
mkdir -p "logs/my_id/relationship_data/my_id/followers/"

touch '01-02-2019~full~11.json'
touch '30-01-2019~full~11.json'
touch '31-01-2019~full~11.json'

```

Then create a docker_quickstart.py with:

---
```
from instapy import InstaPy

bot = InstaPy(username='my_id', password='pass',
              selenium_local_session=False)

#get the unfollowers since beggining
all_unfollowers, active_unfollowers = bot.pick_unfollowers(username="my_id", compare_by="earliest", compare_track="first", live_match=True, store_locally=True, print_out=True)
bot.end()
```
---
*Crash traceback
```
web_1       | ___________________________________________________________________________
web_1       | INFO [2019-02-02 12:48:08] [my_id]  Starting to pick Unfollowers of my_id..
web_1       | """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
web_1       | Traceback (most recent call last):
web_1       |   File "code/docker_quickstart.py", line 7, in <module>
web_1       |     all_unfollowers, active_unfollowers = bot.pick_unfollowers(username="my_id", compare_by="earliest", compare_track="first", live_match=True, store_locally=True, print_out=True)
web_1       |   File "/code/instapy/instapy.py", line 3906, in pick_unfollowers
web_1       |     self.logfolder)
web_1       |   File "/code/instapy/relationship_tools.py", line 566, in get_unfollowers
web_1       |     logfolder)
web_1       |   File "/code/instapy/relationship_tools.py", line 1080, in load_followers_data
web_1       |     structured_entries["years"][entry_year]["months"][entry_month][
web_1       | KeyError: '02'
instapy_web_1 exited with code 1
```

### PR DESCRIPTION
**Pull request by bugre**
Problem originally appeared in load_followers_data () when tried to read 
JSON files changing from January to February, crashing as code was 
trying to use dic entry that didn't exist (yet).

Did a quick fix (checking for existence) but soon found out that there
where other places crashing (year change), so decided doing a rewrite of
this part of the code, replacing it with another approach, using dict
setdefault()

Check the issue https://github.com/timgrossmann/InstaPy/issues/3874 for
more info.

Bellow code diff of this final change /rewrite suggestion.
image

I'm attaching a quick/dirty test script to the issue 3874.
[issue3874-test-case.py.txt](https://github.com/timgrossmann/InstaPy/files/2825723/issue3874-test-case.py.txt)

Fixes #3874

### CODE REVIEW

**Comment by uluQulu** [comment]
Wowo @bugre 
### Great job 🚁


I wrote it in my early python days - 7 months ago and now looking at it looks like it could be simplified too much as you greatly did xD

I think I missed to cover that part because of during writing the relationship tools I ran tests with the data from the same month but well .. 
#### That bug is produced out of this block:


I've even checked the [original file](https://github.com/timgrossmann/InstaPy/blob/de0932cc4f77f93de861cc051e78b5e91a757b43/instapy/relationship_tools.py) from the release I made at #2253 and it's the same code logically.

image

Its solution is, inside the **relationship_tools.py** file,
**replacing**
```python
        existing_months = list(month for month, day in
                               structured_entries["years"][entry_year][
                                   "months"].items())
        existing_days = list(
            day for day, entry in
            structured_entries["years"][entry_year]["months"][entry_month][
                "days"].items())
```
**with**
```python
        existing_months = list(month for month, day in
                               structured_entries["years"][entry_year][
                                   "months"].items()) if entry_year in existing_years else []   # ADDITION HERE
        existing_days = list(
            day for day, entry in
            structured_entries["years"][entry_year]["months"][entry_month][
                "days"].items()) if entry_month in existing_months else []      # ADDITION HERE
```
Added
`if entry_year in existing_years else []`
and
`if entry_month in existing_months else []`

But I like your solution.

---

I tested like this,
```python
from datetime import datetime


tracked_filenames = [
    "18-02-2018", "19-02-2018",
    "26-06-2018", "08-07-2020",
    "22-04-2015", "01-09-2015",
    "03-03-2019", "07-10-2019",
    "07-10-2019"
]
sorted_filenames = sorted(tracked_filenames,
                          key=lambda x: datetime.strptime(x, '%d-%m-%Y'))
structured_entries = {}


def new():
    global structured_entries

    for entry in sorted_filenames:
        entry_day, entry_month, entry_year = entry.split('-')
        structured_entries.setdefault("years", {}).setdefault(entry_year, {}).\
            setdefault("months", {}).setdefault(entry_month, {}).\
            setdefault("days", {}).setdefault(entry_day, {}).\
            setdefault("entries", []).append(entry)

    return structured_entries


def old():
    global structured_entries

    for entry in sorted_filenames:
        entry_year = entry[-4:]
        entry_month = entry[-7:5]
        entry_day = entry[:2]

        if not structured_entries:
            structured_entries = {
                "years": {entry_year: {"months": {entry_month: {
                    "days": {entry_day: {"entries": [entry]}}}}}}}
            continue

        existing_years = list(
            year for year, month in structured_entries["years"].items())
        existing_months = list(month for month, day in
                               structured_entries["years"][entry_year][
                                   "months"].items()) if entry_year in existing_years else []
        existing_days = list(
            day for day, entry in
            structured_entries["years"][entry_year]["months"][entry_month][
                "days"].items()) if entry_month in existing_months else []

        if entry_year not in existing_years:
            structured_entries["years"][entry_year] = {
                "months": {
                    entry_month: {"days": {entry_day: {"entries": [entry]}}}}}
        elif entry_month not in existing_months:
            structured_entries["years"][entry_year]["months"][entry_month] = {
                "days": {entry_day: {"entries": [entry]}}}
        elif entry_day not in existing_days:
            structured_entries["years"][entry_year]["months"][entry_month][
                "days"][entry_day] = {"entries": [entry]}
        else:
            structured_entries["years"][entry_year]["months"][entry_month][
                "days"][entry_day]["entries"].append(entry)

    return structured_entries


# print(old())
print(new())
```


---
Thank you.

Cheers 😁
---

**Review by uluQulu — APPROVED** [review]
Amazing solution ⚽

**Comment by timgrossmann** [comment]
@bugre Awesome improvement!
Thank you very much for this PR.
Also very nice branch naming :+1: 

Thanks for approving and checking it, @uluQulu !

**Comment by bugre** [comment]
Hi Şəhriyar and Tim,

Happy that you did approve and like the suggested rewrite/correction.
Was surprised to not see a lot of issues with this problem, as i just started playing with InstaPy and the first that i would like to know/follow is the new "followers" and those that did leave (unfollow) and that did trigger the error. So, did i use it in a way that is not usual, or the way i used made the bug appear?

Şəhriyar, initially (when i only had seen the "month change problem")  I went for a solution similar to you suggestion, but when i found year problem, and took some time to understand what the code did, after some research i came up with the setdefault() alternative. I think i never used it that way (with so many levels) , but it worked 👍 

I also saw a few PEP8 warnings in this file (i haven't checked others), but i preferred not to mix those changes with the bug fix. Should/could i make those changes (mostly cosmetic) and do a new PR?

Have a few more questions about difficulties i had with my usage, should i open issues for them all? I tried accessing the discord channel, but it says that the link from the README.md (https://discord.gg/FDETsht) is invalid (possible wrong or expired).

Have a nice week.
-werner

**Comment by uluQulu** [comment]
Yes, @bugre 
That's better.

Even if pushing PEP8 changes in a separate commit is fine.
But bug fixes like this should be merged immediately, so that if it had PEP8 changes then, that would take some time to review it, too..

I also saw,
Here is the output from my _SublimeLinter_ which uses famous **pycodestyle** tool for linting:
```log
>>> print("Let's lint this file")
Let's lint this file
SublimeLinter: sublime_linter.py:252  Delay linting 'relationship_tools.py' for 0.0s
SublimeLinter: linter.py:931          pycodestyle: checking lint mode 'background' vs lint reason 'on_user_request'
SublimeLinter: linter.py:931          annotations: checking lint mode 'background' vs lint reason 'on_user_request'
SublimeLinter: #8 linter.py:948       pycodestyle: linting 'relationship_tools.py'
SublimeLinter: #8 python_linter.py:42 pycodestyle: wanted python is 'None'
SublimeLinter: #8 python_linter.py:93 pycodestyle: trying to use globally installed pycodestyle
SublimeLinter: #9 linter.py:948       annotations: linting 'relationship_tools.py'
SublimeLinter: #8 linter.py:1363      Running ...

  C:\Users\shahr\Documents\GitHub\InstaPy-TEST  (working dir)
  > type instapy\relationship_tools.py | "C:\Program Files (x86)\Python37-32\Scripts\pycodestyle.exe" --statistics --max-line-length=79 -

SublimeLinter: #9 linter.py:1021      annotations: no output
SublimeLinter: #8 linter.py:1027      pycodestyle: output:
  stdin:101:17: E131 continuation line unaligned for hanging indent
  stdin:192:80: E501 line too long (86 > 79 characters)
  stdin:203:25: E131 continuation line unaligned for hanging indent
  stdin:204:25: E122 continuation line missing indentation or outdented
  stdin:293:9: E122 continuation line missing indentation or outdented
  stdin:361:17: E131 continuation line unaligned for hanging indent
  stdin:448:80: E501 line too long (86 > 79 characters)
  stdin:459:25: E131 continuation line unaligned for hanging indent
  stdin:460:25: E122 continuation line missing indentation or outdented
  stdin:867:9: E122 continuation line missing indentation or outdented
  stdin:900:9: E122 continuation line missing indentation or outdented
  stdin:1079:13: E122 continuation line missing indentation or outdented
  stdin:1105:13: E122 continuation line missing indentation or outdented
  stdin:1106:17: E125 continuation line with same indent as next logical line
  stdin:1134:17: E122 continuation line missing indentation or outdented
  stdin:1135:5: E125 continuation line with same indent as next logical line
  stdin:1151:80: E501 line too long (101 > 79 characters)
  stdin:1159:5: E122 continuation line missing indentation or outdented
  stdin:1170:1: W391 blank line at end of file
  9       E122 continuation line missing indentation or outdented
  2       E125 continuation line with same indent as next logical line
  4       E131 continuation line unaligned for hanging indent
  3       E501 line too long (86 > 79 characters)
  1       W391 blank line at end of file
SublimeLinter: sublime_linter.py:449  Linting 'relationship_tools.py' took 2.06s
```

But please don't touch lines that PEP8 complains regarding `E712`,
image

I'll write soon about it on another thread, maybe I have to agree with @converge and @timgrossmann about it.
_BTW that file does not have any `E712` violation, but I said in any case_..

---

> Have a few more questions about difficulties i had with my usage, should i open issues for them all? I tried accessing the discord channel, but it says that the link from the README.md (https://discord.gg/FDETsht) is invalid (possible wrong or expired).

_GitHub_ **Issues** is better if your problem/difficulty is unusual so that ppl having that problem in the future can also refer to it easily.
Otherwise, casual problems should be asked directly in _Discord_ just because of it is easier to communicate.

Here is an invite link for you - https://discord.gg/GfWms (_be quick, expires in 6 hours 😎_)

---

Cheers 😁
---

**Comment by timgrossmann** [comment]
@bugre Sure, creating a new PR for the PEP8 fixes is good to keep it clear.
Kind of weird that the link is not working 🤔 when I click it, I'm forwarded to the discord channel invite page.

@uluQulu I think we've discussed the E712 here: https://github.com/timgrossmann/InstaPy/pull/3637
Seems like it's not a problem

**Comment by bugre** [comment]
Hi,
Thanks @uluQulu with that link i could access with discord app. 
I'll look some more around and playing with InstaPy, if i get new difficulties i'll let you know on Issues or Discord. 

Great tool by the way. Congrats to you. 👏 Thanks for releasing it to public source.

Looking at [https://github.com/timgrossmann/InstaPy/pull/3637], i got a clear idea that's being worked.

With this i think we can also safely declare Fixed #3874 (#edit# had forgotten, now added "Fixes #3874" on the PR first comment)

Have a nice week.

PS: Ill be mostly offline for a couple of weeks (🍹 🏖).

**Pull request merged**
