### PR TITLE
fix the login issue with the new login page layout

### PR DESCRIPTION
**Pull request by CharlesCCC**
commented out the line for now until further fix created.

### CODE REVIEW

**Comment by ganeshkrishnan1** [comment]
We don't have to comment out that line. Just set the switch_language=False in quickstart.py

**Comment by deronsizemore** [comment]
switch_language=False doesn't seem to be working for me. Can someone confirm that it's the fix for this?

**Comment by deronsizemore** [comment]
I figured it out after looking through some of the other similar issues. self.switch_language = True needs to be set to False inside of instapy.py.

Setting it to Flase in quickstart.py didn't seem to work for me.

**Comment by uni1783** [comment]
In quickstart.py you need to set it as session.switch_language=False

**Comment by spoonyto** [comment]
@uni1783 Thanks! Actually works!

**Comment by fegomess** [comment]
I still can't make it work. It just don't create the cookie file. By the way, Always when instagram changes my password, i had to delete the cookie file from log folder, then run the script. Now it just dont login... it trys to create a cookie file and crashes. Help, pls

edit:
i tryed everything u guys posted here, but nothing worked for me. Here is what worked: i changed it to Firefox browser, so it could create the freaking file, then i switched back to headless chrome, and TADAA, its working now.

**Comment by farschmessivo** [comment]
@fegomess hi, can you please share the steps how to use FF instead of Chrome? 
thnx

**Pull request closed without merging**
