### PR TITLE
Fix issue #774: follow_user_following

### PR DESCRIPTION
**Pull request by 0x00secJinx**
I put the try/except inside the 'for username in usernames' loops allowing for the use of the continue statement to go to the next username in the list when an Runtime error is caught.

### CODE REVIEW

**Comment by converge** [comment]
@0x00secJinx just tested, great fix, thanks! Can you just adjust it to flake8 ?

**Comment by 0x00secJinx** [comment]
@converge Yes! I will have it adjusted soon

**Comment by 0x00secJinx** [comment]
This should be it. Let me know if I did something incorrectly.

**Comment by converge** [comment]
@0x00secJinx great work! thank you!

**Pull request merged**
