### PR TITLE
Fix issues out of inconsistent delays while after clicking the Unfollow button from the pop up dialog AND some others

### PR DESCRIPTION
**Pull request by uluQulu**
Hey guys

Here is the reasons for this PR,
+ 1st commit - https://github.com/timgrossmann/InstaPy/issues/2882#issuecomment-420370821
Well to say more words,
it happened cos the button accomplished its job after inconsistent time delays and there is a verification block which was misbehaving.
Now, `explicit_wait()` waits for enough time [default- 66 seconds] and releases back as the button has accomplished its job.
In case of it cannot accomplish its  job - it cannot unfollow; There it will timeout after the pre-defined delay [default- 66 seconds] and will reload page and try the same step again and in case of the second timeout, it will break the loop cos it is a sign of shadow ban.

>The usage of `explicit_wait()` is amazing 👈🏼 stability + performance + simplicity + speed

+ 2nd commit - https://github.com/timgrossmann/InstaPy/issues/2890#issuecomment-420382809

----

Cheers 😁
---------

### CODE REVIEW

**Comment by fgisslen** [comment]
I tried this one.
get this error:

INFO [2018-09-14 08:59:04] [xxx]  Ongoing Unfollow [3/400]: now unfollowing 'x''...
ERROR [2018-09-14 08:59:08] [xxx]  Unfollow loop error:  Message: stale element reference: element is not attached to the page document


before that it looked like:

INFO [2018-09-14 08:58:18] [xx]  Ongoing Unfollow [2/400]: now unfollowing 'xx''...
INFO [2018-09-14 08:58:35] [xx]  --> Unfollowed 'xx'!
INFO [2018-09-14 08:58:35] [xx]        Removed '2018-09-06 08:11 ~ xx ~ 1796178268' from followedPool.csv file

INFO [2018-09-14 08:58:48] [xx]  Ongoing Unfollow [3/400]: now unfollowing 'xx''...
INFO [2018-09-14 08:58:52] [xx]  --> Couldn't unfollow 'xx''!     ~maybe unfollowed before
INFO [2018-09-14 08:58:52] [xx]        Removed '2018-08-24 09:50 ~ xx' from followedPool.csv file

INFO [2018-09-14 08:58:56] [xx]  Ongoing Unfollow [3/400]: now unfollowing 'xx''...
INFO [2018-09-14 08:59:00] [xx]  --> Couldn't unfollow 'xx''!   ~maybe unfollowed before
INFO [2018-09-14 08:59:00] [xx]        Removed '2018-09-02 10:50 ~ xx ~ 20613351' from followedPool.csv file

**Comment by fgisslen** [comment]
Ran ut again with another error:

INFO [2018-09-14 09:27:20] [xx]  Ongoing Unfollow [6/400]: now unfollowing 'xx'...
ERROR [2018-09-14 09:29:06] [xx]  --> Unfollow issue with 'xx''!       ~unable to detect the following status
INFO [2018-09-14 09:29:06] [xx]  Checking if 'xx' is logged in...
CRITICAL [2018-09-14 09:29:08] [xx]  --> 'xx' is not logged in!

WARNING [2018-09-14 09:29:08] [xx]  There is a serious issue: 'not logged in'! ~leaving Unfollow-Users activity
INFO [2018-09-14 09:29:08] [xx]  --> Total people unfollowed : 5

**Comment by timgrossmann** [comment]
@fgisslen Thank you very much for investing the time to do some testing 🙏

**Comment by jeremycjang** [comment]
@uluQulu Great work! I think the term "Shadow Ban" should be renamed to something like "action block". Most users know shadowban to mean that their account posts are not being displayed when searching hashtags, so this may cause some confusion. Also from my own testing, Instagram "shadowbanning" doesn't actually appear to be tied to actions performed

**Comment by uluQulu** [comment]
@fgisslen 
### A: hm `StaleElementReferenceException` 😒
Have you applied it properly?

Considering you applied it properly,
1-) **post** that **unfollow_util.py** file [in a _ZIP_]

2-) **open** up **unfollow_util.py** file and **add** this new `raise` line
```python
        except BaseException as e:
            logger.error("Unfollow loop error:  {}\n".format(str(e)))
            raise   # ADD THIS LINE
```
_Then post the output of the thrown exception from console [FULLY] to find the issue_ 🦅

### B: "_There is a serious issue: 'not logged in'!_" ⛔
1-) The changes came in this PR is unrelated to the error message you got;
Actually what this PR has is, if visualized,
+ wait for the action [unfollow] to be accomplished
+ not accomplished?
+ + reload page and re-try the action and wait until it accomplishes its job
+ + still not accomplished?
+ + return `False` with the "_shadow ban_" message

Earlier it was just clicking the button and sleeping some fixed seconds, I wrote detailed in above comments if you like to read more about the use of `explicit_wait()`.

2-) Having known 1st step, you should know that the error message saying "_not logged in_" is laying in different place.
If the logs are correct, it means it unfollows a few users correctly, and then says it is not logged in.
Well, it is a sign of a problem and needs to be solved.
@fgisslen, can you open a new [PROPER] thread for it?

**Hint**: _Most possibly there are some connectivity issues with your setup which might lead to excessive timeouts, etc. THAT might make that problem of not being to able to fetch data from the server BUT in any case that issue should be solved_.

------

Yeah @timgrossmann, 🧐 @fgisslen is a great tester & reporter 👏🏼

Thanks @jeremycjang 🙂 and that's true.  
Actually, after temporary blocks comes shadow ban [mostly]
And the term - "_shadow ban_" is a bit strict word and it kinda scares people 😀 😳

I thought of making it "_possible shadow ban_".
Now I think of using "temporary block" or "possible [action] block" as you offer. 
#### What do you think all? 👆🏼


----

Cheer 😁
------

**Comment by fgisslen** [comment]
@uluQulu of some reason I can’t reproduce the error again. I recently moved one server to digital ocean. Maybe it was something with that. Now it seems to work but I will have a new look later today.

**Comment by uluQulu** [comment]
### Commit 2 - https://github.com/timgrossmann/InstaPy/pull/2901/commits/54e607c84ff50a5d60a4ca7f88bf8f7517832404: revealed bugs from #2926 by @meinert
Ater I saw a bug in there, I started to revise that function and ended up as a total revision.

#### The problem in **Earlier** design (by @sionking):
Total BUGs: 
+ In case of it encounters the first exception it was not reaching the second element find;
+ The scenario of empty string;

Extra BUGs:
+ In case of the page not loading properly it was prone to misbehave cos element was not loaded yet;
+ `contains(text(), 'Follow')` was misbehaving sometimes since it was also getting the element with "_Follow to see their photos and videos._" text etc.;

#### Now:
+ Total structural revision;
+ Strictly safe expressions (_e.g._ now uses `text()='ButtonName'`);
+ It uses `explicit_wait()` WHICH waits for the button to be loaded and when loads returns a reference to that element = simpler + efficient + robust;
_As usual `explicit_wait()` will wait max `66` seconds in default timeout and if the element still is NOT loaded then will return False_.

_In case of the element is not found, it will reload the page and try the same steps once more AND IF the result is STILL False, it will return back with no success to be handled accordingly outside_..

Also it is much simpler now with lesser lines 🛩

----

### Commit 3 - https://github.com/timgrossmann/InstaPy/pull/2901/commits/1e457e793ab59f7a177c7f8c1da83e1024166137: out of the issue raised at #2911 by @adisch79
There is a case where user wants to enter `None` or `0` to `sleep_delay` parameter in unfollow feature.
As it is not a recommended value set, it makes problems while doing e.g. multiplication operation inside the sleep blocks.
Now solved, it will not enter the sleep block once the value is either `0` or `None`.

----

Cheers 😁
----

**Comment by fgisslen** [comment]
nice work @uluQulu

**Comment by MarshallJohansson** [comment]
sorry, how to apply this PR?

**Comment by uluQulu** [comment]
Thanks @fgisslen 🙂

There are lots of ways to do it, @MarshallJohansson, but if you like to do it using powerful git commands you can use a quick guide I wrote once a time at https://github.com/timgrossmann/InstaPy/pull/2042#issuecomment-390280939.

git pull

But this PR is quite little, I mean, if you are afraid of breaking the code of your repo, just tell me the problem you have and the reason you need this PR and I will give the code needed to replace in your file(s) or just read the commit names and find clue and apply manually, etc.


----

Cheers 😁
----

**Comment by MarshallJohansson** [comment]
Hi. now here is the problem:
`INFO [2018-09-18 20:18:43]  Checking if 'account' is logged in...
CRITICAL [2018-09-18 20:18:47]   --> 'account' is not logged in!

WARNING [2018-09-18 20:18:47]   There is a serious issue: 'not logged in'!	~leaving Unfollow-Users activity
`

**Comment by CharlesCCC** [comment]
Please checkout this comment. 
https://github.com/timgrossmann/InstaPy/issues/2926#issuecomment-422896693

**Comment by uluQulu** [comment]
@CharlesCCC 
I have found 2 separate methods to achieve that requirement- getting the profile page from the user ID.
Gonna share soon 🎊

-----

Cheers 😁
------

**Comment by CharlesCCC** [comment]
@uluQulu that will be great, if is another URL or similar thing, hope the quick fix just to replace the URL and consider it solved.

**Pull request merged**
