### PR TITLE
Ensuring the script gets the amount needed to follow

### PR DESCRIPTION
**Pull request by ahmadudin**
- Add simple algorithm to check if amount of user needed to follow is sufficient
- Expand the amount when `random=True` for better sampling distribution

### CODE REVIEW

**Comment by timgrossmann** [comment]
@ahmadudin Thank you! Will check this ASAP

**Comment by timgrossmann** [comment]
@ahmadudin Do you think there is a way to incorporate a new parameter which will let people decide if they want to include all of their followers/following in the `random=True` selection?

e.g. if I want 10 random of my 500 followers, I can simply provide that param and it will scroll until all are loaded? And only then select the 10?

**Comment by ahmadudin** [comment]
@timgrossmann wait, what method this kind of `random=True` for?

**Comment by timgrossmann** [comment]
@ahmadudin It would be interesting for the `.interact_user_...` and `.follow_user_...` the used method is called `scroll_bottom`.

**Comment by ahmadudin** [comment]
@timgrossmann Oh i see, so the parameter will prevent bananas scrolling on account with millions follower/following if including all the followers/following function implemented by default(?)

**Comment by timgrossmann** [comment]
Yes, right now, there is a check if the amount is greater than 50, if it is, it will simply set it to 50 (the scroll_bottom method in utils.py) 

This is bad default behavior since it will simply stop scrolling even if you provide a large enough number like 500.

So e.g. I want to do a follow_user_followers with 500 (random=False) it will simply stop at 270 and say that you've requested more than there are followers. 

This limit is great for accounts with lots and lots of followers, since loading all of them would take hours, therefore it would be nice if we could add a param that forces the scroll_bottom to really go as far as the amount states and not cut it off.

I hope this is somewhat understandable.
I'll try to come up with a good example soon.
Sorry if there are any confusions

**Comment by timgrossmann** [comment]
@ahmadudin Here are a few examples of what I mean:

1. The user wants to use the `.interact_user_followers` feature at a big account with 2Mio followers, in this case the current behaviour is nice because it makes sure the script won't take forever to load all the followers. (It still will only do 50 scrolls to the bottom, because this is the max amount decided in the `scroll_bottom` method <= this definitely needs to be changed) 

2. The user wants to use his own followers/following, in this case he might want to get e.g. 50 random people of his whole followers list. Right now, when providing 50 in the `.interact_user_...` methods, it will simply get a few more and select 50 of them to not only take the latest. But it will never aggregate all the followers/followings before selecting the 50 people.
He himself might only have 500 followers, therefore he wants to use all of his followers instead of only 50 of the 50*3 aggregated.

It might be a good idea to simply create a followers and following list once in a while which will also help us to create features like #352 (unfollow not followers)

**Comment by ahmadudin** [comment]
@timgrossmann sorry, i've been away for a while. For the first example, i think my pull request is already solves it. And for the second i agree, its a good idea to involve the whole followers/following into the population to be sampled, but i think it will be on different method.

**Pull request merged**
