### PR TITLE
Fixes selenium out of bounds exceptions on raspberry pi

### PR DESCRIPTION
**Pull request by espipj**

### CODE REVIEW

**Comment by timgrossmann** [comment]
@espipj Could you quickly point out the problem and write up why this is the solution to the problem?

Thank you very much for contributing!

**Comment by espipj** [comment]
It happens on RasPi to me, same as this issue: https://github.com/timgrossmann/InstaPy/issues/803

**Comment by estebancortero** [comment]
I also had to change the display size to prevent errors.

**Comment by timgrossmann** [comment]
Is this still a problem?

**Comment by estebancortero** [comment]
No, I freshly cloned the repo a couple of days ago on my RPi 3 and it works fine without any adjustments. I guess this PR can be closed.

**Comment by espipj** [comment]
I can't assure that it is working properly now as I haven't used it for a while now but the line on the repo is still the same so it seems to me that is not solved yet...
https://github.com/timgrossmann/InstaPy/blob/1f89a1d476c66639fa969deabe08ce58dae53c1a/instapy/instapy.py#L75
I changed it to a higher resolution to solve the out of bounds exception:
https://github.com/espipj/InstaPy/blob/6c23e4514820f7cf9fababb7a40dfab84616ef12/instapy/instapy.py#L60

**Comment by timgrossmann** [comment]
@espipj What is the reason you're not using the headless version?

**Pull request closed without merging**
