### PR TITLE
#3656 (bug fix) change the way the login link is clicked

### PR DESCRIPTION
**Pull request by converge**
Sometimes the screen is smaller than the Instagram page, and the Login button wont be visible. ActionChains works looking for elements visible on viewport:

```python
(ActionChains(browser)
         .move_to_element(login_elem)
         .click()
         .perform())
```

throws this exception if the Login link isn't visible on viewport:
```selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (901.4916915893555, 640) is out of bounds of viewport width (1280) and height (638)```

(Login button isn't visible)
captura de tela 2019-01-02 as 08 59 34

--
The fix is click the link using the click() function.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@converge Thank you very much for the fix, could we maybe quickly discuss if there is another way to handle this while keeping the action chain movements?
(Thinking about InstaPy being more "human-like")

**Comment by converge** [comment]
sure.. we could scroll down, but isn't a fancy solution.. if we're using it in a big screen, there is no need to scroll down..

I will sleep on it.

**Comment by timgrossmann** [comment]
@converge Perfect, thank you very much.
I'm aware that it's only a problem on small screens and maybe it's unnecessary to think about the difference but maybe it comes in handy at one point, maybe.

Thanks for considering.
If we agree that there is no need, we'll merge this.

**Comment by w4ngel** [comment]
@timgrossmann @converge this isn't happening across the board, would we be able to put it in a try catch instead?

`try:
     (ActionChains(browser)
         .move_to_element(login_elem)
         .click()
         .perform())
except MoveTargetOutOfBoundsException:
     login_elem.click()`

Then we can keep the more "human" way initially.

**Comment by converge** [comment]
@w4ngel sounds like the best idea for me.

**Comment by w4ngel** [comment]
Committed. @timgrossmann this is ready to merge.

**Comment by timgrossmann** [comment]
@converge @w4ngel Awesome teamwork guys!
Thank you very much

**Pull request merged**
