### PR TITLE
Additional fix for the Instagram web API change

### PR DESCRIPTION
**Pull request by CharlesCCC**
fixed to use 
user_data = json.loads(pre)['graphql']['user']

### CODE REVIEW

**Comment by Tjorriemorrie** [comment]
LGTM

**Comment by timgrossmann** [comment]
@CharlesCCC Thank you very much for the quick fix!

**Comment by akyzer** [comment]
I dunno why, but it's not working for me!
Still have the error 

selenium.common.exceptions.WebDriverException: Message: unknown error: **Cannot read property 'followed_by' of undefined**

:'(

**Comment by CharlesCCC** [comment]
@akyzer make sure you get the latest version of master by doing `git pull`

**Pull request merged**
