### PR TITLE
Like different pictures of a user's profile

### PR DESCRIPTION
**Pull request by BernardoGO**
This pull request adds the features requested in #484.

**like_by_users(['natgeo', 'geo'], amount=10, random=True)**

- Moves to the user's profile page and like the given amount of photos
- The image picking can be either random or top-down.
- Includes the restrictions and settings set up before calling the method (including e.g. comment-ratio and like restrictions)
- Clarifai is being used
- Uses built-in follow_user and like_image
- Uses built-in log system

**set_user_interact(amount=10, random=True)**
- Set interaction parameters for `follow_user_follower(['natgeo', 'geo'], amount=20, random=True, interact=True)` and `follow_user_following(['natgeo', 'geo'], amount=20, random=True, interact=True)`
- In this case, for every user of the 20 randomly selected, move to their profile and randomly choose 10 pictures to be liked. 

**get_posts_by_user()**
- Moves to a user profile and returns the posts.
- Scrolls automatically 

**follow_user_followers**
- Now includes interact parameter, calls like_by_user

**follow_user_following**
- Now includes interact parameter, calls like_by_user

**There is a example given in the examples file
There is documentation added in the README**

### CODE REVIEW

**Comment by ahmadudin** [comment]
you're fast

**Comment by timgrossmann** [comment]
@BernardoGO You guys really are fast!
Perfect, thank you for this. I'll look into it and get back to you.

Thank you for contributing.

**Comment by timgrossmann** [comment]
@BernardoGO I just tested it and it already works very well.

Here are a few things I noticed:

- If random is True for the user interaction, it will load more and more without taking into account how many pictures I actually want to like (check out the get_links_for_username method at the other PR) This will take very long with accounts like natgeo which have 14k posts.
- change the like_by_user() to like_by_**users** to keep the interface a bit more consistent
- While testing I ran across a "Sorry this page is not available"-Page which led to the script aborting instantly. Please make sure that this will skip the current user and continue on with the next one.

This is definitely my fault,  but we need to add another parameter to the `set_user_interact`-method, I updated the issue for the requirements.
- add another param which is `percentage=...` like on a lot of the other methods.
Me might want to follow 250 of the given users followers but only interact with ~10% of them.

Thank you very much for contributing!

**Comment by ahmadudin** [comment]
Very well. For adding percentage param, it just came to my mind when i was about to use the feature for real purpose, not just testing.

**Comment by timgrossmann** [comment]
@ahmadudin Haha, yes the same happened to me 😅 
I just then realised that this would be important.

**Comment by timgrossmann** [comment]
@BernardoGO Thank you for contributing, I hope, even though @ahmadudin PR was merged, you'll consider contributing again in the future.

**Comment by stephane-archer** [comment]
is the action `like_by_users` available? @timgrossmann @ahmadudin @BernardoGO

**Pull request closed without merging**
