### PR TITLE
Issue #43 Adding Page Documentation

### PR DESCRIPTION
**Pull request by littleswany**
Based on the Readme I have created a GitHub Pages static page for the Repo. Using the Cayman theme to make it look beautiful.
Only changes are the addition of the Docs folder

### CODE REVIEW

**Comment by timgrossmann** [comment]
@littleswany Please add the part about collaborating: 
```
Think this tool is worth supporting? 
Feel free to contribute to the project in whatever way! 
If you're not familiar with python, you could build a github page for this project (Just head over to the issues, there might be a task for you). You're a marketer? Perfect! hit me with a message on contact.timgrossmann@gmail.com. 
Become a part of InstaPy!
```

And change the color of the header bar to a similar gradient the Instagram logo has.

**Comment by timgrossmann** [comment]
@littleswany also, please change the link of the instagram logo to the new one.

Thank you, it'll be merged then 👍

**Comment by eduardocalazansjr** [comment]
@littleswany could you please add the two guides that are in the "docs" page on the github page?

By the way, nice work!

**Comment by timgrossmann** [comment]
@vlntdds already added 😉

**Comment by littleswany** [comment]
Thanks @timgrossmann and @vlntdds. Sorry for some reason notifications were playing up yesterday, seen you have done the above anyway :)

**Pull request merged**
