### PR TITLE
#1123 bugfix

### PR DESCRIPTION
**Pull request by converge**
* #1121 bugfix
* code organization improvement
* adds bypass_suspicious_attempt back
* adds better documentation

The flow is:
bypass_suspicious_attempt=True and login issue -> it will bypass it, using security code approach
bypass_suspicious_attempt=False and login issue -> wrong login data
bypass_suspicious_attempt=True and login OK -> will login using cookie and shows "Unable to locate email or phone button, maybe bypass_suspicious_login=True isn't needed anymore"
bypass_suspicious_attempt=False and login OK -> will login using cookie

### CODE REVIEW

**Comment by Namaslayer** [comment]
@timgrossmann @converge Here to help! What can I do

**Comment by converge** [comment]
@Namaslayer hey mate, this is a fix for #1123.

I need your help to test it, it's simples, just follow the command line instructions (link in this page), check the README about bypass suspicious login, I think the docs are better now.

**Comment by alexbaldwin** [comment]
Can confirm, this solves my cookie creation problems. 💯

**Comment by Namaslayer** [comment]
@converge, sorry mate. This might be a bit over my head. I think if I start manually changing code, I'll mess the whole thing up and have to start over with a fresh server again.

**Comment by Tkd-Alex** [comment]
Tested and word!

**Comment by charliecode** [comment]
I can also confirm this fixed my problem as well. I was seeing this when trying to run quickstart.py

Cookie file not found, creating cookie...
Unable to locate email or phone button
CRITICAL - Wrong login data!
INFO - Session ended - 2017-12-22 14:58:12
INFO - --------------------

Once I made the changes @converge made via login_util.py and insta.py it is working flawless.

**Comment by Namaslayer** [comment]
The new code is working on my server that was already running. Tried a new account/new server and still having issues.

Just did a git pull on my one server. Spun up a new one on a different account with the latest version of InstaPy and still getting the Critical wrong-login data message.

Suggestions?

**Comment by converge** [comment]
@Namaslayer as it's a new account, it will probably ask you for the security code. So you need to set bypass_suspicious_attempt=True , bypass it, set bypass_suspicious_account=False and try again.

https://github.com/timgrossmann/InstaPy#bypass-suspicious-login-attempt

**Comment by Namaslayer** [comment]
@converge Tried that, got to the part where it asks for a code. Typed in the code from my email and then it crashed. Haven't been able to get a new email with a new code yet. If I bypass it, I get the code message but don't have a code to enter. If I don't bypass it, I get wrong login info.

**Comment by converge** [comment]
you will need the security code to bypass it..

IG delay it sometimes, I just try again like 2 or 3 times, and after some minutes they send the code

**Comment by daz99m** [comment]
its working for me , but the session ended after an hour.

**Comment by converge** [comment]
@daz99m pls paste the full error message

**Comment by daz99m** [comment]
INFO - Session ended - 2017-12-23 01:15:48
INFO - --------------------
theres no error message , it just ended for no reason

**Comment by daz99m** [comment]
just tried again and i got this 
File "quickstart.py", line 19, in <module>
    session.unfollow_users(amount=600, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )
  File "C:\Users\Dairis\Desktop\InstaPy-master\instapy\instapy.py", line 1276, in unfollow_users
    self.logger)
  File "C:\Users\Dairis\Desktop\InstaPy-master\instapy\unfollow_util.py", line 48, in unfollow
    browser.get('https://www.instagram.com/' + username)
  File "C:\Users\Dairis\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 323, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Dairis\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dairis\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

**Comment by converge** [comment]
@daz99m the first message says:

"I did everything you set me up to do, I just finished it and I'm closing"

The other message, there some open issues about it, can you check at issues page ?

**Comment by daz99m** [comment]
wheres the issue page?
and could you please send me what are the best settings for quickstart.py

**Pull request merged**
