### PR TITLE
Fixed login_util

### PR DESCRIPTION
**Pull request by eduardocalazansjr**
Changed the elements and make it work on every login scenario.

Also added the support to ActionChains to avoid Instagram anti-bot
protection and simulate mouse movements

### CODE REVIEW

**Comment by pekapa** [comment]
working fine for me

About the anti-bot, isn't it moving way to fast? Is there a way to slow it down?

**Comment by timgrossmann** [comment]
@vlntdds Really nice and clean. Love it!

**Comment by eduardocalazansjr** [comment]
@pekapa 
No, for the js gather it doesn't count the speed, but the movements on the page.
You will doesn't see the movement, of course, but it will track as an valid x/y movement through the elements.

For the submit time between pages i will keep the sleep after the click.

**Comment by timgrossmann** [comment]
@vlntdds So... do you think xpath with text comparing is the least error prune solution?

**Comment by eduardocalazansjr** [comment]
@timgrossmann i'm testing it in a couple of scenarios and the only thing that remains the same are the text on the elements.

Since they're using react to build the elements/css with random classes and the JS is kind of dubious, i think that text comparing is the best way out (at least for now)

**Pull request merged**
