### PR TITLE
In unfollow utils, removing the person from file if we cant unfollow him

### PR DESCRIPTION
**Pull request by HaimBendanan**
I had a situation where the bot was stuck on a person that can't be unfollowed, solved it by removing this person from the local followed file.

### CODE REVIEW

**Comment by CharlesCCC** [comment]
Good thoughts, the situation like this usually is caused by the followed by user changed their username. 
but one thing I would like to consider is, what if it is false/positive. this could potentially remove any user that should not be removed from the list (e.g. if the internet is acting up etc.)  @sionking I believe you had worked on something like this in the past.

**Comment by sionking** [comment]
I will [post my unfollow file soon

**Comment by sionking** [comment]
but removing every not succeed unfollow is not good !
Since internet connection you will remove all of your list.
Ther should be a verification.

**Comment by timgrossmann** [comment]
@HaimBendanan @sionking Let's wait for @sionking s solution.
Also looking at the diff, it seems like there is no update in the file.

**Comment by HaimBendanan** [comment]
I updated my branch and removed this change, forgot to close the PR.
Thanks for closing :)

**Pull request closed without merging**
