### PR TITLE
Improve the .like_by_feed feature #485

### PR DESCRIPTION
**Pull request by vitormvasc**
Hi @timgrossmann , I've got some progress on this feature. So in a nutshell, I had to rewrite the **.like_by_feed** method completely so that it would be able to implement and call other methods which are necessary to meet the randomization, unfollow criteria and the filtering preferences based on comments and followers/likes restrictions. Currently, a new **.get_links_from_feed** method takes chunks of links present on the feed session and sends them to the **.like_by_feed** method, so that it visits each post's link individually in order to analyse its content - differently from the simple top-bottom approach that was in use before. The Clarifai Image checking is also being called by the **.like_by_feed** method, and if any sensitive content is found, the author gets immediately unfollowed by another new method. The **.like_by_feed** method was also build in a scalable way to be easily added with a **interact=True** parameter latter on the project. This Bounty was tricky, not as simple as you stated before.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@vitormvasc Thank you very much for this!

Well I'm sorry. Looks like I underestimated the work needed for this...
I'll look into this tomorrow and get back at you ASAP.

Thank you for contributing!

>**Note:** Please make sure to resolve the conflicts in the *instapy.py* file 😉

**Comment by timgrossmann** [comment]
@vitormvasc The interaction based on posts is now fully merged.
Would you be interested in adding the `interact=True` to your feature as well?
I'd add another 10$ on top for the more difficult implementation and the addition of the `interact=True`. 

> **Note:** make sure to add the newly done changes from master

Edit: You'd also have to add a little bit of documentation (how to use this feature in the README and an example in the example/example.py).

**Comment by mr-White** [comment]
@vitormvasc thank you for doing this! Much appreciated

**Comment by vitormvasc** [comment]
@timgrossmann Tim, I'd like to contribute with this next feature, however, my schedule for this upcoming week is going to be busy. I'll take it, but, depending on the complexity of this new feature, it might take a couple of days to get done. Anyway, I will try to finish it in a timely manner. I am going to add the example documentation later on the night. I'll let you know if anything changes. Thanks!

**Comment by timgrossmann** [comment]
@vitormvasc Awesome! 
Looking forward to the finished version of this.

Thank you

**Comment by vitormvasc** [comment]
@timgrossmann Documentation was added for the **.like_by_feed**

**Comment by timgrossmann** [comment]
@vitormvasc Awesome, only the `interact` part left 👍

**Comment by satiskmar** [comment]
Will this ever be merged?
C'mon, what are you guys waiting for?

I mean, @vitormvasc you can do it really quick I know. And @timgrossmann, wouldn't it be better to merge this first and make him open another pull request for the other part?
He is taking waaaay too long


I need this feature

**Comment by vitormvasc** [comment]
@timgrossmann you can merge this first and open another pull request for the another part as I won't have the time to finish the `interact` part soon, and I don't want to keep the project on hold. @BernardoGO or @ahmadudin can finish this.

**Comment by timgrossmann** [comment]
@satiskmar People on this project starting to get a little bit too rude... You better improve your attitude or you can develop your features by yourself in the future. If you want it to work out faster, pay for it.

@vitormvasc Ok, I'll merge this and exclude it from the issue to close it.
You'll be able to claim your bounty pretty soon.

**Comment by timgrossmann** [comment]
fixes #485

**Comment by timgrossmann** [comment]
@vitormvasc Looks like they already changed the classes of the links or something...

```bash
Logged in successfully!

Total of links feched for analysis: 0

Total of links feched for analysis: 0

Total of links feched for analysis: 0

Total of links feched for analysis: 0

Total of links feched for analysis: 0

Total of links feched for analysis: 0
```

with this setup:

```python

from instapy import InstaPy

InstaPy(username="contacting.john.doe", password="")\
  .login()\
  .like_by_feed(amount=100, random=True)\
  .end()
```

**Comment by vitormvasc** [comment]
@timgrossmann I got this. So the problem is how the `.like_by_feed(amount=100, random=True)` is written. It should be `randomize=True`, instead of `random=True`, since `random` is a reserved word. They indeed changed the class_name from `'_5l4x8'` to `'_djdmk'`. Now it runs with no problems.

**Comment by BernardoGO** [comment]
We should probably rename it in the whole project to `randomize` instead.

**Comment by timgrossmann** [comment]
@vitormvasc @BernardoGO you're right, we should change this in the whole codebase...

Could any of you guys create a PR for that?

**Comment by vitormvasc** [comment]
@timgrossmann I've just finished the `interact=True` feature. I would appreciate if I could still get the bounty for this. Thanks! I also changed the way `get_links_from_feed` fetches links from the feed area so that when classes names are changed, the application won't break.

**Comment by timgrossmann** [comment]
@vitormvasc I'll open an Issues later/tomorrow and post the rest of the bounty on it 😉
Feel free to create a PR for that.

**Comment by timgrossmann** [comment]
#533

**Comment by timgrossmann** [comment]
@vitormvasc You have to create a new PR for these changes.

**Pull request merged**
