### PR TITLE
Issue/#1748 like by feed

### PR DESCRIPTION
**Pull request by douwevandermeij**
This will fix the issue (on my machine) of not working like by feed.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@douwevandermeij Looks good, works on my machine as well.
Let's wait for one more approval.

@CharlesCCC @sionking

**Comment by sionking** [comment]
@timgrossmann  sorry I don't like by feed.

**Comment by CharlesCCC** [comment]
the code change looks good to me.

**Comment by MNovak12** [comment]
@timgrossmann @douwevandermeij It's working for me!

**Comment by timgrossmann** [comment]
@CharlesCCC Thanks for merging this!

**Pull request merged**
