### PR TITLE
Patch xpath

### PR DESCRIPTION
**Pull request by cmaixen**
Fixes issue #3059

### CODE REVIEW

**Comment by joanroig** [comment]
I have this error on last version after applying the change:
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}

**Comment by cmaixen** [comment]
> I have this error on last version after applying the change:
> NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}

that's another issue #3020.

**Review by mtnbarreto — APPROVED** [review]

**Comment by mtnbarreto** [comment]
@Tjorriemorrie Any chance to get this merrged?

**Comment by timgrossmann** [comment]
@cmaixen @mtnbarreto I'm not convinced, I still have the old elements with the old classes in my Safari instance of instagram.

**Comment by mtnbarreto** [comment]
@timgrossmann  Have you checked in chrome? 
A/B testing? or it renders differently in chrome and safari?

**Comment by timgrossmann** [comment]
@mtnbarreto A/B testing probably.
Still the old one in my chrome instance

**Comment by sionking** [comment]
Works

**Comment by timgrossmann** [comment]
@cmaixen @sionking Yup, 1 day seems to have made a change for me aswell

**Comment by sionking** [comment]
this will fail when post is video and crash the app

**Comment by sionking** [comment]
need to catch index error [1]

**Comment by cmaixen** [comment]
@timgrossmann  there is a new issue ! If you take the picture of someone who you are following, you will unfollow that person. Following introduces a new element in de resultarray, which causes a wrong button click. Working on it ASAP, but all help is welcome :)

**Pull request merged**
