### PR TITLE
interact_by_users: We should only once decide if we will follow user (rather than when viewing each of image)

### PR DESCRIPTION
**Pull request by ghost**
With this settings:
```
session.set_do_follow(True, percentage=50)
session.set_do_like(True, percentage=75)
session.interact_by_users(list_of_500_usernames, amount=4, randomize=True)
```

Because of we decide if we should follow user while see each image - really count of follow will be more than 50%!.

But with this change of code we will decide if we should follow user only one time for one user.

### CODE REVIEW

**Comment by sionking** [comment]
I also wanted to PR this already !
Thanks

**Comment by sionking** [comment]
Hi you did it wrong.
let say you got to follow, you will try to follow each image you interact with (xpath time is expensive!)

Mine:
```
    def interact_by_users(self,
                          usernames,
                          amount=2,
                          randomize=False,
                          source=None,
                          media=None):
        """Likes some amounts of images for each usernames"""
        if self.aborting:
            return self

        total_liked_img = 0
        already_liked = 0
        inap_img = 0
        commented = 0
        followed = 0

        usernames = usernames or []

        for index, username in enumerate(usernames):
            self.logger.info(
                'Username [{}/{}]'.format(index + 1, len(usernames)))
            self.logger.info('--> {}'.format(username.encode('utf-8')))

            # if we are using followers list from saved dict we shall update it
            if self.user_interact_listUsersFromDirectory is True and source == 'dict':
                self.user_interact_dict_users_dir[self.currentUsernameFollowers] += 1
                done = False
                while not done:
                    try:
                        with open('./logs/all_followers_dict.pkl', 'wb') as output:
                            pickle.dump(self.user_interact_dict_users_dir, output, pickle.HIGHEST_PROTOCOL)
                            done = True
                    except OSError:
                        self.logger.error('--> can not dump user_interact_dict_users_dir')
                        sleep(5)

            is_private = False

            valid_user = validate_username(self.browser,
                                           username,
                                           self.dont_like,
                                           self.ignore_if_contains,
                                           self.ignore_users,
                                           self.blacklist,
                                           self.dont_include_language,
                                           self.like_by_followers_upper_limit,
                                           self.like_by_followers_lower_limit,
                                           self.following_to_followers_ratio,
                                           self.logger)
            if valid_user is not True:
                if not self.skip_private_users and valid_user == 'private':
                    is_private = True
                else:
                    self.logger.info(valid_user)
                    continue

            try:
                links = False
                if is_private is False:
                    links = get_links_for_username(self.browser,
                                                   username,
                                                   amount,
                                                   self.logger,
                                                   randomize,
                                                   media)
            except NoSuchElementException:
                self.logger.error('Element not found, skipping this username')
                continue

            following = random.randint(0, 100) <= self.follow_percentage

            if (self.do_follow and
                username not in self.dont_include and
                following and
                    self.follow_restrict.get(username, 0) < self.follow_times):

                is_followed = follow_user(self.browser,
                                        self.follow_restrict,
                                        self.username,
                                        username,
                                        self.blacklist,
                                        is_private,
                                        self.logger,
                                        self.logfolder)
                followed += is_followed

                if is_followed and (self.save_do_follow_statistics() == 0):
                    self.end()
                    return
            else:
                self.logger.info('--> Not following')
                sleep(1)

            if links is False:
                continue

            # Reset like counter for every username
            liked_img = 0

            for i, link in enumerate(links):
                # Check if target has reached
                if liked_img >= amount:
                    self.logger.info('-------------')
                    self.logger.info("--> Total liked image reached it's "
                                     "amount given: {}".format(liked_img))
                    break

                self.logger.info('Post [{}/{}]'.format(liked_img + 1, amount))
                self.logger.info(link)
                # go back to user page for reliability
                self.browser.back()

                try:
                    inappropriate, user_name, is_video, most_prob_language, reason = (
                        check_link(self.browser,
                                   link,
                                   self.dont_like,
                                   self.ignore_if_contains,
                                   self.ignore_users,
                                   self.dont_include_language,
                                   self.username,
                                   False,
                                   False,
                                   self.logger)
                    )

                    if not inappropriate:
                        liking = random.randint(0, 100) <= self.like_percentage

                        if self.do_like and liking:
                            liked = like_image(self.browser,
                                               user_name,
                                               self.blacklist,
                                               self.logger,
                                               self.logfolder)
                            if liked:
                                if self.save_do_like_statistics() == 0:
                                    if self.do_end() is True:
                                        return self

                                total_liked_img += 1
                                liked_img += 1
                        else:
                            liked = True

                        if liked:
                            checked_img = True
                            temp_comments = []
                            commenting = random.randint(
                                0, 100) <= self.comment_percentage

                            if self.use_clarifai and (following or commenting):
                                try:
                                    checked_img, temp_comments = (
                                        check_image(self.browser,
                                                    self.clarifai_api_key,
                                                    self.clarifai_img_tags,
                                                    self.logger,
                                                    self.clarifai_full_match)
                                    )
                                except Exception as err:
                                    self.logger.error(
                                        'Image check error: {}'.format(err))
                            if (self.do_comment and
                                user_name not in self.dont_include and
                                checked_img and
                                    commenting):

                                # if we looked for language in post
                                # and we composed comments by language(dict not list)
                                if self.dont_include_language and isinstance(self.comments, dict):
                                    try:
                                        # if found language contain comments
                                        comments = self.comments[most_prob_language]
                                    except KeyError:
                                        # if found language don't contain comments use english
                                        comments = self.comments['en']
                                else:
                                    comments = self.comments

                                if temp_comments:
                                    # use clarifai related comments only!
                                    comments = temp_comments
                                elif is_video:
                                    comments = (comments +
                                                self.video_comments)
                                else:
                                    comments = (comments +
                                                self.photo_comments)

                                commented += comment_image(self.browser,
                                                           user_name,
                                                           comments,
                                                           self.blacklist,
                                                           self.logger,
                                                           self.logfolder)
                            else:
                                self.logger.info('--> Not commented')
                                sleep(1)
                        else:
                            already_liked += 1

                    else:
                        self.logger.info(
                            '--> Image not liked: {}'.format(reason.encode('utf-8')))
                        inap_img += 1
                except NoSuchElementException as err:
                    self.logger.error('Invalid Page: {}'.format(err))

            if liked_img < amount:
                self.logger.info('-------------')
                self.logger.info("--> Given amount not fullfilled, image pool "
                                 "reached its end\n")

        self.logger.info('Liked: {}'.format(total_liked_img))
        self.logger.info('Already Liked: {}'.format(already_liked))
        self.logger.info('Inappropriate: {}'.format(inap_img))
        self.logger.info('Commented: {}'.format(commented))

        return self
```

My code is a bit diffrent but you can see where I put the follow on

**Comment by sionking** [comment]
Basically, 
You should do the 
"follow_user"
before
"for i, link in enumerate(links):"

**Comment by ghost** [comment]
Got it. Yes, we trying to follow user when viewing each image. But if we do follow before iteration - we also don't check if user is not inappropriate (based on like_by_followers_upper_limit and like_by_followers_lower_limit).

P.S. I have added "set following to False" after we already done. So now we don't trying to follow while view second and etc images.

**Comment by eorione** [comment]
Hi there!

Can anybody send me the best combination code to maximize followers?
I could run Python, but Im not a coder, so I dont know how to write the best code to get max follower performance.

Thanks!!!

**Pull request merged**
