### PR TITLE
Description encoding problem solved.

### PR DESCRIPTION
**Pull request by hicay**

### CODE REVIEW

**Comment by timgrossmann** [comment]
@hicay This won't fix the solve the problem in the terminal. If the terminal output is set to be ASCII even encoding it with utf-8 won't help.

Did it work for your machine?

**Comment by timgrossmann** [comment]
Reverted, since it didn't work

**Comment by hojabbr** [comment]
Just add these lines to `quickstart.py` and `instapy.py`:

```
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by timgrossmann** [comment]
@hojjabr Feel free to submit a PR with these changes 👍

**Pull request merged**
