### PR TITLE
Pass arguments by CLI

### PR DESCRIPTION
**Pull request by uluQulu**
<p align="center">
  
  
<p>

Thanks to @RuiFerreira#9357 from our _Discord_ server for the idea of parsing CLI args after what I've decided to share the solution with the community 🎊
And special thanks to @timgrossmann for design decisions.

I encourage you to view the changes at Readme - [Pass arguments by CLI](https://github.com/uluQulu/InstaPy/tree/dev#pass-arguments-by-cli) which explains _almost_ everything I can say.
One of the good news is it is implemented to be **fully flexible** for several use cases user can produce.

<br />

By default, it can parse 10 formal arguments of the _InstaPy_ constructor - [Currently these flags are supported](https://github.com/uluQulu/InstaPy/tree/dev#currently-these-flags-are-supported).

To get the list of available commands, you can type,
```erlang
python quickstart.py -h
# or
python quickstart.py --help
```

<h3>
  <a href="https://github.com/uluQulu/InstaPy/tree/dev#examples-2">
    Examples
  </a>
</h3>

⚽ Let's quickly set your username and password right by CLI,   
```erlang
python quickstart.py -u Toto.Lin8  -p 4X27_Tibor
# or
python quickstart.py --username Toto.Lin8  --password 4X27_Tibor
# or
python quickstart.py -u "Toto.Lin8"  -p "4X27_Tibor"
```

⚽ Enable Firefox,
```erlang
python quickstart.py -uf
# or
python quickstart.py --use-firefox
```

<br />

<h3>
  <a href="https://github.com/uluQulu/InstaPy/tree/dev#----advanced---">
    Advanced
  </a>
</h3>

You can extend it per your use case like this,
```python
# inside quickstart script

import argparse


my_parser = argparse.ArgumentParser()
my_parser.add_argument("--my-data-files-name")
args, args_unknown = my_parser.parse_known_args()

filename = args.my_data_files_name
with open(filename, 'r') as f:
    my_data = f.read()
```
```erlang
python quickstart.py --my-data-files-name "C:\\Users\\Anita\\Desktop\\data_file.txt"
```

<br />

🌌 You can also import that function into your **quickstart** script and parse the **formal** flags into there to be used, as well.
```python
# inside quickstart script

from instapy.util import parse_cli_args


cli_args = parse_cli_args()
username = cli_args.username

print(username)
```
👆🏼👉🏼 as you will pass the _username_ like,
```erlang
python quickstart.py -u abc
```

>**NOTE**:
Arguments passed from CLI has higher priorities than the arguments inside a **quickstart** script (_read more [here](https://github.com/uluQulu/InstaPy/tree/dev#pass-arguments-by-cli)_).

>**TIP**: 
**quickstart.py** is just a name of the sample _**quickstart** script_.
Your _**quickstart** script_ might be called anything else, e.g. **simple_but_effective.py** and then you'll pass arguments normally,
```erlang
python simple_but_effective.py -u abc -p 123
```

### Details
I have used **argparse**.
E.g. I've noticed **pip** itself uses **optparse** (_see `pip -h`_). 
Or my fav python package- **youtube-dl** also uses **optparse** in most portions but also has a minimal **argparse** usage.

So why I chose **argparse** over others?
As of today, it is the best option.
Why?
- Is part of the standard library.
- Supported by Python >= 2.7.
- Is better than **optparse** (_which is an older lib_) in almost all ways and can produce better help screens than it.
Also, **optparse** has been deprecated with these official statements;
"_[Deprecated since version 2.7](https://docs.python.org/2/library/optparse.html): The **optparse** module is deprecated and will not be developed further; development will continue with the **argparse** module._"
"_[Deprecated since version 3.2](https://docs.python.org/3/library/optparse.html): The **optparse** module is deprecated and will not be developed further; development will continue with the **argparse** module._"

#### What about other alternatives?
There are several built-in and also external packages that are really good and some of them are more high-level increasing ease of use.
But for our case **argparse** is sufficient enough and of course, if there could be a case where **argparse** couldn't handle, then other alternatives would be considered in the future since it will be not any difficult having that kind of libs working analogically.

### Final

What does this style **bring**?
 - It opens new possibilities to users to extend their usage 🎂
 - It adds another layer of security for users who has mistakenly shared their login credentials in several places while providing their setup for debugging issues 🔐
 - It'll help ppl who vastly schedule jobs and now with CLI args, it will devastatingly ease their usage 🏍
 - Help contributors, collaborators & Tim to push files without worrying if they have removed the login credentials from the _**quickstart** script_ 😂
 - Quickly set/test different arguments without opening a text editor 👈🏼 debuggers friend 🥰
 - Etc.

## Other changes
+ Turn **off** verification based on _relationship bounds_ **by default**, completely - https://github.com/timgrossmann/InstaPy/commit/757815f73ed1246c5340dc487a8b1c556b4f20db.

_Before_ I **extended** the verification based on _relationship bounds_, it was _already_ enabled **by default** with pre-defined values, so after that I _preserved_ it.  
And I _initially_ supported that idea - being enabled **by default** until user _explicitly disables_..  
Cos I thought it'd kind of 'force' ppl to target the correct audience of their choice.  

But, during that time, I have seen **lots of** newbies who really complain that _`'it does not like anything'`_ [or so] and then they realize that it's cos of not configuring the relationship bounds well.  
Although, **logger messages** regarding _relationship bounds_ are very **clear**, it's just some of the very new users who _couldn't_ understand it..  
Also, right now, that config is **quite famous** amongst usage, so that is _fine_ to turn it off **by default**.  

  
###### _Please, read the **commit descriptions** for the **other** _little_ changes that occurred_.
---

<p> 
 

</p>

<sub>Please, feel free to ask any question you've got.</sub>

### CODE REVIEW

**Comment by antwal** [comment]
I have already added this function in the configmanager but I have to send it :)

Together with a new logger system and extension support

**Comment by sionking** [comment]
This is great tool, Thanks @uluQulu, but still how can someone write soooo much on argument parser ?
👍

**Comment by uluQulu** [comment]
Thank you, @sionking.
I would like to know which part(s) you find redundant.
But also please, remember, I'm still a newbie and newbies write a lot and it's first time I've learnt and wrote an argument parser xD


@antwal I have seen your PR.
Apart from code review, you've got advanced skills, for sure.

---

Cheers 🤩
---

**Comment by CharlesCCC** [comment]
Holy cow, you made this :) This is great, I actually thought of implement this.  Great work, I will definitely check this out.  and I'm back from super busy schedule, from now on, I should able to get back to contribute (after I catch up all those great additional you guys bought to Instapy).

**Comment by timgrossmann** [comment]
@uluQulu Awesome! And really nice documentation, like always 😉 

@antwal You have quite a lot of changes in your PR, it will take some time to go through them and approve them all. Have you figured out the problems with the tox tests? 
Maybe @uluQulu can help you with making the tests pass 👍 

Also, could you guys @uluQulu @antwal please find a way to "combine" your two cli arg parse logic and take the best from both 🙈 

@CharlesCCC 🙌 good to have you back 😊 

Thank you :v:

**Comment by antwal** [comment]
@timgrossmann yes, in the next commit the changes are even more; I use only python >= 3.5 and it works perfectly, I'm applying all the changes I made to my version so that it is no longer necessary to continuously change the InstaPy code to each new PR, but just create an extension to a personal folder for to be able to apply the new changes; currently the code is not dynamic. Then as soon as I have some time I check the problems with the previous versions

**Comment by timgrossmann** [comment]
@uluQulu Thank you very much for this feature, we will now release our first version of the new InstaPy with this.

@antwal The discussions with your big feature config manager will take a little bit longer.
We can still use the dev branch from now on to develop new features that will then be released.

**Pull request merged**
