### PR TITLE
#919 Smart hashtags Sort parameter

### PR DESCRIPTION
**Pull request by harrypython**
In addition to sorting random and Top (equivalent to popularity or rank in the json) we can order by relevance (same name in the json) of the hashtag.

### CODE REVIEW

**Comment by converge** [comment]
Thank you for the contribution, new ideas are always welcome. I just don't know if it will be good to the users. I like the "less ir more", that's why I added just rank and random option initially.

It's just my(personal) point of view, if you guys would like to merge it, I would love to help in everything you need. @harrypython let's wait a bit more and have more one opinion about it ?

@timgrossmann what do you think ?

**Comment by harrypython** [comment]
@converge I agree with you in "less is more", but I really like more order by category of relevance than by ranking. 
When we talk about  social media the relevance is more important than number of occurrences/rank.
Anyway the conversation about is valid :)

**Comment by timgrossmann** [comment]
@harrypython @converge If we should be going for the new sort params, then we definitely have to write good documentation about what each of the parameters does.

What's the difference between `rank` and `relevance`?

**Comment by timgrossmann** [comment]
@harrypython Any updates on this? Would really love to merge this!

**Comment by harrypython** [comment]
I'm so sorry. Did I duplicate something?

https://github.com/timgrossmann/InstaPy/pull/970#issuecomment-348289771

**Comment by timgrossmann** [comment]
@harrypython No it looks like this one does not include the Facebook thing, am I right?
So these are two different PRs

**Comment by harrypython** [comment]
@timgrossmann the Facebook thing is about a way to search locations and we talk about here https://github.com/timgrossmann/InstaPy/issues/976

**Comment by timgrossmann** [comment]
@harrypython Do you know if the facebook api also give indications about age, gender, nationality and location?

If yes, we might really need to integrate it even though it's a separate api...

**Comment by timgrossmann** [comment]
@harrypython Just saw that it's mandatory to have an instagram business account in order to use the api... this is not the right approach for instapy...

**Comment by harrypython** [comment]
@timgrossmann I understand

**Pull request closed without merging**
