### PR TITLE
Update URL

### PR DESCRIPTION
**Pull request by specdrake**
The URL `https://www.instagram.com/p` should be replaced by `https://www.instagram.com/`

### CODE REVIEW

**Comment by timgrossmann** [comment]
@specdrake `/p/` is necessary when viewing a post, why does it have to be removed here?

**Comment by specdrake** [comment]
I was talking in the page context as Instagram pages don't have `/p`. I think there is something wrong with the `check_link` function in `like_util.py`. Please take a look there.

**Comment by timgrossmann** [comment]
@specdrake Looks like they might start to remove that `/p/` section of the URL. However when I open a post on Instagram I see the `/p/` path in the URL

**Comment by specdrake** [comment]
Yeah, posts do have a `/p` section in the URL. My use case is : "Interacting on a given profile" and it's URL doesn't contain the `/p` part, although removing it doesn't fix the errors. I think Instagram must have changed something in the "Window" object as I can't find the `data` property at the given path. So, the `check_link` function may have become outdated. I am not experienced with JavaScript, so I couldn't change the DOM manipulation for troubleshooting.

**Pull request closed without merging**
