### PR TITLE
Blacklist feature

### PR DESCRIPTION
**Pull request by converge**
- Had to create a new PR to fix the rebase problem.
- Now it's easier to merge/test it. 
- There isn't README update yet, because I want to check if it's everything ok first.

**How does it work ?**

Blacklist feature for the campaign called "comments_campaign". Every interaction with a user, is stored in a csv file (blacklist.csv). This file contains a header (a dictionary), and you can find informations just opening the csv file and locating what you need through the dictionary (ex. blacklist{'campaign'} will list all campaign, and you can easily filter it by campaign, actions and users.

The csv field names are **profile,campaign,action**, and an example of how it's stored is:
profile,campaign,action
user1,campaign_1,followed
user1,campaign_1,liked
user2,campaign_1,followed
user2,campaign_1,commented
user3,campaign_1,liked
user1,campaign_say_hello,liked
user7,campaign_say_hello,commented

**How to use:**
```python
session.set_blacklist(enabled=True, campaign='comments_campaign')
```

### CODE REVIEW

**Comment by justinf102** [comment]
Do i need to update to use?

**Comment by converge** [comment]
hey @justinf102 you do need to update.
these steps will do it:
```
git checkout -b converge-blacklist_feature_new_pr master
git pull https://github.com/converge/InstaPy.git blacklist_feature_new_pr
```
to back to master you could do:
```
git checkout master
```

**Comment by timgrossmann** [comment]
@converge I know it's the least interesting part of adding a feature, but could you extend the documentation a little bit?
It's really hard to get what this feature is all about 😉 

Still really awesome feature, thank you very much!

**Comment by converge** [comment]
@timgrossmann totally agree! I will extend the docs. I think it will be more clear when we add features to work integrated with blacklist feature, like some kind of interaction with the campaign backlist made.

**Comment by timgrossmann** [comment]
@converge Sounds awesome!
You're really flooding the PR section with greatness. 

Is this ready to get merged?
Looks like it's only the rebase problem and some missing documentation, right? 😄

**Comment by converge** [comment]
finally learned how to rebase 🎉 🎉 🎉  :octocat: ✌️

**Comment by timgrossmann** [comment]
@converge Awesome, that took me weeks to do right 😄

**Pull request merged**
