### PR TITLE
add username to log file for follower and followed

### PR DESCRIPTION
**Pull request by MattiaMarchiorato**
Hello, 

i added the username to log file for followed/er log, so you can filter that data by grep on username that you need.

Thanks

MM

### CODE REVIEW

**Comment by CharlesCCC** [comment]
@insology thank you for the PR effort. I got one question for you, since those two files already within the folder that named by the username. I don't see the reason we need add the username to the file content ?

**Comment by MattiaMarchiorato** [comment]
Hello, @CharlesCCC the logs are in this dir InstaPy/logs and the name of the files are
followerNum.txt
followingNum.txt

I can't find a directory named by username, maybe i do something wrong?

**Comment by CharlesCCC** [comment]
@insology  uhhh, Do you have the latest version of InstaPy ? if not, have you tried to turn on the multiple logs ?  `session = InstaPy(username='test', password='test', multi_logs=True)` login ?

**Comment by MattiaMarchiorato** [comment]
@CharlesCCC yes i have the last version of InstaPy and no, i have not set multi_logs, i'll try now, maybe that is the problem.
Thanks.

MM

**Comment by MattiaMarchiorato** [comment]
@CharlesCCC  multi_logs=True works fine.
Thanks

MM

**Pull request closed without merging**
