### PR TITLE
Add context manager to interaction calls

### LINKED ISSUE #3804: Like by Tags does not interact with users when blacklist is turned on
## Expected Behavior
Like by Tags method likes posts by tags and then interacts with the users of those posts and adds them to the blacklist

## Current Behavior
Scenario:
Like by Tags and interact with users with blacklist enabled

```
# Like posts based on hashtags and like 3 posts of its poster and add to blacklist
session.set_blacklist(enabled=True, campaign='nature_blacklist')
session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
session.like_by_tags(['natgeo', 'world'], amount=10, interact=True)
```

Redacted extract from general.log:
```
INFO [2019-01-04 15:10:46] [myusername]  [1/10]
INFO [2019-01-04 15:10:46] [myusername]  https://www.instagram.com/p/picture/
INFO [2019-01-04 15:10:51] [myusername]  Image from: b'username_of_person'
INFO [2019-01-04 15:10:51] [myusername]  Link: picture
INFO [2019-01-04 15:10:51] [myusername]  Description: b'description of post'
INFO [2019-01-04 15:10:51] [myusername]  Location: b'location in post'
INFO [2019-01-04 15:10:57] [myusername]  User: 'username_of_person'  |> followers: x  |> following: x|> relationship ratio: x
INFO [2019-01-04 15:11:04] [myusername]  --> Image Liked!
INFO [2019-01-04 15:11:04] [myusername]  --> username_of_person added to blacklist for nature_blacklist campaign (action: liked)
INFO [2019-01-04 15:11:45] [myusername]  --> Not commented
INFO [2019-01-04 15:11:46] [myusername]  --> Not following
INFO [2019-01-04 15:11:47] [myusername]  --> User gonna be interacted: 'username_of_person'
INFO [2019-01-04 15:11:47] [myusername]  Username [1/1]
INFO [2019-01-04 15:11:47] [myusername]  --> b'username_of_person'
INFO [2019-01-04 15:11:47] [myusername]  Username in BlackList: username_of_person
INFO [2019-01-04 15:11:47] [myusername]  --> Not a valid user: ---> username_of_person is in blacklist  ~skipping user

INFO [2019-01-04 15:11:47] [myusername]  User: b'username_of_person'
INFO [2019-01-04 15:11:47] [myusername]  Liked: 0
INFO [2019-01-04 15:11:47] [myusername]  Already Liked: 0
INFO [2019-01-04 15:11:47] [myusername]  Commented: 0
INFO [2019-01-04 15:11:47] [myusername]  Inappropriate: 0
INFO [2019-01-04 15:11:47] [myusername]  Not valid users: 1
```

The issue lies in the fact that `like_by_tags` calls `like_image` from `.like_util` which adds the user to the blacklist if the blacklist is enabled. Then if there are any interactions to be done `like_by_tags` calls `like_by_users` and passes the username of the current post to it. However since `like_by_users` also validates the username which is now contained in the blacklist, the user never gets interacted with.

## Possible Solution (optional)
Username validation for the blacklist (or validation on the whole)  needs to be turned off for the `like_by_users`  function if the user was already validated.

`interact_by_users` has the following code:
```
# standalone means this feature is started by the user
		standalone = True if "interact_by_users" not in \
							 self.internal_usage.keys() else False
		# skip validation in case of it is already accomplished
		users_validated = True if not standalone and not \
		self.internal_usage["interact_by_users"]["validate"] else False
```

I believe something like this can be added to `like_by_users` to prevent it from re-validating the user if the user was already validated and therefore allow the user to be interacted with with the blacklist is turned on.

### LINKED ISSUE #3849: Blacklist strange behavior
## Expected Behavior
Hello,

I'm using `follow_likers` with `interact=True` (cf full InstaPy's configuration below)  and if I use `set_blacklist` I expect users are added **after** interactions (at the end of all interactions: like, comment...)

## Current Behavior
No interaction are made with users because user, that just have been followed is added to the blacklist and considered  as not a valid user:

> INFO [2019-01-29 14:19:25] [xxx]  User: 'user1'  |> followers: x  |> following: x  |> relationship ratio: x 
> INFO [2019-01-29 14:19:27] [xxx]  --> Followed 'b'user1''! 
> INFO [2019-01-29 14:19:27] [xxx]  --> user1 added to blacklist for myblacklist campaign (action: followed) 
> 
> ____________________________________________________________________ 
> INFO [2019-01-29 14:19:31] [xxx]  Starting to interact by users..
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2019-01-29 14:19:31] [xxx]  Username [1/1]
> INFO [2019-01-29 14:19:31] [xxx]  --> b'user1'
> INFO [2019-01-29 14:19:31] [xxx]  Username in BlackList: user1  
> INFO [2019-01-29 14:19:31] [xxx]  --> not a valid user: ---> user1 is in blacklist  ~skipping user
> 
> INFO [2019-01-29 14:19:32] [xxx]  Total Follow: 1 
## InstaPy configuration

> bot.set_blacklist(enabled=True, campaign='myblacklist')
> bot.set_relationship_bounds(enabled=True, potency_ratio=0, delimit_by_numbers=True, max_followers=xxx, max_following=xxx, min_followers=xxx, min_following=xxx)
> bot.set_user_interact(amount=4, randomize=True, percentage=100, media='Photo')
> bot.set_do_follow(enabled=True, percentage=75)
> bot.set_do_like(enabled=True, percentage=100)
> bot.set_simulation(enabled=True, percentage=100)
> bot.set_do_comment(enabled=False, percentage=0)
> bot.follow_likers (['user'], photos_grab_amount=2, follow_likers_per_photo=15, randomize=True, sleep_delay=100, interact=True)

### PR DESCRIPTION
**Pull request by traincodesleep**
By submitting this pull request I acknowledge that I have read and agree to the code of conduct for this project.

This pull request addresses the following issues:
fixes #3804 and fixes #3849 

Interaction calls in the methods `like_by_tags` and `follow_likers` did not also use the `feature_in_feature` context manager method to prevent re-validating users after they have been added to the blacklist by an earlier action.

This pull request fixes this behavior by turning off re-validation when an interaction method call is being made in `like_by_tags` and `follow_likers` and also and adding missing logic to `like_by_users` which is used by `like_by_tags` to do its interaction.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@emmanuelclarke Looks good, I'll have to test this change once before merging.
Thank you very much for this fix! 😊

**Comment by timgrossmann** [comment]
@emmanuelclarke I've resolved the conflicts with the current dev branch.

Could you please make sure that your logic still is intact and hasn't changed? 👍

**Comment by traincodesleep** [comment]
@timgrossmann looks good! 👍

**Comment by timgrossmann** [comment]
@converge Could you give this a quick check, please 😊

**Comment by timgrossmann** [comment]
@emmanuelclarke Just tested it, seems to be working as expected, thank you very much! 💪

**Comment by Herrox** [comment]
@emmanuelclarke @timgrossmann Not sure if this PR is really working as expected.
In the logs of `InstaPy` I see something like `follower1 added to blacklist for mybalcklist campaign (action: followed)` but when I grep in the log files (especially in `blacklist.csv`) there is no such `follower1`. Moreover, `backlist.csv` file has not been modified since a while.

How may I help you guys fixing the issue ?

**Comment by timgrossmann** [comment]
@Herrox I think the problem is not with this PR itself but rather deeper in the code of the feature.
This PR simply refactors the code but keeps the logic intact. It is not doing any changes to how the blacklist is built or something like that.

If you're interested in digging deeper into where your problem could be, I suggest taking a closer look at the methods you're using and check the behaviour of blacklist there 👍

**Pull request merged**
