### PR TITLE
like image changed xpath

### PR DESCRIPTION
**Pull request by ghost**
bugfix for issue https://github.com/timgrossmann/InstaPy/issues/2344

### CODE REVIEW

**Comment by timgrossmann** [comment]
@ilmetu Thank you very much for the quick fix.
Maybe we need to make this selector less error prune as well.

Best
Tim

**Comment by ghost** [comment]
@timgrossmann i'm glad to help 👍

**Comment by marcomokastyle** [comment]
@timgrossmann @ilmetu 

it's working also with these:
```python
like_xpath = "//button/span[text()='Like']/.."
unlike_xpath = "//button/span[text()='Unlike']"
spans = [x.text.lower() for x in browser.find_elements_by_xpath("//article//button/span")]
```

**Comment by timgrossmann** [comment]
@marcomokastyle Awesome, could you please create a PR for that? 😊

**Comment by ghost** [comment]
@marcomokastyle i will create a Pull Request with your code after i try it out ok ?

**Comment by marcomokastyle** [comment]
@ilmetu was faster than me :P  @timgrossmann by the way i'm still working on various things, for me, and maybe some of this edits i will PR them.

**Comment by timgrossmann** [comment]
@marcomokastyle Sounds good, already looking forward to it 😉

**Pull request merged**
