### PR TITLE
FIX visibility #615 problem

### PR DESCRIPTION
**Pull request by CuARRONBADO**
Checks if visible. Forces visibility and click

### CODE REVIEW

**Comment by CuARRONBADO** [comment]
#615

**Comment by CuARRONBADO** [comment]
#615

**Review by iSimonWeb — COMMENTED** [review]
We have to fix the "driver" variable called to execute_script. The Selenium webdriver is named "browser".

**Comment by chrisscholly** [comment]
Thanks guys!

**Comment by timgrossmann** [comment]
@iSimonWeb Thank you

**Comment by chrisscholly** [comment]
Thank you guys 🙏🏻

**Comment by kushpvo** [comment]
Even after the latest pull (#620) , i'm still getting this error.

**Pull request merged**
