### PR TITLE
FIX-->TypeError: window.insta_data is undefined

### PR DESCRIPTION
**Pull request by turtlebking**

### CODE REVIEW

**Comment by christophe-duc** [comment]
can you correct the errors on black and flake8 ?

**Comment by turtlebking** [comment]
> can you correct the errors on black and flake8 ?

I'm pretty new to github. i did not touch the file black & flake8.
could you tell me how to correct the errors?

**Comment by turtlebking** [comment]
i try to repost the pull request again

**Comment by christophe-duc** [comment]
you can reopen and continue to commit, it will show up in the PR.

black and flake8 are 2 utilities we use to confirm the code is correct.
black is just formatting, you can install it with pip (pip install black) and then you can just reformat the file you modified with: black -t py33 <yourfile> 

contact us on discord if you need more help.

**Pull request closed without merging**
