### PR TITLE
Delete user from followedPool if no longer exists (account suspended / removed / name changed)

### PR DESCRIPTION
**Pull request by joanroig**
[Discussed here: #2359] Delete user if followed with InstaPy, and when trying to unfollow it doesn't exist and remains in the followedPool.
Removed some unnecessary encodes (tested for weeks with no issues).

### CODE REVIEW

**Comment by sionking** [comment]
I can tell you, you ahve many issues with this.
- first you will never reach this line since the function have error handling inside.
- What if instagram web is down ? you will remove a valid user.
There are so many options that you will remove a vaild followed user!

**Comment by joanroig** [comment]
@sionking Hi, thanks for the review. Well, I've tested this line and checked during weeks that is reached when the user page is not available. 

I cannot confirm what happens when Instagram web is down, but I suspect it will throw a timeout because will not retrieve data (not tested). Have you got a better idea on this?

As said, I've tested this with some accounts where a lot of lost follows were stuck in the followedPool, occasionating an accumulation of accounts that makes the bot lose time when unfollowing (and if you try to unfollow X users on different bot sessions every Y minutes, you'll be trying to unfollow the same users forever if the number of lost follows is greater than X, which is a major problem).

**Comment by ortegafernando** [comment]
HI,

> What if instagram web is down ? you will remove a valid user.
There are so many options that you will remove a vaild followed user!

May be, if you could put this as an option, it will be easy to run it one a month and avoid the risk ?

regards,

**Comment by shariqmoosa** [comment]
Hi I am facing the same issue:

ERROR [2018-08-29 13:31:54] [them] --> Unfollow error with b'emilykonopka', maybe no longer exists....
ERROR [2018-08-29 13:31:54] [them] --> Unfollow error with b'emilykonopka', maybe username has changed or he/she blocked you...
ERROR [2018-08-29 13:31:54] [them] --> Unfollow error with b'emilykonopka', maybe no longer exists...

I have tried the above code and got this error:

File "quickstart-merch.py", line 1, in 
from instapy import InstaPy
File "[path]\instapy_init_.py", line 2, in 
from .instapy import InstaPy
File "[path]\instapy\instapy.py", line 44, in 
from .unfollow_util import get_given_user_followers
File "[path]\instapy\unfollow_util.py", line 287
except:
^
TabError: inconsistent use of tabs and spaces in indentation

Please help I am new to Python and GIT

**Pull request closed without merging**
