### PR TITLE
set_dont_unfollow_active_users code improvement and #931 fix

### PR DESCRIPTION
**Pull request by converge**
is there a better approach for line 144 ?

### CODE REVIEW

**Comment by thomascello** [comment]
Did I do something wrong? 

```
[tm@tm InstaPy]$ git pull origin pull/935/head
Depuis https://github.com/timgrossmann/InstaPy
 * branch            refs/pull/935/head -> FETCH_HEAD
[tm@tm InstaPy]$ python unfollow.py 
Logged in successfully!
Traceback (most recent call last):
  File "unfollow.py", line 8, in <module>
    .set_dont_unfollow_active_users(enabled=True, posts=2)\
  File "/home/tm/Desktop/Projets Info/Instagram/InstaPy/instapy/instapy.py", line 1436, in set_dont_unfollow_active_users
    active_users = get_active_users(self.browser, self.username, posts)
  File "/home/tm/Desktop/Projets Info/Instagram/InstaPy/instapy/util.py", line 135, in get_active_users
    "//span[@class='_fd86t']").text)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='_fd86t']"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.13.12-1-ARCH x86_64)
```

**Comment by converge** [comment]
@thomascello you can test it in this way:
```git checkout -b converge-set_dont_unfollow_active_users master```
```git pull https://github.com/converge/InstaPy.git set_dont_unfollow_active_users```

it will move your current branch to this PR branch, after testing you can go back to master branch:
```git checkout master```

**Comment by thomascello** [comment]
That's what I did...

I tried another time and I still get this error message:
```
[tm@tm InstaPy]$ python unfollow.py 
Logged in successfully!
Traceback (most recent call last):
  File "unfollow.py", line 8, in <module>
    .set_dont_unfollow_active_users(enabled=True, posts=2)\
  File "/home/tm/Desktop/Projets Info/Instagram/InstaPy/instapy/instapy.py", line 1436, in set_dont_unfollow_active_users
    active_users = get_active_users(self.browser, self.username, posts)
  File "/home/tm/Desktop/Projets Info/Instagram/InstaPy/instapy/util.py", line 135, in get_active_users
    "//span[@class='_fd86t']").text)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='_fd86t']"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.13.12-1-ARCH x86_64)
```

**Comment by converge** [comment]
@thomascello could you update your chromedriver to latest version and try again ?

**Comment by converge** [comment]
@thomascello thanks for the testing. Just fixed that, could you update and test it again ?

**Comment by thomascello** [comment]
Hi! 

Thanks for your work! I just tried out and it crashes directly:

```
[tm@tm InstaPy]$ python unfollow.py 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './assets/chromedriver': './assets/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "unfollow.py", line 6, in <module>
    InstaPy(username=insta_username, password=insta_password)\
  File "/home/tm/Desktop/Projets Info/Instagram/InstaPy/instapy/instapy.py", line 127, in __init__
    self.set_selenium_local_session()
  File "/home/tm/Desktop/Projets Info/Instagram/InstaPy/instapy/instapy.py", line 178, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

Is it a problem from my chromedriver or is it because of Instapy itself?
Thanks,
Best,
Thomas

**Comment by converge** [comment]
@thomascello it's just because you dont have the chromedriver in the assets/ folder.

**Comment by thomascello** [comment]
I'm sorry for this stupid question, but what should I change to fix that? 
I didn't change anything on my laptop since last time...

**Comment by converge** [comment]
@thomascello no problem! you're helping a lot! if you need, I'm at Slack channel.

you just need to do it again: 
```
git checkout -b converge-set_dont_unfollow_active_users master
git pull https://github.com/converge/InstaPy.git set_dont_unfollow_active_users
```

**Comment by thomascello** [comment]
Let's talk on Slack! 
How can I discuss with you on Slack? I'm sorry I am a very new user of Slack :) What is the Slack workstation I have to join to discuss with you?

**Comment by converge** [comment]
our Slack workspace: https://join.slack.com/t/instapy/shared_invite/enQtMjYzNTgwMDg3MDEyLTk2NWI0MjY2MTVjYmM2NjFlYjVmMmE0ZjU1OGQ0OWM2MTQwOTc1NTIyOGVhZDEwMTFkYzFmODE5ZWIxZjhjMTQ

**Comment by AlessioBucaioni** [comment]
hi @converge can you please copy here the code of the new util.py solving the issue?

**Comment by converge** [comment]
@AlessioBucaioni https://gist.github.com/converge/354e6e8626db5811fa0fe4e85b547740

sounds like it's not working on Linux, it does work on Mac

**Comment by converge** [comment]
Just tested in Linux, it works without issues, same as MacOS. Hard to know what's wrong..

**Comment by converge** [comment]
thank you very much @thomascello for help testing it !

**Comment by thomasmesnard** [comment]
You are more than welcome

**Pull request merged**
