### PR TITLE
fix to instagram graphql change

### PR DESCRIPTION
**Pull request by pekapa**
Hold this for now, need to make sure every account changed to the new graphql or treat both scenarios!

#131

### CODE REVIEW

**Comment by pekapa** [comment]
@vlntdds, can you please check if it's working with the accounts without graphql? (i.e. the ones that didn't break like #131)

It's working fine for me, but my account was affected.

**Comment by eduardocalazansjr** [comment]
I think that we must abandon the JS element and focus on XPATH.
Maybe moving to js was a mistake, since there's no postback of this data and It can't be reliable.

**Comment by pekapa** [comment]
XPATH can be really slow and they can change those nodes just like they can change the JS interface.
I'm not sure which is the best option here...

**Comment by alvinlee123** [comment]
How often does instagram update stuff like this? This issue was just a quick refactor of like_util

```
`user_name = browser.execute_script("return window._sharedData.entry_data.PostPage[0].graphql.shortcode_media.owner.username")
  image_text = browser.execute_script("return window._sharedData.entry_data.PostPage[0].graphql.shortcode_media.caption")
    or
image_text ="return window._sharedData.entry_data.PostPage[0].graphql.shortcode_media.edge_media_to_comment.edges[0].node.text"`

**Comment by eduardocalazansjr** [comment]
XPATH isn't slow, read about it before say that.
XPATH by text maybe the best solution, since text doesn't change between accounts.
And the JS isn't reliable, since as i said, there's no postback of the info.

@alvinlee123 some accounts doesn't have graphql.

**Comment by pekapa** [comment]
I just tried a few options on selenium, mainly: raw XPATH, find by tag, and find by link text.
by text was the fastest and (in my test) took 300ms to take all the 150 links on a page
in second came by tag, with 1.9s
the slowest was the raw version, with 2.1s

**Comment by AlainPilon** [comment]
The question is: Do we want to be as fast as possible? If they track by mouse movement, we may want to be as slow as a human to not be noticed.

**Comment by eduardocalazansjr** [comment]
Realized that business accounts doesn't have the graphql, but openGraph.
So, there's accounts without the change, accounts with graphql and accounts with openGraph.
The best way of achieve the same results for all is XPATH, but with the right selectors, not some "relaxed selectors". 

@AlainPilon maybe it's the right time to think about the "anti-bot way" and refactor?

screen shot 2017-04-17 at 23 11 39

**Comment by pekapa** [comment]
Shall we merge this fix so people can still use it while we think and do the refactoring?

@vlntdds, start a new develop branch so we can keep this one "stable" and work on that one as wee need. What do you think?

**Comment by mcnamee** [comment]
Thanks @pekapa - I've just switched, and am now using your _graphql_ branch - it's working a treat for me so far

**Comment by AlainPilon** [comment]
I can't test until tonight. If @timgrossmann can't test/merge by then, I will.

**Comment by sugionodjojo** [comment]
if it help, here is the results

root@ubuntu-1gb-nyc2-01:/InstaPy# python3.5 quickstart.py
Logged in successfully!
Tag [1/5]
**--> b'#**********'**
[1/100]
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    .like_by_tags(['#***r'], amount=100) \
  File "/InstaPy/instapy/instapy.py", line 235, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
**TypeError: check_link() takes 7 positional arguments but 8 were given**


notice the bold

**Comment by eduardocalazansjr** [comment]
I'm testing it right now and seems that the account that have the graphql until yesterday doesn't have it for now.
It changed for the openGraph, seems kinda weird.

**Comment by pekapa** [comment]
@sugionodjojo That's weird, the signature is correct, can you show us how your `check_link` function looks like? Should be around line 47 of the `like_util.py` file

**Comment by pekapa** [comment]
@vlntdds I still have graphQL in my account.

**Comment by sugionodjojo** [comment]
@pekapa 
you are right, pardon me, i deleted my comment.

here is the result after i fix that check_link
root@ubuntu-1gb-nyc2-01:/InstaPy# python3.5 quickstart.py
Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    InstaPy(username='******', password='*********')\
  File "/InstaPy/instapy/instapy.py", line 82, in login
    log_follower_num(self.browser, self.username)
  File "/InstaPy/instapy/print_log_writer.py", line 8, in log_follower_num
    browser.get('https://www.instagram.com/' + username)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-72-generic x86_64)

**Comment by sugionodjojo** [comment]
#133 may be a problem related? 
here is the result 
root@ubuntu-1gb-nyc2-01:/InstaPy# python3.5 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    InstaPy(username='********', password='***********')\
  File "/InstaPy/instapy/instapy.py", line 73, in login
    if not login_user(self.browser, self.username, self.password):
  **File "/InstaPy/instapy/login_util.py", line 18, in login_user
    login_div = browser.find_element_by_class_name('_uikn3')**
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 413, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"_uikn3"}
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-72-generic x86_64)

**Comment by timgrossmann** [comment]
@vlntdds @pekapa @sugionodjojo 
This is working on my machine... Is this ready to be merged?

**Comment by eduardocalazansjr** [comment]
As i said, is a little dubious.
I'm testing with some accounts and every time the result or the page elements change and some strange crash occurs.
Already working on it, btw.

**Comment by timgrossmann** [comment]
@vlntdds Awesome!
Like you already mentioned, It's probably now time to bring it up one more time and then use the time until the next crash to refactor...

Also, the two features with follow a list and media types are merged now... All the feature PR's are now merged. Perfect time to refactor 👍

**Comment by sugionodjojo** [comment]
@timgrossmann 

i tried https://github.com/pekapa/InstaPy/blob/2abd4064d8078f48c98f93a2fa24745390f9236a/instapy/like_util.py

and the result is my terminal stuck, till i press ctrl +c , then came up below message

root@ubuntu-1gb-nyc2-01:/InstaPy# python3.5 quickstart.py
^CTraceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    InstaPy(username='****', password='*******')\
  File "/InstaPy/instapy/instapy.py", line 73, in login
    if not login_user(self.browser, self.username, self.password):
  File "/InstaPy/instapy/login_util.py", line 28, in login_user
    browser.find_element_by_class_name('_q90d5')
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 413, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
maybe something wrong with my machine?

it always stuck on 
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)

**Comment by eduardocalazansjr** [comment]
@timgrossmann i think that it's time to merge this.
Only doesn't work for some business accounts.
ASAP i will think in a better way out for this and implement the ActionChains here too.

Thanks for the quick work, @pekapa

**Review by eduardocalazansjr — APPROVED** [review]

**Comment by kaerus01** [comment]
I'm still seeing this error after a fresh pull. 

socrates@socrates ~/InstaPy $ sudo python my_runner.py
0
Logged in successfully!
Traceback (most recent call last):
  File "my_runner.py", line 13, in <module>
    session.login()
  File "/home/socrates/InstaPy/instapy/instapy.py", line 89, in login
    log_follower_num(self.browser, self.username)
  File "/home/socrates/InstaPy/instapy/print_log_writer.py", line 10, in log_follower_num
    followed_by = browser.execute_script("return window._sharedData.entry_data.ProfilePage[0].user.followed_by.count")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.13.0-37-generic x86_64)

Running ubuntu 14.04

**Pull request merged**
