### PR TITLE
Update How_to_Raspberry.md

### PR DESCRIPTION
**Pull request by mwargan**
Uses the new `pip install instapy` and updates a few instructions. Works and tested on Raspian and Raspian Lite and happily running this way on 9 of my devices (RPi3 b+) so far!

Also added easy instructions to start script on boot.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@mwargan Awesome, thank you very much for your PR.

@JoeFertig is the Raspi guy here. I think he's best to review this PR.

**Comment by tE3m** [comment]
@timgrossmann I thought @JoeFertig was already working on a new How_to_Raspberry?:grimacing:

**Comment by mwargan** [comment]
> @timgrossmann I thought @JoeFertig was already working on a new How_to_Raspberry?😬

If he/you (@JoeFertig) are, I'll be happy to help out with my experiences on Raspian and Raspian Lite!

**Comment by tE3m** [comment]
Also, the `wget` and `unzip` steps aren't required anymore. It's possible to install a chromedriver for RPis from pip now:
```
python -m pip install instapy-chromedriver==2.36.post0
```
(Inside the venv) @mwargan 
EDIT: Sorry, forgot to add -chromedriver.... xD

**Comment by mwargan** [comment]
@TarekJ03 wouldn't you need to run:
`pip3 uninstall instapy-chromedriver`
and
`pip3 install instapy-chromedriver==2.36.post0`

as per your comments here: https://github.com/timgrossmann/InstaPy/issues/3891 ?

**Comment by tE3m** [comment]
@mwargan yes, that's correct. I simply wanted to clarify that it's available via pip, but to install it you first need ro remove it, and reinstall it after that.:+1:

**Comment by mwargan** [comment]
@timgrossmann also am pushing some suggested updates for the main readme to hopefully make installation clearer and easier for new comers!

**Comment by timgrossmann** [comment]
@mwargan Thank you for the suggestions. May I ask you to move them to a separate PR, please?
Those are no related to your work on the raspberry guide and by adding those changes to the same PR we can't just merge one but not the other.
Thank you :blush:

**Comment by mwargan** [comment]
> @mwargan Thank you for the suggestions. May I ask you to move them to a separate PR, please?
> Those are no related to your work on the raspberry guide and by adding those changes to the same PR we can't just merge one but not the other.
> Thank you 😊

@timgrossmann yes of course - my apologies, worked on the wrong branch and thought I could sneakily get away with it :P

**Comment by timgrossmann** [comment]
@mwargan Sorry for the delay and now closed PR 🙁 
The new location of the how tos now is: https://github.com/InstaPy/instapy-docs/tree/master/How_Tos

Could you please PR the changes there? 🙈

**Comment by mwargan** [comment]
@timgrossmann no problem - just waiting on a new Pi Zero (should come on Thursday) to test the install procedure on this device too - I got it down on a Pi3 B and Pi3 B+, now just going to test it on the Zero and I'll push my findings :)!

**Comment by timgrossmann** [comment]
@mwargan Perfect, thank you!
I think @JoeFertig should also be ready with the new guide.

**Comment by mwargan** [comment]
@timgrossmann Ok! Actually I've found that it's super simple, just three commands needed on a fresh install of either Raspian or Raspian Lite:
`pip3 install instapy`
`pip3 uninstall --yes instapy-chromedriver`
and
`pip3 install instapy-chromedriver==2.36.post0`
very simple stuff. Of course a user needs to install pip3 before with `sudo apt-get install python3-pip`, and run the quickstart scripts with `python3` as opposed to `python`, which was definitely a major source of confusion when I started.

**Pull request closed without merging**
