### PR TITLE
Add new table for all the bot's activity 

### PR DESCRIPTION
**Pull request by leoch20**
Create new table and populate. [3272](https://github.com/timgrossmann/InstaPy/issues/3272) for more info.

### CODE REVIEW

**Comment by sionking** [comment]
can you rebase to latest ?

**Comment by sionking** [comment]
I think it will better fit to update_activery moudle

**Comment by leoch20** [comment]
@sionking I'm not sure what you mean by update_activery moudle, could you elaborate?

**Comment by sionking** [comment]
I do the same as you do with the "source" so I pass it to follow_user/like_image/comment method for example and than to update_activety method which is called from those functions.
This way you won't have to add table record after each action call.

**Comment by sionking** [comment]
so log_table_activity won't be duplicated each action

**Comment by leoch20** [comment]
@sionking I think I know what you mean, but I can't locate the update_activity method. Does it get called by the other methods in `Instapy.py`?

**Comment by sionking** [comment]
not from instapy but from follow_user/like_image methods that are not in instapy file

**Comment by sionking** [comment]
I will explain:
now you have:
```
                                comment_state, msg = comment_image(self.browser,
                                                                   user_name,
                                                                   comments,
                                                                   self.logger
                                                                   self.logfolder)
                                if comment_state == True:
                                    commented += 1
                                     # Populate logs table
                                    action = 'Commented'
                                    logtime = datetime.now().strftime('%Y-%m-%d %H:%M')
                                    log_table_activity(self.username, action, user_name, self.logger,
                                                       self.logfolder, logtime, location)
```

While it will be best to just:
```
                                comment_state, msg = comment_image(self.browser,
                                                                   user_name,
                                                                   comments,
                                                                   **source**
                                                                   self.logger
                                                                   self.logfolder)
```

So you just need to add your code in 3 places comment_image/like_image/follow_user ...

Sion.

**Comment by leoch20** [comment]
@sionking I think I got it now but I'm still testing it a bit, what do you think?. Thanks for the tips btw. 

Also, I saw this Issue you opened [1636](https://github.com/timgrossmann/InstaPy/issues/1636), any luck?

**Comment by leoch20** [comment]
@sionking @timgrossmann can this be added to the master? I think there is certain demand for it

**Comment by timgrossmann** [comment]
@leoch20 Judging by the commits alone, we can't merge it like this...
You also have to rebase on latest master.

@sionking Was your proposed change considered and applied? Can you approve this addition?

**Comment by sionking** [comment]
@timgrossmann It seems that the proposal did applied, I did not test it yet (and will probably won't soon).
I think there should be another rebase ? 
@leoch20 thank you !

**Comment by sionking** [comment]
Another important thing:
I think we shall pass ("location", location) as a tuple and not only location as it will be confusing to not know where this source is.
also for tags...

**Comment by leoch20** [comment]
@sionking you're right. I will add 'Location' before.
@timgrossmann im pretty new to git. I have been looking how to rebase but I haven't been able to do so. I'm trying to do it with gitkraken. I just haven't had much time to play around with it

**Comment by timgrossmann** [comment]
@sionking @leoch20 Guys, I'm really sorry this haven't been merged yet. The last days have been quite busy and I couldn't read through all the comments, and in this case, the approval of @sionking.

If you're somehow able to rebase it, we can definitely merge it.
Thank you for your effort.

**Comment by timgrossmann** [comment]
@leoch20 Any updates on this?
Thanks

**Comment by leoch20** [comment]
@timgrossmann sorry it took me so long to answer. I've pretty busy too. I have not been able to rebase, every time. It seems I can't get the latest version for some reason. Not sure what Im doing wrong. Thanks for your help tho

**Comment by timgrossmann** [comment]
@leoch20 Sorry to hear that and sorry for the extreme delay in response...

We haven't looked over and tested this proposal, yet... sorry for that.
We'll try to do that in the coming days (best, later today).

**Comment by rosinbum** [comment]
This would be super helpful functionality. I was about to write this myself. Collecting data about actions  is the first step. What I really want to see is capturing more metadata about a user InstaPy interacts with and if the user returns any engagement. This would help target users who are more likely to engage.

**Pull request closed without merging**
