### PR TITLE
Revised and enhanced `follow_commenters`, `follow_user_likers` (now is renamed to `follow_likers`) and `follow_by_list` features to have smart 'sleep_delay' and 'interact' capability

### PR DESCRIPTION
**Pull request by uluQulu**
In @jeremyccheung's request at #1956,
I have done several additions and modifications to those three functions:
`follow_commenters` and `follow_user_likers` functions are calling `follow_by_list` method for doing follow activity. So I first edited that function.
1. **Now**, `follow_by_list` function can do interatcions on **followed** users (_interaction configuration are handled by `set_user_interact` method_) and it has `interact=False` parameter by default.  
_Also_, it was missing sleep delays after certain amount of follows where I added a smart sleeper which does take 2 randomized points: instead of typical "_sleep 600 seconds per each 10 follows_", I did randomize both values, now it will sleep `random.randint(sleep_delay*0.85, sleep_delay*1.14)` and after each `random.randint(7, 14)` and these values both are being regenerate after each sleep activity.
```python
follow_by_list(followlist, times=1, sleep_delay=600, interact=False)
## `sleep_delay` and `interact` parameters are new
```
2. **For** the `follow_commenters` feature, I have just added same `sleep_delay` functionality and `interact` capability
```python
follow_commenters(usernames, amount=10, daysold=365, max_pic=50, sleep_delay=600, interact=False)
## `sleep_delay` and `interact` parameters are new
```
3. **For** the `follow_user_likers` feature, I did add same `sleep_delay` functionality and `interact` capability and also merged it's engine function `follow_likers` function into it for the ease of maintenance (_I don't think somebody would use that function standalone, it was just following likers of a user from a picture's URL_)
```python
follow_user_likers (usernames, photos_grab_amount=3, follow_likers_per_photo=3, randomize=True, sleep_delay=600, interact=False)
## `sleep_delay` and `interact` parameters are new
```

* I will tell a decision I've made:
Currently there are 3 sleep handlers one for each modified function, well, I tried to minimize it to 1 just for `follow_by_list` handling those all, but for the sake of accuracy, we need it. Yes it is possible if we get entire userlist in `follow_commenters` and/or `follow_user_likers` and only then start `follow_by_list` feature, then it can handle accurate sleep delays but I think getting a userlist (_one-by-one_) and following then again, is more appropriate regarding the efficient activity, so having a sleep delay handler for each of those functions seems fair.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@uluQulu this is incredible! Thank you very much for all the improvements you're doing.
It's really great that someone is unifying the API.

Unfortunately none of those issues has a bounty associated, but if you post your PayPal handle here, I can send you a little love from the InstaPy account.

Thank you!

One thing you probably still have to do @uluQulu is to update the documentation a bit.

**Comment by uluQulu** [comment]
A pleasure to read such a wondrous remark! @timgrossmann,
I believe, I should not expect a reward from contributing to such a peachy open-source project but my PayPal email is shahriyaguliyev@hotmail.com, PayPal.me is not supported in my country, yet :)
Thanks! 🤩
I got a few modifications to be done in mind, thinks would need to do some further modifications;
Well the thing stucked in my mind is merging `follow_likers` method (_feature_) into `follow_user_likers` feature.
By default, `follow_user_likers` uses usernames to find pic URLs and then it passes those URLs into `follow_likers`, so as it is `follow_likers(photo_urls, amount)` and it can be itself used separately as a feature, if you provide pic URLs....
Do you think somebody would still use it just by passing URLs?
I find it ineffective but if somebody still would use it, I can change the design to make it separate method (feature) again.
Waiting for reviews, @jeremyccheung! 👨🏼‍💻
So thinks to add README lines for the new parameters at final stage..

**Comment by timgrossmann** [comment]
@uluQulu I don't really thinks so since it's pretty annoying and inconvenient to use.

It's a pleasure to have you as a contributor to this project.
Thank you

**Comment by uluQulu** [comment]
Hey @timgrossmann, I just thought, instead of having it as a separate method (_feature_), we can add a new parameter inside, `follow_user_likers` function, so it will do the job of prior usable `follow_likers` method (_feature_) too,
so, sth like
```python
follow_user_likers (by_photo_URLs, by_usernames, photos_grab_amount=3, follow_likers_per_photo=3, randomize=True, sleep_delay=600, interact=False)
## idk, but this is prone to cause confusion, although README part can be written well...
```
I really think it is truly inconvenient and inefficient way to use, but having it as a parameter will provide flexibility to some users who would like to use it..
What are your final thoughts? - keep it as a parameter **OR** make it a separate function again **OR** keep it as it is in this PR (_merged inside `follow_user_likers` where URL method will not be accessible separately, you must provide usernames_)

**Comment by uluQulu** [comment]
While working on this, I realized there are too many functions (_features_) doing the same things.
There should be a major re-design in structure where each function's capabilities would be **unique**.
Well, it has a downside which will break many people's existing codes and modifications based on old code, but it is the way for better future.
Alongside structure, there must be `namespace` policy for a cleaner code.
Also some very little functions needs to be merged together which are causing mess (_this has not much work, though_).
And, of course, having a unified realtime controller like QS :)

**Comment by sionking** [comment]
Thank you for the hard work. But I do think we should point more effort in stuff like detection prevention instead of more "like by" features.

One day all of those feature will be useless if IG decide to fight bots in a smart way (beside ip pools only as they do now).

**Comment by uluQulu** [comment]
hi @sionking,
I have clearly stated my opinions [here](https://github.com/timgrossmann/InstaPy/issues/1909#issuecomment-384407264).
as for recompilation of a webdriver, since _chromdriver_ is written in `cpp` I can find a way to recompile it, but we must find an automated way of doing it, cos user will eventually update webdriver many times and there must be a recompiler function existed for doing the job,.. it is a bit portably difficult issue...
but having help from a JS expert would be very valuable, there are lots of dispatchers & event handlers to be taken under control :)

**Comment by uluQulu** [comment]
Alrighty guys,
To prevent possible confusion, I have renamed `follow_user_likers` to `follow_likers` to be analogical with `follow_commenters` style.
In the future, if people would want to do the activity with pic `URL`s instead of `usernames` list, just adding a new parameter inside `follow_likers` would be sufficient as shown in this https://github.com/timgrossmann/InstaPy/pull/1981#issuecomment-387378343.
Also added missing README lines, too, like access links and formatted in good-looking style
@timgrossmann, checked markdown links, they are working good this time🏂🏼

**Comment by timgrossmann** [comment]
@uluQulu Perfect, thank you very much!

**Comment by jeremycjang** [comment]
@uluQulu Thank you so much for this update; finally got some time to update everything and test it out so here's the overdue review I owe you!

I tested ```follow_likers``` running this with a small follow amount and with GUI to see the process. I used the following code as writtenwith usernames removed:

```
session.follow_likers(['user1' , 'user2'], photos_grab_amount=2, follow_likers_per_photo=10, randomize=False, sleep_delay=600,interact=True)
```

- It looks like that program does open a user's picture posts to grab users that liked the photo, however it does not do so for videos and displays the "video has no likes? Moving on" message before moving to the next post. Haven't found the corresponding code yet, but my initial guess is that it is related to how video post metrics display views instead of likes, though having the program interact with the "# views" link will effectively also open the same likes page for videos.

- After setting ```interact=True``` in ```follow_likers``` , the program did not appear to carry out the interact process. I will re-test this again another time as I did not have a space between the last parameter comma and this parameter (```sleep_delay=600,interact=True```), though I am not sure if this matters in Python.

**Comment by uluQulu** [comment]
I appreciate your innovative thinking that results, brilliant commits,
@jeremycjang,
But you should know that, neither you have requested that media type `Video` grabbing in #1956 NOR this PR covered it. But that's right about viewers link, maybe you can improve and implement it.
For interaction to be happened, I guess you've forgotten one thing,
`interaction configuration are handled by set_user_interact method`,
_as I wrote in first comment above and included in README_
Just enable `interact=True` parameter and set your interaction configuration before the feauture to use it (_README has examples_).
> I think so, too, space after a comma is not required for Python.

**Comment by jeremycjang** [comment]
@uluQulu Thank you so much for this update; finally got some time to update everything and test it out so here's the overdue review I owe you!

I tested running  ```follow_likers``` with a small follow amount and GUI to see the process. My exact code was as follows (usernames removed)

```
 session.follow_likers(['user1' , 'user2'], photos_grab_amount=2, follow_likers_per_photo=10, randomize=False, sleep_delay=600,interact=True)

```

Observations:

- The program does open a user's picture posts to grab users that liked the photo, however it does not do so for videos and displays the "video has no likes? Moving on" message before moving to the next post. I couldn't pinpoint the corresponding conditional that throws the statement, but my initial guess is that it is related to how video post metrics display **views** instead of **likes**, though having the program interact with the **# views** link also effectively opens the list of likers. Perhaps **# views** can be appended to the check for **# likes** to make it work

- The program did not perform the ```interact``` portion of the code as intended. I did forget to add a space after the comma when separating the parameters ``` sleep_delay=600,interact=True``` , but I am unsure if this makes a difference in Python. Can definitely run a re-test  of the program very soon

**Comment by uluQulu** [comment]
@jeremycjang,
It seems to be a duplicate of previous comment with slight changes on `views` functionality.
I wish I could look at that some time. It is easy to do, why don't you implement yourself?
> If there is any misbehaviors related to the changes in this PR or any of my commits, please let me know

**Pull request merged**
