### PR TITLE
Clarifai Util: Fix for Tag Extraction for Celebrity and Demographics Models

### PR DESCRIPTION
**Pull request by dfundingsland**
Fixed the `get_clarifai_tags` function to properly extract all tags from the celebrity and demographic models response.

### CODE REVIEW

**Comment by sionking** [comment]
@timgrossmann  @dfundingsland You broke the comments styling I did. please revert.

**Comment by timgrossmann** [comment]
@sionking Really sorry to hear that, do you know what broke that?
Was it #3147 ?

**Comment by dfundingsland** [comment]
@sionking Apologies and sorry to hear as well. 

 @timgrossmann #3147 does appear to be the offending PR. Specifically, the changes to `instapy.py` were undone in commit `d43d3480`.

**Comment by dfundingsland** [comment]
@timgrossmann @sionking I ran a diff against a reverted version of `instapy.py` and went through to merge the relevant changes. Please take a look. Hopefully addresses the issue. If not, let me know how else I might be able to help.

**Comment by timgrossmann** [comment]
@sionking Could you approve to merge this?
@dfundingsland Restored the changes you made and mentioned.

**Pull request merged**
