### PR TITLE
Feature/hide headless

### PR DESCRIPTION
**Pull request by breuerfelix**
firefox extension to hide headless browser

how to use:

- delete your instapy cookies
- `git clone https://github.com/timgrossmann/InstaPy.git`
- `cd instapy`
- `git checkout feature/hide-headless`
- `pip3 uninstall instapy`
- `pip3 install -e .`

start your Quickstart script

__note:__ this only works with firefox !! make sure to use it!

btw I can't fix the codacy issues since they are irrelevant, once we merged it, I will ignore them by codacy :)

### CODE REVIEW

**Comment by sionking** [comment]
try passing this test:
https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html

**Comment by breuerfelix** [comment]
> https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html

I do since I followed his guide (both of them) on how to hide it and implemented everything :P this guy is awesome

**Comment by ghost** [comment]
Just tried, but It is being blocked after about 40 likes. Sorry, but on my side it does not work.

**Comment by x225am** [comment]
Hi I tried this but I have got error unexpected keyword argument 'use_firefox'
I am on Ubuntu

**Comment by breuerfelix** [comment]
> Hi I tried this but I have got error unexpected keyword argument 'use_firefox'
> I am on Ubuntu

yep just don't use this keyword since we only have firefox, so you don't need to specify that :)

**Comment by x225am** [comment]
> > Hi I tried this but I have got error unexpected keyword argument 'use_firefox'
> > I am on Ubuntu
> 
> yep just don't use this keyword since we only have firefox, so you don't need to specify that :)

Ok, it pass this step after changing Import Settings as well. Unfortunately there are some issue with web driver:
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by breuerfelix** [comment]
> > > Hi I tried this but I have got error unexpected keyword argument 'use_firefox'
> > > I am on Ubuntu
> > 
> > 
> > yep just don't use this keyword since we only have firefox, so you don't need to specify that :)
> 
> Ok, it pass this step after changing Import Settings as well. Unfortunately there are some issue with web driver:
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

ye saw the settings bug, I fixed it :D

do you have firefox installed on your system ? you need that :)

**Comment by dmsfabiano** [comment]
I tried this for a few days. It was working as expected when I was using the proxy. However, I have problems with the integration to native instapy. 

I am running the `interact_user_followers` function to test it, and it immediately gets stuck at 0% percent with `Failed to load deesired amount of users!` the instapy is just stuck there with no response.

This causes for me to cancel quickstart.py run, and after this it doesn't work again. I get this error:

```
Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    session = InstaPy(username=insta_username, password=insta_password,headless_browser=True,multi_logs=True)
  File "c:\users\diego fabiano\instagram\instapy\instapy\instapy.py", line 302, in __init__
    self.logger)
  File "c:\users\diego fabiano\instagram\instapy\instapy\browser.py", line 119, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary = True)
  File "c:\users\diego fabiano\instagram\instapy\instapy\browser.py", line 32, in create_firefox_extension
    with zipfile.ZipFile(zip_file, 'w', zipfile.ZIP_DEFLATED, False) as zipf:
  File "C:\Users\Diego Fabiano\Anaconda3\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Diego Fabiano\\InstaPy\\assets\\extension.xpi'
```

so I believe the new features destructor is not cleaning something up in the assets folder.

**Comment by jctommasi** [comment]
It Works, I had been banned from following, and switching to firefox makes the ban disappears. But I can only follow with session.follow_likers cause follow_followers crash and raise a Xpath error, here is the traceback:

```
Traceback (most recent call last):
  File "loop_ubuntu2.py", line 138, in <module>
    choice();
  File "loop_ubuntu2.py", line 117, in follow_followers
    session.follow_user_followers(hitting_accounts, amount=rand_follow, randomize=True, interact=True, sleep_delay=rand_sleep)
  File "/InstaPy/instapy/instapy.py", line 3215, in follow_user_followers
    self.logfolder)
  File "/InstaPy/instapy/unfollow_util.py", line 1084, in get_given_user_followers
    logger, logfolder)
  File "/InstaPy/instapy/unfollow_util.py", line 807, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //body/div[3]/div/div[2]
```

Running InstaPy on Ubuntu server from digitalocean.

**Comment by Tachenz** [comment]
And I can't even log in for some reason... ideas what that "Login A/B testing detected is?" In browser it never gets to entering login-password:
Untitled

**Comment by x225am** [comment]
> > > > Hi I tried this but I have got error unexpected keyword argument 'use_firefox'
> > > > I am on Ubuntu
> > > 
> > > 
> > > yep just don't use this keyword since we only have firefox, so you don't need to specify that :)
> > 
> > 
> > Ok, it pass this step after changing Import Settings as well. Unfortunately there are some issue with web driver:
> > selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> 
> ye saw the settings bug, I fixed it :D
> 
> do you have firefox installed on your system ? you need that :)

thanks for suggestions. I think you are correct, I have issue with Installation gecodriver. Do you have any resent instruction how to do this? Which folder I have to put (assign) this gecodriver file?

**Comment by Tachenz** [comment]
@breuerfelix So the log in issue is resolved. Now the problem seems to be with:
session.interact_user_followers - it always gives either "Failed to load desired amount of users" or  "grabbed 0 followers to interact with" message with this build.

What happens in Firefox it gets to the window with "Suggestions" - down to the button of "See all suggestions" (after clicking on someone else followers list) and just gets stuck there

PS this error is absent in the main brunch

**Comment by Tachenz** [comment]
Any news on "grabbed 0 users to interact with" for this PR?

**Comment by breuerfelix** [comment]
@Tachenz I will merge Gui features and this PR tonight / tomorrow into dev so everybody will be able to work on fixing all issues here ! :) just be a little more patient please :)

**Review by MedRedha — APPROVED** [review]

**Comment by Tachenz** [comment]
> @Tachenz I will merge Gui features and this PR tonight / tomorrow into dev so everybody will be able to work on fixing all issues here ! :) just be a little more patient please :)

Roger that! Hey, I thought I was hoping I am helping by finding those :P

**Comment by breuerfelix** [comment]
> > @Tachenz I will merge Gui features and this PR tonight / tomorrow into dev so everybody will be able to work on fixing all issues here ! :) just be a little more patient please :)
> 
> Roger that! Hey, I thought I was hoping I am helping by finding those :P

you are !! for real :) we are not able to test everything that's why its perfect that you guys are testing this :)

just wanted to let you know that this is finally our focus now :D

**Pull request merged**
