### PR TITLE
Multilanguage Like

### PR DESCRIPTION
**Pull request by eduardocalazansjr**
I've tested with multiple languages, resolutions, users and locations
and seems that the coreSpriteLikeHeart class never changes.
When the image is not liked yet, the class is coreSpriteLikeHeartOpen,
when the image is already liked the class changes to
coreSpriteLikeHeartFull.
This should fix the language/locale issue with the like function, but
the comment function must be reviewed.

### CODE REVIEW

**Comment by timgrossmann** [comment]
fixes part of #28

**Comment by timgrossmann** [comment]
@vlntdds Just a quick question, how do you test stuff like different languages and locations?

**Comment by eduardocalazansjr** [comment]
@timgrossmann I have multiple machines with different regional/locale settings on OS (tested on Windows and OSx)

But you can try adding an argument to chromedriver and call chrome with another locale config:

`options.add_argument('--lang=es')`
[ref](https://developer.chrome.com/extensions/i18n#locales-testing)

**Comment by timgrossmann** [comment]
@vlntdds Oh, wow that's amazing!
What's the reason you have them?

Really glad you're interested in committing to this project.

**Comment by eduardocalazansjr** [comment]
@timgrossmann in my work i use windows (en-US language w/ Brazil locale), at home i use a mix of OSx (en-US language w/ en-US locale + pt-BR language w/ Brazil locale).
Also i have a bunch of VMs on Azure with a lot of mess setups, hahah.

I dive into Selenium documentation and realize that the following line will set the chromedriver locale and change instagram language

`chrome_options.add_experimental_option('prefs', {'intl.accept_languages': 'pt-br'})`

Give it a try.

**Pull request merged**
