### PR TITLE
add like_by_locations.  remove .DS_Store

### PR DESCRIPTION
**Pull request by dylancaponi**
Tested and working on my machine.  Check it out.

locations must be in the form:
`.like_by_locations(['86195'])`
or
`.like_by_locations(['86195/petersen-automotive-museum/'])`

### CODE REVIEW

**Comment by timgrossmann** [comment]
@dylancaponi Awesome, thank you!

Could you please also write a bit of documentation on how to use the feature (in the Readme and docs/index.md) ?

Also make sure to describe where to get the location "numbers" from 😉

**Comment by dylancaponi** [comment]
Changes made.

Why are there two docs that are almost identical?

**Comment by timgrossmann** [comment]
@dylancaponi One is for the GitHub "Frontpage" and the other one is for the webpage...

**Comment by matthewswogger** [comment]
I'm having an issue getting this to work for me.

`session.like_by_locations(['383655954/cuvee-coffee-bar/'], amount=10)`

And here is the output, what's up?

> Logged in successfully!
> Location [1/1]
> --> b'383655954/cuvee-coffee-bar/'
> Load button not found, working with current images!
> Too few images, aborting
> 
> Session ended

**Comment by dylancaponi** [comment]
My guess is slow internet.  Did this happen repeatedly?

Most of this project uses blind waits instead of waiting for specific elements to load.  So if something doesn't load within a timeout the whole thing crashes.  This should be changed.

I ran it without problems:
Logged in successfully!
Location [1/1]
--> b'383655954/cuvee-coffee-bar/'
[1/10]
Image from: b'austinbeerworks'
Number of Followers: 23002
--> Image not liked: Number of followers exceeds limit

[2/10]
Image from: b'365thingsaustin'
Number of Followers: 157837
--> Image not liked: Number of followers exceeds limit

[3/10]
Image from: b'cyties'
Number of Followers: 11192
--> Image not liked: Number of followers exceeds limit

**Comment by matthewswogger** [comment]
Here is all of my code, it did the same thing again, maybe I don't know how to use the instapy api. I'm running it on a t2.micro on ec2. Do I need to add more to this script to make it work?
```
from instapy import InstaPy

session = InstaPy(username="<insta_username>",
                  password="<password>",
                  nogui=True)

session.login()
session.like_by_locations(['383655954/cuvee-coffee-bar/'], amount=10)
session.end()
```
Thanks for all your help!

**Comment by matthewswogger** [comment]
Here is all of my code, it did the same thing again, maybe I don't know how to use the instapy api. I'm running it on a t2.micro on ec2. Do I need to add more to this script to make it work?

```
from instapy import InstaPy

session = InstaPy(username="<insta_username>",
                  password="<password>",
                  nogui=True)

session.login()
session.like_by_locations(['383655954/cuvee-coffee-bar/'], amount=10)
session.end()
```
Thanks for all your help!

**Comment by matthewswogger** [comment]
I got it figured out, the t2.micro doesn't have enough ram, only one G, but the t2.small works great.

**Comment by ujazzz** [comment]
@dylancaponi is it possible to add multiple locations and set different amount of likes/comments for different locations? how would the code look like for that?

EDIT: Fount it. All I had to do was seperate locations with comma

e.g-
`session.like_by_locations(['460754225','128694164','678043073','93235534'], amount=50)`

**Pull request merged**
