### PR TITLE
Fix `following_link` layout change in `unfollow_users` and add graphql approach to get `likes_count` and `possible_posts` values

### PR DESCRIPTION
**Pull request by uluQulu**
* Now `like_by_locations` feature will also use _possible posts_ amount which will provide great accuracy while getting links (_solves https://github.com/timgrossmann/InstaPy/issues/1825#issuecomment-380301233_).

* Adds graphql approach of getting values for `possible_posts` and `likes_count` (_their values are numbers_) which sometimes have troubles getting by elements resulting an empty string either is a result of a layout change or something related to the visibility setting such as, `display:block` that I could not determine and it happened in some users only and also is not persistent, yet which will definitely be solved by using this graphql approach, hopefully.  
Mentioned in https://github.com/timgrossmann/InstaPy/issues/1924#issuecomment-385247307.  
Affects #1924, #1957, #2032, #2039, #2047

* Adds correct XPATH of `following_link` to be used with `unfollow_users` in `onlyInstapyFolloed=False` **and** `onlyNotFollowMe=False` condition.  
Mentioned in https://github.com/timgrossmann/InstaPy/issues/2031#issuecomment-389608594.  
Affects #2031, #1977, #2024, #2026, #2044

### CODE REVIEW

**Comment by timgrossmann** [comment]
@uluQulu You sir, are on fire! This is great.

Thank you very much for all those incredible improvements.

**Comment by sionking** [comment]
can you explain what is the "simulated_list" that you unfollow.
Can you please not unfollow only by validation fail, many real account do follow friends and don't want to get them unfollow by mistake.

**Comment by uluQulu** [comment]
Thanks @timgrossmann 🖐,
@sionking, I've included information about that in #2012 which adds it,

simula

The only place it unfollows a user is once the simulatedly followed user's relationship bounds does not match pre-defined relationship bounds.
And you should know that, it does simulated follows in dialog boxes where the user was not yet followed and the button was `Follow` which means that user is not your friend, yet.
In other places, if validation returns False, it will not unfollow, instead, will skip further interactions on that user, I mean I didn't change anything in that mechanism.

**Comment by sionking** [comment]
One more thing:
I also wanted to merge ( I been using this long time ago) the validate_username check with the check_link in like_by_tag/location. but I think this flow make more sense:
**check_link** and then **validate_username** and not opposite.
There is no point in wasting good bandwidth and time moving to another page (profile page) while the current (post page) is not valid.

SCK

**Comment by redsector72** [comment]
Is there a way to manually pull this from git?

**Comment by uluQulu** [comment]
Good point, @sionking,
It can be applied to some methods iterated over posts.
I will implement it soon👍

**Comment by uluQulu** [comment]
@redsector72,
I have very less `git` knowledge but you can do this,
1. change remote repository to the one containing this PR
```erlang
git remote set-url origin https://github.com/uluQulu/InstaPy.git
```
2. verify that it did change the remote URL
```erlang
git remote -v
```
3. go ahead and `pull` the commit (_I've written a detailed post on pulling properly in https://github.com/timgrossmann/InstaPy/issues/2013#issuecomment-389371842_)

Since my fork is up-to-date with main repository, this will be a good easy method for you. But if you try to apply this method on forks (_or repositories_) which has other modifications, too, then it will bring troubles.

Good luck!

**Comment by uluQulu** [comment]
#### UPDATE:
**1**. In @sionking's suggestion, in methods those are iterated over post links taken from pages (_FeedPage, TagPage, LocationPage_) I did relocate `validate_username` to be run after `check_link` which is much more efficient as posts with insappropriate content will not be matched through `validate_username` which costs a profile page navigation in case of **relationship bounds** is used.
_those affected methods are: `like_by_locations`, `comment_by_locations`, `like_by_tags`, `like_by_feed`, `follow_by_tags`_

**2**. Having used in several places to provide an efficient page navigation, I did pull `current_url` _checking and matching_ against the URL to be navigated into a new definition called `web_adress_navigator(browser, link)` for ease of access.

**3**. Added global `self.not_valid_usernames` and instant `not_valid_usernames` variable to keep track of **not valid usernames'** count and print it after each method alongside other information.

>Also, removed unused `self.username` argument from `check_link` which was in use before `validate_username` came out and did some syntax correction for clearer source code and good-looking output.

**Comment by Mehran** [comment]
i get Error `TypeError: validate_username() missing 1 required positional argument: 'logger' `on `python3 `.

is it fixed ?

**Comment by uluQulu** [comment]
Of course, @Mehran, I've included it in this PR.
To solve it in your own, open up **instapy.py** file and find `like_by_locations` method and in there **pass** the _missing_ `self.username` variable in `validate_username` function **call**.
```python
validation, details = validate_username(self.browser,
                               link,  #after the last commit this line is `user_name` but until merges this PR, don't touch it
                               self.username,   ##ADD this line
                               self.ignore_users,
                               self.blacklist,
                               self.potency_ratio,
                               self.delimit_by_numbers,
                               self.max_followers,
                               self.max_following,
                               self.min_followers,
                               self.min_following,
                               self.logger)
```

**Comment by S4nderr** [comment]
Hi, 

The simulated follows seems like a great add!

Is there also a way to turn it off?

Sander.

**Comment by uluQulu** [comment]
@S4nderr 
Sure, you can add some logical expression to return `False` value into this statement,
>_e.g., ` 5==6` which always returns `False`_

in **unfollow_util.py** file, simply add that new _condition_ like this,
```python
if (5==6 and  
    (simulator_counter > random.randint(5, 17) or
        abort==True or
            total_list >= amount or
                sc_rolled==random.randint(3, 5))):
```
_Simulated follows are considerably so less and in return provides a genuine activity flow._

Good luck!

**Comment by sionking** [comment]
@uluQulu or Just:
`if (False and   ##added this new expression
...

**Comment by uluQulu** [comment]
cool @sionking 
haven't used that before, it is a way more direct and that much confusing 🌊

**Comment by S4nderr** [comment]
@uluQulu 
I am really new to this... can you tell me what I've done wrong because I am still getting simulated followers :cry:...

In the unfollow_util.py file I've changed

`
        # Will follow a little bit of users in order to simulate real interaction
        if (simulator_counter > random.randint(5, 17) or
                abort==True or
                    total_list >= amount or
                        sc_rolled==random.randint(3, 5)):
`

to

`
        # Will follow a little bit of users in order to simulate real interaction
        if (5==6 and   ##added this new expression
        simulator_counter > random.randint(5, 17) or
            abort==True or
                total_list >= amount or
                    sc_rolled==random.randint(3, 5)):
`

Maybe I did not do it well..?

**Comment by uluQulu** [comment]
@S4nderr 
Better zip and attach **unfollow_util.py**, I could look

**Comment by S4nderr** [comment]
[unfollow_util.zip](https://github.com/timgrossmann/InstaPy/files/2023634/unfollow_util.zip)

If you can take a look that would be much appreciated!

**Comment by uluQulu** [comment]
@S4nderr 
**UPDATE** 😟
It's not related to indentation but logic xD
use this,

```python
if (5==6 and  
    (simulator_counter > random.randint(5, 17) or
        abort==True or
            total_list >= amount or
                sc_rolled==random.randint(3, 5))):
```
>_there are **or** expressions at the same level which I didn't consider_

**Comment by S4nderr** [comment]
Its working now but now I am getting:
`
Traceback (most recent call last):
  File "clubs_nl.py", line 87, in <module>
    amount=25, skip_top_posts=False)
  File "C:\Users\Boswachter\Documents\Github\InstaPy\InstaPy\instapy\instapy.py", line 797, in like_by_locations
    self.logger)
TypeError: validate_username() missing 1 required positional argument: 'logger'
`

:cry:

**Comment by uluQulu** [comment]
@S4nderr 
Pull latest commits, it will fix it.

**Comment by lokmanm** [comment]
@uluQulu i keep getting simulated follow how can i disable ? Yesterday it was running fine now i pulled out  the latest one and i keep getting this simulated follow...

**Comment by uluQulu** [comment]
@lokmanm 
https://github.com/timgrossmann/InstaPy/pull/2042#issuecomment-390544237

**Comment by lokmanm** [comment]
@uluQulu  Can you upload me a sample file how it should look like ? I keep getting an error :/

**Comment by uluQulu** [comment]
@lokmanm 
Make sure your files are up-to-date, then attach **unfollow_util.py** file in a zip, I will help you.

**Comment by lokmanm** [comment]
@uluQulu 

[unfollow_util.zip](https://github.com/timgrossmann/InstaPy/files/2076897/unfollow_util.zip)

**Comment by uluQulu** [comment]
@lokmanm
[unfollow_util.zip](https://github.com/timgrossmann/InstaPy/files/2077149/unfollow_util.zip)

**Comment by nadavdrukker** [comment]
@uluQulu I've just started using the new version and was surprised by the simulated follow. I wanted to ask, does it check against followRestriction? Also, how is it compatible with the setting to not follow randomly?

Thanks!

**Comment by m0mus** [comment]
Folks, it would be a good design to make simulated follow feature configurable. For old version users, after upgrading, it's surprising that scripts starts following users having session.set_do_follow(enable=False).

**Pull request merged**
