### PR TITLE
adding no_comments engagement_mode

### PR DESCRIPTION
**Pull request by ishandutta2007**

### CODE REVIEW

**Comment by breuerfelix** [comment]
@ishandutta2007 is this PR done ? or is there more needed to accomplish this ?

also could you just quickly mention no_comments in the readme please ? would be awesome so this topic can be closed and merged ! thanks !! :)

**Comment by ishandutta2007** [comment]
> @ishandutta2007 is this PR done ? or is there more needed to accomplish this ?

Done


> also could you just quickly mention no_comments in the readme please ? would be awesome so this topic can be closed and merged ! thanks !! :)

Done

**Comment by breuerfelix** [comment]
@ishandutta2007 awesome mate ! thanks alot :) guess alot of people are waiting for this feature !

**Comment by ishandutta2007** [comment]
> @ishandutta2007 awesome mate ! thanks alot :) guess alot of people are waiting for this feature !

provided you can keep leechers at bay. You need to review [this](https://github.com/InstaPy/instapy-quickstart/pull/70/files) too so that people start using it.

**Comment by breuerfelix** [comment]
> > @ishandutta2007 awesome mate ! thanks alot :) guess alot of people are waiting for this feature !
> 
> provided you can keep leechers at bay. You need to review [this](https://github.com/InstaPy/instapy-quickstart/pull/70/files) too so that people start using it.

done

**Pull request merged**
