### PR TITLE
Major [structural] changes on the verification block of follow & unfollow actions AND introduce custom action delays setting for the user to configure easily AND add CHANGELOG

### PR DESCRIPTION
**Pull request by uluQulu**
Hello there!
This is the exact set of the changes I have told of and wrote a ~month ago and just now could find time to clear up and share.
To make it more easier to understand, I added each change in a separate commit with an adaptive description.
For more information on any line of code, please ask me.

Shortly I can say that now the `follow_user` and `unfollow_user` generic functions are more good-looking 😛
And the `get_following_status` is more efficient.

Also, worth mention- I set a default delay per each action and if the user enters a lesser time of delay than the default value, then it will pick the default value.
I made it to provide safety cos sleeping e,.g. `10` to `15` seconds after an unfollow is very important to avoid possible temporary blocks and if the user enters e.g. `3` seconds for that without realizing the outcome...
Also there is a random range which is interesting, by enabling `randomize` parameter, you can enjoy having random delays at desired range, e.g.
```python
set_action_delays(enabled=True, like=5.2, randomize=True, random_range=(70, 140))
```
E.g. it will get a random sleep delay between `3.64` and `7.28` values each time, every time after putting a like 🤫

You can **also** put e.g. only max range as- `random_range=(None, 200)`
At that part, the min range will be 100% - the same time delay itself.
And the random sleep delays will be between `5.2` and `10.4` values.

Meanwhile I am going to write a documentation for the usage of custom action delays at README.
Hope it is gonna be a useful addition.

---

Cheers 😊
----

### CODE REVIEW

**Comment by sionking** [comment]
There is no use for random delay.
You should delay action according to **last executed action**
I already published something you can use.

Thanks for making small PR due !

**Comment by timgrossmann** [comment]
@uluQulu Thank for this proposal and the nice description and good documentation.

@sionking Where did you publish this?

Haha, yeah the small PR is nice

**Comment by CharlesCCC** [comment]
you all mean small `commit` ?  LOL

**Comment by timgrossmann** [comment]
@CharlesCCC Haha, no the PR is nice and small, there are several commits, but that's good, too.
One PR being one features is a good to review 😉

**Comment by fabian-pandas** [comment]
@uluQulu thanks a lot, set_action_delay works amazing!
Unfortunately now I'm receiving  "Last follow is not verified!	~smells of a temporary block".

**Comment by uluQulu** [comment]
Thanks all 🤩

@sionking 
>You should delay action according to last executed action

Nope. I want pure randomization in sleep delays for every post-action moment. I think that's not what you talk about.
>I already published something you can use.

I believe, it is the only optimal way to do it regardless of the method you could offer I'm unaware of.
>There is no use for random delay.

I really want that randomization and thinks other people might want, too.
_Well, in future there could have been a smart global randomization handler, only then, it might have been reconsidered as many other randomization parameters.._

@timgrossmann @sionking @CharlesCCC 
I think you mean lots of unique commits rather than bulky general commit(s).
Well, earlier I didn't know of doing partial commit (_in GitHub Desktop app_), you know, using the blue red and green colors 😛 but recently I learnt it and now try to use it every time possible cos having the commits that target only one unique JOB is very handy for the viewers.

@timgrossmann 
>One PR being one features is a good to review 😉

I still cannot do work on branches 😟 so expect only one PR at a time 🤝🏼
Also, I always write everything [mixture of changes] and then try to push, that's where partial commits come to help.

@fabian-pandas 
Thanks for trying out my code ☕
I decided to wrote the custom action delays mainly after having a user who wanted `40` seconds of delay after each unfollow 😂 Crazy but it's also a case.
> Unfortunately now I'm receiving "Last follow is not verified! ~smells of a temporary block".

I think you have applied the changes MANUALLY by hand and at some place missed merging properly.
Cos, the error message you provided is now deprecated with this PR.
Earlier it printed,
```erlang
logger.warning("Last follow is not verified!\t~smells of a temporary block\n")
```
for the follow action. And the unfollow action verification failure had a different message.
Now it prints,
```erlang
logger.warning("Phew! Last {0} is not verified."
                                    "\t~'{1}' might be temporarily blocked from {0}ing\n"
                                        .format(action, username))
```
for both follow and unfollow action verification failures- it is generic.

I suggest you to download my fork and test with it since it is up-to-date with the main repo and the only diff is this PR.

----

Cheers 🧐
---

**Comment by sionking** [comment]
> Nope. I want pure randomization in sleep delays for every post-action moment. I think that's not what you talk about.

So you know what could be the outcome ?
1. going to 1 user; time=0
2. liking this user time=5 (+ 5 sec verification time)
3. waiting ~30 sec; time=35
4. going to 2 user; time=35
5. liking this user time=40 (+5 sec verification time)
6. waiting ~30 sec; time=70
*** While you wanted to wait 60 sec you got 70 between likes.**

My logic:
1. going to 1 user; time=0
2. liking this user time=5 (+ 5 sec verification time)
3. waiting **~25** sec; time=30
4. going to 2 user; time=30
5. liking this user time=35 (+5 sec verification time)
6. waiting ~25 sec; time=60
*** waited ~60 second.**

Now take verification time to 30 sec and check again.


BTW,
> Also, worth mention- I set a default delay per each action and if the user enters a lesser time of delay than the default value, then it will pick the default value.

is breaking my logic, so please make it optional or don't change user input.

**Comment by uluQulu** [comment]
@sionking 
Sorry, I hardly understood your example. Can you write more clearer and accurate?
It would be much better if you provided its source code.

I used straight-forward logic.
#### A1: User wants to wait 5 seconds after each like.
Okay:
```python
set_action_delays(enabled=True, like=5)
```
_Always 5 seconds_,
```python
After Like No-1: sleep 5 seconds
After Like No-2: sleep 5 seconds
After Like No-3: sleep 5 seconds
After Like No-4: sleep 5 seconds
```

#### A2: User wants to wait _around_ 5 seconds after each like in the random range of (70, 140).
Okay:
```python
set_action_delays(enabled=True, like=5, randomize=True, random_range=(70,140))
```
_It will sleep between 3.5 (70% of 5) and 7 (140% of 5) seconds_,
```powershell
After Like No-1: sleep 3.54 seconds
After Like No-2: sleep 6.6 seconds
After Like No-3: sleep 5.01 seconds
After Like No-4: sleep 4.881 seconds
```

As you see it is pretty straight-forward and I don't consider how much time it takes for other processes cos liking is a unique process itself.

>is breaking my logic, so please make it optional or don't change user input.

I think you mean the use of default values.
It might be discussed cos I am also unsure about it and it was just a thought I had.
But think about this.
User puts 0.1 seconds of delay for likes.
And the program works for a long time WHERE it produces a very unwanted behavior and might cause a BLOCK...
And yes, I have heard from people WHO wants to have bigger delays JUST TO prevent temporary BLOCKs out of that matter.

That's why there have to be default values to prevent that possibility.
And the default values I put there is the exact values they were before the custom action delays.
```erlang
    defaults = {"like": 2,
                "comment": 2,
                "follow": 3,
                "unfollow": 10}
```

Maybe adding a parameter for that, as- `safety_match=[True, False]` for the people who still want to overcome defaults with?

---

Cheers 🙂
---

**Comment by uluQulu** [comment]
@timgrossmann 
I invested time yesterday and I wrote a good CHANGELOG for the project out of your request at https://github.com/timgrossmann/InstaPy/pull/3147#issuecomment-433329900.

It really was hard to find a good one cos there are many styles.
##### Should I automate the CHANGELOG generation?
Using some handly picked commits and a few lines of code or using some famous extrernal software [bad choice].
But no. It is a difficult job:
- [x]  Commit messages are mostly geeky and written for the other programmers to understand but CHANGELOG is for the users.
- [x] Not all commits are written in good [undertstandable text, good explaining, etc.] format and you can't force contributors to write in good format cos it's practically impossible.
- [x] Writing a few lines of code to the CHANGELOG must be so easy for the programmer write it in no time cos if it is a bit of complicated, it will be a boring job. But CHANGELOG is so imporant for a good software project. That's why using the simplest form is important.


#### Fine CHANGELOG is gonna be written manually by the contributor. But which format?
There are tons of CHANGELOG styles and I read from many webpages and saw many samples.
And found a very good project at - https://keepachangelog.com/en/1.0.0/ and used it's simple and standartized format.
It is so simple and explains everything in its little page.,
sekil

The contributor can easily read in its page if has some question about usage. And I think after a while, as the CHANGELOG gets more input, it will be easier to add new entries by looking into others.

As you can see at [CHANGELOG.md](https://github.com/uluQulu/InstaPy/blob/master/CHANGELOG.md)
One entry is,
"_Custom action delays capability (see README)._"

It hits to this PR and the user is gonna open README and search ["_action delays_"] for find that new entry.
Some CHANGELOG styles also include the commit number and the contributor username,
"_Custom action delays capability (see README). #2f15eed @uluQulu_"
But I did not add that information. Cos it brings complexity and some entries in the CHANGELOG will not have a proper commit cos it will be part of some other big commit.
And most of the CHANGELOG readers will be normal users and it will be a bit noisy.
And yes, who wants to learn more about the code of that entry in CHANGELOG, then user can see the commits posted in that date and find the wanted one and read.

@timgrossmann I think this project also uses [semantic versioning](https://semver.org/spec/v2.0.0.html), right? Cos the only release have the `0.1.0` label, I thought so,..

@timgrossmann, I also think it is mostly your job to demand a CHANGELOG entry from the contributors before merging it [ with the correct date]. Or you could add them yourself [just a few sentences..]

It must work 100% properly to make this project grow. So that people don't need to also checkout the long commits list out of a missing CHANGELOG entry...

Also, I think AS you are all experienced programmers 😉 you already know what should be added to the CHANGELOG. But I will note down my thought.
E.g. you can see the example of this PR.
It has 16 commits and more than 500 lines but I added only 5 lines into the [CHANGELOG](https://github.com/uluQulu/InstaPy/blob/master/CHANGELOG.md) off this PR.
Having read at https://keepachangelog.com/en/1.0.0/ will clear out what should be included into a CHANGELOG.
Shortly, I would say,
+ If any commit change something that affects the USER of the software, MUST BE noted in CHANGELOG in an understandable and explanatory and short directive sentence.

And for last, this sentence from a SO thread makes it very clear the situation of "_commit message_" vs "_changelog entry_":

>_The problem with this is that, even assuming that every contributor to your project writes clear and readable commit messages, you'll still be generating a "changelog" containing TONS of noise. Changelogs should be written with the goal of explaining to the users of your project the notable changes relevant to them that occurred between releases, whereas commit messages should be focused on explaining to developers what improvements your commit makes to the code. Sometimes there's overlap there, but not always. 
Or, to make that a bit more concrete, this method will create a "change log" containing lots of entries like "Fixed spelling of fooMethod in ZModule" and "Refactor XModule to use new version of XYLibarary". Your users don't care about that. They want to know what changes were made from their perspective as users, not your perspective as a developer. And that's even ignoring stuff like "Merge PR #123 from xdev/foo" and "Opps, fixed newFeature so it actually works" type things that are likely to exist in any real-world repo._

Sorry for a long comment, I couldn't make it shorter 😛
I wish @timgrossmann and all other **commit mergers** good luck in attentivity for the continuous CHANGELOG entry requests from the contributors for the sake of better user experience.


---

Cheers 😁
---

**Comment by fabian-pandas** [comment]
@uluQulu yes you're right =) I edited the code manually in order to  understand it better. I'm using R on a daily basis. Python is new to me but in many cases it's quiet similar to R i think.  If you've got any advice regarding some python basics I would be very pleased =)

**Comment by uluQulu** [comment]
@fabian-pandas 
Wow _R_ is very unknown to me.
You are very right to do it, it really teaches you while applying the changes manually but meanwhile you have to understand the possible consequences out of missed lines of 🙂 merges.
E.g. the changes on action verification block is really fuzzy I know of and for that kind of changes I would just pick the ready code rather than trying to re-apply.

Personally, I write with _C++_ and my _python_ knowledge is [almost] restricted with the **InstaPy** usage.
That's how & where I learnt python, not read a leaf of book on it yet. But I think @timgrossmann can suggest you some good book or a tutorial since I heard he has taught python to beginners 😉
Initially, when I had almost no any python knowledge, the InstaPy source code helped me to understand many things by just reading the code and trying to find meanings. Then writing similar lines 😛
Now I still read code and see the usage examples sometimes, but now most of time I do search "_How to...?_" in web.
And when the web has no any help, I go to the **freenode** _IRC_ channel of `#python` WHERE are amazing people, more than ~1700 ppl online all the time who are of great help.


_Hope now there is no problem with this PR after applying (and testing) the changes properly_ 😄

---

Cheers 😁
---

**Comment by timgrossmann** [comment]
@uluQulu @sionking Is the problem with "breaking" your implementation fixed?

@uluQulu Really nice work 👍

**Comment by uluQulu** [comment]
Thanks 🙋🏼‍♂️ @timgrossmann,
> Is the problem with "breaking" your implementation fixed?

I just added a new parameter I told of- `safety_match`, to turn off that behavior in case of user really wants to GO UNSAFE.
As @sionking told,
>is breaking my logic, so please make it optional or don't change user input.

So if that is the case, then it has been cleared out [solved].

Also thanks to @cormo1990 for adding the source code for his template quickly 🚀

_BTW @sionking, I saw the code of your ideas while getting the _quickstart template_ of @loopypanda at #3046 🧐_ and more precisely understood your point and I am now very sure that we need a straight-forward unique action delays as I suggested in this PR. My extended thought on this posted in a comment above  is still actual you can re-read.

Also, @timgrossmann, in case of merging, I think you [or merger] should change **the date** of the entries from this PR I have added in the CHANGELOG into the date the PR would be merged.

---

Cheers 😁
---

**Comment by sionking** [comment]
> I just added a new parameter I told of- `safety_match`, to turn off that behavior in case of user really wants to GO UNSAFE.

where do you take those names ?'safety_match' LOL. thanks.

**Comment by uluQulu** [comment]
Welcome @sionking
İt really is very important to me - the naming, and also very difficult to find a good name sometimes.
For this İ thought for some time and couldn't find better one.
İt is all about-
Since this setting- set_action_delays, is all about "values" so it is understandable that safety_match will mean,
"Match those values within Safety Considerations [off defaults]"
İ definetely need to read a good book on Naming some day 😂

Cheers
Sent from MailDroid<https://goo.gl/ODgwBb>

-----Original Message-----

**Comment by timgrossmann** [comment]
@uluQulu Awesome!
I changed the changelog, let's get this merged so we can get the changelog and your delays in there!

Good that you and @sionking could resolve the delay problem.

**Comment by Tachenz** [comment]
@uluQulu Unfortunately still getting the same error even with this fix https://github.com/timgrossmann/InstaPy/issues/3085

**Comment by uluQulu** [comment]
Hello @tachenz
Actually, that fix I mentioned was intended for another issue (_find and read my comment above_) and I thought your problem there could also be related to that issue that's why that fix would also solve your problem.

It seems, your issue is different. So don't expect my fix in this post to solve it so :)
I will try to look at it once gets some free time :)

**Comment by boldestfortune** [comment]
Thanks for this @uluQulu . I've been adding something like this in a (much) less dynamic way, and had to do it every time I updated. So glad I don't have to anymore. 

Question: How does this interact with `sleep_delay` in `session.unfollow_users` ? If you space the delay in `set_action_delays` high enough can you disable `sleep_delay` or is that too risky?

**Comment by uluQulu** [comment]
Welcome, @boldestfortune.

>How does this interact with sleep_delay in session.unfollow_users ?

There are sleep delays in lots of places throughout the program AND `set_action_delays()` customizes only the sleep delays of `post-action-states` (_the delay after sending every single like/comment/follow/unfollow_).

>If you space the delay in set_action_delays high enough can you disable sleep_delay or is that too risky?

By `sleep_delay` you mean the parameter in `unfollow_users(**kwargs, sleep_delay=600)` feature.
And as I said above, `set_action_delays()` has nothing to do with that kind of delays.
That parameter particularly, set the delay post bunch of UNFOLLOW actions,.


But I got your point.
I wanted to unfollow quickly last time and do it safely.
What I used is QS.
I put the amount of ~60 as the max unfollow peak in QS settings (_400 in daily_) and then in the `unfollow_users(**kwargs, sleep_delay=250)`, also, put `1` seconds in the custom action delay for every unfollow.
So that the big sleep delay it was taking was only after filling the hourly limit...

It was my personal usage and it worked well last time to unfollow couple thousands of nonfollowers 🙂 but maybe it will make problems in the long run.
Why? ..cos as well as there is a hourly/daily limit, there also is momentary limits like allowing only some amount per minute, etc.. (_I thought of adding momentary limit to QS earlier days, too, but it just smelt like so advanced 😂 for usage.._)
For that reason having slept some couple of minutes after each ~10 unfollow and having a good sleep delay after each unfollow is a safe study.
And I think current default configuration is safe enough in that regards.

My suggestion to you would be to consider all those points and write your style for that.
If you say you can space the delay in `set_action_delay` to compensate all those delays- [momentary, hourly, daily], then do it.
It is less than risky.


---

Cheers 😁
---

**Comment by boldestfortune** [comment]
Okay @uluQulu, I understand. I will set it up based on your guidelines. Thanks again!

**Comment by itayoron** [comment]
@uluQulu @sionking I want to thank you for all the time and effort you put in to this project. 
Regarding the delays, is it implemented already? I want to be able to set the minimal time between actions, I believe the same way @sionking logic follows. (For example min time between follow action set as a random between 32 and 38 seconds). How can I use it to do so?

**Comment by uluQulu** [comment]
Thanks, @itayoron 
This PR was merged and the usage on custom action delays has been documented.

Have a read [Custom action delays](https://github.com/timgrossmann/InstaPy/blob/master/README.md#custom-action-delays) section ad **README.md** and let us know if that's what you've expected.

---

Cheers 😁
---

**Comment by itayoron** [comment]
Thanks @uluQulu 
I read the Custom action delays section. Is it just adding a defined sleep delay after an action? Or is it taking into consideration the time passes between actions and adds the necessary sleep to meet the defined minimum time to wait between actions? 

I will give an example:
Let say I want minimal time to pass between follows to be 32 seconds.
1st follow was made, time=0
Other actions occur and 17 seconds pass before the next follow should be made, time =17
Will defining set_action_delays to be 32 seconds adds a 15 second sleep?

**Comment by itayoron** [comment]
I will give an example:
Let say I want minimal time to pass between follows to be 32 seconds.
1st follow was made, time=0
Other actions occur and 17 seconds pass before the next follow should be made, time =17
Will defining set_action_delays to be 32 seconds adds a 15 second sleep?

**Pull request merged**
