### PR TITLE
follow_user and follow_given_user 	Click on button via js

### PR DESCRIPTION
**Pull request by iSimonWeb**
I think I've solved the issue with the un-clickable Follow button by just trying to find it by text (as it yet was for follow_given_user).
I hope I've done right with the code since its my first step into Python.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@iSimonWeb Thank you for contributing, there are a few PR's now that do quite the same, I'll check them all out and merge then 😉

**Comment by timgrossmann** [comment]
@iSimonWeb I just don't think that clicking the buttons with JavaScript is such a good idea 😅

**Comment by timgrossmann** [comment]
#585

**Comment by iSimonWeb** [comment]
@timgrossman I'm using it this way and fortunately my account is still up. I give you that it could be a way to get busted, you can remove it if you thinks so.

**Comment by timgrossmann** [comment]
@iSimonWeb Yes, I already merged your PR and replaced it with the `send_keys('\n')` version 😉 

Thank you for helping out!
Looking forward to future contributions

**Pull request merged**
