### PR TITLE
Record activity, generate statistics

### PR DESCRIPTION
**Pull request by converge**
I tried to make as simple as possible:

every server call is recorded at logs/activity.csv file, page load, page content, likes, comments, follows and unfollows are recorded by day in this file.

the file layout is:
```
date,likes,comments,follows,unfollows,server_calls
11/01/17,18,14,52,0,84
11/02/17,14,10,32,0,156
```

more informations about this feature: #839 

if you guys wanna keep activity.csv open to analyse it, this frankstein can help:
```python
# osx
from subprocess import call
from time import sleep

while(True):
  with open('activity.csv') as f:
    for line in f:
      print line
      sleep(0.2)
      if 'str' in line:
        break
    else:
      call(['clear'])

### CODE REVIEW

**Comment by timgrossmann** [comment]
@converge Awesome, thank you for that PR!

I'll try to look at it later today.

**Comment by timgrossmann** [comment]
@converge Seems to be working like charm!

Do you want to add this before adding #835 ?

**Review by timgrossmann — APPROVED** [review]

**Comment by converge** [comment]
@timgrossmann Just merged this. I'll extend the blacklist feature doc before our merge.

**Comment by Radzam** [comment]
I have updated to latest InstaPy but it does not record activities when Im using docker microservice. Can you please instruct me how to do it?

**Comment by converge** [comment]
hello @Radzam , checks your logs/activity.csv file. maybe we need add it this to readme.

**Comment by Radzam** [comment]
@converge I checked already but it doesnt record anything. Im using docker microservice setup and not on my local machine.

**Comment by timgrossmann** [comment]
@Radzam I think keeping state in a Docker container that always starts over, when it's time to start a new InstaPy session, is pretty hard to do, isn't it?

I only worked with "real" stateless micro services and Docker so I can't tell a lot about this case here...
You probably somehow have to "extract" the recorded statistics out of the container into the host system

(Docker guys correct me if I'm wrong, please)

**Comment by Radzam** [comment]
@timgrossmann I see. It is however outputting the logFile.txt errors and info so perhaps use the same approach for activity.csv?

**Comment by Naramsim** [comment]
Hi @converge, the statistic named "likes" count real likes or even the attempted ones?

**Comment by converge** [comment]
@Naramsim it counts only liked posts, the attempts counts as server_call

**Comment by Naramsim** [comment]
Would it be useful to split the data regarding script runs?
I use Schedule so my script never really stops, and Instapy runs multiple time per day, with different settings. Right now with this PR I have an entire day data all aggregated.

I would prefer something like:
```
date,run,likes,comments,follows,unfollows,server_calls
11/01/17,1st,18,14,52,0,84
11/01/17,2nd,14,10,32,0,156
11/02/17,1st,19,11,31,0,154
```

@converge @timgrossmann @Radzam

**Comment by converge** [comment]
@Naramsim this makes me think we could have a general campaign_name setting, and aggregate it by campaign, what do you guys think ? (blacklist feature uses campaign_name to organize it's csv file).

**Comment by gitpatrickhub** [comment]
I like it! It would allow for more detailed analysis.

**Comment by riccardorighettiphoto** [comment]
I don't know if I missed something, but I cannot find any .csv file in the logs folder about recorded activities.
I am also looking for a way to analyze my runs based on information stored in the general log file.
Did someone develop (even in any fork) anything for storage statistics RAW data?
Thank you.

**Pull request merged**
