### PR TITLE
Enhanced interaction verification based on relationship bounds

### PR DESCRIPTION
**Pull request by uluQulu**
As of @DimIsaev's request from #1858, revised and enhanced helpful feature

### CODE REVIEW

**Comment by timgrossmann** [comment]
@uluQulu This is great, thank you!

Would you be able to add two more examples in the readme?
It might be a little bit confusing to only see the whole example with all the values set.

Maybe change it to one using the ratio, one only using upper and lower bound and one where only one of the values is set. Add the documentation you put below the big example to every example on it's on.

This will clear things up a lot. 

I really like this, thank you very much for all the hard work you put into this.

**Comment by sionking** [comment]
Thanks
I will test it someday :)

**Comment by uluQulu** [comment]
Welcome @timgrossmann,
I've also thought of adding more examples but in favor of saving some space in README I put only one example, but **now** I think you're right, it is setting **4 + 1** configuration which could be confusing to new users, so just **added** all of the required examples in the simplest form and rewrote text within markdown syntax.
>BTW thanks for inviting to collaborate, it is an honor! 🎖

My pleasure, @sionking, due to being requested too many times I've added three blocks of getting _followers_/_following_ count (2 different _XPATH_ & a _graphql_) 🎯

**Comment by sionking** [comment]
I do like your coding style.
I acctually using graphql only for long time with no issues, adding XPATH may results in incorrect numbers (windows size change the xpath for example) so I would have start with graphql then check for xpath

**Comment by uluQulu** [comment]
Thanks mate, @sionking,
I really thought about it and if remembers that problematic `entry_data` queries sometimes stucks in temporary outage (_in `Issues` panel, there are threads from last year July as of last times_) and needs reloading (_eats from time_) and it happened so often to so many guys, so, recently rewrote an XPATH variant in #1338 already and used it here, too. 
>Also, after the latest change in some endpoints so-called _stable_ graphql suffers.  

Well, we are dependant on page elements in whole program if they differ after window size change, it would crash in many places before reaching this part, and if anytime some class name changes, we can re-find them easily with plain `inspection`, take it easy, page elements are good  xD
_BTW_ I also did take their time difference, before and after, for each 3 and it takes (_with `time.time()`_)
1st _XPATH_: 0.14901328086853027
2nd _XPATH_: 0.15800833702087402
`entry_data`: 0.020002126693725586 (without reload)
_graphql approach is ~0.13 seconds faster (_but if it takes a reload after outage then it will be ~1 seconds slower_)_.
You choose, a bit of speed or easier stability..

**Comment by uluQulu** [comment]
Heh, I misunderstood, @sionking, you mean, _e.g._, after a window resize _it can get_, _e.g._, _**posts count**_ in `li[2]` element instead of **followers count**, although 1st XPATH can't do that cos it directly looks for followers & following keywords `@href,'followers')]/span"` & `@href,'following')]/span"` in links, but 2nd one with `li` elements _has a drolling possibility_ to misbehave as you said.
I will replace the order in your suggestion. 🙂

**Comment by timgrossmann** [comment]
@uluQulu Awesome, thank you.

One last thing we have to change might be the layout and "style" of the README part, the link from the "table of content" is not working and it looks a bit overwhelming. But that's just a small fix.

**Comment by uluQulu** [comment]
Welcome, @timgrossmann,
Yeah right, I noticed Atom's markdown **previewer** shows in _different looks_ than Github's _webpage_ markdown viewer. It looks well now.
I think modifications are done.

**Comment by timgrossmann** [comment]
@uluQulu Awesome, thank you very much!

**Pull request merged**
