### PR TITLE
Faster way to check if user is private

### PR DESCRIPTION
**Pull request by timgrossmann**
Updated how we check if the user is private because it took 25 seconds with the find_element_by_xpath function.
It takes less than a second with this edit.

Work by @mehdichekori @sionking

### CODE REVIEW

**Comment by timgrossmann** [comment]
@sionking Could you double check, please?

Also, what was the idea of having the following parameter?
We do not know whether we are following the user at the point of checking for private, was the idea to add that check beforehand?

Thank you

**Comment by sionking** [comment]
I am not really checking for following before is_private most of the cases.

But you **can't** check the xpath for user that is private but you do follow.
the graphql however will give you is_private True even if you already following the user (so you see his post and there is no real visual evidence for been private)!

You better not check the xpath and leave the following=true all the time since the graphql error that we experienced before not really reproducing.

**Comment by timgrossmann** [comment]
@sionking Ok, good to know, thank you very much.
Then we'll merge it like this and can do further adjustments in #2242 if needed.

Thank you

**Comment by Iiviin** [comment]
Really excited for this feature!

**Pull request merged**
