### PR TITLE
Update RPi Docs

### PR DESCRIPTION
**Pull request by Marto32**
This updates the Raspberry Pi documentation to use chrome (as noted in #1357). I have also created some ansible playbooks [here](https://github.com/Marto32/ansible-raspi-playbooks) to make this process much easier. LMK if there is interest and I can port them into this repo along with alternate setup instructions.

### CODE REVIEW

**Comment by timgrossmann** [comment]
@Marto32 Awesome, thank you very much!

**Comment by ganeshkrishnan1** [comment]
A minor correction: chromedriver is not by default installed in /usr/bin/chromedriver. Its installed in 
/usr/lib/chromium-browser/chromedriver

Stackoverflow (https://stackoverflow.com/questions/22476112/using-chromedriver-with-selenium-python-ubuntu) and my experience says the same but please double check

**Comment by Marto32** [comment]
@ganeshkrishnan1 interesting - when I did this I found mine in `/usr/bin/`. If you run the following, does it go to `/usr/lib/chrom...` or `/usr/bin/`?

```
sudo su
echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list
apt-get update
apt-get install chromium-browser
apt-get install chromedriver
mv /usr/bin/chromedriver /path/to/InstaPy/assets/chromedriver
```

**Comment by ganeshkrishnan1** [comment]
it got installed to /usr/lib..

https://askubuntu.com/questions/539498/where-does-chromedriver-install-to
I have a heavily modified raspbian so I can't say if it's the default.

We will leave it as is and wait for other users to confirm.

**Pull request merged**
