### PR TITLE
Remove Python2 from project

### PR DESCRIPTION
**Pull request by timgrossmann**
#3580

### CODE REVIEW

**Comment by timgrossmann** [comment]
@breuerfelix Could you please check the changes I made to the yaml file just to make sure that I removed those parts correctly (you're much more familiar with this than I am 😉 )

Thank you

**Comment by breuerfelix** [comment]
@timgrossmann approved ! checked it against my own changes for removing python2 support :)

btw don't forget to change the readme (change pip to pip3 and python to python3) :))

**Comment by timgrossmann** [comment]
@breuerfelix Awesome, thank you very much!
Will do that for the next release 🙌 Thanks for the hint

**Review by breuerfelix — APPROVED** [review]

**Comment by breuerfelix** [comment]
added some small hint, think thats enough :)

**Comment by thinhago** [comment]
The quickstart_templates are removed? i  was using as a basis for my studies, keep legal serial for beginners to understand better! thank you for the beatiful work

**Pull request merged**
