### PR TITLE
Added location to image description

### PR DESCRIPTION
**Pull request by ohio36**
Added the location (if any) of an image to the image_text in the check_link method in like_util.py, so the mandatory words check also checks the location. 

This is useful when targeting images with a certain hashtag that where taking in a certain location. Sometimes the user tags the location, sometimes the location is in the description. Both should be included.

### CODE REVIEW

**Comment by visualheroes** [comment]
Great!
How does it works (script side)?

**Comment by ohio36** [comment]
@visualheroes the script gets the location information from the graphql data and appends it to the image_text. Image_text already contained the description of the image and the first comment, so now also the location info. That's pretty much it. :)

**Comment by visualheroes** [comment]
Thanks for the clarification!
Hope it gets merged soon, it's a great idea. Thanks!

**Comment by timgrossmann** [comment]
@ohio36 Thank you for this PR and the good idea with filtering for locations.

One thing I have to ask you before we'll merge this is that it might make sense to:
1. Document your idea in the Readme (a short section where you describe what you mentioned above will be perfectly fine)
2. Add an entry in the CHANGELOG file with the modification you did

Thank you very much
Once those things are done, we can merge this.

**Comment by ohio36** [comment]
@timgrossmann Done! Let me know if there is anything still missing!

**Comment by timgrossmann** [comment]
@ohio36 Awesome! Thank you very much. I'm pretty sure I can say this for the whole community 😊

Looking forward to more great contributions.
Congrats to your first contribution to InstaPy. 🙌

**Comment by visualheroes** [comment]
@ohio36 
I tested it this morning with like_by_tags and it works great. I'll use it a lot!

Thank you again!

**Comment by ohio36** [comment]
Thank you @timgrossmann and @visualheroes! :)

**Pull request merged**
