### PR TITLE
Smart hashtags

### PR DESCRIPTION
**Pull request by converge**
```python
# Generate smart hashtags based on https://displaypurposes.com ranking,
# banned and spammy tags are filtered out.
# (limit) defines amount limit of generated hashtags by hashtag
# (sort) sort generated hashtag list 'top' and 'random' are available
# (log_tags) shows generated hashtags before use it
# (use_smart_hashtags) activates like_by_tag to use smart hashtags

session.set_smart_hashtags(['cycling', 'roadbike'], limit=3, sort='top', log_tags=True)
session.like_by_tags(amount=10, use_smart_hashtags=True)
```

### CODE REVIEW

**Comment by timgrossmann** [comment]
@converge This is awesome!

Could you also add the `return self` at the end of the method to make sure we don't loose the method chaining way 😄 

Thank you very much for this!

Also,
```
Traceback (most recent call last):
  File "quickstart_ben.py", line 51, in <module>
    .like_by_tags(amount=10, use_smart_hashtags=True) \
  File "/Users/TG/git/InstaPy/instapy/instapy.py", line 606, in like_by_tags
    tags = list(map(str.strip, tags))
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

**Comment by sionking** [comment]
Great

**Comment by converge** [comment]
hey @timgrossmann , how did you raise that TypeError ? I'm trying to reproduce it.

**Comment by timgrossmann** [comment]
@converge right after logging in and moving to the profile page, it prints out this:

```bash
Logged in successfully!
[smart hashtag generated: bike]
[smart hashtag generated: cycling]
[smart hashtag generated: mtb]
[smart hashtag generated: bike]
[smart hashtag generated: cycling]
[smart hashtag generated: mtb]
[smart hashtag generated: cycling]
[smart hashtag generated: bicycle]
[smart hashtag generated: cycle]
Traceback (most recent call last):
  File "quickstart_ben.py", line 50, in <module>
    .set_smart_hashtags(['cycling', 'roadbike'], limit=3, sort='top', log_tags=True)\
AttributeError: 'NoneType' object has no attribute 'like_by_tags'
```

Maybe a problem with Python2 ?

Edit: Sorry, this one was the `return self` part

Edit2: Yepp, python2 does not like the way you strip...

```bash
Traceback (most recent call last):
  File "quickstart_ben.py", line 51, in <module>
    .like_by_tags(amount=10, use_smart_hashtags=True)\
  File "/Users/TG/git/InstaPy/instapy/instapy.py", line 605, in like_by_tags
    tags = list(map(str.strip, tags))
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

**Comment by timgrossmann** [comment]
@converge Nice pythonic solution for this 😉 
Thanks for fixing that

**Comment by harrypython** [comment]
In addition to sorting random and Top (equivalent to popularity or rank in the json) we can order by relevance (same name in the json) of the hashtag.

In this case we need a new issue?

**Comment by converge** [comment]
hi @harrypython , feel free to propose a PR. let's improve this feature :)

open a new issue is not needed.

**Pull request merged**
